Update patch set 5
Patch Set 5:

> Change has been successfully rebased and submitted as a26da27271822e842b106f0b58b61766d1b5da39 by Commit Bot

FYI: I think this is still causing build breaks on at least some ChromeOS/ARM build configs.
I'm building Chromium for ChromeOS board_name=peach_pi and I'm getting:

[2717/30090] CXX obj/components/metrics/leak_detector/leak_detector/leak_detector.o
FAILED: obj/components/metrics/leak_detector/leak_detector/leak_detector.o 
/mnt/oldssd/chromium/.cros_cache/common/goma+2/gomacc armv7a-cros-linux-gnueabi-clang++ -B/mnt/oldssd/chromium/.cros_cache/chrome-sdk/tarballs/peach_pi+9649.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/binutils-bin/2.25.51-gold -Wno-unknown-warning-option -MMD -MF obj/components/metrics/leak_detector/leak_detector/leak_detector.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"307486-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DOS_CHROMEOS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DPROTOBUF_USE_DLLS -I../.. -Igen -I../../third_party/protobuf/src -Igen/protoc_out -Igen/components/metrics/proto -I../../third_party/protobuf/src -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics --target=arm-linux-gnueabihf -march=armv7-a -mfloat-abi=hard -mtune=generic-armv7-a -mfpu=neon -mthumb -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O0 -fomit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../../.cros_cache/chrome-sdk/tarballs/peach_pi+9649.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=gnu++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -pipe -march=armv7-a -mtune=cortex-a15 -mfpu=neon -mfloat-abi=hard -fno-split-dwarf-inlining -D__google_stl_debug_vector=1 -Wno-unknown-warning-option -Wno-inline-asm -c ../../components/metrics/leak_detector/leak_detector.cc -o obj/components/metrics/leak_detector/leak_detector/leak_detector.o
In file included from ../../components/metrics/leak_detector/leak_detector.cc:5:
In file included from ../../components/metrics/leak_detector/leak_detector.h:15:
In file included from ../../base/feature_list.h:18:
In file included from ../../base/synchronization/lock.h:12:
In file included from ../../base/threading/platform_thread.h:16:
In file included from ../../base/time/time.h:63:
In file included from ../../base/numerics/safe_math.h:8:
In file included from ../../base/numerics/checked_math.h:13:
In file included from ../../base/numerics/checked_math_impl.h:17:
In file included from ../../base/numerics/safe_conversions.h:19:
../../base/numerics/safe_conversions_arm_impl.h:65:11: error: immediate operand must be in the range [0,31]
      asm("usat %[dst], %[shift], %[src]"
          ^
<inline asm>:1:11: note: instantiated into assembly here
        usat r0, #64, r0
                 ^
1 error generated.

Patch-set: 5
CC: Sergey Volk <1123449@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>