Revert of Re-reland: Add MemoryCoordinator (patchset #2 id:20001 of https://codereview.chromium.org/2149063002/ )
Reason for revert:
Seems to break building on Windows.

See https://uberchromegw.corp.google.com/i/chromium/builders/Win/builds/45228/steps/compile/logs/stdio

[11860/34084] CXX obj\components\memory_coordinator\child\memory_coordinator_child.child_memory_coordinator_impl.obj
FAILED: obj/components/memory_coordinator/child/memory_coordinator_child.child_memory_coordinator_impl.obj
ninja -t msvc -e environment.x86 -- C:\b\build\slave\cache\cipd\goma/gomacc "C:\b\depot_tools\win_toolchain\vs_files\95ddda401ec5678f15eeed01d2bee08fcbc5ee97\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\components\memory_coordinator\child\memory_coordinator_child.child_memory_coordinator_impl.obj.rsp /c ..\..\components\memory_coordinator\child\child_memory_coordinator_impl.cc /Foobj\components\memory_coordinator\child\memory_coordinator_child.child_memory_coordinator_impl.obj /Fdobj\components\memory_coordinator_child.cc.pdb
c:\b\build\slave\win\build\src\services\shell\public\cpp\interface_provider.h(8): fatal error C1083: Cannot open include file: 'services/shell/public/interfaces/interface_provider.mojom.h': No such file or directory
[11861/34084] CXX obj\mojo\gen\mojo\public\interfaces\bindings\tests\mojo_public_test_interfaces_blink.no_module.mojom-blink.obj

Original issue's description:
> Re-reland: Add MemoryCoordinator
>
> This is second attempt. Hope GYP Mac is happy with this :(
>
> Original description:
>
> This CL adds MemoryCoordinator mojo interface and
> its implementation. When --enable-features=MemoryCoordinator
> is specified the browser and renderers create their
> MemoryCoordinators. MemoryCoordinatorImpl (which lives in
> the browser process) creates a mojo message pipe when a
> renderer is launched.
>
> This CL doesn't add actual handling of memory events, which
> will be implemented in follow-up CLs.
>
> BUG=617492
> TBR=chrisha@chromium.org,haraken@chromium.org,dcheng@chromium.org,jam@chromium.org
>
> Committed: https://crrev.com/94d4a4349b199ffef3ee1c4a8616b05b225f7dc9
> Cr-Commit-Position: refs/heads/master@{#405460}

TBR=chrisha@chromium.org,dcheng@chromium.org,haraken@chromium.org,jam@chromium.org,bashi@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=617492

Review-Url: https://codereview.chromium.org/2145403002