Update patch set 15
Patch Set 15:

> Patch Set 15:
> 
> (1 comment)
> 
> Thanks, cq'ing for real now hopefully :-)

For real this time, yes!

> I also sent you the crashpad-side version of this.

Thanks.

> Re failures, when running the binary a few times locally, I got:
> 
> [ RUN      ] ProcessInfo.OtherProcess
> ../../third_party/crashpad/crashpad/test/win/child_launcher.cc(84): error: Value of: CreateProcess(executable_.c_str(), &command_line[0], nu
> llptr, nullptr, true, 0, nullptr, nullptr, &startup_info, &process_information)
>   Actual: false
> Expected: true

Aww, it’s a bummer that nobody streamed GetLastError() to that ASSERT_TRUE(). I can at least fix that now.

> ../../third_party/crashpad/crashpad/util/win/process_info_test.cc(155): error: Expected: child.Start() doesn't generate new fatal failures i
> n the current thread.
>   Actual: it does.
> [  FAILED  ] ProcessInfo.OtherProcess (5 ms)
> 
> (got this one twice)
> 
> 
> 
> [ RUN      ] ProcessInfo.OtherProcess
> [1025/140145.940:ERROR:file_io.cc(89)] ReadExactly: expected 8, observed 0
> [1025/140145.940:FATAL:file_io.cc(142)] Check failed: LoggingReadFileExactly(file, buffer, size).

This is happening trying to read the stdout of a process started through the same interface that was failing above, so it may be related? Although this time, the child did launch (and maybe died before writing to stdout).

> Backtrace:
>         base::debug::StackTrace::StackTrace [0x00F718B0+32]
>         base::debug::StackTrace::StackTrace [0x00F7140D+13]
>         logging::LogMessage::~LogMessage [0x00F6E19E+78]
>         crashpad::CheckedReadFileExactly [0x00F61E3A+90]
>         std::vector<crashpad::ProcessInfo::Module,std::allocator<crashpad::ProcessInfo::Module> >::_Tidy [0x00F42EA9+1271]
>         testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test,void> [0x00F603DE+64]
>         testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void> [0x00F5A2A0+67]
>         testing::Test::Run [0x00F5977B+193]
>         testing::TestInfo::Run [0x00F59DF7+213]
>         testing::TestCase::Run [0x00F5A194+246]
>         testing::internal::UnitTestImpl::RunAllTests [0x00F5E07E+606]
>         testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::TestFactoryBase,testing::Test *> [0x00F60466+64]
>         testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl,bool> [0x00F5DDF2+67]
>         testing::UnitTest::Run [0x00F5DD44+178]
>         main [0x00F7EE8F+55]
>         __scrt_common_main_seh [0x00F7FB1A+248] (f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283)
>         BaseThreadInitThunk [0x7686336A+18]
>         RtlInitializeExceptionChain [0x773298F2+99]
>         RtlInitializeExceptionChain [0x773298C5+54]
> 
> 
> (got this one once)

Thanks, I haven’t seen either of these before. I’d like to try to reproduce locally. I assume that this was with the clang build. Are you on Windows 10, x86_64?

Patch-set: 15
Reviewer: Mark Mentovai <1174099@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>