keycodes: Fix non-X11 build when use_xkbcommon=1
Since M51, ui/events/keycodes/xkb_keysym.h follows X11 path, even if
use_xkbcommon=1 is set because USE_XKBCOMMON is not defined, leading
to the following compilation error in this case:

  In file included from ../../ui/events/keycodes/keyboard_code_conversion_xkb.h:12:0,
                   from ../../ui/events/keycodes/keyboard_code_conversion_xkb.cc:5:
  ../../ui/events/keycodes/xkb_keysym.h:19:19: fatal error: X11/X.h: No such file or directory

BUG=none

Review-Url: https://codereview.chromium.org/2239833003