Update patch set 8
Patch Set 8:

So I rebased this and added new tests to the .gn files, but they don't pass on Windows. These all fail:

[  FAILED  ] 7 tests, listed below:
[  FAILED  ] DirectoryReader.BadPaths
[  FAILED  ] DirectoryReader.FilesAndDirectories
[  FAILED  ] Filesystem.MoveFileOrDirectory
[  FAILED  ] Filesystem.IsRegularFile
[  FAILED  ] Filesystem.IsDirectory
[  FAILED  ] Filesystem.RemoveFile
[  FAILED  ] Filesystem.RemoveDirectoryW

The failures all look like some variant of

[ RUN      ] DirectoryReader.FilesAndDirectories
[1025/131833.694:ERROR:filesystem_test_util.cc(61)] CreateSymbolicLink: A required privilege is not held by the client. (0x522)
../../third_party/crashpad/crashpad/util/file/directory_reader_test.cc(83): error: Value of: CreateSymbolicLink(temp_dir.path().Append(file)
, temp_dir.path().Append(link))
  Actual: false
Expected: true
[  FAILED  ] DirectoryReader.FilesAndDirectories (22 ms)
[----------] 3 tests from DirectoryReader (110 ms total)


Creating symlinks on Windows requires admin permissions prior to Win 10, so I think these tests are all valid broken. I'll omit them from the .gn files for now.

Patch-set: 8
Reviewer: Nico Weber <1001629@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0