Reland of Fix tab redirect to apps in Herb mode. (patchset #1 id:1 of https://codereview.chromium.org/2419483002/ )
Reason for revert:
Reland.

Issue fixed by https://codereview.chromium.org/2408233003/

Original issue's description:
> Revert of Fix tab redirect to apps in Herb mode. (patchset #1 id:1 of https://codereview.chromium.org/2411903003/ )
>
> Reason for revert:
> Does not compile:
>
> ../../chrome/android/java/src/org/chromium/chrome/browser/ChromeTabbedActivity.java:857: error: method updateHerbIntent in class ChromeLauncherActivity cannot be applied to given types;
>                 ChromeLauncherActivity.updateHerbIntent(ChromeTabbedActivity.this,
>                                       ^
>   required: Context,Intent
>   found: ChromeTabbedActivity,Intent,Uri
>   reason: actual and formal argument lists differ in length
>
> Original issue's description:
> > Fix tab redirect to apps in Herb mode.
> >
> > BUG=653254
> >
> > Review-Url: https://codereview.chromium.org/2398833002
> > Cr-Commit-Position: refs/heads/master@{#423355}
> >
> > Support native app redirects to herb.
> >
> > If in Herb mode, use the same intent handling logic as Chrome,
> > which more aggressively intents out to external applications
> > than a normal CCT.
> >
> > BUG=653254
> >
> > Review-Url: https://codereview.chromium.org/2412613002
> > Cr-Commit-Position: refs/heads/master@{#424483}
> > Committed: https://chromium.googlesource.com/chromium/src/+/1005c8597f728173c822bdc1d8a01609f8cbd02c
>
> TBR=tedchoc@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=653254

TBR=tedchoc@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=653254

Review-Url: https://codereview.chromium.org/2404163005