Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > The Google styleguide is very explicit on this matter, there is no room for subjective interpretation on what it currently allows or not.
> > 
> > Pasting from https://google.github.io/styleguide/jsguide.html#formatting-braces (I put the "*" for emphasis no the relevant parts).
> > 
> > "Braces are required for all control structures (i.e. if, else, for, do, while, as well as any others), *even if the body contains only a single statement*. The first statement of a non-empty block must begin on its own line."
> > 
> > Exception: A simple if statement that *can fit entirely on a single line* with no wrapping (and that doesn’t have an else) may be kept on a single line with no braces when it improves readability. *This is the only case in which a control structure may omit braces and newlines*."
> > 
> > In other words
> > 
> > // Valid per Google styleguide
> > if (foo) return;
> > 
> > // Invalid per Google styleguide, valid with current Chromium styleguide.
> > if (foo)
> >   return;
> 
> This is the current Chromium style guidance:
> 
> * Omit curly braces for single-line if statements.

Yes, but what does it mean? It probably means:

// Valid per Chromium and Google style guide, therefore redundant
if (foo) return;

But if we believe that (and we remove it), we have a problem: Chromium code has a lot of the following, which the Google style guide explicitly forbids:

if (foo)
  return;

The Chromium style guide needs to explicitly say that the Google style guide does not apply here: Braces may be omitted when an "if (condition)" sub-expression is one line *and* the "body" of the if statement is one line, like the example above.

Specifically, Chromium conforms to the C++ style guide with respect to line breaks: https://engdoc.corp.google.com/eng/doc/devguide/cpp/styleguide.shtml?cl=head#Conditionals

(Ignore the first part about space characters inside parens.)

TL;DR: I'm fine removing this redundant "rule" as long as we add what Google's C++ style guide has about when braces may be omitted.

Patch-set: 3
Reviewer: Michael Giuffrida <1003321@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>