gfx: build fix about VectorIconSource
clang complains it doesn't initialize const member, so this CL calls the
default constructor explicitly.

../../ui/gfx/paint_vector_icon.cc:287:3: error: constructor for 'gfx::(anonymous namespace)::VectorIconSource' must explicitly initialize the const member 'path_'
  VectorIconSource(VectorIconId id,
  ^
../../ui/gfx/paint_vector_icon.cc:324:34: note: 'path_' declared here
  const std::vector<PathElement> path_;
                                 ^
1 error generated.

Review URL: https://codereview.chromium.org/1577743002