Revert of Don't use barcodes in ProtocolPerfTests (patchset #4 id:100001 of https://codereview.chromium.org/2420183002/ )
Reason for revert:
This CL is suspect of breaking ChromotingHostTest.ConnectWhenAnotherClientIsConnected on several bots.

See, for example, https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/53765
https://build.chromium.org/p/chromium.linux/builders/Linux%20Tests%20%28dbg%29%281%29/builds/58134

[ RUN      ] ChromotingHostTest.ConnectWhenAnotherClientIsConnected
[5433:5433:1018/003452:29645201974:INFO:chromoting_host.cc(107)] Starting host

GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: SetCapabilities(@0x7ffca86a1668 40-byte object <60-55 00-02 00-00 00-00 60-77 45-61 A6-3E 00-00 00-00 00-00 00-00 00-00 01-00 00-00 00-00 00-00 E0-75 45-61 A6-3E 00-00>)
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See http://code.google.com/p/googlemock/wiki/CookBook#Knowing_When_to_Expect for details.
[5433:5433:1018/003452:29645202704:INFO:client_session.cc(336)] Client disconnected: user@domain/rest-of-jid; error = 0
../../build/linux/debian_wheezy_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../include/c++/4.6/debug/safe_iterator.518:
    error: attempt to compare a singular iterator to a past-the-end iterator
    .

Objects involved in the operation:
iterator "lhs" @ 0x0x7ffca86a0d60 {
  state = singular;
  references sequence @ 0x0x7ffca86a0d60
}
iterator "rhs" @ 0x0x7ffca86a0d28 {
  state = past-the-end;
  references sequence @ 0x0x7ffca86a0d28
}
Received signal 6
#0 0x7f7299fb9ade base::debug::StackTrace::StackTrace()
#1 0x7f7299fb961f base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7f729a3f8cb0 <unknown>
#3 0x7f7294000035 gsignal
#4 0x7f729400379b abort
#5 0x7f72946005ad __gnu_debug::_Error_formatter::_M_error()
#6 0x00000123b828 __gnu_debug::operator!=<>()
#7 0x000001239ac5 remoting::ChromotingHost::OnSessionAuthenticated()
#8 0x0000012508fd remoting::ClientSession::OnConnectionAuthenticated()
#9 0x0000007534dd remoting::ChromotingHostTest::SimulateClientConnection()
#10 0x000000751eff remoting::ChromotingHostTest_ConnectWhenAnotherClientIsConnected_Test::TestBody()
#11 0x0000006a00aa _ZN7testing8internal12InvokeHelperIvSt5tupleIJEEE12InvokeMethodIN8remoting8protocol39MessageReaderTest_ReadFromCallback_TestEMNS7_17MessageReaderTestEFvvEEEvPT_T0_RKS3_
#12 0x000000a659fe testing::internal::HandleExceptionsInMethodIfSupported<>()
#13 0x000000a5a265 testing::Test::Run()
#14 0x000000a5aa08 testing::TestInfo::Run()
#15 0x000000a5afaa testing::TestCase::Run()
#16 0x000000a602ec testing::internal::UnitTestImpl::RunAllTests()
#17 0x000000a7b0ea testing::internal::HandleSehExceptionsInMethodIfSupported<>()
#18 0x000000a6735e testing::internal::HandleExceptionsInMethodIfSupported<>()
#19 0x000000a5ff8f testing::UnitTest::Run()
#20 0x00000132a801 RUN_ALL_TESTS()
#21 0x000001329762 base::TestSuite::Run()
#22 0x0000004f23c9 _ZN4base8internal13FunctorTraitsIMN18OAuth2TokenService7FetcherEFvvEvE6InvokeIPS3_JEEEvS5_OT_DpOT0_
#23 0x0000004f22f1 _ZN4base8internal12InvokeHelperILb0EvE8MakeItSoIRKMN18OAuth2TokenService7FetcherEFvvEJPS5_EEEvOT_DpOT0_
#24 0x000000597457 _ZN4base8internal7InvokerINS0_9BindStateIMNS_9TestSuiteEFivEJNS0_17UnretainedWrapperIS3_EEEEEFivEE7RunImplIRKS5_RKSt5tupleIJS7_EEJLm0EEEEiOT_OT0_NS_13IndexSequenceIJXspT1_EEEE
#25 0x00000059739c _ZN4base8internal7InvokerINS0_9BindStateIMNS_9TestSuiteEFivEJNS0_17UnretainedWrapperIS3_EEEEEFivEE3RunEPNS0_13BindStateBaseE
#26 0x00000051e6ab base::internal::RunMixin<>::Run()
#27 0x00000132c2a9 base::(anonymous namespace)::LaunchUnitTestsInternal()
#28 0x00000132c114 base::LaunchUnitTests()
#29 0x0000005971fe main
#30 0x7f7293feb7ed __libc_start_main
#31 0x0000004a0d85 <unknown>
  r8: 00007f728c0f2980  r9: 00007ffca86a0588 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffca86a0a98 r13: 0000000000000038 r14: 0000000000000001 r15: 0000000000000000
  di: 0000000000001539  si: 0000000000001539  bp: 0000000000000002  bx: 00007ffca86a0a28
  dx: 0000000000000006  ax: 0000000000000000  cx: ffffffffffffffff  sp: 00007ffca86a05d8
  ip: 00007f7294000035 efl: 0000000000000206 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
[772/772] ChromotingHostTest.ConnectWhenAnotherClientIsConnected (CRASHED)
1 test crashed:
    ChromotingHostTest.ConnectWhenAnotherClientIsConnected (../../remoting/host/chromoting_host_unittest.cc:291)
Tests took 9 seconds.

Original issue's description:
> Don't use barcodes in ProtocolPerfTests
>
> Previously the perf tests were using a unique barcode to identify video
> frames when measuring latency. This is not longer necessary. Now the
> tests will use fake input event timestamps and video stats messages to
> measure latency.
>
> Committed: https://crrev.com/69d9c4d4f5a66e0f7bcf02c40058d7d2e122300b
> Cr-Commit-Position: refs/heads/master@{#425895}

TBR=jamiewalch@chromium.org,sergeyu@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2431513003