Update patch set 2
Patch Set 2:

Adenilson, got some bad news.
All of Chromium's Android targets have a minimum of ARMv7 and thus always support NEON. But the Cronet component (which relies on zlib) also targets ARMv6.

In file included from ../../third_party/zlib/contrib/arm/chunkcopy.h:10:
/b/build/slave/Android_Cronet_ARMv6_Builder/build/src/third_party/llvm-build/Release+Asserts/lib/clang/6.0.0/include/arm_neon.h:28:2: error: "NEON support not enabled"
#error "NEON support not enabled"

The BUILD.gn already checks for arm_use_neon. Maybe Cronet doesn't set that?

Patch-set: 2
Reviewer: Chris Blume <1189229@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>