Revert of Enable gpu_times for all platforms other than windows. (patchset #1 id:1 of https://codereview.chromium.org/1029423002/)
Reason for revert:

I'm seeing most perf bots failing gpu_times ever since this landed (Eg.
http://goo.gl/uLzMVe).

I missed this earlier because we had a bunch of persistent redness today caused by multiple bad V8 rolls and didn't notice this crept in as well.

Failure is just on cuteoverload.com with this error:
MarkerMismatchError: Number or order of timeline markers does not match provided labels

Original issue's description:
> Enable gpu_times for all platforms other than windows.
>
> R=nednguyen@google.com
> BUG=453131, 455292
>
> Committed: https://crrev.com/95325bb92cdce4b3c4fd93ae3509e72f89536c9c
> Cr-Commit-Position: refs/heads/master@{#322273}

TBR=nednguyen@google.com,dyen@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=453131, 455292

Review URL: https://codereview.chromium.org/1039083002