The port of r1943 failed to compile becuase of:
71>.\main.cc(227) : error C3861: 'GetInstallReturnCode': identifier not found

I've just removed the check because it seems the check for !incremental_install
is adequate.

If there's another check that should be here, let me know and I will add it.

TBR= kuchhal@chromium.org
Review URL: http://codereview.chromium.org/2830

git-svn-id: svn://svn.chromium.org/chrome/branches/chrome_official_branch/src@2189 0039d316-1c4b-4281-b951-d872f2087c98