Roll pdfium to 905cc10ecd.
https://codereview.chromium.org/1259123005 broke the clang/win bots thusly:

..\..\third_party\pdfium\core\src\fxge\ge\fx_ge_fontmap.cpp(456,7) :
error: field 'm_pFontInfo' will be initialized after field
'm_bListLoaded' [-Werror,-Wreorder]
    : m_pFontInfo(nullptr),
      ^

905cc10 fixed this, so roll pdfium forward in the hope of fixing the clang/win
bots.

905cc10  Add CFX_FontFaceInfo constructor.
2526930  Early object closing in PDF via premature 'endobj' keyword
8d8a990  Remove the unused IFX_StreamRead::SetRange() mechanism.
2b91781  CPDF_Parser shouldnt be in the business of opening files
5cd3985  FPDF_Creator can only create file through embedder-supplied callback.

BUG=82385,493126
R=thestig@chromium.org
TBR=thestig@chromium.org

Review URL: https://codereview.chromium.org/1274263005 .