Revert of [tracing] Add browser-side tests for memory dumps. (patchset #2 id:20001 of https://codereview.chromium.org/1295753002/ )
Reason for revert:
This CL flakily causes failures on try bots, specifically in SingleProcessMemoryTracingTest.BrowserInitiatedSingleDump:

c:\b\build\slave\win_builder__dbg_\build\src\content\browser\tracing\memory_tracing_browsertest.cc(142): error: Mock function called more times than expected - returning default value.
    Function call: OnMemoryDump(@3286BA0C 4-byte object \u003C01-00 00-00>, 3286B920)
          Returns: false
         Expected: to be called once
           Actual: called twice - over-saturated and active

On Win7 - https://build.chromium.org/p/chromium.win/builders/Win7%20Tests%20%28dbg%29%281%29/builds/40855

and ../../content/browser/tracing/memory_tracing_browsertest.cc:148: Failure
Value of: last_callback_success_
  Actual: false
Expected: true

on Mac 10.8: https://build.chromium.org/p/chromium.mac/builders/Mac10.8%20Tests/builds/6628

Original issue's description:
> [tracing] Add browser-side tests for memory dumps.
>
> This is a rebase of https://codereview.chromium.org/1064413002. The
> `OverlappingRequests` test has been removed.
>
> Committed: https://crrev.com/a4c2539f13510a650d51e65204ea52426979659c
> Cr-Commit-Position: refs/heads/master@{#343408}

TBR=primiano@chromium.org,dsinclair@chromium.org,ruuda@google.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1294833004