Update patch set 4
Patch Set 4:

Hi, I'm not sure whether this CL causes a build error from clean build. Or do I miss something?

----------------------------------------------
My args.gn
----------------------------------------------
use_goma = true
is_component_build = true
is_debug = true
use_ozone = true
target_os = "chromeos"
enable_wayland_server = true
dcheck_always_on = true


----------------------------------------------
Error log:
----------------------------------------------
ninja: Entering directory `out/Default'
[1/8] python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libash.so" --tocfile="./libash.so.TOC" --output="./libash.so"  -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -Werror -Wl,--gdb-index -Wl,--fatal-warnings -nostdlib++ --sysroot=../../build/linux/debian_stretch_amd64-sysroot -L../../build/linux/debian_stretch_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_stretch_amd64-sysroot/lib/x86_64-linux-gnu -L../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath=\$ORIGIN/. -Wl,-rpath-link=. -o "./libash.so" -Wl,-soname="libash.so" @"./libash.so.rsp"
FAILED: libash.so libash.so.TOC 
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libash.so" --tocfile="./libash.so.TOC" --output="./libash.so"  -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -Werror -Wl,--gdb-index -Wl,--fatal-warnings -nostdlib++ --sysroot=../../build/linux/debian_stretch_amd64-sysroot -L../../build/linux/debian_stretch_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_stretch_amd64-sysroot/lib/x86_64-linux-gnu -L../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath=\$ORIGIN/. -Wl,-rpath-link=. -o "./libash.so" -Wl,-soname="libash.so" @"./libash.so.rsp"
obj/ash/ash/tablet_power_button_controller.o:tablet_power_button_controller.cc:function ash::TabletPowerButtonController::OnPowerButtonEvent(bool, base::TimeTicks const&): error: undefined reference to 'ash::TabletPowerButtonController::kScreenStateChangeDelay'
obj/ash/ash/tablet_power_button_controller.o:tablet_power_button_controller.cc:function ash::TabletPowerButtonController::OnPowerButtonEvent(bool, base::TimeTicks const&): error: undefined reference to 'ash::TabletPowerButtonController::kIgnoreRepeatedButtonUpDelay'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Patch-set: 4
CC: Jiaquan He <1145089@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>