Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> (3 comments)
> 
> Thank you very much! This is very useful work, and I'm grateful that you're doing it.
> 
> Let's see how this fares with the trybots before we plan next steps.

Apparently fuzz tests are being broke by omit callback

./sqlite3_ossfuzz_fuzzer
./../third_party/sqlite/fuzz/ossfuzz.c:59: error: undefined reference to 'sqlite3_progress_handler'

I'm removing this omit flag on the next patch.

Patch-set: 1
Reviewer: Claudio M. D. Souza Junior <1140375@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>