Revert of Add Store+Sync to reading list. (patchset #20 id:380001 of https://codereview.chromium.org/2451843002/ )
Reason for revert:
Failing compile on ios-simulator-xcode-clang:

reading_list_store_unittest.cc:75:12: error: no viable conversion from returned value of type 'unique_ptr<TestModelTypeChangeProcessor>' to function return type 'unique_ptr<syncer::ModelTypeChangeProcessor>'
    return processor;
           ^~~~~~~~~

It isn't legal to return a unique_ptr<B> from a function that returns
unique_ptr<A> even if A is a base class. You need to explicitly declare
|processor| to have type unique_ptr<syncer::ModelTypeChangeProcessor>.
I'm not sure why this wasn't picked up by the try bots.

Original issue's description:
> Add Store+Sync to reading list.
>
> This CL creates a ModelTypeService for reading list.
> This service will store persistent data for the Reading list model and sync
> data between devices.
>
> The previous store using NSUserDefaults will not be cleaned.
> As it was only accessible from canary behind an experimental flag, no user
> should be affected.
>
> BUG=661668
>
> Committed: https://crrev.com/faa080c524c6a80c2ac276359e29dec8cf7946c4
> Cr-Commit-Position: refs/heads/master@{#432845}

TBR=pavely@chromium.org,skym@chromium.org,jif@chromium.org,olivierrobin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=661668

Review URL: https://codereview.chromium.org/2507053005 .