Revert of ash/mash: Add a mus-client that sets up ash to provide the system ui for mash. (patchset #5 id:80001 of https://codereview.chromium.org/1676713002/ )
Reason for revert:
This CL is breaking the build. See https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20GN%20%28dbg%29/builds/17919

The linker error is
[1834/2095] SOLINK ./libash_sysui_library.so
FAILED: python "/b/build/slave/Linux_ChromiumOS_GN__dbg_/build/src/build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm"  --sofile="./libash_sysui_library.so" --tocfile="./libash_sysui_library.so.TOC" --output="./libash_sysui_library.so" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -B../../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -Wl,--icf=all -pthread -m64 -Wl,--export-dynamic -o "./libash_sysui_library.so" -Wl,-soname="libash_sysui_library.so" @"./libash_sysui_library.so.rsp"
../../ash/mus/shell_delegate_mus.cc:23: error: undefined reference to 'user_manager::UserInfoImpl::UserInfoImpl()'
../../ash/mus/sysui_application.cc:126: error: undefined reference to 'message_center::MessageCenter::Initialize()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Original issue's description:
> ash/mash: Add a mus-client that sets up ash to provide the system ui for mash.
>
> We only want a small number of the components of ash (e.g. shelf, wallpaper,
> system-tray, app-list) etc. for mash, but for now, the mus-client loads all of
> ash. The bare minimum set of delegates have stub implementations. These will
> grow as we hook them up with other mojo/mus services.
>
> BUG=585141
>
> Committed: https://crrev.com/dfd7833ae942a8339853ed02907bb31e0806badc
> Cr-Commit-Position: refs/heads/master@{#374470}

TBR=sky@chromium.org,vmpstr@chromium.org,sadrul@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=585141

Review URL: https://codereview.chromium.org/1683853003