Revert "[Merge to M61] Add minimal migration support"
This reverts commit 6f97f8e886c05c9a5b5237a7ff1be677f54c5d7b.

Reason for revert: breaks compile
chromeos/cryptohome/homedir_methods.cc:223:43: error: variable has incomplete type 'cryptohome::MigrateToDircryptoRequest'
chromeos/dbus/cryptohome_client.cc:941:46: error: no member named 'kCryptohomeMigrateToDircryptoEx' in namespace 'cryptohome'
chromeos/dbus/cryptohome_client.cc:948:38: error: no viable conversion from 'const cryptohome::MigrateToDircryptoRequest' to 'const google::protobuf::MessageLite'


Original change's description:
> [Merge to M61] Add minimal migration support
> 
> This is a cherry-pick of two CLs to M61:
> - Add minimal migration support
>   https://chromium-review.googlesource.com/612086
> - Commit minimal migration status to local state prefs
>   https://chromium-review.googlesource.com/647454
> 
> I lumped them together because the second commit is a bugfix
> for a possible race condition in the first commit, and so that
> it could be reverted without problems.
> 
> ---
> Commit minimal migration status to local state prefs
> 
> Commit minimal migration status to local state PrefService.
> Introduces a CommitPendingWrite function with a callback to be sure that
> prefs landed on disk.
> 
> ---
> Add minimal migration support
> 
> Add EcryptfsMigrationStrategy value MINIMAL_MIGRATE, which performs a
> minimal ext4 migration, with only few files (esp. auth tokens and
> channel binding information) whitelisted. This is similar to WIPE but
> ensures that the user won't have to enter their password twice.
> 
> We monitor how long the minimal migration takes, and if it is longer
> than 45 seconds, require a password re-entry for privacy reasons.
> 
> Depends on Chrome OS side CL:
> https://chromium-review.googlesource.com/c/612249.
> 
> BUG=747907
> TEST=unit_tests --gtest_filter=EncryptionMigrationScreenHandlerTest*
>      Manual test with pre-existing ecryptfs user profile and user policy
>      EcryptfsMigrationStrategy set to MINIMAL_MIGRATE(4).
> 
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: Ib09cf759f0e277456e15b714bf2d879ea1d82402
> Reviewed-on: https://chromium-review.googlesource.com/652999
> Reviewed-by: Pavol Marko <pmarko@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3163@{#1123}
> Cr-Branched-From: ff259bab28b35d242e10186cd63af7ed404fae0d-refs/heads/master@{#488528}

TBR=pmarko@chromium.org

Change-Id: Ic02611eb11365f56e052acdf91d9768dc7223dd0
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 747907
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation