Revert of Add 200MS delay before starting toolbar scale animation (patchset #2 id:20001 of https://codereview.chromium.org/1389293003/ )
Reason for revert:
Breaks the Android Builder

[17814/24986] ACTION Packaging ui_android_unittests
Warning: org.chromium.test.reporter.TestStatusReporter: can't find referenced
method 'void postOnUiThreadDelayed(java.lang.Runnable,long)' in class
org.chromium.base.ThreadUtils
Warning: org.chromium.test.reporter.TestStatusReporter$1: can't find referenced
method 'void postOnUiThreadDelayed(java.lang.Runnable,long)' in class
org.chromium.base.ThreadUtils
Warning: there were 2 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile them and try again.
         Alternatively, you may have to specify the option
         '-dontskipnonpubliclibraryclassmembers'.
Error: Please correct the above warnings first.

https://build.chromium.org/p/chromium/builders/Android/builds/48738

Original issue's description:
> Add 200MS delay before starting toolbar scale animation
>
> Title scale-down animation might happen at a too early stage, making
> users confused about what they see. This CL adds a 200MS delay between
> toolbar initialization and the time we decide to start to animate.
>
> BUG=505620
>
> Committed: https://crrev.com/36f275146662f6067e34695a97e98bd146c47379
> Cr-Commit-Position: refs/heads/master@{#358862}

TBR=yusufo@chromium.org,yfriedman@chromium.org,ianwen@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=505620

Review URL: https://codereview.chromium.org/1438583003