Revert "Switch Mac to use time_exploded_posix.cc."
This reverts commit dcb7897c8ab8914a67a8eb4467772432875685b1.

Reason for revert: Caused compile errors on iso-device-xcode-clang.

https://build.chromium.org/p/chromium.mac/builders/ios-device-xcode-clang/builds/43807

../../net/cert/x509_certificate.cc:100:24: error: comparison of constant 2147483647 with expression of type 'const uint16_t' (aka 'const unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
  if (generalized.year > base::Time::kExplodedMaxYear) {
      ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../net/cert/x509_certificate.cc:104:24: error: comparison of constant -2147483648 with expression of type 'const uint16_t' (aka 'const unsigned short') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
  if (generalized.year < base::Time::kExplodedMinYear) {
      ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

Original change's description:
> Switch Mac to use time_exploded_posix.cc.
> 
> Previously, we would use a CoreFoundation-based version of these
> functions implemented in time_mac.cc because time_t on Mac was
> capped at year 2038. However, with 64-bit that is no longer the
> case and we can just use time_exploded_posix.cc.
> 
> From UMA sampling profiler data (see bug), we know that the
> CoreFoundation versions of these functions are slow and currently
> account for around 80ms cost during startup. After this change
> is submitted and makes it to Canary, we can see how the POSIX
> versions of these functions perform - hopefully much faster than
> the CoreFoundation ones.
> 
> Some code in net/ had assumptions around the min and max years
> that are supported on different platforms by these functions. To
> make that logic a bit cleaner, this CL introduces two constants
> in time.h specifying the platform-specific limits - so that
> downstream code like net can use them instead of baking their
> own assumptions. Some net error codes are changing as a result
> of this clean up - which can be seen in the updated net tests.
> 
> BUG=781601
> 
> Cq-Include-Trybots: master.tryserver.chromium.android:android_cronet_tester;master.tryserver.chromium.mac:ios-simulator-cronet
> Change-Id: I2cf030fd4d3ed8da87e41bc8ba3dc3b1b99e8f6d
> Reviewed-on: https://chromium-review.googlesource.com/754079
> Commit-Queue: Alexei Svitkine <asvitkine@chromium.org>
> Reviewed-by: Matt Mueller <mattm@chromium.org>
> Reviewed-by: Yuri Wiitala <miu@chromium.org>
> Reviewed-by: Mark Mentovai <mark@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#515062}

TBR=miu@chromium.org,mattm@chromium.org,asvitkine@chromium.org,mmenke@chromium.org,mark@chromium.org

Change-Id: I260bd4e8e0ab98580ba22646e5d66d56e8933d63
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 781601
Cq-Include-Trybots: master.tryserver.chromium.android:android_cronet_tester;master.tryserver.chromium.mac:ios-simulator-cronet