Revert "Re-land: Add localized default audio device names."
Seems to be causing failurs on Windows 7 Intel:

http://build.chromium.org/p/chromium.gpu.fyi/builders/Win7%20Release%20%28Intel%29/builds/13657

[ RUN      ] AudioManagerTest.EnumerateOutputDevices
c:\b\build\slave\gpu_win_builder\build\src\media\audio\audio_manager_unittest.cc(95):
error: Expected: (AudioManager::GetDefaultDeviceName()) !=
(it->device_name), actual: "FakeString" vs "FakeString"
[  FAILED  ] AudioManagerTest.EnumerateOutputDevices (0 ms)

[ RUN      ] AudioManagerTest.EnumerateOutputDevicesWinMMDevice
c:\b\build\slave\gpu_win_builder\build\src\media\audio\audio_manager_unittest.cc(95):
error: Expected: (AudioManager::GetDefaultDeviceName()) !=
(it->device_name), actual: "FakeString" vs "FakeString"
[  FAILED  ] AudioManagerTest.EnumerateOutputDevicesWinMMDevice (3 ms)

BUG=497001
TBR=thakis@chromium.org,ajm@chromium.org,dalecurtis@chromium.org

This reverts commit c82ba18e50843b4bfecb1238205db4c23b533d91.

Review URL: https://codereview.chromium.org/1381433002