Add missing .Pass() on return of SampleVector
On VS2015 without this causes:

d:\src\cr3\src\base\metrics\histogram.cc(372): error C2248: 'scoped_ptr<base::SampleVector,base::DefaultDeleter<T>>::scoped_ptr': cannot access private member declared in class 'scoped_ptr<base::SampleVector,base::DefaultDeleter<T>>'
        with
        [
            T=base::SampleVector
        ]
d:\src\cr3\src\base\memory\scoped_ptr.h(312): note: see declaration of 'scoped_ptr<base::SampleVector,base::DefaultDeleter<T>>::scoped_ptr'
        with
        [
            T=base::SampleVector
        ]

I'm not entirely sure why this doesn't happen on earlier compilers,
I guess something's move-ability changed.

R=isherman@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/882783002