Revert of Allow build under GTK+ 2.24. (patchset #1 id:1 of https://codereview.chromium.org/813823003/)
Reason for revert:
broke GoogleChrome Linux Build
http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux/builds/38993

FAILED: cd ../../chrome; flock -- /tmp/linux_package_lock bash ../out/Release/installer/debian/build.sh -o../out/Release -b ../out/Release -a ia32 -c stable
dpkg-shlibdeps: warning: binaries to analyze should already be installed in their package's directory.
13c13
< libglib2.0-0 (>= 2.28.0)
---
> libglib2.0-0 (>= 2.26.0)

ERROR: Shared library dependencies changed!
If this is intentional, please update:
chrome/installer/linux/debian/expected_deps_ia32
chrome/installer/linux/debian/expected_deps_x64

Probably you need to change those expected_deps files too.

Original issue's description:
> Allow build under GTK+ 2.24.
>
> Some parts of libgtk2ui use newer function and #define names than what's in
> GTK+ 2.24, which is what ships with RHEL/CentOS 6.6. This commit allows
> Chromium to work on RHEL/CentOS 6.6 by checking for the appropriate GTK version
> and using the appropriate API.
>
> This is the same as the already reviewed issue 806843004, just submitted from
> the correct email address.
> https://codereview.chromium.org/806843004/
>
> BUG=443005
> R=erg@chromium.org
>
> Committed: https://crrev.com/5cd198a55b73f7f32e5e8225aa6d8ac0bc39a2fb
> Cr-Commit-Position: refs/heads/master@{#308883}

TBR=erg@chromium.org,ian.scott@arteris.com
NOTREECHECKS=true
NOTRY=true
BUG=443005

Review URL: https://codereview.chromium.org/814723002