Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> msw@, I need some help with this, please.
> 
> The change is causing a failure on the win_chromium_rel_ng bot in gfx_unittests (Windows-7-SP1) on RenderTextTest.ElidedText/HarfBuzz.  One particular line fails:
> ../../ui/gfx/render_text_unittest.cc(1043): error:       Expected: WideToUTF16(cases[i].display_text)
>       Which is: L"012\xF0\x2026"
> To be equal to: render_text->GetDisplayText()
>       Which is: L"012\xF0\x9D\x2026"
> Google Test trace:
> ../../ui/gfx/render_text_unittest.cc(1028): Testing cases[22] '012??'
> 
> This test passes on linux (bots and my workstation).
> 
> I don't know how Windows and Linux differ in their rendertext implements to understand why it can fail on one platform instead of the other, not can I read / understand unicode enough to figure out what that test case is meant to test.  (Too bad it wasn't commented like many of other unicode-like tests in the file.)
> 
> You reviewed the original change by skanuj@ that landed this test.
> https://codereview.chromium.org/119813002
> 
> This means I have at least three reasons you might have knowledge I don't that could help figure this out.
> 
> Please. :-)
> 
> thanks,
> mark

The RenderText code should be almost completely shared between the two platforms, but there are two reasons I can imagine that Windows and Linux would differ here. My first guess was fonts (since this test uses actual layout/shaping sizes and not set_glyph_width_for_test). But, this test case is odd... BreakIterator::IsGraphemeBoundary might differ by platform here; I'm not sure exactly how/why, but here's my thought:

The failure is that one extra character is being rendered before the ellipsis. In the input, "\xF0\x9D\x84\x9E" is the UTF-8 multi-char sequence for MUSICAL SYMBOL G CLEF '𝄞'. I find it very odd that we expect the output to include the first UTF-8 character of that sequence before the ellipsis. The first character "\xF0" alone would seem to be latin small letter eth 'ð', which really doesn't seem like an elided representation of the full text (ie. we shouldn't elide '𝄞' as 'ð…'); the width of that glyph might also determine the final outcome of the test case (since we determine the clamping width from the expected final text).

I suggest changing the test case's expected |display_text| to L"012\x2026", which would eliminate the entire musical symbol. Hopefully that simply works on all platforms, and doing so would eliminate a really strange test case, which we honestly shouldn't expect...

If you encounter other issues, I do wonder if the terminating condition of the loop is indeed correct, given the approximations of "|text_width| is actually the length of text.length(), not text.length()-1" and "|lo_width| may have been calculated from |lo| minus one, not |lo|".

Patch-set: 4
Reviewer: Michael Wasserman <1001118@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>