Revert "VR: Format omnibox suggestion text"
This reverts commit ae83c7b322fb358846cd8d44d59d73a9d7224b3b.

Reason for revert: Breaks compile on at least linux-chromeos-rel

https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium.chromiumos%2Flinux-chromeos-rel%2F4396%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

../../chrome/browser/vr/testapp/vr_test_context.cc:495:23: error: no member named 'MakeUnique' in namespace 'base'
  auto result = base::MakeUnique<OmniboxSuggestions>();

Original change's description:
> VR: Format omnibox suggestion text
> 
> This CL introduces a generic means of formatting single-line Text UI
> elements, and uses it to apply the already-supplied suggestion
> formatting to the appropriate elements.
> 
> BUG=799176
> 
> Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
> Change-Id: I355e8f97254b3c19c2506363f6f2685bf8976a52
> Reviewed-on: https://chromium-review.googlesource.com/868991
> Commit-Queue: Christopher Grant <cjgrant@chromium.org>
> Reviewed-by: Ian Vollick <vollick@chromium.org>
> Reviewed-by: Yash Malik <ymalik@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#529833}

TBR=vollick@chromium.org,cjgrant@chromium.org,ymalik@chromium.org

Change-Id: Ia299da20888617e3ebdacbc997dfc51a027eb072
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 799176
Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel