Revert "Align 'IsPotentiallyTrustworthy' with the spec for `localhost`."
This reverts commit 8da2a80724a9b896890602ff77ef2216cb951399.

Reason for revert: Fails CTS


[FAIL] android.webkit.cts.WebSettingsTest#testAllowMixedMode:
junit.framework.AssertionFailedError: expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:199)
	at junit.framework.Assert.assertEquals(Assert.java:205)
	at android.webkit.cts.WebSettingsTest.testAllowMixedMode(WebSettingsTest.java:983)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)

See https://crbug.com/412058#c25

Original change's description:
> Align 'IsPotentiallyTrustworthy' with the spec for `localhost`.
> 
> This patch brings our treatment of localhost names into line with the
> secure contexts spec, which is ~safe enough to do since we're locking
> DNS resolution for `localhost` to loopback addresses as of
> https://chromium-review.googlesource.com/c/chromium/src/+/598068.
> 
> This has a few impacts:
> 
> * `http://*.localhost` subresources will not be treated as mixed content.
> * `http://*.localhost` top-level documents will be considered secure contexts.
> 
> Intent to Ship: https://groups.google.com/a/chromium.org/d/msg/blink-dev/RC9dSw-O3fE/E3_0XaT0BAAJ
> 
> Bug: 412058
> Change-Id: I3df040e233ebb6c40f098bc45246415f63249451
> Reviewed-on: https://chromium-review.googlesource.com/702277
> Reviewed-by: Ryan Sleevi <rsleevi@chromium.org>
> Reviewed-by: Bo <boliu@chromium.org>
> Reviewed-by: Emily Stark <estark@chromium.org>
> Commit-Queue: Mike West <mkwst@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#510678}

TBR=rsleevi@chromium.org,boliu@chromium.org,estark@chromium.org,yolandyan@chromium.org,mkwst@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 412058
Change-Id: Ib208848042eeb8fd2bcfadaba36050bb8ce9c0f9