Fix build error caused by core/editing/commands/EditingState.h
This patch fixed following compilation error introduced by crrev.com/374111
in  chromeos_x86-generic_chromium_compile_only_ng

../../third_party/WebKit/Source/core/editing/commands/CompositeEditCommand.cpp: In member function 'void blink::CompositeEditCommand::appendNode(WTF::RawPtr<blink::Node>, WTF::RawPtr<blink::ContainerNode>, blink::EditingState*)':
../../third_party/WebKit/Source/core/editing/commands/CompositeEditCommand.cpp:379:89: error: 'ASSERT_IN_EDITING_COMMAND' was not declared in this scope
         || (parent->isElementNode() && toElement(parent.get())->tagQName() == objectTag));

BUG=n/a
NOTRY=true
TBR=yosin@chrmium.org

Review URL: https://codereview.chromium.org/1676333003