Revert of Revert of Update V8 to version 3.31.23 (based on d15d453fa5aaeeb1f7e010a1baf71e7b3306802b). (patchset #1 id:1 of https://codereview.chromium.org/762683002/)
Reason for revert:
This wasn't the problem; the expected dependencies just needed to be updated. Unreverting.

Original issue's description:
> Revert of Update V8 to version 3.31.23 (based on d15d453fa5aaeeb1f7e010a1baf71e7b3306802b). (patchset #1 id:1 of https://codereview.chromium.org/749183003/)
>
> Reason for revert:
> Suspect may be the cause of linux compile error:
>
> ERROR: Shared library dependencies changed!
>
> Original issue's description:
> > Update V8 to version 3.31.23 (based on d15d453fa5aaeeb1f7e010a1baf71e7b3306802b).
> >
> > TBR=machenbach@chromium.org
> >
> > Committed: https://crrev.com/9ed94cd05fbf85ab5a2075c4bc33c2dd2127a086
> > Cr-Commit-Position: refs/heads/master@{#305708}
>
> TBR=machenbach@chromium.org,v8-autoroll@chromium.org
> NOTREECHECKS=true
> NOTRY=true
>
> Committed: https://crrev.com/89aeeb85a7764141312230d3d96c96cffa961861
> Cr-Commit-Position: refs/heads/master@{#305753}

TBR=machenbach@chromium.org,v8-autoroll@chromium.org,rlp@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/748223006