Update patch set 5
Patch Set 5:

(5 comments)

LG but it looks like this CL (or a dependent CL) introduces a dependency from ios_components_unittests to test_hooks via many paths (BrowserViewController, MainController, ...). I do not think this is correct as ios_components_unittests should not depend on anything in ios/chrome as far as I can tell.

This is causing the following compilation failure:

Undefined symbols for architecture x86_64:
  "tests_hook::DisableFirstRun()", referenced from:
      -[MainController createInitialUI:] in main_controller.o
      -[BrowserViewController presentViewController:animated:completion:] in browser_view_controller.o
  "tests_hook::RunTestsIfPresent()", referenced from:
      -[MainController startUpBrowserForegroundInitialization] in main_controller.o
  "tests_hook::DisableGeolocation()", referenced from:
      -[LocationManager locationServicesEnabled] in location_manager.o
  "tests_hook::SetUpTestsIfPresent()", referenced from:
      -[MainController startUpBrowserForegroundInitialization] in main_controller.o
  "tests_hook::DisableContextualSearch()", referenced from:
      +[TouchToSearchPermissionsMediator isTouchToSearchAvailableOnDevice] in touch_to_search_permissions_mediator.o
  "tests_hook::DisableSigninRecallPromo()", referenced from:
      +[SigninPromoViewController shouldBePresentedForBrowserState:] in signin_promo_view_controller.o
ld: symbol(s) not found for architecture x86_64
[11557/12078] LINK obj/ios/components/x64/ios_components_unittests

Additionally, is it possible to add test for any of the newly added classes?

Patch-set: 5
Reviewer: Sylvain Defresne <1116027@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>