Compilation fails due to missing namespace
../../ui/accessibility/platform/atk_util_auralinux_gtk2.cc:59:6: error: use of undeclared identifier 'AtkUtilAuraLinux'; did you mean 'ui::AtkUtilAuraLinux'?
bool AtkUtilAuraLinux::PlatformShouldEnableAccessibility() {
     ^~~~~~~~~~~~~~~~
     ui::AtkUtilAuraLinux
../../ui/accessibility/platform/atk_util_auralinux.h:17:7: note: 'ui::AtkUtilAuraLinux' declared here
class AtkUtilAuraLinux {
      ^
../../ui/accessibility/platform/atk_util_auralinux_gtk2.cc:74:6: error: use of undeclared identifier 'AtkUtilAuraLinux'; did you mean 'ui::AtkUtilAuraLinux'?
void AtkUtilAuraLinux::PlatformInitializeAsync() {
     ^~~~~~~~~~~~~~~~
     ui::AtkUtilAuraLinux
../../ui/accessibility/platform/atk_util_auralinux.h:17:7: note: 'ui::AtkUtilAuraLinux' declared here
class AtkUtilAuraLinux {
      ^
2 errors generated.
Change-Id: I0b683c6d1f193dfabf8ff1beac8572220262e5a3