Update patch set 3
Patch Set 3:

while i'm able to repro them locally, i don't understand these closure compiler errors at all:

(ERROR) Error in: power.js
## /b/build/slave/linux/build/src/chrome/browser/resources/settings/device_page/power.js:74: ERROR - Bad type annotation. Unknown type chrome.settingsPrivate.PrefObject
##     /** @private {chrome.settingsPrivate.PrefObject} */
##                   ^
## 
## /b/build/slave/linux/build/src/chrome/browser/resources/settings/device_page/power.js:78: ERROR - Bad type annotation. Unknown type chrome.settingsPrivate.PrefObject
##         return /** @type {chrome.settingsPrivate.PrefObject} */ ({});
##                           ^
## 
## /b/build/slave/linux/build/src/chrome/browser/resources/settings/device_page/power.js:218: ERROR - Property settingsPrivate never defined on chrome
##       type: chrome.settingsPrivate.PrefType.BOOLEAN,
##                    ^^^^^^^^^^^^^^^
...

what do i need to do to make chrome.settingsPrivate visible within my .js file? display.js is using it as well, but i can't see what it (or display.html) is doing that power.js isn't.

Patch-set: 3
Reviewer: Dan Erat <1000042@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0