Add missing dependency for //sandbox/linux:seccomp_starter_android
Commit 5fb31977a3765bdece87afb6f5ae55331a627ade added this new target but
didn't depend on the //sandbox:sandbox_features target so it failed to
compile:

In file included from ../../sandbox/linux/seccomp-bpf-helpers/seccomp_starter_android.cc:5:                                                                       
../../sandbox/linux/seccomp-bpf-helpers/seccomp_starter_android.h:10:10: fatal error: 'sandbox/sandbox_features.h' file not found                                 
#include "sandbox/sandbox_features.h"                                                                                                                             

NOTRY=true

Bug: 742028
Bug: 730066
Bug: 739879
Change-Id: Ib0bc9f34f0cbf35be0f9f3cf412cd0fdcf678f3f