Revert of libyuv work around for drmemory bug on pinsrw instruction (patchset #6 id:100001 of https://codereview.chromium.org/1457103002/ )
Reason for revert:
breaks compilation:

third_party/libyuv/source/row_gcc.cc:1809:5: error: inline assembly requires more registers than available
    "sub       %[u_buf],%[v_buf]               \n"

Original issue's description:
> libyuv work around for drmemory bug on pinsrw instruction
>
> drmemory v1.5 flags pinsrw reads of 2 bytes as a memory exception.
> version 1.9 resolves this, but pinsrw behavior is not well defined,
> and can read up to 16 bytes depending on the cpu.
> On current generation intel cpus, its quite slow, so switching to
> movd or movzx improves performance.  This CL uses movzx which reads
> 2 bytes, but is slightly slower than movd.
> The AVX2 version of this function uses movd as it reads 4 bytes at
> a time, so performance of SSSE3 version only impacts older intel
> cpus.
>
> Was I411ToARGB_Opt (906 ms)
> Now I411ToARGB_Opt (624 ms)
>
> Full list of revisions
> https://chromium.googlesource.com/libyuv/libyuv/+log/1019e453..b7dfb725
>
> R=xhwang@chromium.org
> BUG=libyuv:525
>
> Committed: https://crrev.com/35e5706a4ab85555b6dc21139783436263e6af3f
> Cr-Commit-Position: refs/heads/master@{#360759}

TBR=xhwang@chromium.org,fbarchard@chromium.org,fbarchard@google.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=libyuv:525

Review URL: https://codereview.chromium.org/1456383004