Revert of Move NegotiatingClientAuthentication creation to ChromotingClient. (patchset #2 id:40001 of https://codereview.chromium.org/1778023002/ )
Reason for revert:
Appears to be breaking compile on Linux and Mac:
https://build.chromium.org/p/chromium/builders/Linux/builds/72875

https://build.chromium.org/p/chromium/builders/Mac/builds/13060

Output:

FAILED: /b/build/slave/Linux/build/src/build/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ ... -c ../../remoting/test/chromoting_test_fixture.cc -o obj/remoting/test/chromoting_test_driver.chromoting_test_fixture.o
In file included from ../../remoting/test/chromoting_test_fixture.cc:14:
In file included from ../../remoting/test/test_chromoting_client.h:14:
In file included from ../../remoting/client/chromoting_client.h:19:
In file included from ../../remoting/protocol/negotiating_client_authenticator.h:15:
In file included from ../../remoting/protocol/negotiating_authenticator_base.h:16:
../../third_party/webrtc/libjingle/xmllite/xmlelement.h:17:10: fatal error: 'webrtc/libjingle/xmllite/qname.h' file not found
#include "webrtc/libjingle/xmllite/qname.h"
         ^
1 error generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> Move NegotiatingClientAuthentication creation to ChromotingClient.
>
> For the new SPAKE2 authenticator we need to pass client_jid
> to the authenticator. This wasn't possible previously because
> NegotiatingClientAuthenticator was created before signaling is
> connected. Moved NegotiatingClientAuthentication creation to
> ChromotingClient.
>
> BUG=589698
>
> Committed: https://crrev.com/279bf7c76a3e0bfbbd28748d0d02fcead88f4436
> Cr-Commit-Position: refs/heads/master@{#380779}

TBR=jamiewalch@chromium.org,sergeyu@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=589698

Review URL: https://codereview.chromium.org/1788943002