Fix 160>.\plugin_tests.cc(147) : error C2440: 'initializing' : cannot convert from 'std::wstring' to 'FilePath' 160>        Constructor for class 'FilePath' is declared 'explicit' TBR=jam
Review URL: http://codereview.chromium.org/108027

git-svn-id: svn://svn.chromium.org/chrome/branches/172/src@15314 0039d316-1c4b-4281-b951-d872f2087c98