Fix VC++ 2017 STL break with deque iterator
circular_deque_const_iterator has non-const versions of operator* and
operator->. The VC++ 2017 STL implementation of vector::assign ends up
with const iterators (reasonable enough) and then cannot dereference
them, leading to this error:

include\xmemory(125): error C2678: binary '*': no operator found which
takes a left-hand operand of type 'const base::internal::circular_deque_iterator<T>'

when compiling:

output.assign(history_.begin(), history_.end());

in components\drive\event_logger.cc. The fix is to tag the functions as
const.

Note that this breakage happens with both the clang and VC++ 2017
compilers, whenever the VC++ 2017 STL is used.

BUG=683729

Change-Id: Id6aad72017015cfbb16673fee1f1009d10ed6602