Add missing dependencies on bindings generators for loader
This showed up on Fuchsia (see linked bug), but is cross-platform.

The dependency on mojo_bindings is for:

In file included from ../../third_party/WebKit/Source/platform/loader/fetch/ResourceTimingInfo.cpp:5:
In file included from ../../third_party/WebKit/Source/platform/loader/fetch/ResourceTimingInfo.h:37:
In file included from ../../third_party/WebKit/Source/platform/loader/fetch/ResourceResponse.h:42:
../../third_party/WebKit/public/platform/WebURLResponse.h:42:10: fatal error: 'public/platform/modules/fetch/fetch_api_request.mojom-shared.h' file not found

The dependency on make_platform_generated is for:

In file included from ../../third_party/WebKit/Source/platform/loader/fetch/ResourceTimingInfo.h:36:
../../third_party/WebKit/Source/platform/loader/fetch/ResourceRequest.h:32:10: fatal error: 'platform/HTTPNames.h' file not found

Bug: 758381
Change-Id: I0c8737beae0d6a2be12ccfa8d976bd4f203b4bca