Revert of Added tombstones in instrumentation tests results. (patchset #11 id:200001 of https://codereview.chromium.org/2201833002/ )
Reason for revert:
This breaks the stack_tool_for_tombstones step for many bots in https://build.chromium.org/p/chromium.android, like this:
W    0.547s Main  No tombstones.
Traceback (most recent call last):
  File "/b/c/b/Android_Webview_L__dbg_/src/build/android/tombstones.py", line 304, in <module>
    sys.exit(main())
  File "/b/c/b/Android_Webview_L__dbg_/src/build/android/tombstones.py", line 300, in main
W    0.547s Main  No tombstones to resolve.
    for line in resolved_tombstones:
TypeError: 'NoneType' object is not iterable

Please make sure to have proper tests in place before relanding.

Original issue's description:
> Added tombstones in instrumentation tests results.
>
> If an instrumentation test crashes, the cl will grab the tombstones and
> add the tombstones as a part of the result.
>
> BUG=631213
>
> Committed: https://crrev.com/d7dd97f2828447fb9af45ea119e703500b167cb8
> Cr-Commit-Position: refs/heads/master@{#410929}

TBR=mikecase@chromium.org,jbudorick@chromium.org,hzl@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=631213

Review-Url: https://codereview.chromium.org/2231693002