Update patch set 2
Patch Set 2:

danakj, can you please take a look? This is the cause of some interesting errors in the jni generator:

In file included from gen/base/base_jumbo_6.cc:10:
In file included from ./../../base/threading/platform_thread_android.cc:14:
In file included from ../../base/android/jni_android.h:8:
../../third_party/android_tools/ndk/platforms/android-16/arch-arm/usr/include/jni.h:642:5: error: no member named 'CalllongMethodV' in 'JNINativeInterface'; did you mean 'CallLongMethodV'?
    CALL_TYPE(jlong, Long)
    ^

Patch-set: 2
Reviewer: danakj <1000887@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Daniel Bratell <1114374@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false