Revert of Roll Clang 214024:216630 (+216684) and switch to CMake (patchset #20 id:380001 of https://codereview.chromium.org/453513004/)
Reason for revert:
Builds failing with:

../../third_party/skia/include/core/SkRect.h:280:25: error: reference cannot be bound to dereferenced null pointer in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]
        SkASSERT(&a && &b);
                    ~~  ^
../../third_party/skia/include/core/SkTypes.h:96:56: note: expanded from macro 'SkASSERT'
    #define SkASSERT(cond)              SK_ALWAYSBREAK(cond)
                                                       ^
../../third_party/skia/include/core/SkPostConfig.h:173:19: note: expanded from macro 'SK_ALWAYSBREAK'
              if (cond) break; \
                  ^

(From http://build.chromium.org/p/chromium.linux/builders/Linux%20GN%20%28dbg%29/builds/12335/steps/compile/logs/stdio)

Original issue's description:
> Roll Clang 214024:216630 (+216684) and switch to CMake
>
> This updates Chromium's clang version to r216630 with
> r216684 cherry-picked to fix an ASan issue.
>
> It also changes the build script for Clang to use CMake
> instead of Autoconf. The ASan team say this configuration
> is better tested, and it also makes us consistent with
> the Windows Clang build which already uses CMake.
>
> BUG=400849
> R=thakis@chromium.org
>
> Committed: https://chromium.googlesource.com/chromium/src/+/ff31c1ba254ca37f7a8b45549e1b7b1c978b3390

TBR=thakis@chromium.org,samsonov@google.com,eugenis@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=400849

Review URL: https://codereview.chromium.org/567443003