Reland of ll closure compiler and update sources (patchset #1 id:1 of https://codereview.chromium.org/1661853004/ )
Reason for revert:
My revert is breaking the compile

note: Running closure compiler on suggestion_controller.js
note: Running closure compiler on autofill_controller.js
java -jar ../third_party/closure_compiler/compiler/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS "--jscomp_error=accessControls" "--jscomp_error=ambiguousFunctionDecl" "--jscomp_error=constantProperty" "--jscomp_error=deprecated" "--jscomp_error=externsValidation" "--jscomp_error=globalThis" "--jscomp_error=invalidCasts" "--jscomp_error=nonStandardJsDocs" "--jscomp_error=suspiciousCode" "--jscomp_error=undefinedNames" "--jscomp_error=unknownDefines" "--jscomp_error=uselessCode" "--jscomp_error=visibility" --js "autofill/ios/browser/resources/suggestion_controller.js" --js_output_file "/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/suggestion_controller.js"
java -jar ../third_party/closure_compiler/compiler/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS "--jscomp_error=accessControls" "--jscomp_error=ambiguousFunctionDecl" "--jscomp_error=constantProperty" "--jscomp_error=deprecated" "--jscomp_error=externsValidation" "--jscomp_error=globalThis" "--jscomp_error=invalidCasts" "--jscomp_error=nonStandardJsDocs" "--jscomp_error=suspiciousCode" "--jscomp_error=undefinedNames" "--jscomp_error=unknownDefines" "--jscomp_error=uselessCode" "--jscomp_error=visibility" --js "autofill/ios/browser/resources/autofill_controller.js" --js_output_file "/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/autofill_controller.js"
Error: Invalid or corrupt jarfile ../third_party/closure_compiler/compiler/compiler.jarError: Invalid or corrupt jarfile ../third_party/closure_compiler/compiler/compiler.jar

make: *** [/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/autofill_controller.js] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/b/build/slave/iOS_Device/build/src/xcodebuild/DerivedSources/Release/suggestion_controller.js] Error 1
Command /bin/sh failed with exit code 2

Original issue's description:
> Revert of Roll closure compiler and update sources (patchset #6 id:140001 of https://codereview.chromium.org/1473723002/ )
>
> Reason for revert:
> Breaks the FirstRunUIBrowserTest.FirstRunFlow
>
> See the log while it's hot:
> https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Tests%20%28dbg%29%281%29/builds/11491/steps/browser_tests/logs/FirstRunUIBrowserTest.FirstRunFlow
>
> Relevant bits:
> ...
> [28690:28690:0202/170602:ERROR:CONSOLE(31)] "Uncaught Error: Assertion failed: [object SVGSVGElement] is not a[n] HTMLElement", source: chrome://resources/js/util.js (31)
> BrowserTestBase signal handler received SIGTERM. Backtrace:
> #0 0x7f32d1d6496e base::debug::StackTrace::StackTrace()
> #1 0x0000024791da content::(anonymous namespace)::DumpStackTraceSignalHandler()
> #2 0x7f32bf3a7150 <unknown>
> #3 0x7f32bf4589d3 __poll
> #4 0x7f32c0142ff6 <unknown>
> ....
>
> Original issue's description:
> > Roll closure compiler and update sources
> >
> > Change log:
> > https://github.com/google/closure-compiler/compare/53f3d8a41579c002ec656bb645ce5d54470f6e0b...972497be96e537b8eee93fbeb367ede9c878df7a
> > chrome_extensions.js: 56292b9c2ae3991e75c0c8d5e86ef91a94058d2e -> a40c181d7d0f0e35ced922d0d8c935821b8ab214
> >
> > Update $() to return HTMLElement.
> > Add a base.getHtmlElement to remoting.
> >
> > BUG=
> > R=dbeam@chromium.org, hirono@chromium.org, jamiewalch@chromium.org, stevenjb@chromium.org
> >
> > Committed: https://chromium.googlesource.com/chromium/src/+/3d7d66a9c117d92000e87d75509bdc12d79aa455
>
> TBR=dbeam@chromium.org,tbreisacher@chromium.org,jamiewalch@chromium.org,mtomasz@chromium.org,hirono@chromium.org,stevenjb@chromium.org,rdevlin.cronin@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=
>
> Committed: https://crrev.com/9f7d03b5af98c508629ed52a18fa222e6996db5f
> Cr-Commit-Position: refs/heads/master@{#373233}

TBR=dbeam@chromium.org,tbreisacher@chromium.org,jamiewalch@chromium.org,mtomasz@chromium.org,hirono@chromium.org,stevenjb@chromium.org,rdevlin.cronin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/1660373003