Revert of O(1) descendant slots by keeping track of insertion/removal of slots in a shadow tree. (patchset #4 id:60001 of https://codereview.chromium.org/1589903002/ )
Reason for revert:
Caused compiler failure on oilpan bots:
../../third_party/WebKit/Source/core/dom/shadow/ShadowRoot.cpp:352:5: error: static_assert failed "Garbage collected static local needs to be wrapped up with a persistent reference"
    DEFINE_STATIC_LOCAL(WillBeHeapVector<RefPtrWillBeMember<HTMLSlotElement>>, emptyList, ());
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/WebKit/Source/wtf/StdLibExtras.h:86:5: note: expanded from macro 'DEFINE_STATIC_LOCAL'
    STATIC_ASSERT_FOR_LOCAL_WITH_GARBAGE_COLLECTED_TYPE(Name, Type); \
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/WebKit/Source/wtf/StdLibExtras.h:68:5: note: expanded from macro 'STATIC_ASSERT_FOR_LOCAL_WITH_GARBAGE_COLLECTED_TYPE'
    static_assert(!WTF::IsGarbageCollectedType<Name##NoReferenceType>::value || WTF::IsPersistentReferenceType<Name##NoReferenceType>::value, "Garbage collected static local needs to be wrapped up with a persistent reference")

Original issue's description:
> O(1) descendant slots by keeping track of insertion/removal of slots in a shadow tree.
>
> In slots assigning, we have to traverse a shadow tree to collect all slot elements in the tree.
> This may take O(N), where N is the number of a node in the tree.
>
> To make it O(1) amortized, this CL keeps track of insertion or removal of slot elements
> and re-use the previous result if nothing has changed.
>
> According to the micro benchmark, v1-distribution.html, which is included in this CL,
> the distribution calculation became 20% faster, in case of N=100.
>
> With this CL:    avg 6680.41 runs/s
> Without this CL: avg 5486.71 runs/s
>
> BUG=531990
>
> Committed: https://crrev.com/7c3c73ac4cec5fff67b4e24f29c22fbdcd14655f
> Cr-Commit-Position: refs/heads/master@{#369992}

TBR=tkent@chromium.org,kochi@chromium.org,yuzus@chromium.org,hayato@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=531990

Review URL: https://codereview.chromium.org/1604443002