Revert of Fix ProcessUtilTest.GetTerminationStatusCrash on Android L+ (patchset #2 id:20001 of https://codereview.chromium.org/1241333002/)
Reason for revert:
This patch broke the mips builder for Android

../../third_party/lss/linux_syscall_support.h:121:21: fatal error: sgidefs.h: No
such file or directory
 #include <sgidefs.h>

Original issue's description:
> Fix ProcessUtilTest.GetTerminationStatusCrash on Android L+
>
> On Android L+, signal and sigaction symbols are provided by libsigchain
> that override the system's versions. There is a bug in these functions
> where they essentially ignore requests to install SIG_DFL. This causes
> ProcessUtilTest.GetTerminationStatusCrash to fail (as
> CrashingChildProcess goes into infinite loop instead of crashing).
>
> Workaround this issue by explicitly performing a syscall to
> __NR_rt_sigaction to install SIG_DFL on Android, as breakpad does
> (see https://breakpad.appspot.com/1804002/).
>
> BUG=512255
> TEST=ProcessUtilTest.GetTerminationStatusCrash
>
> Committed: https://crrev.com/31510fe3e2d3b1f3123f391db52372b2506c46ca
> Cr-Commit-Position: refs/heads/master@{#339584}

TBR=thakis@chromium.org,primiano@chromium.org,cullinan@amazon.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=512255

Review URL: https://codereview.chromium.org/1247023002