Revert "Delivers drag and drop methods from Surface to DataDevice."
This reverts commit c59f62607a029f9247374a0c2bea418c7eec77b8.

Reason for revert: Broke compilation on Linux ChromiumOS Builder (dbg)

../../components/exo/data_device_delegate.h:28: error: undefined reference to 'vtable for exo::DataDeviceDelegate'
../../third_party/binutils/Linux_x64/Release/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original change's description:
> Delivers drag and drop methods from Surface to DataDevice.
> 
> The CL lets Surface observe drag and drop events and delegates the events to
> DataDevice thorugh DataDeviceManager.
> 
> Bug: b:31988797
> Test: None
> Change-Id: I9574cd86137922d7527bd297d182a7b45e632c9e
> Reviewed-on: https://chromium-review.googlesource.com/579250
> Commit-Queue: Daichi Hirono <hirono@chromium.org>
> Reviewed-by: David Reveman <reveman@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#491951}

TBR=reveman@chromium.org,hirono@chromium.org,hidehiko@chromium.org

Change-Id: Ie770510e27a19b94f5e621ef41d24138c219104c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: b:31988797