Explicit WTF:: qualifier for passed, unretained, wrapUnique and makeUnique.
The functions listed in the title of the CL description exist both in
WTF:: and in base:: namespaces and differ only by the case (uppercase vs
lowercase) of the first character in their identifiers.  This will lead
to compile errors after renaming the WTF functions to follow Chromium
style (PascalCaseFunctionNames) because of |using| statements that today
enable the WTF functions to be used without namespace qualification -
such usage will be ambiguous after the rename.  Example:

    ../../third_party/WebKit/Source/platform/WaitableEvent.cpp:17:11:
    error: call to 'WrapUnique' is ambiguous
      impl_ = WrapUnique(new base::WaitableEvent(
              ^~~~~~~~~~
    ../../base/memory/ptr_util.h:17:20:
    note: candidate function [with T = base::WaitableEvent]
    std::unique_ptr<T> WrapUnique(T* ptr) {
                       ^
    ../../third_party/WebKit/Source/wtf/PtrUtil.h:16:20:
    note: candidate function [with T = base::WaitableEvent]
    std::unique_ptr<T> WrapUnique(T* ptr) {
                       ^
This CL
1) adds WTF:: namespace qualifier to all calls to the affected WTF
   functions
2) removes |using| statements that import the affected WTF functions
   into the global namespace

The second change means that failure to namespace-qualify a call will be
a compile error (e.g. error: use of undeclared identifier 'WrapUnique')
when the argument doesn't come from base or WTF namespace (preventing
reoccurence of the problem in these cases).  When the argument comes
from base or WTF namespace, then ADL will pick the function from the
corresponding namespace.

The Google C++ Style Guide allows using type aliases (including |using
other_namespace::Foo|), although it also says to prefer placing
nonmember functions in a namespace and to use completely global
functions rarely.  The guide also explicitly says "You may not use a
using-directive to make all names from a namespace available" - this is
not what WTF is doing here, but I guess one could argue that all the
individual |using WTF::foo| declarations taken together are not that
different from just doing |using namespace WTF|.  FWIW, I don't see
(grepping for 'using.*base') any |using| statement in a header file
under //base that would pull a name from base:: into the global
namespace (except using base::PathService which is there for legacy
reasons).  References:
- https://google.github.io/styleguide/cppguide.html#Aliases
- https://google.github.io/styleguide/cppguide.html#Namespaces
- https://google.github.io/styleguide/cppguide.html#Nonmember,_Static_Member,_and_Global_Functions

This CL was generated in a fairly mechanical way:
- Run the following under third_party/WebKit/Source for (passed,
  unretained, wrapUnique):
  $ ag '\bpassed\b\(' -l | xargs -n 1 \
      sed -e 's/\([^:]\)\bpassed\b(/\1WTF::passed(/g' -i
- Run the following under third_party/WebKit/Source (for makeUnique):
  $ ag '\bmakeUnique' -l | xargs -n 1 \
      sed -e 's/\([^:]\)\bmakeUnique<\(.*\)>(/\1WTF::makeUnique<\2>(/g' -i
- Manually remove |using WTF::foo| declarations.
- Manually fixup function definitions (where no WTF:: qualifier should
  be used).
- git cl format
- Manually fix formatting inside comments.
- Do a self-review.

Affected functions:
- third_party/WebKit/Source/wtf/PtrUtil.h:
  - WTF::wrapUnique / base::WrapUnique
  - WTF::makeUnique / base::MakeUnique
- third_party/WebKit/Source/wtf/Functional.h:
  - WTF::passed / base::Passed
  - WTF::unretained / base::Unretained

Note that there are a lot more using statements under WTF that can
potentially conflict with things from other namespaces.  This CL tweaks
only names that are known to cause compile failures after the automatic
rename from blinkStyleFunctions into ChromiumStyleFunctions.  In
particular, the following things are not tweaked by this CL:
- wtf/ASCIICType.h (e.g. WTF::isASCIILower function)
- wtf/AutoReset.h (WTF::AutoReset class)
- wtf/text/Base64.h (e.g. WTF::base64Encode function)
- wtf/Time.h (e.g. WTF::TimeDelta class)

BUG=670908
CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_layout_tests_slimming_paint_v2

Review-Url: https://codereview.chromium.org/2547053003