Revert of Disabled two IPC messages on ChromeOS (patchset #1 id:1 of https://codereview.chromium.org/1221523002/)
Reason for revert:
Likely broke ChromiumOS build:

../../components/printing/test/print_web_view_helper_browsertest.cc: In member function 'void printing::PrintWebViewHelperTestBase::VerifyPagesPrinted(bool)':
../../components/printing/test/print_web_view_helper_browsertest.cc:198:14: error: 'PrintHostMsg_TempFileForPrintingWritten' has not been declared
              PrintHostMsg_TempFileForPrintingWritten::ID) != NULL);

Original issue's description:
> Disabled two IPC messages on ChromeOS
>
> PrintHostMsg_AllocateTempFileForPrinting and
> PrintHostMsg_TempFileForPrintingWritten were used only
> by Cloud Print Dialog.
>
> BUG=408684
>
> Committed: https://crrev.com/3401f2836863aaee76e2115bc502820a149774c9
> Cr-Commit-Position: refs/heads/master@{#336614}

TBR=inferno@chromium.org,jschuh@chromium.org,nasko@chromium.org,vitalybuka@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=408684

Review URL: https://codereview.chromium.org/1214183005