Revert of Add a presubmit check that warns about declaring Singleton<T> in header files (patchset #2 id:20001 of https://codereview.chromium.org/929043002/)
Reason for revert:
Reverting because of presubmit crashes:

Traceback (most recent call last):
  File "/usr/local/google/ssd/depot_tools/git_cl.py", line 2983, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/google/ssd/depot_tools/git_cl.py", line 2969, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/google/ssd/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/usr/local/google/ssd/depot_tools/git_cl.py", line 1614, in CMDpresubmit
    change=cl.GetChange(base_branch, None))
  File "/usr/local/google/ssd/depot_tools/git_cl.py", line 936, in RunHook
    rietveld_obj=self.RpcServer())
  File "/usr/local/google/ssd/depot_tools/presubmit_support.py", line 1396, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "/usr/local/google/ssd/depot_tools/presubmit_support.py", line 1313, in ExecPresubmitScript
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File "<string>", line 1727, in CheckChangeOnCommit
  File "<string>", line 1455, in _CommonChecks
  File "<string>", line 1322, in _CheckSingletonInHeaders
  File "/usr/local/google/ssd/depot_tools/presubmit_support.py", line 472, in ReadFile
    raise IOError('Access outside the repository root is denied.')
IOError: Access outside the repository root is denied.

Original issue's description:
> Add a presubmit check that warns about declaring Singleton<T> in header files
> (except for base/memory/singleton.h)
> This check is copied from presubmit_canned_checks.py in depot_tools/ with an
> added exception for base/memory/singleton.h.
> The corresponding code will be removed from presubmit_canned_checks.py afterwards.
>
> BUG=349861
> R=phajdan.jr@chromium.org,
>
> Committed: https://crrev.com/9b73d0393037452d13358f4e2766cb62adbdede8
> Cr-Commit-Position: refs/heads/master@{#316546}

TBR=phajdan.jr@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=349861

Review URL: https://codereview.chromium.org/934723003