Partially fix compilation of chrome with Xcode 7 (OS X 10.11 SDK).
Use a local variable so that Xcode knows which -setDelegate: method
is invoked (it seems that -[NSApplication sharedApplication] return
value is sub-typed).

Fixes the following error (only the listing the first few lines):
../../chrome/app_shim/chrome_main_app_mode_mac.mm:159:3: error: multiple methods named 'setDelegate:' found [-Werror,-Wobjc-multiple-method-names]
  [[NSApplication sharedApplication] setDelegate:delegate_];
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSApplication.h:167:56: note: using
@property (nullable, assign) id<NSApplicationDelegate> delegate;
                                                       ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSFileManager.h:129:57: note: also found
@property (nullable, assign) id <NSFileManagerDelegate> delegate NS_AVAILABLE(10_5, 2_0);
                                                        ^~~~~~~~

BUG=517914

Review URL: https://codereview.chromium.org/1339563003