Revert "Create the flag to override the pinned state in MessageView"
This reverts commit 033d4edf16c6a9191f1eea32de0417179c4731ba.

Reason for revert: breaks compile

FAILED: obj/ui/message_center/message_center/notification_view_md.obj 
ninja -t msvc -e environment.x64 -- "c:\b\c\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/ui/message_center/message_center/notification_view_md.obj.rsp /c ../../ui/message_center/views/notification_view_md.cc /Foobj/ui/message_center/message_center/notification_view_md.obj /Fd"obj/ui/message_center/message_center_cc.pdb"
../../ui/message_center/views/notification_view_md.cc(567): error C2039: 'UpdateControlButtonsVisibilityWithNotification': is not a member of 'message_center::NotificationViewMD'

Original change's description:
> Create the flag to override the pinned state in MessageView
> 
> We should ignore the pinned state on popup notification. This CL adds a flag to override the state.
> 
> This CL also removes the duplicated "pinned" flag in ArcNotificationItem, since we already have the flag in MessageView.
> 
> This change affects only for Chrome OS, since the pinned state is efficient only on Chrome OS.
> 
> TBR=yoshiki@chromium.org
> 
> (cherry picked from commit a701b1b2c9b63981ad0a56bc793b9175cb33ba1f)
> 
> Bug: 755891
> Change-Id: I51c626a29f4e8f8bf9a292d0c63b8afa86b95907
> Reviewed-on: https://chromium-review.googlesource.com/609393
> Commit-Queue: Yoshiki Iguchi <yoshiki@chromium.org>
> Reviewed-by: Yuichiro Hanada <yhanada@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#495154}
> Reviewed-on: https://chromium-review.googlesource.com/645409
> Reviewed-by: Yoshiki Iguchi <yoshiki@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3163@{#1030}
> Cr-Branched-From: ff259bab28b35d242e10186cd63af7ed404fae0d-refs/heads/master@{#488528}

TBR=yoshiki@chromium.org,yhanada@chromium.org

Change-Id: I3beed3634dec8faafa0761e6ace9e7cb45e4751b
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 755891, 760909