Update patch set 4
Patch Set 4:

CQ is trying da patch.

Note: The patchset sent to CQ was uploaded after this CL was approved.
"error c2071 on win no need to export class member" https://chromium-review.googlesource.com/c/656201/4

Follow status at: https://chromium-cq-status.appspot.com/v2/patch-status/chromium-review.googlesource.com/656201/4

Bot data: {"action": "start", "triggered_at": "2017-09-14T00:57:32.0Z", "cq_cfg_revision": "3afac2bac2b2a53f9e1a33d082a3e64f7e1ab983", "revision": "d8bdb6e724c6e4148d68209612794dd8d9fb834b"}

Patch-set: 4
Tag: autogenerated:cq:full-run