Add missing #include
core_winrt_util.h references ScopedHString without a definition of it
necessarily being in scope. This slipped by because the reference is in
a template. However when compiling with /permissive- this error is
caught. The fix is to add the necessary #include.

With this fix (and the Fall Creators Update SDK) I can build base
cleanly with /permissive-.

The error message was:

    c:\src\chromium3\src\base\win\core_winrt_util.h(48):
        error C2760: syntax error: expected ';' not 'identifier'

Change-Id: Iac5729b617c8915e1a52eef3fa2c282c00bf90bc