Revert "Android: Add --wait-for-java-debugger to test_runner.py"
This reverts commit d77bb0d5597845d282f38df6dbc9a8207cae0b84.

Reason for revert: Fails on Android Cronet Perf bot(s).

I    0.000s Main  command: /b/build/slave/Android_Cronet_x86_Builder/build/src/build/android/test_runner.py perf --release --verbose --steps /tmp/tmpXHMqQY.json --blacklist-file /b/build/slave/Android_Cronet_x86_Builder/build/src/out/bad_devices.json --num-retries 0 --collect-chartjson-data --trace-output /tmp/test_runner_traceD1Y0JQ/test_trace.json --adb-path /b/build/slave/Android_Cronet_x86_Builder/build/src/third_party/android_tools/sdk/platform-tools/adb
E    0.001s Main  Unrecognized error occurred.
Traceback (most recent call last):
  File "/b/build/slave/Android_Cronet_x86_Builder/build/src/build/android/test_runner.py", line 1001, in main
    return RunTestsCommand(args)
  File "/b/build/slave/Android_Cronet_x86_Builder/build/src/build/android/test_runner.py", line 745, in RunTestsCommand
    return RunTestsInPlatformMode(args)
  File "/b/build/slave/Android_Cronet_x86_Builder/build/src/build/android/test_runner.py", line 850, in RunTestsInPlatformMode
    env = environment_factory.CreateEnvironment(args, infra_error)
  File "/b/build/slave/Android_Cronet_x86_Builder/build/src/build/android/pylib/base/environment_factory.py", line 13, in CreateEnvironment
    return local_device_environment.LocalDeviceEnvironment(args, error_func)
  File "/b/build/slave/Android_Cronet_x86_Builder/build/src/build/android/pylib/local/device/local_device_environment.py", line 148, in __init__
    self._wait_for_java_debugger = args.wait_for_java_debugger
AttributeError: 'Namespace' object has no attribute 'wait_for_java_debugger'
step returned non-zero exit code: 1

Original change's description:
> Android: Add --wait-for-java-debugger to test_runner.py
> 
> I used this to debug test listing in the instrumentation test runner.
> This is nicer that using set-debug-app separately, because it disables
> all timeouts (or else the process gets killed as you're debugging).
> 
> Change-Id: I7cd58c747534b3b539afcc84fcbae48475c4d9c3
> Reviewed-on: https://chromium-review.googlesource.com/693218
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Reviewed-by: Yoland Yan <yolandyan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#506049}

TBR=agrieve@chromium.org,yolandyan@chromium.org

Change-Id: I7cf9a5e3c52f29b24df77e0e27eb6272416c5f30
No-Presubmit: true
No-Tree-Checks: true
No-Try: true