Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> tyoshino@ and foolip@, I faced presubmit errors. But I don't understand the errors well. Why should console error messages include error message? Could you please let me know it?
> 
> ** Presubmit ERRORS **
> * The following files are passing testharness results without console error messages, they should be removed:
>  /b/build/slave/linux/build/src/third_party/WebKit/LayoutTests/external/wpt/XMLHttpRequest/setrequestheader-bogus-name-expected.txt
>  /b/build/slave/linux/build/src/third_party/WebKit/LayoutTests/external/wpt/XMLHttpRequest/setrequestheader-bogus-value-expected.txt
> ERROR: found passing testharness results without console error messages.

This means you can just remove those two files, since there are now no failures in there. Yay!

Patch-set: 1
Reviewer: Philip Jägenstedt <1157920@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>