Revert of MD Settings: make custom UIs look "actionable" (patchset #3 id:40001 of https://codereview.chromium.org/2094813002/ )
Reason for revert:
This CL causes SettingLanguagesBrowserTest.LanguagesPage to fail on ChromiumOS and Win7 (confirmed by building ChromeOS locally in Release, observing the failure, reverting the CL, and seeing that the failure goes away). Example failure: https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Tests%20%281%29/builds/21718/steps/browser_tests%20on%20Ubuntu-12.04/logs/SettingsLanguagesPageBrowserTest.LanguagesPage.

Relevant snippet from test output:

[11504:11504:0624/023830:INFO:CONSOLE(1196)] "Running TestCase SettingsLanguagesPageBrowserTest.MAYBE_LanguagesPage", source: test_api.js (1196)
[11504:11504:0624/023830:ERROR:CONSOLE(44)] "Mocha test failed: languages page manage languages
AssertionError: expected false to be true
    at Function.assert.isTrue (chai.js:2423:31)
    at assertTrue (test_api.js:851:17)
    at Context.<anonymous> (languages_page_browsertest.js:81:7)
", source: mocha_adapter.js (44)

Original issue's description:
> MD Settings: make custom UIs look "actionable"
>
> Currently, that just entails a cursor: pointer; but may involve e.g. a
> :hover effect in the future.
>
> This introduces the shared variable:
>
>   --settings-actionable: {
>     cursor: pointer;
>   };
>
> which can be used from places that don't want all the settings shared
> style (which generally applies to the sections in the middle).
>
>   .my-custom-thing {
>     @apply(--settings-actionable);
>   }
>
> For stuff inside of <settings-main> (or code otherwise using
> settings-shared), it's probably easier to just use the new:
>
>   [actionable] {
>     @apply(--settings-actionable);
>   }
>
> and just annotate your element with that attribute, i.e.
>
>   <div id="frobber" on-tap="onFrobberTap_" actionable>
>
> FYI: This CL is semi-automatedly generated via:
>
>   vim -p `git grep -l on-tap -- chrome/browser/resources/settings`
>
> and lots of hacking.
>
> R=dpapad@chromium.org
> BUG=611826
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.linux:closure_compilation
>
> Committed: https://crrev.com/a298aa9c3276b78073a61613787909a0b2427302
> Cr-Commit-Position: refs/heads/master@{#401763}

TBR=dpapad@chromium.org,dbeam@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=611826

Review-Url: https://codereview.chromium.org/2089313005