Revert of cc::CompositorFrame: Implement ParamTraits vs. StructTraits perf test (patchset #6 id:100001 of https://codereview.chromium.org/2109863002/ )
Reason for revert:
Compile error on Mac GYP (dbg) builds:

../../cc/ipc/cc_serialization_perftest.cc:10:10: fatal error: 'cc/ipc/compositor_frame.mojom.h' file not found
#include "cc/ipc/compositor_frame.mojom.h"

http://build.chromium.org/p/chromium.mac/builders/Mac%20GYP%20%28dbg%29/builds/583/steps/compile/logs/stdio

Original issue's description:
> cc::CompositorFrame: Implement ParamTraits vs. StructTraits perf test
>
> This CL modifies the existing cc ParamTraits perf test to
> also perform the equivalent test using Mojo StructTraits,
> and compares the two side by side.
>
> This CL creates CompositorFrames with SolidColorDrawQuads
> instead of PictureDrawQuads because PictureDrawQuads are
> not serialized by other ParamTraits or StructTraits.
>
> Finally, this CL renames CCParamTraitsPerfTest to
> CCSerializationPerfTest to better capture what it does.
>
> BUG=624459
> CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel
>
> Committed: https://crrev.com/0409a7c70ee6087295121da095b5520c2fe14499
> Cr-Commit-Position: refs/heads/master@{#404011}

TBR=yzshen@chromium.org,danakj@chromium.org,dcheng@chromium.org,fsamuel@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=624459

Review-Url: https://codereview.chromium.org/2125833004