Revert of clang plugin: Compute absolute paths on Windows as well. (patchset #6 id:100001 of https://codereview.chromium.org/2318733002/ )
Reason for revert:
The bots are sad. From https://build.chromium.org/p/chromium.fyi/builders/ClangToTLinux%20%28dbg%29/builds/4060/steps/gclient%20runhooks/logs/stdio

/b/c/b/ClangToTLinux__dbg_/src/tools/clang/plugins/ChromeClassTester.cpp: In member function ‘bool ChromeClassTester::InBannedDirectory(clang::SourceLocation)’:
/b/c/b/ClangToTLinux__dbg_/src/tools/clang/plugins/ChromeClassTester.cpp:129:41: error: ‘resolvedPath’ was not declared in this scope
   } else if (realpath(filename.c_str(), resolvedPath)) {
                                         ^
/b/c/b/ClangToTLinux__dbg_/src/tools/clang/plugins/ChromeClassTester.cpp:130:33: error: redeclaration of ‘char resolvedPath [4096]’
     char resolvedPath[MAXPATHLEN];
                                 ^
/b/c/b/ClangToTLinux__dbg_/src/tools/clang/plugins/ChromeClassTester.cpp:129:41: error: ‘<typeprefixerror>resolvedPath’ previously declared here
   } else if (realpath(filename.c_str(), resolvedPath)) {
                                         ^

Original issue's description:
> clang plugin: Compute absolute paths on Windows as well.
>
> The motivation is to suppress diagnostics on the v8 bot,
> which have "v8" somewhere on the path, but not in the
> filename segments the compiler sees.  This makes the
> behavior on Windows match the behavior on non-Windows.
>
> BUG=644096
> NOTRY=true
>
> Committed: https://crrev.com/df0eb747fca2699d116ad80d0ccbd967317fdbd4
> Cr-Commit-Position: refs/heads/master@{#417701}

TBR=dcheng@chromium.org,thakis@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=644096

Review-Url: https://codereview.chromium.org/2323273004