Revert of [DevTools] Remove extra plumbing from InspectorWorkerAgent, prepare to multi-client. (patchset #3 id:40001 of https://codereview.chromium.org/1774323002/ )
Reason for revert:
Seems to have broken compile on WebKit Linux non-Oilpan Builder:

https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20non-Oilpan%20Builder/builds/2317

Output snippet:
In file included from ../../third_party/WebKit/Source/core/inspector/PageConsoleAgent.cpp:31:
In file included from ../../third_party/WebKit/Source/core/inspector/PageConsoleAgent.h:35:
In file included from ../../third_party/WebKit/Source/core/inspector/InspectorConsoleAgent.h:29:
In file included from ../../third_party/WebKit/Source/core/inspector/InspectorBaseAgent.h:35:
In file included from ../../third_party/WebKit/Source/core/inspector/InstrumentingAgents.h:1:
In file included from gen/blink/core/InstrumentingAgentsInl.h:7:
In file included from ../../third_party/WebKit/Source/platform/heap/Handle.h:35:
In file included from ../../third_party/WebKit/Source/platform/heap/HeapAllocator.h:9:
../../third_party/WebKit/Source/platform/heap/TraceTraits.h:173:5: error: static_assert failed "T should be traced"
    static_assert(WTF::NeedsTracing<T>::value || WTF::IsWeak<T>::value, "T should be traced");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../third_party/WebKit/Source/platform/heap/Visitor.h:193:24: note: in instantiation of member function 'blink::TraceTrait<WTF::HashSet<WTF::RawPtr<blink::WorkerInspectorProxy>, WTF::PtrHash<WTF::RawPtr<blink::WorkerInspectorProxy> >, WTF::HashTraits<WTF::RawPtr<blink::WorkerInspectorProxy> >, WTF::PartitionAllocator> >::trace' requested here
        TraceTrait<T>::trace(Derived::fromHelper(this), &const_cast<T&>(t));
                       ^
../../third_party/WebKit/Source/core/inspector/PageConsoleAgent.cpp:67:14: note: in instantiation of function template specialization 'blink::VisitorHelper<blink::Visitor>::trace<WTF::HashSet<WTF::RawPtr<blink::WorkerInspectorProxy>, WTF::PtrHash<WTF::RawPtr<blink::WorkerInspectorProxy> >, WTF::HashTraits<WTF::RawPtr<blink::WorkerInspectorProxy> >, WTF::PartitionAllocator> >' requested here
    visitor->trace(m_workersWithEnabledConsole);
             ^
../../third_party/WebKit/Source/core/inspector/PageConsoleAgent.cpp:63:1: note: in instantiation of function template specialization 'blink::PageConsoleAgent::traceImpl<blink::Visitor *>' requested here
DEFINE_TRACE(PageConsoleAgent)
^
../../third_party/WebKit/Source/platform/heap/Visitor.h:77:39: note: expanded from macro 'DEFINE_TRACE'
    void T::trace(Visitor* visitor) { traceImpl(visitor); }                    \
                                      ^

Original issue's description:
> [DevTools] Remove extra plumbing from InspectorWorkerAgent, prepare to multi-client.
>
> For multiclient, we will move the global collection of WorkerInspectorProxy objects
> to a static collection in WorkerInspectorProxy class.
>
> BUG=590878
>
> Committed: https://crrev.com/fe63b6b42585c51c7ab9a3b158b20d08d5b552dd
> Cr-Commit-Position: refs/heads/master@{#380666}

TBR=pfeldman@chromium.org,dgozman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=590878

Review URL: https://codereview.chromium.org/1777323004