Revert of [DevTools] Migrate DevToolsTracingHandler to generated handler. (patchset #6 id:130001 of https://codereview.chromium.org/635733003/)
Reason for revert:
Broke compile, e.g. obj/content/gen/content/browser/devtools/protocol/content_browser.devtools_protocol_handler_impl.o
gen/content/browser/devtools/protocol/devtools_protocol_handler_impl.cc:951:7: error: no viable conversion from 'std::string' (aka 'basic_string<char>') to 'const std::string *' (aka 'const basic_string<char> *')
      in_categories,
      ^~~~~~~~~~~~~
../../content/browser/devtools/protocol/tracing_handler.h:40:26: note: passing argument to parameter 'categories' here
      const std::string* categories,
                         ^
1 error generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> [DevTools] Migrate DevToolsTracingHandler to generated handler.
>
> This patch also adds SendRawMessage, which is used for performance
> in tracing handler.
>
> BUG=405566
>
> Committed: https://crrev.com/f7762cb9261c8e2e15f2cf2b36f5408c75d72bdd
> Cr-Commit-Position: refs/heads/master@{#300711}

TBR=caseq@chromium.org,vkuzkokov@chromium.org,dgozman@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=405566

Review URL: https://codereview.chromium.org/675473005