remoting: Remove duplicate remoting_perftests dependency
This dependency is duplicated below under the enable_remoting_host==1
condition, and doesn't exist when that condition is false. This fixes
the following error when remoting=1 enable_remoting_host=0:

KeyError: '/ssd/src/chromium/src/remoting/remoting.gyp:remoting_perftests#target'

BUG=none
TEST=GYP_DEFINES='use_ozone=1' gclient runhooks

Review URL: https://codereview.chromium.org/1351143003