Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> Oops, I thought that you used "unsigned char" as the underlying type.
> 
> My only concern is how we can detect a possible future overrun of the bit fields (not limited to this case, in general).  We're now using static_cast.  Do compilers will warn anything?  Then, I have no worry.

The static_cast is not used to narrow (from the full enum to the bitfield), only to expand the value from the bitfield into the the enum, so it's not lossy.

The only risk of loss due to narrowing to the bit field width would be when we initialize these structs. Fortunately, clang has a warning (-Wbitfield-constant-conversion) for this case when a constant is used to initialize, as it is by our generated code. Build failure looks like this:

gen/blink/bindings/core/v8/V8Window.cpp:9152:80: error: implicit truncation from 'blink::V8PrivateProperty::CachedAccessorSymbol' to bit-field changes value from 2 to 0 [-Werror,-Wbitfield-constant-conversion]
    { "document", V8Window::documentAttributeGetterCallback, nullptr, nullptr, V8PrivateProperty::kWindowDocumentCachedAccessor, static_cast<v8::PropertyAttribute>(v8::DontDelete | v8::ReadOnly), V8DOMConfiguration::kOnInstance, V8DOMConfiguration::kCheckHolder, V8DOMConfiguration::kAllWorlds },

For this reason I am comfortable making the bitfield just as large as we need now, and adding bits as we need them in the future.

> Otherwise, if we could define the size of the bit fields close to the enum definition, that would be better.  For example,
>     enum class X {
>       kValue1 = 1 << 0,
>       ...
>       kValueN = 1 << (n-1),
>       kNumberOfBits = n
>     };
> 
>     struct Y {
>       unsigned bit_field_ : X::kNumberOfBits;
>     };
> Although, I don't know if this grammatically works or not.

It's possible to do, but hard to statically check that it's correct (except for the aforementioned check). If we had many uses of the bitfield size, I'd like to have such a constant (though probably not as an enumerator), but since our uses are localized to a few structs in V8DOMConfiguration I'm not sure it's worth the noise.

Patch-set: 3
Reviewer: Jeremy Roman <1002854@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0