Revert "Fix crash in ArcSupportHost::OnMessage"
This reverts commit cdc1d65f43ea8089a0fe58b84f7178577ee0d32f.

Reason for revert: breaks compile
../../chrome/browser/chromeos/arc/arc_support_host.cc:274:15: error: no member named 'SetPath' in 'base::DictionaryValue'

Original change's description:
> Fix crash in ArcSupportHost::OnMessage
> 
> Nullptr exception for auth_delegate_. The logs indicate that the
> devices are NOT in Active Directory management mode, so the crashing
> code should never be executed. We conclude that it is most likely
> due to webview events that are raised without the URL being set.
> 
> To test this assumption, this CL adds a guard that rejects webview
> events before the Active Directory authentication page is shown and
> after onAuthSucceeded or onAuthFailed is fired. This guarantees that
> events are only sent while auth_delegate_ is valid.
> 
> Moreover, the CL adds logs to verify the assumption that
> ActiveDirectoryAuthPage::setUrls is never called. In case the crashes
> still occur, the error_message from the onAuthFailed message is
> logged in order to track down the root cause.
> 
> BUG=chromium:756144
> TEST=Tested on AD-managed device
> TBR=ljusten@chromium.org
> 
> (cherry picked from commit 3378189464384739fb0bedef6b251f28ae4f6f8f)
> 
> Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
> Change-Id: Ie1f1cdc520b40c66aaae021f1758b96ed875c45b
> Reviewed-on: https://chromium-review.googlesource.com/620660
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Reviewed-by: Hidehiko Abe <hidehiko@chromium.org>
> Reviewed-by: Yury Khmel <khmel@chromium.org>
> Commit-Queue: Lutz Justen <ljusten@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#500001}
> Reviewed-on: https://chromium-review.googlesource.com/659857
> Reviewed-by: Roman Sorokin <rsorokin@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3163@{#1157}
> Cr-Branched-From: ff259bab28b35d242e10186cd63af7ed404fae0d-refs/heads/master@{#488528}

TBR=xiyuan@chromium.org,rsorokin@chromium.org,hidehiko@chromium.org,khmel@chromium.org,ljusten@chromium.org

Change-Id: Ic67a701a7b84df0092cdafe7804f123b856805cc
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: chromium:756144
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation