Fix nacl_helper CrOS GN build
This fixes the following error in the CrOS ozone GN build
(target_os="chromeos" use_ozone="true"):

FAILED: ../third_party/llvm-build/Release+Asserts/bin/clang++ -pie -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -B../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -Wl,--icf=all -pthread -m64 -Wl,-rpath-link=../out_gn_ozone -Wl,--disable-new-dtags -o "./nacl_helper" -Wl,--start-group @"./nacl_helper.rsp"  -Wl,--end-group  -ldl -lrt -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lfontconfig -lfreetype -lharfbuzz -ldbus-1 -lresolv -ldrm -lffi -lexpat -lasound -lm -lz
../content/common/child_process_sandbox_support_impl_linux.cc:69: error: undefined reference to 'blink::WebFontRenderStyle::setDefaults()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: cannot make progress due to previous errors.

Review URL: https://codereview.chromium.org/1682843002