Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> Code looks ok to me but linux-chromeos-rel is still failing chromevox_tests on EditingTest.RichTextImageByCharacter. Could you look into whether that's related to your change?

It probably is related, since there is a focus() call in that test. However, I've not been able to build chromevox_tests, unfortunately.

I was trying to follow https://chromium.googlesource.com/chromium/src/+/lkcr/docs/accessibility/chromevox_on_desktop_linux.md

However, with both build targets "chrome" and "chromevox_tests", the build fails with the following error:                                             
ninja: Entering directory `out/cros'
[1/15] LINK newlib_pnacl_nonsfi/nacl_helper_nonsfi
FAILED: newlib_pnacl_nonsfi/nacl_helper_nonsfi newlib_pnacl_nonsfi/exe.unstripped/nacl_helper_nonsfi 
python "../../build/toolchain/gcc_link_wrapper.py" --output="newlib_pnacl_nonsfi/nacl_helper_nonsfi" --strip="../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pnacl-strip" --unstripped-file="newlib_pnacl_nonsfi/exe.unstripped/nacl_helper_nonsfi" -- ../../native_client/toolchain/linux_x86/pnacl_newlib/bin/pnacl-clang++ --pnacl-allow-translate --pnacl-allow-native -Wl,--noirt -Wt,--noirt -Wt,--noirtshim -nodefaultlibs -arch x86-32-nonsfi --target=i686-unknown-nacl -Werror -Wl,-O1 -Wl,--gc-sections -Wl,--fatal-warnings -o "newlib_pnacl_nonsfi/exe.unstripped/nacl_helper_nonsfi" -Wl,--start-group @"newlib_pnacl_nonsfi/nacl_helper_nonsfi.rsp"  -Wl,--end-group   -lc++ -lm -lc -lpnaclmm 
newlib_pnacl_nonsfi/obj/ppapi/proxy/libppapi_proxy.a(interface_list.o): error: undefined reference to 'ppapi::thunk::GetPPB_MediaStreamVideoTrack_0_1_Thunk()'
newlib_pnacl_nonsfi/obj/ppapi/proxy/libppapi_proxy.a(interface_list.o): error: undefined reference to 'ppapi::thunk::GetPPB_Compositor_0_1_Thunk()'
ninja: build stopped: subcommand failed.

Does anyone have any pointers on how to build this target?

Patch-set: 5
Reviewer: Shubham Agrawal <1244275@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>