Update patch set 24
Patch Set 24:

> Patch Set 24:
> 
> > Patch Set 24:
> > 
> > (2 comments)
> > 
> > > Patch Set 23:
> > > 
> > > > Patch Set 23:
> > > > 
> > > > > Patch Set 23:
> > > > > 
> > > > > > Patch Set 23:
> > > > > > 
> > > > > > > Patch Set 23:
> > > > > > > 
> > > > > > > > Patch Set 23:
> > > > > > > > 
> > > > > > > > > Patch Set 23:
> > > > > > > > > 
> > > > > > > > > > Patch Set 23:
> > > > > > > > > > 
> > > > > > > > > > Also have we able to verify that this benchmark will have non zero return code if there are leaks?
> > > > > > > > > 
> > > > > > > > > Currently the return code is Success even when there are leaks.
> > > > > > > > > I could not find a way to modify the result values with metrics, so I was thinking of adding a script like run_leak_detector_as_googletest (just like run_telemetry_benchmark_as_googoletest) and changing the results there.
> > > > > > > > > Could you tell me what you think?
> > > > > > > > 
> > > > > > > > I think you should discuss with Ben & Ethan about extending the metrics system to support failure value. One idea I have is that in your memory leak metric, you can add s.t like:
> > > > > > > > 
> > > > > > > > if leaked_objects > 0:
> > > > > > > >   add failure value
> > > > > > > 
> > > > > > > Why does the benchmark need to return nonzero if there are leaks? Also, is there a link to the Catapult-side CL that implements the metric?
> > > > > > 
> > > > > > leakDetectionMetric was added in https://chromiumcodereview.appspot.com/3012153002
> > > > > > 
> > > > > > Metrics can make run_benchmark return nonzero exit code by throwing an error. I added `throw new Error('occam');` to memoryMetric:
> > > > > > 
> > > > > > ~/dev/o/src ./tools/perf/run_benchmark system_health.memory_desktop --story-filter=blank --pageset-repeat=1 --browser=stable
> > > > > > [ RUN      ] load:chrome:blank@{'case': 'load', 'group': 'chrome'}
> > > > > > (WARNING) 2017-11-06 10:45:07,034 timeline_based_measurement._ComputeTimelineBasedMetrics:327  Processing resulting traces took 1.963 seconds
> > > > > > Traceback (most recent call last):
> > > > > >   File "/usr/local/google/home/benjhayden/dev/o/src/third_party/catapult/telemetry/telemetry/value/failure.py", line 41, in _GetExcInfoFromMessage
> > > > > >     raise Exception(message)
> > > > > > Exception: MapFunctionError: occam
> > > > > >     at new memoryMetric 
> > > > > > ... redacted TBMv2 back trace...
> > > > > > [  FAILED  ] load:chrome:blank@{'case': 'load', 'group': 'chrome'} (16980 ms)
> > > > > > [  PASSED  ] 0 tests.
> > > > > > [  FAILED  ] 1 test, listed below:
> > > > > > [  FAILED  ]  load:chrome:blank@{'case': 'load', 'group': 'chrome'}
> > > > > > 1 FAILED TEST
> > > > > > View result at file:///usr/local/google/home/benjhayden/dev/o/src/tools/perf/results.html
> > > > > > ~/dev/o/src echo $?
> > > > > > 1
> > > > > > 
> > > > > > 
> > > > > > The results.html file contains only the benchmark_duration value produced by telemetry, nothing from the memoryMetric. If you want to use results.html to drill down into leaks, then I would submit for consideration making telemetry synthesize FailureValues from non-numeric samples, so that your metric can say `histogram.addSample('error message', {...diagnostics});` instead of throwing an error. That would allow telemetry to produce a useful results.html (with tables for errors and their diagnostics), and also return non-zero exit code.
> > > > > > 
> > > > > > But I would also like to know why the benchmark needs to return nonzero.
> > > > > 
> > > > > This benchmark will also be used as a test on CQ. Any CL that causes a leak would turn this one red & blocks CQ
> > > > 
> > > > Sorry, I should have been clearer. I was asking for the next "why". https://en.wikipedia.org/wiki/5_Whys
> > > > 
> > > > Why should that be a feature of telemetry? Do you anticipate other uses of the feature?
> > > 
> > > Because if you just run Telemetry benchmark command locally. i.e: "run_benchmark leak_detection", the command needs to return non zero code as well.
> > >   
> > > > Or should that be handled by a post-processing script, like upload_perf_dashboard_results.py?
> > > 
> > > It seems very wrong to put in upload_perf_dashboard_results. The name of script implies that it's only used for uploading results to the perf dashboard.
> > > 
> > > > The post-processing script could read histograms.json, iterate over the HistogramSet if necessary or look up specific Histograms by name, and assert their statistics are low enough, or whatever. A handful of lines of code, nice and modular, no need to play jenga with telemetry.
> > > 
> > > Who would invoke this post-processing script? If this involves infra change, I don't see how this is simpler. It also fails the test of "local run needs to return non zero code"
> > 
> > So am I correct in understanding that my options are below?
> > (1) in metrics, throw an error
> > (2) modify the metric system to return failure value 
> > (3) write a post-script to modify the results
> > 
> > I don't want to do (1) throw an error when there is a leak, because I wouldn't be able to see the stats of leaked objects in results.html, which are essential information for the debugging process.
> > 
> > And I'm not completely sure (2) modifying catapult metric system would be the best thing to do either. If there are gonna be more correctness benchmarks like this detector, the ability to return a failure value would be useful. But if not, I don't know if we need a special feature just for my case. 
> > As for returning non-zero code when running the benchmark locally, IMO it would be nice to have but not necessary as long as results.html has #s of leaked objects.
> > 
> > So I (3) wrote a post-script (CL: https://chromium-review.googlesource.com/c/chromium/src/+/756101). This is very much in draft yet, but the script would look something like this. I thought it would be pretty straight-forward adding a script, but I might be missing something. Ned, could you tell me what other infra-side changes need to happen with (3)? 
> > 
> > 
> > (Also reflected Ned's comments about directory change so PTAL :) )
> 
> I like the general sentiment that if this is the memory leak is an one off use cases, we should find the cheapest solution. Though adding an extra processing script & modify the infra code to invoke that script is anything but a cheap solution.
> 
> It worths noting that the pattern of using FailureValue is already supported in the python value system, so I don't think it's a too off base to extend metric HTML should also support the concept of Failure value. I am open to other ideas to implement this though.

Ned, if you foresee a need for cohesive failure machinery in the histogram system, I propose that we take that discussion offline. I've started a doc here: https://docs.google.com/document/d/1tZwzruU2AOGw-xjs1P0G2bq1SH_pAK-P5_zuAKlwzhE/edit# to discuss moving forward with these ideas. I invite you and Ben to work with me there.

For the time being, to sidestep that design discussion, let me recommend a workaround for this use case. Since metrics can throw at any time, it would be possible to simply add the relevant histograms, throw after adding them, and make sure we still surface the HistogramSet even if the metric throws an exception. So I would suggest the following plan, which avoids the need for any post-processing and allows this to work at the run_benchmark level:

1. Modify the metric to add the histograms, and throw at the very end if there were leaks
2. Make sure that the machinery in Telemetry raises the Python exception, but also still saves the results.html even if there is a FailureValue in the PageTestResults.

Patch-set: 24
Reviewer: Ethan Kuefner <1116849@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>