DOMException: Make |code|, |name| and |message| not enumerable.
According to https://heycam.github.io/webidl/#es-DOMException-call and
https://tc39.github.io/ecma262/#sec-error-message, the |code|, |name| and
|message| properties should be created with the following property
descriptor settings:

    [[Configurable]]: true
    [[Enumerable]]: false
    [[Writable]]: true

while we currently have

    [[Configurable]]: true
    [[Enumerable]]: true
    [[Writable]]: false

For now, just make them not enumerable, as the way |message| is currently
handled in DOMException may require some additional work and discussions
before we can make it writable.

Bug: 737497
Change-Id: I0f8f9cbb082daf14810e88ef44eaea26fa3bb3e8