Revert "media: Split CdmService from MediaService"
This reverts commit e0281b79c4b54256e9127e7067f97a1510bb401a.

Reason for revert: Suspected of breaking Mac:
https://logs.chromium.org/v/?s=chromium%2Fbb%2Fchromium%2FMac%2F36060%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

[42520/57721] CXX obj/media/mojo/services/media_service_unittests/media_service_unittest.o
FAILED: obj/media/mojo/services/media_service_unittests/media_service_unittest.o 
export DEVELOPER_DIR=/b/c/b/mac/src/build/mac_files/Xcode.app;  /b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/media/mojo/services/media_service_unittests/media_service_unittest.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_XCODE_VERSION=0832 -DCR_CLANG_REVISION=\"321204-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBP_EXTERN=extern -DGTEST_API_= -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=1 -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 -DSK_BUILD_FOR_MAC -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DLEVELDB_PLATFORM_CHROMIUM=1 -DENABLE_IPC_FUZZER -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DMESA_EGL_NO_X11_HEADERS -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DFEATURE_ENABLE_VOICEMAIL -DGTEST_RELATIVE_PATH -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_MAC -DUNIT_TEST -I../.. -Igen -I../../third_party/libwebp/src -I../../third_party/libyuv/include -I../../third_party/khronos -I../../gpu -I../../third_party/googletest/src/googletest/include -I../../third_party/libwebm/source -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/vulkan/include -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/mesa/src/include -I../../third_party/webrtc_overrides -I../../third_party/webrtc -I../../third_party/webrtc/common_video/include -I../../third_party/ced/src -I../../third_party/googletest/custom -I../../third_party/googletest/src/googlemock/include -fno-strict-aliasing -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -arch x86_64 -Wall -Werror -Wextra -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -Wno-enum-compare-switch -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-tautological-constant-compare -Wtautological-constant-out-of-range-compare -O2 -fno-omit-frame-pointer -gdwarf-2 -isysroot ../../build/mac_files/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9.0 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=c++14 -stdlib=libc++ -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../media/mojo/services/media_service_unittest.cc -o obj/media/mojo/services/media_service_unittests/media_service_unittest.o
../../media/mojo/services/media_service_unittest.cc:36:10: fatal error: 'media/mojo/interfaces/media_service_mac.mojom.h' file not found
#include "media/mojo/interfaces/media_service_mac.mojom.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.


Original change's description:
> media: Split CdmService from MediaService
> 
> Current CdmService is just an alias of MediaService because the latter
> can also support hosting a CDM. This help prevent duplication of code.
> However, there are a few issues with this approach:
> 1. It makes the code harder to understand.
> 2. CdmService doesn't need all the functionality provided by the
> MediaService.
> 3. CdmService needs some customization (e.g. LoadCdm) which introduces
> some complexity to MediaService.
> 
> This CL split CdmService from MediaService so that we can do some clean
> up. More simplification will follow in future CLs.
> 
> BUG=771791
> TEST=No functionality change.
> 
> Change-Id: I0ee627f2d01a77b33610956482197fbdc5425dcd
> Reviewed-on: https://chromium-review.googlesource.com/833369
> Commit-Queue: Xiaohan Wang <xhwang@chromium.org>
> Reviewed-by: Greg Kerr <kerrnel@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Reviewed-by: John Abd-El-Malek <jam@chromium.org>
> Reviewed-by: John Rummell <jrummell@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#525875}

TBR=dcheng@chromium.org,xhwang@chromium.org,jam@chromium.org,jrummell@chromium.org,kerrnel@chromium.org

Change-Id: I575ed4ffde40e6bec7ce8960e0e5eaa80c1ee0c8
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 771791