Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> After this revert, I get a broken build:
> 
> [...] -o obj/third_party/WebKit/Source/core/layout/layout/LayoutTableCell.o
> ../../third_party/WebKit/Source/core/layout/LayoutTableCell.cpp:63:7: error: member initializer 'is_spanning_collapsed_row_' does not name a non-static data member or base class
>       is_spanning_collapsed_row_(false),
>       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

Yes, the reason for that is that the MSAN issue was already fixed by another CL: https://chromium-review.googlesource.com/c/597031

Will you re-land both again?

Patch-set: 2
Reviewer: Morten Stenshorne <1111894@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>