Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> It looks like this broke the jumbo build? I'm getting the following errors: 
> 
> C:\src\chromium\src\third_party\WebKit\Source\core\animation\CSSRotateInterpolationType.cpp(154,7):  error: redefinition of 'InheritedRotationChecker'
> class InheritedRotationChecker
>       ^
> C:\src\chromium\src\third_party\WebKit\Source\core\animation\CSSOffsetRotateInterpolationType.cpp(64,7):  note: previous definition is here
> class InheritedRotationChecker
>       ^
> In file included from gen/third_party/WebKit/Source/core/animation/animation_jumbo_1.cc:36:
> C:\src\chromium\src\third_party\WebKit\Source\core\animation\CSSRotateInterpolationType.cpp(199,40):  error: no viable conversion from 'blink::OptionalRotation' to 'blink::StyleOffsetRotation'
>       InheritedRotationChecker::Create(inherited_rotation));
>                                        ^~~~~~~~~~~~~~~~~~
> C:\src\chromium\src\third_party\WebKit\Source\core\style\StyleOffsetRotation.h(12,8):  note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'blink::OptionalRotation' to 'const blink::StyleOffsetRotation &' for 1st argument
> struct StyleOffsetRotation {
>        ^
> C:\src\chromium\src\third_party\WebKit\Source\core\style\StyleOffsetRotation.h(12,8):  note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'blink::OptionalRotation' to 'blink::StyleOffsetRotation &&' for 1st argument
> C:\src\chromium\src\third_party\WebKit\Source\core\animation\CSSOffsetRotateInterpolationType.cpp(68,27):  note: passing argument to parameter 'inherited_rotation' here
>       StyleOffsetRotation inherited_rotation) {
>                           ^
> 2 errors generated.
> ninja: build stopped: subcommand failed.

Not sure if it's caused by this,haven't looked at the details of this change, it's just that the error is on these files.

Patch-set: 6