Revert "Revert "zlib: inflate using wider loads and stores""
This reverts commit e1f30a329eccf19ce1c8772e873abf88970cb65c.

Reason for revert: This patch was originally reverted because
we have an ARMv6 build target (part of Cronet) which
incorrectly set NEON support in our build files. As a result,
the NEON intrinsics were included despite ARMv6 not
supporting NEON.

The build problem was addressed here:
https://chromium-review.googlesource.com/c/chromium/src/+/639931

Now that ARMv6 builds do not set NEON support, these zlib
changes (which are only applied if NEON support is set in the
build) will not cause errors on ARMv6 targets.

Original change's description:
> Revert "zlib: inflate using wider loads and stores"
> 
> This reverts commit ad8fca9f4ad29ab87e49ec91a3577ef3696b3a84.
> 
> Reason for revert: broke Android_Cronet_ARMv6_Builder:
> error: "NEON support not enabled"
> 
> Original change's description:
> > zlib: inflate using wider loads and stores
> > 
> > In inflate_fast() the output pointer always has plenty of room to write.  
> > This means that so long as the target is capable, wide un-aligned 
> > loads and stores can be used to transfer several bytes at once.
> > 
> > When the reference distance is too short simply unroll the data a 
> > little to increase the distance. Patch by Simon Hosie.
> > 
> > PNG decoding performance gains should be around 30-33%.
> > 
> > BUG=697280
> > 
> > Change-Id: I59854eb25d2b1e43561c8a2afaf9175bf10cf674
> > Reviewed-on: https://chromium-review.googlesource.com/627098
> > Reviewed-by: Adenilson Cavalcanti <cavalcantii@chromium.org>
> > Reviewed-by: Mike Klein <mtklein@chromium.org>
> > Commit-Queue: Adenilson Cavalcanti <cavalcantii@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#497866}
> 
> TBR=scroggo@chromium.org,agl@chromium.org,cavalcantii@chromium.org,cblume@chromium.org,mtklein@chromium.org,adenilson.cavalcanti@arm.com
> 
> Change-Id: I93030617e4ed4feb665de1095c411bce80c531a9
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Bug: 697280
> Reviewed-on: https://chromium-review.googlesource.com/639399
> Reviewed-by: Paul Miller <paulmiller@chromium.org>
> Commit-Queue: Paul Miller <paulmiller@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#497938}

TBR=scroggo@chromium.org,agl@chromium.org,cavalcantii@chromium.org,paulmiller@chromium.org,cblume@chromium.org,mtklein@chromium.org,adenilson.cavalcanti@arm.com

Change-Id: I0b4cd1a393464c960c6a1e48a022a20340781e75
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 697280