Add missing safe_json_parser_message_filter dep on content_common
safe_json.gypi:safe_json_parser_message_filter is missing dependency
on content_common:

In file included from ../../content/public/common/common_param_traits_macros.h:25:0,
                 from ../../content/public/common/common_param_traits.h:21,
                 from ../../components/safe_json/safe_json_parser_messages.h:11,
                 from ../../components/safe_json/safe_json_parser_message_filter.cc:9:
../../ui/accessibility/ax_node_data.h:14:39: fatal error: ui/accessibility/ax_enums.h: No such file or directory
 #include "ui/accessibility/ax_enums.h"

Note that the said dependency already exists in safe_json/BUILD.gn

BUG=None

Review URL: https://codereview.chromium.org/1248363004