Update patch set 7
Patch Set 7:

> Patch Set 7:
> 
> > Patch Set 7:
> > 
> > This seems to be causing a build failure on the GPU FYI waterfall and ANGLE CQ:
> > 
> > ../../ash/mus/ash_window_tree_host_mus.cc:77:28: error: out-of-line definition of 'SetCursorConfig' does not match any declaration in 'ash::AshWindowTreeHostMus'
> > void AshWindowTreeHostMus::SetCursorConfig(
> >                            ^~~~~~~~~~~~~~~
> > ../../ash/mus/ash_window_tree_host_mus.cc:83:28: error: out-of-line definition of 'ClearCursorConfig' does not match any declaration in 'ash::AshWindowTreeHostMus'
> > void AshWindowTreeHostMus::ClearCursorConfig() {
> >                            ^~~~~~~~~~~~~~~~~
> > 
> > https://build.chromium.org/p/chromium.gpu.fyi/builders/Linux%20ChromiumOS%20Builder/builds/32613
> 
> Let me take a look. It's likely the case that ash_window_tree_host needs to include the header that defines USE_OZONE.

I see it. Will submit a fix shortly.
I will mention the gpu fyi bot you pointed at is building chromeos with X11. That config is going away (which is why this didn't break the main waterfall). I'll file a bug.

Patch-set: 7