Revert of Roll ANGLE f047097..71168a0 (patchset #1 id:1 of https://codereview.chromium.org/2597443002/ )
Reason for revert:
https://build.chromium.org/p/chromium/builders/Win%20x64/builds/6994/steps/compile/logs/stdio

ninja -t msvc -e environment.x64 -- C:\b\c\cipd\goma/gomacc.exe "C:\b\depot_tools\win_toolchain\vs_files\d3cb0e37bdd120ad0ac4650b674b09e81be45616\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/third_party/angle/src/tests/angle_perftests/UniformsPerf.obj.rsp /c ../../third_party/angle/src/tests/perf_tests/UniformsPerf.cpp /Foobj/third_party/angle/src/tests/angle_perftests/UniformsPerf.obj /Fd"obj/third_party/angle/src/tests/angle_perftests_cc.pdb"
c:\b\c\b\win_x64_archive\src\third_party\angle\src\tests\perf_tests\uniformsperf.cpp(148): error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_x64_archive\src\third_party\angle\src\tests\perf_tests\uniformsperf.cpp(148): warning C4267: 'initializing': conversion from 'size_t' to 'GLint', possible loss of data
c:\b\c\b\win_x64_archive\src\third_party\angle\src\tests\perf_tests\uniformsperf.cpp(149): warning C4267: 'initializing': conversion from 'size_t' to 'GLint', possible loss of data

Original issue's description:
> Roll ANGLE f047097..71168a0
>
> https://chromium.googlesource.com/angle/angle.git/+log/f047097..71168a0
>
> BUG=chromium:674143
>
> TBR=cwallez@chromium.org
>
> TEST=bots
>
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.win:win_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.android:android_optional_gpu_tests_rel
>
> Committed: https://crrev.com/47cd7960532e2a1bd4e7a987b69c66f632f7f6c9
> Cr-Commit-Position: refs/heads/master@{#439866}

TBR=cwallez@chromium.org,jmadill@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=chromium:674143

Review-Url: https://codereview.chromium.org/2587413003