Update patch set 2
Patch Set 2:

FYI:
This may have broken the build on branch-heads/3325:

../../ash/login/ui/login_pin_view.cc:137:23: error: use of undeclared identifier 'ax'
    node_data->role = ax::mojom::Role::kButton;

That enum should probably be ui::AX_ROLE_BUTTON
due to CL:877417 not being on the M-65/3325 branch.

Patch-set: 2