Update patch set 2
Patch Set 2:

Please take a look. I'll need to cherry-pick this into canary branch.

This is the failure when building canary:

FAILED: obj/ios/chrome/browser/ui/qr_scanner/qr_scanner/camera_controller.o 
export DEVELOPER_DIR=/b/build/slave/canary-device/build/src/build/ios_files/Xcode.app;  /b/build/slave/cache/goma_client/gomacc clang++ -MMD -MF obj/ios/chrome/browser/ui/qr_scanner/qr_scanner/camera_controller.o.d -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DOFFICIAL_BUILD -DGOOGLE_CHROME_BUILD -DCR_XCODE_VERSION=0910 -DCR_CLANG_REVISION=\"317263-4\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNS_BLOCK_ASSERTIONS=1 -DEXPAT_RELATIVE_PATH -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_SUPPORT_GPU=0 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -I../.. -Igen -I../../third_party/libwebp/src -I../../ios/third_party/material_components_ios/src/components/AppBar/src -I../../ios/third_party/material_components_ios/src/components/ActivityIndicator/src -I../../ios/third_party/material_components_ios/src/components/ButtonBar/src -I../../ios/third_party/material_components_ios/src/components/Buttons/src -I../../ios/third_party/material_components_ios/src/components/CollectionCells/src -I../../ios/third_party/material_components_ios/src/components/CollectionLayoutAttributes/src -I../../ios/third_party/material_components_ios/src/components/Collections/src -I../../ios/third_party/material_components_ios/src/components/Dialogs/src -I../../ios/third_party/material_components_ios/src/components/FlexibleHeader/src -I../../ios/third_party/material_components_ios/src/components/HeaderStackView/src -I../../ios/third_party/material_components_ios/src/components/Ink/src -I../../ios/third_party/material_components_ios/src/components/private/UIMetrics/src -I../../ios/third_party/material_components_ios/src/components/NavigationBar/src -I../../ios/third_party/material_components_ios/src/components/OverlayWindow/src -I../../ios/third_party/material_components_ios/src/components/Palettes/src -I../../ios/third_party/material_components_ios/src/components/ProgressView/src -I../../ios/third_party/material_components_ios/src/components/ShadowElevations/src -I../../ios/third_party/material_components_ios/src/components/ShadowLayer/src -I../../ios/third_party/material_components_ios/src/components/Snackbar/src -I../../ios/third_party/material_components_ios/src/components/Themes/src -I../../ios/third_party/material_components_ios/src/components/Typography/src -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/third_party/vulkan -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fcolor-diagnostics -no-canonical-prefixes -arch arm64 -Wall -Werror -Wextra -Wundeclared-selector -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-address-of-packed-member -Oz -fno-omit-frame-pointer -gdwarf-2 -isysroot /b/build/slave/canary-device/build/src/build/ios_files/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk -stdlib=libc++ -miphoneos-version-min=9.0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=c++14 -fobjc-call-cxx-cdtors -Wobjc-missing-property-synthesis -Wunguarded-availability -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fobjc-arc -c ../../ios/chrome/browser/ui/qr_scanner/camera_controller.mm -o obj/ios/chrome/browser/ui/qr_scanner/qr_scanner/camera_controller.o
../../ios/chrome/browser/ui/qr_scanner/camera_controller.mm:372:12: error: 'AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableDueToSystemPressure' is only available on iOS 11_1 or newer [-Werror,-Wunguarded-availability-new]
      case AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableDueToSystemPressure:
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/b/build/slave/canary-device/build/src/build/ios_files/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.1.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureSession.h:92:5: note: 'AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableDueToSystemPressure' has been explicitly marked partial here
    AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableDueToSystemPressure NS_AVAILABLE_IOS(11_1) = 5,
    ^
../../ios/chrome/browser/ui/qr_scanner/camera_controller.mm:372:12: note: enclose 'AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableDueToSystemPressure' in an @available check to silence this warning
      case AVCaptureSessionInterruptionReasonVideoDeviceNotAvailableDueToSystemPressure:
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Patch-set: 2
Reviewer: Olivier Robin <1144530@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Stepan Khapugin <1148126@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false