Revert "Enable chrome.automation.getDesktop on all aura platforms."
This reverts commit 35b188a996e59c65787207818c7b90d70007f03d.

Caused browser_tests AutomationApiTest.DesktopLoadTabs to fail

e.g.:
https://build.chromium.org/p/chromium.linux/builders/Linux%20Tests/builds/22541

"""
AutomationApiTest.DesktopLoadTabs (run #1):
[ RUN      ] AutomationApiTest.DesktopLoadTabs
Xlib:  extension "RANDR" missing on display ":9".
Xlib:  extension "RANDR" missing on display ":9".
[25828:25828:0327/163831:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
[25828:25932:0327/163832:WARNING:data_reduction_proxy_config.cc(330)] SPDY proxy OFF at startup
[25828:25828:0327/163832:WARNING:password_store_factory.cc(259)] Using basic (unencrypted) store for password storage. See http://code.google.com/p/chromium/wiki/LinuxPasswordStorage for more information about password storage options.
[25828:25828:0327/163832:INFO:CONSOLE(0)] "calling getTree() callback", source: chrome-extension://mojndmjfhfgjjicpoiodenhflfmkopil/load_tabs.html (0)
[25828:25828:0327/163832:INFO:CONSOLE(0)] "calling getTree() callback", source: chrome-extension://mojndmjfhfgjjicpoiodenhflfmkopil/load_tabs.html (0)
[25828:25828:0327/163832:INFO:CONSOLE(0)] "[FAIL] testLoadTabs: uncaught exception: Cannot read property 'firstChild' of undefined: TypeError: Cannot read property 'firstChild' of undefined
    at testLoadTabs (chrome-extension://mojndmjfhfgjjicpoiodenhflfmkopil/load_tabs.js:28:36)
"""

NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=Original Patch Had No Bug!?!
TBR=dmazzoni@chromium.org, oshima@chromium.org, sky@chromium.org, dtseng@chromium.org

Review URL: https://codereview.chromium.org/1040863002