Disable NEON support on ARMv6 build targets.
ARMv6 does not support NEON.
Clang deliberately errors when attempting to use NEON intrinsics when
targeting ARMv6:

/b/build/slave/Android_Cronet_ARMv6_Builder/build/src/third_party/llvm-build/Release+Asserts/lib/clang/6.0.0/include/arm_neon.h:28:2:
error: "NEON support not enabled"

BUG=759993

Change-Id: I0b099823604d25fae20c80a72f7fca28ab6b5121