WPT import: Pass the right variable to ImportNotifier.format_commit_list
ImportNotifier.file_new_failures() calls LocalWPT's commits_in_range()
method, which returns a list of (SHA, commit subject) pairs.

It was then passing this list of tuples directly to format_commit_list(),
which expects a simple list of hashes instead, which led to failures such
as:

Traceback (most recent call last):
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/wpt-import", line 25, in <module>
    main()
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/wpt-import", line 18, in main
    host.exit(importer.main())
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 168, in main
    if not self.send_notifications(local_wpt):
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/test_importer.py", line 631, in send_notifications
    issue, patchset)
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/import_notifier.py", line 64, in main
    self.file_new_failures(wpt_revision_start, wpt_revision_end, issue, gerrit_url)
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/import_notifier.py", line 179, in file_new_failures
    commit_list = self.format_commit_list(imported_commits, full_directory)
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/import_notifier.py", line 199, in format_commit_list
    line = '{}: {}'.format(self.local_wpt.commit_subject(commit), GITHUB_COMMIT_PREFIX + commit)
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/local_wpt.py", line 191, in commit_subject
    output = self.run(['git', 'show', '--format=%s', '-q', commit])
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/w3c/local_wpt.py", line 50, in run
    return self.host.executive.run_command(command, cwd=self.path, **kwargs)
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/common/system/executive.py", line 337, in run_command
    (error_handler or self.default_error_handler)(script_error)
  File "/mnt/data/b/rr/tmpObTKGC/w/src/third_party/WebKit/Tools/Scripts/webkitpy/common/system/executive.py", line 244, in default_error_handler
    raise error
webkitpy.common.system.executive.ScriptError: Failed to run "['git', 'show', '--format=%s', '-q', (u'a4c37295163abd475704cc032a304c83b14f9202', u'Add tests for slot.assignedElements method (#8636)')]" exit_code: 128 cwd: /tmp/wpt
output: fatal: ambiguous argument '(u'a4c37295163abd475704cc032a304c83b14f9202', u'Add tests for slot.assignedElements method (#8636)')': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
step returned non-zero exit code: 1
(via https://ci.chromium.org/buildbot/chromium.infra.cron/wpt-importer/7486)

Bug: 765334
Change-Id: Iec2f574e5c308cd10f028e9ad1496be7967c0843