Revert of Fix scoped_ptr free to use delete [] instead of delete. (patchset #1 id:1 of https://codereview.chromium.org/1055433003/)
Reason for revert:
It looks like this broke the following test on XP Tests (1):
sbox_unittests WinUtils.SameObject

Example output:
WinUtils.SameObject (run #1):
[ RUN      ] WinUtils.SameObject
c:\b\build\slave\win_builder\build\src\sandbox\win\src\win_utils_unittest.cc(78): error: Value of: SameObject(file.Get(), file_name_nt1.c_str())
  Actual: false
Expected: true
c:\b\build\slave\win_builder\build\src\sandbox\win\src\win_utils_unittest.cc(79): error: Value of: SameObject(file.Get(), file_name_nt2.c_str())
  Actual: false
Expected: true
[  FAILED  ] WinUtils.SameObject (16 ms)

Original issue's description:
> Fix scoped_ptr free to use delete [] instead of delete.
>
> BUG=101717
>
> Committed: https://crrev.com/7804b679be3af7e24578394af0a85ba1249344a9
> Cr-Commit-Position: refs/heads/master@{#324013}

TBR=cpu@chromium.org,wfh@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=101717

Review URL: https://codereview.chromium.org/1065833002