Update patch set 3
Patch Set 3:

The Google styleguide is very explicit on this matter, there is no room for subjective interpretation on what it currently allows or not.

Pasting from https://google.github.io/styleguide/jsguide.html#formatting-braces (I put the "*" for emphasis no the relevant parts).

"Braces are required for all control structures (i.e. if, else, for, do, while, as well as any others), *even if the body contains only a single statement*. The first statement of a non-empty block must begin on its own line."

Exception: A simple if statement that *can fit entirely on a single line* with no wrapping (and that doesn’t have an else) may be kept on a single line with no braces when it improves readability. *This is the only case in which a control structure may omit braces and newlines*."

In other words

// Valid per Google styleguide
if (foo) return;

// Invalid per Google styleguide, valid with current Chromium styleguide.
if (foo)
  return;

Patch-set: 3
Reviewer: Demetrios Papadopoulos <1115893@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>