Update patch set 2
Patch Set 2:

Tests are failing with:

  ./../media/capture/video/video_capture_device_unittest.cc(483): error: Mock function called 
  more times than expected - taking default 
    action specified at:
    ../../media/capture/video/video_capture_device_unittest.cc(170):
      Function call: OnError(@0873F778 16-byte object <2C-54 EE-00 A8-53 EE-00 29-03 00-00 E0-
  BC A7-00>, @0873F740 
    "VideoCaptureDeviceMFWin: No suitable transform was found to encode or decode the content. 
  (0xC00D5212)")
           Expected: to be never called
             Actual: called once - over-saturated and active

I experienced this issue with C920 at 1920*1080 and with MJPEG format.

I found why!
Unlike other implementations, IMFCaptureEngine in preview mode performs video decoding itself.
The video stream follow the path camera -> IMFCaptureSource -> IMFTransform -> IMFCaptureSink -> Chromium.
So, the video media type set in IMFCaptureSource must match one exposed by the camera (i.e. 1080p NV12, 1080 MJPEG, ...).
And the video media type set in IMFCaptureSink must be any RAW/uncompressed video format.
IMFCaptureEngine will automatically setup an IMFTransform taking camera stream as input and decoded stream as output.

The IMFCaptureSink media type must always be an uncompressed format, but which one? From what I understood reading VideoCaptureClient implementation, any retrieved frame will be converted to I420. Therefore, I decided to fix the video format output to I420 to avoid performing the same operation multiple times.

Video capture device MF implementation will always emit I420 frames.

Patch-set: 2
Reviewer: Réda Housni Alaoui <1213761@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false