Update patch set 1
Patch Set 1:

Looks like we forgot to update the unittest in the same cl. Should be a quick fix :)
[1/1] perf_device_trigger_unittest.PerfDeviceTriggerUnittest.testBasic failed unexpectedly 0.0021s:
  Traceback (most recent call last):
    File "/b/swarming/w/ir/tools/perf/perf_device_trigger_unittest.py", line 60, in testBasic
      'args', '--id', 'build1'])
  AssertionError: Lists differ: ['/path/to/swarming.py', 'trig... != ['/path/to/swarming.py', 'trig...
  
  First differing element 9:
  -bot
  --id

Patch-set: 1
Reviewer: Ashley Enstad <1189781@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>