Update patch set 5
Patch Set 5:

This seems to be causing breakages on the bot:

java.lang.AssertionError: Overview mode should not be showing
	at org.junit.c.a(Assert.java:88)
	at org.junit.c.a(Assert.java:41)
	at org.junit.c.b(Assert.java:64)
	at org.chromium.chrome.browser.widget.bottomsheet.BottomSheetNewTabControllerTest.testCloseNTP(BottomSheetNewTabControllerTest.java:186)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at org.junit.runners.a.e.b(FrameworkMethod.java:50)
	at org.junit.internal.runners.a.c.a(ReflectiveCallable.java:12)
	at org.junit.runners.a.d.a(FrameworkMethod.java:52)
	at org.junit.internal.runners.c.f.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.c.h.evaluate(RunBefores.java:26)
	at org.chromium.base.test.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:37)
	at org.chromium.chrome.test.ChromeActivityTestRule$1.evaluate(ChromeActivityTestRule.java:59)
	at android.support.test.internal.a.a.evaluate(UiThreadStatement.java:55)
	at android.support.test.d.b.evaluate(ActivityTestRule.java:270)
	at org.junit.a.e.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.chromium.base.test.BaseJUnit4ClassRunner.runChild(BaseJUnit4ClassRunner.java:135)
	at org.chromium.base.test.BaseJUnit4ClassRunner.runChild(BaseJUnit4ClassRunner.java:36)
	at org.junit.runners.h.run(ParentRunner.java:290)
	at org.junit.runners.f.a(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.g.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.h.run(ParentRunner.java:290)
	at org.junit.runners.f.a(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.g.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.b.e.a(JUnitCore.java:137)
	at android.support.test.internal.runner.k.a(TestExecutor.java:3115)
	at android.support.test.runner.a.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

Patch-set: 5