Update patch set 2
Patch Set 2:

This change breaks cross compile build for mips32r2.

Please make sure cross compilation works before merging this change.
You can test this by using:

gn gen out/mips32r2 --args="is_debug=false target_os=\"linux\" target_cpu=\"mipsel\" mips_arch_variant=\"r2\""

ninja -C out/mips32r2 -j4 chrome


Reported error is:


[11/49472] CXX obj/base/allocator/tcmalloc/malloc_hook.o

In file included from ../../third_party/tcmalloc/chromium/src/malloc_hook.cc:698:
In file included from ../../third_party/tcmalloc/chromium/src/malloc_hook_mmap_linux.h:51:
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:1897:51: error: invalid use of a cast in a inline asm context requiring an l-value: remove the cast or build with -fheinous-gnu-extensions
                       unsigned long,  f, void *, a)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:1526:64: note: expanded from macro '_syscall5'
                                "r"(__r6), "m" ((unsigned long)arg5)          \
                                                ~~~~~~~~~~~~~~~^~~~
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:2019:47: error: invalid use of a cast in a inline asm context requiring an l-value: remove the cast or build with -fheinous-gnu-extensions
                         loff_t *, res, uint, wh)
                         ~~~~~~~~~~~~~~~~~~~~~^~~
../../third_party/tcmalloc/chromium/src/base/linux_syscall_support.h:1526:64: note: expanded from macro '_syscall5'
                                "r"(__r6), "m" ((unsigned long)arg5)          \
                                                ~~~~~~~~~~~~~~~^~~~
2 errors generated.

Patch-set: 2
CC: Petar Jovanovic <1002356@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
CC: Gordana Cmiljanovic <1117686@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
CC: Milko Leporis <1158814@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>