Update patch set 2
Patch Set 2: -Code-Review

Hmm, how do I remove "Work in progress" from this CL?

gerrit_util.GerritError: Conflict: Failed to submit 1 change due to the following problems:
Change 575063: Change 575063 is work in progress

Patch-set: 2
Reviewer: Hugo Holgersson <1207755@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=0