MacViewsBrowser: Fix broken compile - renamed method after r395397
r395397 is "Simplify some old avatar menu button code."

`compile` step broke in http://go/macviewsbuilder/builds/10802 with

browser_non_client_frame_view_mac.h:42:23:
error: only virtual member functions can be marked 'override'
  void UpdateAvatar() override;

It just needs to be renamed to UpdateProfileIcons().

BUG=425229,614244
TBR=estade@chromium.org

Review-Url: https://codereview.chromium.org/2001383002