Enhance the error message if the build fails due to a bad zip file.
I killed an ongoing build and a zip file got corrupted.  Then all
subsequent builds were failing, but I didn't know where.

This adds/clears up the message IMO.

Previous output:
  File "/...../src/build/android/gyp/util/build_utils.py", line 228, in
ExtractAll
    with zipfile.ZipFile(zip_path) as z:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

New output:
  File "../../build/android/gyp/javac.py", line 90, in
_ExtractClassFiles
    build_utils.ExtractAll(jar_path, path=dest_dir,
predicate=extract_predicate)
  File "/...../src/build/android/gyp/util/build_utils.py", line 229, in
ExtractAll
    raise Exception('Invalid zip file: %s' % zip_path)
Exception: Invalid zip file: gen/base/base_java__compile_java.javac.jar

BUG=

Review-Url: https://codereview.chromium.org/2001353002