Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> I'm a bit confused by this CL. Isn't the eventual plan to remove the prefixed versions anyway? Why would we point them at the thing that will be removed in the deprecation message?

Currently, on Canary and on Stable, you can run
videoelement.webkitEnterFullscreen()

and it works, but it also gives you a deprecation message saying to use requestFullscreen() instead. Then when you try to use requestFullscreen it gives you an error "Uncaught TypeError: video.requestFullscreen is not a function".

So the point is just that if we're going to have a flag that determines what functions are available, then we should also have that flag determine what function we recommend the developer using in the deprecation message. In this way, we don't tell the developer to use a function that doesn't exist.

Patch-set: 3
Reviewer: Caleb Rouleau <1149061@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>