Update patch set 1
Patch Set 1:

(1 comment)

The command output will now look like:

== Device attached, but failed for some reason ==
E    4.555s list_tests(ENU7N15B12001822)  Shard failed: list_tests(ENU7N15B12001822)
Traceback (most recent call last):
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_environment.py", line 59, in wrapper
    return f(dev, *args, **kwargs)
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_gtest_run.py", line 367, in list_tests
    device=dev)
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/android/crash_handler.py", line 32, in RetryOnSystemCrash
    return f(device)
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_gtest_run.py", line 366, in <lambda>
    None, d, flags='--gtest_list_tests', timeout=30),
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_gtest_run.py", line 184, in Run
    stdout_file.name, device.StatPath(stdout_file.name).get('st_size', 0))
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/android/device_utils.py", line 1890, in StatPath
    'Cannot find file or directory: %r' % device_path, str(self))
CommandFailedError: (device: ENU7N15B12001822) Cannot find file or directory: '/sdcard/temp_file-fc8e738835f0f.gtest_out'
E    4.555s list_tests(ENU7N15B12001822)  Device ENU7N15B12001822 blacklisted: list_tests
E    4.558s Main  Error occurred.
Traceback (most recent call last):
  File "/usr/local/google/code/clankium/src/build/android/test_runner.py", line 934, in main
    return RunTestsCommand(args)
  File "/usr/local/google/code/clankium/src/build/android/test_runner.py", line 692, in RunTestsCommand
    return RunTestsInPlatformMode(args)
  File "/usr/local/google/code/clankium/src/build/android/test_runner.py", line 806, in RunTestsInPlatformMode
    raw_results = test_run.RunTests()
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_test_run.py", line 77, in RunTests
    tests = self._GetTests()
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_gtest_run.py", line 376, in _GetTests
    test_lists = self._env.parallel_devices.pMap(list_tests).pGet(None)
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/utils/parallelizer.py", line 263, in pMap
    r.pFinish(None)
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/utils/parallelizer.py", line 135, in pFinish
    self._objs.JoinAll()
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/utils/reraiser_thread.py", line 186, in JoinAll
    self._JoinAll(watcher, timeout)
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/utils/reraiser_thread.py", line 158, in _JoinAll
    thread.ReraiseIfException()
  File "/usr/local/google/code/clankium/src/third_party/catapult/devil/devil/utils/reraiser_thread.py", line 81, in run
    self._ret = self._func(*self._args, **self._kwargs)
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_environment.py", line 70, in wrapper
    on_failure(dev, f.__name__)
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_environment.py", line 268, in BlacklistDevice
    'All devices were blacklisted due to errors')
NoDevicesError: All devices were blacklisted due to errors


== No devices at all from the beginning ==
$ out/Debug/bin/run_tracing_perftests 
E    0.032s Main  Error occurred.
Traceback (most recent call last):
  File "/usr/local/google/code/clankium/src/build/android/test_runner.py", line 934, in main
    return RunTestsCommand(args)
  File "/usr/local/google/code/clankium/src/build/android/test_runner.py", line 692, in RunTestsCommand
    return RunTestsInPlatformMode(args)
  File "/usr/local/google/code/clankium/src/build/android/test_runner.py", line 798, in RunTestsInPlatformMode
    with json_writer, logcats_uploader, env, test_instance, test_run:
  File "/usr/local/google/code/clankium/src/build/android/pylib/base/test_run.py", line 39, in __enter__
    self.SetUp()
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_gtest_run.py", line 319, in SetUp
    self._env.parallel_devices.pMap(
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_environment.py", line 195, in parallel_devices
    return parallelizer.SyncParallelizer(self.devices)
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_environment.py", line 186, in devices
    self._InitDevices()
  File "/usr/local/google/code/clankium/src/build/android/pylib/local/device/local_device_environment.py", line 134, in _InitDevices
    raise device_errors.NoDevicesError('No devices were available')
NoDevicesError: No devices were available

Patch-set: 1
Reviewer: John Budorick <1181690@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Primiano Tucci <1002871@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Juan Antonio Navarro Pérez <1123010@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>