Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> I think this broke the tree:
> 
> https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.win%2FWin_x64_Builder__dbg_%2F56672%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout
> 
> gen/tools/traffic_annotation/chrome_settings_full_runtime.pb.cc(8738): fatal error C1091: compiler limit: string exceeds 65535 bytes in length

I think some more things got added to chrome_settings_full_runtime in the time between running the tryjobs and landing the cl, and those changes just barely caused a string to go over 65535 bytes ಠ_ಠ

Patch-set: 4