Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> > Patch Set 4:
> > 
> > > Patch Set 4:
> > > 
> > > (2 comments)
> > > 
> > > PTAL.
> > 
> > Thanks! There is one more ios issue:
> > FAILED: obj/ios/chrome/browser/ui/settings/settings/time_range_selector_collection_view_controller.o 
> > ../../ios/chrome/browser/ui/settings/time_range_selector_collection_view_controller.mm:42:1: error: static_assert failed "Strings have to match the enum values."
> > static_assert(
> > ^
> > 1 error generated.
> > 
> > I think you have to add the new string to ios/chrome/app/strings/ios_strings.grd and add it to kStringIDS
> 
> Done.
> Hi Christian, Is it possible to get the tryjob access? Is there any process apply for it? Thank you.

Awesome, I started the trybot again. 

It should be possible to get try job access for you. (https://www.chromium.org/getting-involved/become-a-committer the section about try job access). Are the commits from s.singapati@gmail.com and s.singapati@samsung.com from you as well? 

One note: Commit-Queue+2 means that you start tests and commit the CL if successful. Commit-Queue+1 is only running the tests.
Before you can commit the CL you still need owners approval for the change in browsing_data/, android/ and metrics/. msramek@ would be the right person for browsing_data/. For android/ twellington@ usually reviews my CBD CLs. For metrics just pick anyone from the metrics owners file.

Patch-set: 5
Reviewer: Christian Dullweber <1183839@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>