Update patch set 5
Patch Set 5:

I think this broke jumbo builds because of too many PublicKeyCallbacks but I've not investigated further than the error message.

In file included from gen/third_party/WebKit/Source/modules/credentialmanager/credentialmanager_jumbo_1.cc:16:
./../../third_party/WebKit/Source/modules/credentialmanager/WebAuthenticationClient.cpp:22:7: error: typedef redefinition with different types ('WebAuthenticationClient::PublicKeyCallbacks' (aka 'WebCallbacks<StructPtr<webauth::mojom::blink::PublicKeyCredentialInfo>, blink::WebCredentialManagerError>') vs 'blink::(anonymous namespace)::PublicKeyCallbacks')
using PublicKeyCallbacks = WebAuthenticationClient::PublicKeyCallbacks;
      ^
./../../third_party/WebKit/Source/modules/credentialmanager/CredentialsContainer.cpp:124:7: note: previous definition is here
class PublicKeyCallbacks : public WebAuthenticationClient::PublicKeyCallbacks {
      ^

Patch-set: 5
CC: Daniel Bratell <1114374@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>