Revert "Roll src/third_party/catapult/ a71decf74..507c4af8b (2 commits)"
This reverts commit 383bc1fa89311c568194da1a9ecb66ab5ccb9823.

Causes failures in the information builders: Unhandled AttributeError: 'NoneType' object has no attribute 'GetChromePid'.

BUG=750243

Change-Id: I79a978574dfcf1de0bd79c2bc24cf7fcc4b06b41