Update patch set 1
Patch Set 1:

I patched this in and then added a error and built. I got this output:

../../base/win/enum_variant.cc(14): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

In the solution I am using (a minimal solution that I have nursed along since the gyp days) I found that that text in the output window did not work. Double-clicking did not navigate to the error.

Once I stripped the leading ../../ then it worked. This may just be a quirk of my setup but I wanted to confirm.

BTW, the way I did the build from the command-line and then used Tools->External Tools, configured to run fromclip.exe, to get the output variants into the output window.

Maybe /FC should be off by default but we should give developers the option to enable it in order to get 100% reliable finding of code.

Patch-set: 1
Reviewer: Bruce Dawson <1128439@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>