Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> Hi! This CL caused gcc/arm64 and arm32 compilation failures. 
> 
> A short snippet from the log - 
> 
> /home/msisov/code/AGL-master/build/tmp/work/aarch64-agl-linux/chromium-ozone-wayland/66.0.3335.0.r532296.igalia.1-r0/recipe-sysroot/usr/include/c++/6.3.0/bits/stl_vector.h:324:31:   required from 'std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = mojo::StructPtr<mojo::native::SerializedHandle>; _Alloc = std::allocator<mojo::StructPtr<mojo::native::SerializedHandle> >]'
> /home/msisov/code/AGL-master/build/tmp/work/aarch64-agl-linux/chromium-ozone-wayland/66.0.3335.0.r532296.igalia.1-r0/recipe-sysroot/usr/include/c++/6.3.0/type_traits:1403:12:   required from 'struct std::is_trivially_copy_constructible<std::vector<mojo::StructPtr<mojo::native::SerializedHandle> > >'
> ../../base/optional.h:291:22:   required from 'class base::internal::OptionalBase<std::vector<mojo::StructPtr<mojo::native::SerializedHandle> > >'
> ../../base/optional.h:374:7:   required from 'class base::Optional<std::vector<mojo::StructPtr<mojo::native::SerializedHandle> > >'
> gen/mojo/public/interfaces/bindings/native_struct.mojom.h:261:52:   required from here
> /home/msisov/code/AGL-master/build/tmp/work/aarch64-agl-linux/chromium-ozone-wayland/66.0.3335.0.r532296.igalia.1-r0/recipe-sysroot/usr/include/c++/6.3.0/bits/stl_construct.h:75:7: error: 'mojo::StructPtr<S>::StructPtr(const mojo::StructPtr<S>&) [with S = mojo::native::SerializedHandle]' is private within this context
>      { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
>        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> The StructPtr has DISALLOW_COPY_AND_ASSIGN and it's meant only to has move-only semantics, but for some reason is_trivially_copy_constructible is used as you can see from the short log. Any suggestions how to fix it?

sorry, is_trivially_copy_constructible is actually correct, because move is not trivial there.

Patch-set: 5