Update patch set 2
Patch Set 2:

Adding the revert reason:
This CL is suspected of causing a build failure here:
https://ci.chromium.org/buildbot/chromium.chrome/Google%20Chrome%20Win/26226

Here is the error snippet from the log file:
[27778/45926] CXX obj/media/mojo/services/services/cdm_service.obj
FAILED: obj/media/mojo/services/services/cdm_service.obj 
...
In file included from ../../media/mojo/services/cdm_service.cc:5:
../..\media/mojo/services/cdm_service.h(49,21):  error: use of undeclared identifier 'CdmHostFilePath'
        std::vector<CdmHostFilePath>* cdm_host_file_paths) = 0;
                    ^
1 error generated.

Patch-set: 2