Revert of Refactoring: Merge VideoSenderConfig and AudioSenderConfig. (patchset #4 id:100001 of https://codereview.chromium.org/2113783002/ )
Reason for revert:
[1226/2497] CXX obj/media/cast/sender/cast_h264_vt_encoder_unittests.h264_vt_encoder_unittest.o
FAILED: obj/media/cast/sender/cast_h264_vt_encoder_unittests.h264_vt_encoder_unittest.o
/b/build/slave/cache/cipd/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/media/cast/sender/cast_h264_vt_encoder_unittests.h264_vt_encoder_unittest.o.d -DV8_DEPRECATION_WARNINGS -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORE=0 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=274369-1 -DCOMPONENT_BUILD -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_EXTERNAL_POPUP_MENU -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGIN_INSTALLATION=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_BROWSER_SPELLCHECKER=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DGTEST_HAS_POSIX_RE=0 -DGTEST_LANG_CXX11=0 -DPROTOBUF_USE_DLLS -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DUNIT_TEST -DGTEST_HAS_RTTI=0 -DUSE_LIBPCI=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -Igen -I../.. -I../../third_party/khronos -I../../gpu -I../.. -I../../skia/config -Igen/angle -Igen/protoc_out -I../../third_party/protobuf/src -I../../testing/gmock/include -I../../testing/gtest/include -I../../third_party/ffmpeg/chromium/config/Chromium/mac/x64 -I../../third_party/ffmpeg -isysroot /b/build/slave/Mac_GYP__dbg_/build/src/build/mac_files/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -O0 -gdwarf-2 -fvisibility=hidden -Werror -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-selector-type-mismatch -Wpartial-availability -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -fno-threadsafe-statics -fcolor-diagnostics -Xclang -load -Xclang /b/build/slave/Mac_GYP__dbg_/build/src/third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.dylib -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Xclang -plugin-arg-find-bad-constructs -Xclang check-implicit-copy-ctors -fno-strict-aliasing -fstack-protector-strong  -c ../../media/cast/sender/h264_vt_encoder_unittest.cc -o obj/media/cast/sender/cast_h264_vt_encoder_unittests.h264_vt_encoder_unittest.o
../../media/cast/sender/h264_vt_encoder_unittest.cc:267:10: error: unknown type name 'VideoSenderConfig'; did you mean 'VideoDecoderConfig'?
  static VideoSenderConfig video_sender_config_;
         ^~~~~~~~~~~~~~~~~
         VideoDecoderConfig
../../media/base/video_decoder_config.h:26:20: note: 'VideoDecoderConfig' declared here
class MEDIA_EXPORT VideoDecoderConfig {
                   ^
../../media/cast/sender/h264_vt_encoder_unittest.cc:235:24: error: no matching constructor for initialization of 'media::cast::H264VideoToolboxEncoder'
    encoder_.reset(new H264VideoToolboxEncoder(
                       ^
../../media/cast/sender/h264_vt_encoder.h:38:3: note: candidate constructor not viable: no known conversion from 'media::VideoDecoderConfig' to 'const media::cast::FrameSenderConfig' for 2nd argument
  H264VideoToolboxEncoder(
  ^
../../media/cast/sender/h264_vt_encoder.h:125:28: note: candidate constructor not viable: requires 1 argument, but 3 were provided
  DISALLOW_COPY_AND_ASSIGN(H264VideoToolboxEncoder);
                           ^
../../media/cast/sender/h264_vt_encoder_unittest.cc:256:26: error: no viable overloaded '='
    video_sender_config_ = GetDefaultVideoSenderConfig();
    ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../media/base/video_decoder_config.h:26:20: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'media::cast::FrameSenderConfig' to 'const media::VideoDecoderConfig' for 1st argument
class MEDIA_EXPORT VideoDecoderConfig {
                   ^
../../media/cast/sender/h264_vt_encoder_unittest.cc:257:26: error: reference to non-static member function must be called; did you mean to call it with no arguments?
    video_sender_config_.codec = CODEC_VIDEO_H264;
    ~~~~~~~~~~~~~~~~~~~~~^~~~~
                              ()
../../media/cast/sender/h264_vt_encoder_unittest.cc:257:32: error: expression is not assignable
    video_sender_config_.codec = CODEC_VIDEO_H264;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../../media/cast/sender/h264_vt_encoder_unittest.cc:283:1: error: unknown type name 'VideoSenderConfig'; did you mean 'VideoDecoderConfig'?
VideoSenderConfig H264VideoToolboxEncoderTest::video_sender_config_;
^~~~~~~~~~~~~~~~~
VideoDecoderConfig
../../media/base/video_decoder_config.h:26:20: note: 'VideoDecoderConfig' declared here
class MEDIA_EXPORT VideoDecoderConfig {
                   ^
6 errors generated.

Original issue's description:
> Refactoring: Merge VideoSenderConfig and AudioSenderConfig.
> In the CL: 1) VideoSenderConfig and AudioSenderConfig are merged to
> FrameSenderConfig. 2) CastRtpParams is removed . RtpParams is directly
> converted to/from FrameSenderConfig.
>
> BUG=530839
>
> Committed: https://crrev.com/4c97152e0f2b9bf5883d7ea7f149c932598c3afc
> Cr-Commit-Position: refs/heads/master@{#404520}

TBR=mek@chromium.org,miu@chromium.org,xjz@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=530839

Review-Url: https://codereview.chromium.org/2133223003