Roll WebRTC 14190:14262 (72 commits)
Changes: https://chromium.googlesource.com/external/webrtc/trunk/webrtc.git/+log/1dd0a8c..ccd06a2

$ git log 1dd0a8c..ccd06a2 --date=short --no-merges --format=%ad %ae %s
2016-09-16 henrik.lundin@webrtc.org NetEq: Remove a test printout
2016-09-16 sakal@webrtc.org Change AppRTCDemoJUnitTest to use LocalRobolectricTestRunner.
2016-09-16 minyue@webrtc.org Adding DTX controller to audio network adaptor.
2016-09-16 nisse@webrtc.org Revert of Update test code to use I420Buffer when writing pixel data. (patchset #2 id:140001 of https://codereview.webrtc.org/2342783003/ )
2016-09-16 nisse@webrtc.org Reland of Update test code to use I420Buffer when writing pixel data. (patchset #1 id:1 of https://codereview.webrtc.org/2342123003/ )
2016-09-16 sakal@webrtc.org Remove Android tests GYP target.
2016-09-16 phoglund@webrtc.org Enable turn, sdp, pseudotcp and stun parse/validator fuzzers.
2016-09-16 sakal@webrtc.org Revert of Fix android_junit_tests and add a GN target for them. (patchset #3 id:90001 of https://codereview.webrtc.org/2344133002/ )
2016-09-16 sakal@webrtc.org Reland of Fix android_junit_tests and add a GN target for them. (patchset #1 id:1 of https://codereview.webrtc.org/2341213003/ )
2016-09-16 henrika@webrtc.org Revert of Fix android_junit_tests and add a GN target for them. (patchset #1 id:20001 of https://codereview.webrtc.org/2346793002/ )
2016-09-16 sakal@webrtc.org Update anroidapp/README for GN build.
2016-09-16 nisse@webrtc.org Revert of Update test code to use I420Buffer when writing pixel data. (patchset #5 id:80001 of https://codereview.webrtc.org/2333373007/ )
2016-09-16 palmkvist@webrtc.org Removing, opening and creating files in platform_file and file
2016-09-16 nisse@webrtc.org Update test code to use I420Buffer when writing pixel data.
2016-09-16 zijiehe@chromium.org Wrap ScreenCapturer with ScreenCapturerDifferWrapper This change is to add an DesktopCapturerOptions accurate_updated_region() with default value as false to indicate whether a pixel-wise differentiation is required. And ScreenCapturer::Create() function will wrap the implementation with ScreenCapturerDifferWrapper.
2016-09-16 peah@webrtc.org Correcting the enabling of the level controller in the audio processing simulator
2016-09-15 hbos@webrtc.org PeerConnection[Interface]::GetStats(RTCStatsCollectorCallback*) added.
2016-09-15 deadbeef@webrtc.org Fixing a couple cases that cause ProcessAllMessageQueues to hang.
2016-09-15 honghaiz@webrtc.org Adding logs to track potential cause of not starting port allocation.
2016-09-15 solenberg@webrtc.org Add voe_cmd_test to voice_engine/BUILD.gn (and remove it from voice_engine.gyp, together with the channel_transport gyp target)
2016-09-15 sakal@webrtc.org Add logging available fps ranges to Camera2Session.
2016-09-15 sakal@webrtc.org Fix android_junit_tests and add a GN target for them.
2016-09-15 danilchap@webrtc.org Merge RtcpReceiver::Handle<Packet>Item functions into Handle<Packet> As a preparation to replace parsing implementation.
2016-09-15 perkj@webrtc.org Revert of Replace interface VideoCapturerInput with VideoSinkInterface. (patchset #13 id:280001 of https://codereview.webrtc.org/2257413002/ )
2016-09-15 perkj@webrtc.org Replace VideoCapturerInput with VideoSinkInterface. Adds new method VideoSendStream::SetSource(rtc::VideoSourceInterface* and VieEncoder::SetSource(rtc::VideoSourceInterface*)
2016-09-15 danilchap@webrtc.org Split RtcpReceiver::HandleSenderReceiverReport into two functions as a preparation to replace parsing implementation
2016-09-15 nisse@webrtc.org Use I420Buffer rather than VideoFrameBuffer when writing pixels.
2016-09-15 hbos@webrtc.org Removed the const char* (StaticString) type from RTCStatsMember.
2016-09-15 magjed@webrtc.org Android SurfaceViewRenderer: Create EGL context on render thread
2016-09-15 maxmorin@webrtc.org Reland of Add arraysize to rtc_base_approved. Remove dependency of audio_device on rtc_base. (patchset #1 id:1 of https://codereview.webrtc.org/2340253003/ )
2016-09-15 stefan@webrtc.org Disable all screen-capturer tests
2016-09-15 kjellander@webrtc.org GYP: Remove targets inside include_tests==1 that are converted to GN.
2016-09-15 ehmaldonado@webrtc.org Assume ProjectRootPath() equals ../.. in Desktop
2016-09-15 philipel@webrtc.org Stash non layer-sync frames if we have not yet received an earlier frame for this layer.
2016-09-15 kthelgason@webrtc.org [GN] Add rtc_sdk_framework_objc target to GN
2016-09-15 solenberg@webrtc.org The VoE functionality to apply receive-side processing to VoE channels is unused. I'm removing it so we can avoid instantiating a full APM per channel (and thus also for webrtc::AudioSendStream and webrtc::AudioReceiveStream), and then never use it.
2016-09-15 kjellander@webrtc.org MB: Change Android Clang to build shared instead of static.
2016-09-15 kthelgason@webrtc.org Fix undefined reference to log2 on android
2016-09-15 maxmorin@webrtc.org Revert of Add arraysize to rtc_base_approved. Remove dependency of audio_device on rtc_base. (patchset #1 id:1 of https://codereview.webrtc.org/2346763002/ )
2016-09-15 maxmorin@webrtc.org Add arraysize to rtc_base_approved. Remove dependency of audio_device on rtc_base.
2016-09-15 kjellander@webrtc.org GN: Change group deps to public_deps.
2016-09-15 henrik.lundin@webrtc.org Remove a couple of unnecessary dependencies on gflags
2016-09-14 kjellander@webrtc.org iSAC: Remove unnecessary WEBRTC_LINUX define
2016-09-14 nisse@webrtc.org Add method cricket::VideoCapturer::NeedsDenoising, use in VideoCapturerTrackSource.
2016-09-14 zijiehe@chromium.org [WebRTC] Add TwoCapturers test and TwoMagnifierCapturers test
2016-09-14 danilchap@webrtc.org Move CopyOnWriteBuffer functions definitions from .h to .cc
2016-09-14 minyue@webrtc.org Adding ChannelController to audio network adaptor.
2016-09-14 hbos@webrtc.org Fix issues with rtc_stats_unittests tests so that they can run on bots. This target is not run on bots so a couple of issues went under the radar. If we expose the tests and run them on the bots[1] two issues are surfaced which this CL fixes. After this CL lands we can enable this target on the bots without it going red.
2016-09-14 solenberg@webrtc.org Relaxed unnecessarily stringent thread checking in WebRtcAudioSendStream::OnData().
2016-09-14 nisse@webrtc.org Use I420Buffer rather than VideoFrameBuffer when writing pixels.
2016-09-14 sakal@webrtc.org Change onCameraOpening to take camera name as a parameter instead of camera id.
2016-09-14 kwiberg@webrtc.org webrtc/modules/audio_processing: Use RTC_DCHECK() instead of assert()
2016-09-14 ehmaldonado@webrtc.org GN: Declare resources for targets.
2016-09-14 gaetano.carlucci@gmail.com Enable BWE logging to command line when rtc_enable_bwe_test_logging is set to true
2016-09-14 magjed@webrtc.org Android EglBase: Include EGL error code in exceptions
2016-09-14 kthelgason@webrtc.org Refactor QualityScaler and MovingAverage
2016-09-14 nisse@webrtc.org New method TimestampAligner::TranslateTimestamp
2016-09-14 maxmorin@webrtc.org Remove dependency of audio_device on metrics_default.
2016-09-13 danilchap@webrtc.org Remove handling unused rtcp packets. App, ExtendedJitterReport and VoipMetric in ExtenedReports are not used when received (no callbacks, no state change), so removed.
2016-09-13 nisse@webrtc.org Delete Timing class, timing.h, and update all users.
2016-09-13 peah@webrtc.org Added build flag around the Intelligibility enhancer performance test code
2016-09-13 minyue@webrtc.org Adding basic implementation of AudioNetworkAdaptor.
2016-09-13 danilchap@webrtc.org Reland of Make rtcp parsing implementation private in RtcpReceiver (patchset #1 id:1 of https://codereview.webrtc.org/2332673003/ )
2016-09-13 kwiberg@webrtc.org Replace a DCHECK with static_assert
2016-09-13 solenberg@webrtc.org Moved webrtc/test/channel_transport/ into webrtc/voice_engine/test/
2016-09-13 charujain@webrtc.org Fixed video_loopback target.
2016-09-13 danilchap@webrtc.org Make CopyOnWriteBuffer keep capacity for SetData and Clear functions too.
2016-09-13 danilchap@webrtc.org Update rtcp receiver fuzzer to use generic function IncomingPacket(const uint8_t* packet, size_t size) instead of implementation specific IncomingRTCPPacket(PacketInfo* out, Parser* in) This would allow switch parse implementation
2016-09-13 brandtr@webrtc.org Minor fixes in FEC and RtpSender{,Video}
2016-09-13 solenberg@webrtc.org Revert of Moved webrtc/test/channel_transport/ into webrtc/voice_engine/test/ (patchset #7 id:120001 of https://codereview.webrtc.org/2319583005/ )
2016-09-13 kwiberg@webrtc.org webrtc/base: Use RTC_DCHECK() instead of assert()
2016-09-13 solenberg@webrtc.org Moved webrtc/test/channel_transport/ into webrtc/voice_engine/test/

TBR=
CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_chromium_archive_rel_ng;master.tryserver.chromium.mac:mac_chromium_archive_rel_ng
BUG=

Review-Url: https://codereview.chromium.org/2341173003