Revert "Make it easier to test changes to a .icon file."
Reason for revert:
build errors on GN bots

LINUX:
FAILED: /mnt/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ui/views/examples/views_examples_lib/vector_example.o.d .....
../../ui/views/examples/vector_example.cc:112:14:error: no member named 'CreateVectorIconFromSource' in namespace 'gfx'
        gfx::CreateVectorIconFromSource(contents, size_, color_));
        ~~~~~^
1 error generated.

WIN:
[472/771] LINK generate_barcode_video.exe
FAILED: ninja -t msvc -e environment.x64 -- E:\b\build\goma/gomacc.exe "E:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64/cl.exe" /nologo /showIncludes /FC @obj/ui/views/examples/views_examples_lib/vector_example.obj.rsp ....
e:\b\build\slave\win_x64_gn\build\src\ui\views\examples\vector_example.cc(112) :error C2039: 'CreateVectorIconFromSource' : is not a member of 'gfx'
e:\b\build\slave\win_x64_gn\build\src\ui\views\examples\vector_example.cc(112) :error C3861: 'CreateVectorIconFromSource': identifier not found
ninja: build stopped: subcommand failed.

>   Make it easier to test changes to a .icon file.

>   No need to recompile Chrome; views_examples_exe will read from a file. This would also be useful for the tool which will allow de
>
>   Since this is potentially unsafe (could crash on the wrong inputs) and doesn't serve a purpose in Chrome itself, it's ifdef'd out
>
>   BUG=505953
>
>   Review URL: https://codereview.chromium.org/1268633002
>
>   Cr-Commit-Position: refs/heads/master@{#341667}

TBR=estade@chromium.org
BUG=

Review URL: https://codereview.chromium.org/1264343003 .