third_party/freetype2: Add missing zlib dep.
Add zlib dependency in third_party/freetype2/BUILD.gn, as it is
already done in third_party/freetype-android/BUILD.gn to fix the
following compilation error:

  ../../src/third_party/freetype2/src/src/gzip/ftgzip.c:49:18: fatal
    error: zlib.h: No such file or directory

BUG=none

Review-Url: https://chromiumcodereview.appspot.com/2442733003