Disable thumb when building tcmalloc
This fixes the arm/linux build which is currently
broken because third_party/tc_malloc is not currently
buildable with -mthumb:

atomicops-internals-arm-v6plus.h:268:8:
 error: instruction requires: arm-mode "strexd  %0, %2, [%3]\n"`

BUG=564059

Review-Url: https://codereview.chromium.org/2515503002