Update patch set 7
Patch Set 7:

For those of us who can't get to uberchromegw.corp.google.com, the build failures are warnings-as-errors of this sort:

FAILED: obj/third_party/libpng/libpng_sources/palette_neon_intrinsics.o 
/b/build/slave/cache/goma_client/gomacc clang -MMD -MF obj/third_party/libpng/libpng_sources/palette_neon_intrinsics.o.d -DPNG_ARM_NEON_OPT=2 -DPNG_ARM_NEON_IMPLEMENTATION=1 -DV8_DEPRECATION_WARNINGS -DNO_TCMALLOC -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_XCODE_VERSION=0920 -DCR_CLANG_REVISION=\"321529-1\" -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DNS_BLOCK_ASSERTIONS=1 -I../.. -Igen -I../../third_party/libpng -I../../third_party/zlib -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fcolor-diagnostics -no-canonical-prefixes -arch armv7 -Oz -fno-omit-frame-pointer -gdwarf-2 -isysroot /b/build/slave/cache/xcode_ios_9c40b.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -stdlib=libc++ -miphoneos-version-min=10.0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Werror -Wall -Wno-unused-variable -Wunguarded-availability -Wundeclared-selector -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-address-of-packed-member -Wno-tautological-constant-out-of-range-compare -std=c11 -c ../../third_party/libpng/arm/palette_neon_intrinsics.c -o obj/third_party/libpng/libpng_sources/palette_neon_intrinsics.o
../../third_party/libpng/arm/palette_neon_intrinsics.c:33:7: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
      vdupq_n_u8(0x00),
      ^~~~~~~~~~~~~~~~~

Got to remember that those structured types look like

struct uint8x8x4_t {
    uint8x8_t vals[4];
};

a struct with a single array of vectors member.  I usually like to initialize them like

uint8x8x4_t foo = {{
  vdup_n_u8(0),
  vdup_n_u8(0),
  vdup_n_u8(0),
  vdup_n_u8(0),
}};

Patch-set: 7