Update patch set 1
Patch Set 1: Code-Review+1

../../chrome/browser/safe_browsing/safe_browsing_service_browsertest.cc:1874:15: error: no member named 'NOTIFICATION_SAFE_BROWSING_UPDATE_COMPLETE' in namespace 'chrome'
      chrome::NOTIFICATION_SAFE_BROWSING_UPDATE_COMPLETE,

Need to update browser test too.

Patch-set: 1
Reviewer: Jialiu Lin <1144209@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1