Update patch set 10
Patch Set 10:

> Patch Set 10:
> 
> > Patch Set 10:
> > 
> > > Patch Set 10:
> > > 
> > > > Patch Set 10:
> > > > 
> > > > I notice your in-progress Apache update for Windows ( https://chromium-review.googlesource.com/c/chromium/src/+/707535 ) also doesn't include mod_env. Is there any chance it could be included so %TEMP% can be propagated through to CGI?
> > > 
> > > Yep - I'm pretty sure that this CL will land before that one, so I'll just rebase that CL off of this one after it lands and make sure it includes mod_env at the end :-)
> > 
> > Thank you! To be clear, though: the DLL itself is actually missing, so simply adding it to the config is not working on Windows (on Mac and Linux it is present, though.) How should I go about adding the mod_env DLL?
> 
> In general, the mod_* DLLs for Win Apache are uploaded to Google Storage in the bucket "chromium-apache-win32".
> 
> The process for adding a DLL to be used by Win Apache should be: put it in //third_party/apache-win32/modules/, then call
> 
>   upload_to_google_storage.py --bucket chromium-apache-win32 third_party/apache-win32/modules/mod_env.dll
> 
> This will create a .sha1 file referencing a file stored in GS. Then the original dll could be deleted. To test: On Windows, running gclient runhooks should download the new DLL, then third_party/WebKit/Tools/Scripts/run-blink-httpd should still work. This can be tried with try jobs.

Unfortunately I seem to lack permission to upload there:

~/chromium/src$ (
wget https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-openssl-0.9.8y.msi
wget https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1
msiextract httpd-2.2.25-win32-x86-openssl-0.9.8y.msi | fgrep mod_env.so
mv Program\ Files/Apache\ Software\ Foundation/Apache2.2/modules/mod_env.so third_party/apache-win32/modules/
rm -rf Program\ Files
if [ "`sha1sum httpd-2.2.25-win32-x86-openssl-0.9.8y.msi | awk '{print $1}'`" = "`cat httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1 | awk '{print $1}'`" ]; then
  upload_to_google_storage.py --bucket chromium-apache-win32 third_party/apache-win32/modules/mod_env.so
fi
rm httpd-2.2.25-win32-x86-openssl-0.9.8y.msi
rm httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1
)
--2017-11-28 14:11:49--  https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-openssl-0.9.8y.msi
Resolving archive.apache.org (archive.apache.org)... 163.172.17.199
Connecting to archive.apache.org (archive.apache.org)|163.172.17.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6438912 (6.1M) [application/x-msi]
Saving to: ‘httpd-2.2.25-win32-x86-openssl-0.9.8y.msi’

httpd-2.2.25-win32-x86-openssl-0.9.8y.msi        100%[==========================================================================================================>]   6.14M  --.-KB/s    in 0.1s

2017-11-28 14:11:49 (48.9 MB/s) - ‘httpd-2.2.25-win32-x86-openssl-0.9.8y.msi’ saved [6438912/6438912]

--2017-11-28 14:11:49--  https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1
Resolving archive.apache.org (archive.apache.org)... 163.172.17.199
Connecting to archive.apache.org (archive.apache.org)|163.172.17.199|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 83 [application/x-sha1]
Saving to: ‘httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1’

httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1   100%[==========================================================================================================>]      83  --.-KB/s    in 0s

2017-11-28 14:11:49 (6.81 MB/s) - ‘httpd-2.2.25-win32-x86-openssl-0.9.8y.msi.sha1’ saved [83/83]

Program Files/Apache Software Foundation/Apache2.2/modules/mod_env.so
Main> Calculating hash for third_party/apache-win32/modules/mod_env.so...
Main> Done calculating hash for third_party/apache-win32/modules/mod_env.so.
0> Uploading third_party/apache-win32/modules/mod_env.so...
Hashing 1 files took 0.000456 seconds
Uploading took 41.441918 seconds
Encountered error on uploading third_party/apache-win32/modules/mod_env.so to gs://chromium-apache-win32/acf0b18c9fb0b07f725e7c6e63b1d91e0a02caee
Copying file://third_party/apache-win32/modules/mod_env.so [Content-Type=application/octet-stream]...
AccessDeniedException: 403 bsittler@chromium.org does not have storage.objects.create access to chromium-apache-win32/acf0b18c9fb0b07f725e7c6e63b1d91e0a02caee.

Patch-set: 10
Reviewer: Benjamin Wiley Sittler <1204072@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0