Update patch set 1
Patch Set 1:

Hi, this is still a WIP CL, but I just want to throw a question that needs your help.

As you can see, there is compile error:
-----------------------------------
../../third_party/boringssl/src/include/openssl/base.h:71:10: fatal error: 'openssl/is_boringssl.h' file not found                                                                      
#include <openssl/is_boringssl.h>             
         ^~~~~~~~~~~~~~~~~~~~~~~~  
-----------------------------------

(1)Root cause analysis:
I think it should be caused by fetch_api_request.mojom is imported in service_worker_client.mojom, because we need use the mojom enum type RequestContextFrameType.
But fetch_api_request.mojom.h would finally depends on a content header "referrer.h", IIUC, anything in the third_party/WebKit/common/ should *NOT* depend on things outside, so the error happens.

(2) How to fix:
I am not sure the solution, but I think create a new service_worker_client_info.mojom in third_party/WebKit/public/platform/modules/serviceworker/ should fix that?
But it violate "new mojom files also used by browser should be in third_party/WebKit/common/". But it seems we only can put the simple mojom file that not depends on outside files into the ~/common/ folder?

Maybe we can also create a new mojom file only includes RequestContextFrameType in ~/common/, but that seems weird and I am not sure it's a valid way.

Based on above, could you give some suggestion? We should do this mojofication to implement the mojo interface ServiceWorkerHost.

Patch-set: 1
Reviewer: Matt Falkenhagen <1000128@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Kinuko Yasuda <1001472@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Makoto Shimazu <1125915@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
CC: Han Leon <1161621@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Xiaofeng Zhang <1223459@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false