Missing dependency to use histogram in webrtc
browser target should depend on webrtc:init_webrtc to unblock webrtc from using
histogram even in component build.

In component build, the static lib generated by webrtc_override:init_webrtc is
not included in chrome/browser:browser target and triggers build breaks like,

========================
[64275/77781] SOLINK ./libchrome.cr.so
FAILED: libchrome.cr.so libchrome.cr.so.TOC lib.unstripped/libchrome.cr.so 
python "../../build/toolchain/gcc_solink_wrapper.py" ...
../../third_party/webrtc/modules/desktop_capture/blank_detector_desktop_capturer_wrapper.cc:82: error: undefined reference to 'webrtc::metrics::HistogramFactoryGetEnumeration(...)'
========================

Refer to build break log,
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.win%2Fwin_chromium_compile_dbg_ng%2F469708%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout
and
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.android%2Fandroid_arm64_dbg_recipe%2F321334%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout
when
https://chromium-review.googlesource.com/c/615852
is submitted.

It's preferred for the clients of webrtc to decide which target to link. See
https://codereview.chromium.org/2998583002/ as a reference.

Bug: webrtc:8040, webrtc:8046
Change-Id: I42983ed598863ae2a6ddd9db10bc9085abde0a8a