Update patch set 3
Patch Set 3:

chromium-win bot got sad:

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.win%2FWin_Builder%2F41181%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

FAILED: nacl_win64/obj/base/base/task_scheduler.obj 
ninja -t msvc -e environment.x64 -- C:\b\c\goma_client/gomacc.exe "c:\b\c\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64/cl.exe" /nologo /showIncludes /FC @nacl_win64/obj/base/base/task_scheduler.obj.rsp /c ../../base/task_scheduler/task_scheduler.cc /Fonacl_win64/obj/base/base/task_scheduler.obj /Fd"nacl_win64/obj/base/base_cc.pdb"
c:\b\c\b\win\src\base\task_scheduler\task_scheduler_impl.h(109): error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win\src\base\task_scheduler\task_scheduler_impl.h(109): warning C4067: unexpected tokens following preprocessor directive - expected a newline

Does this need to be `#if defined(COM_INIT_CHECK_HOOK_ENABLED)` instead of `#if COM_INIT_CHECK_HOOK_ENABLED()` ?

Patch-set: 3
CC: Joshua Bell <1001349@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>