Revert of Resurrect Aura Linux accessibility. (patchset #15 id:280001 of https://codereview.chromium.org/975113002/)
Reason for revert:
Caused compile failure on Linux x64 bot (http://build.chromium.org/p/chromium.chrome/builders/Google%20Chrome%20Linux%20x64/builds/56532)

Output snippet:
FAILED: cd ../../chrome; flock -- /tmp/linux_package_lock bash ../out/Release/installer/debian/build.sh -o../out/Release -b ../out/Release -a x64 -c unstable
dpkg-shlibdeps: warning: binaries to analyze should already be installed in their package's directory.
2a3
> libatk1.0-0 (>= 1.12.4)

ERROR: Shared library dependencies changed!
If this is intentional, please update:
chrome/installer/linux/debian/expected_deps_ia32
chrome/installer/linux/debian/expected_deps_x64

Original issue's description:
> Resurrect Aura Linux accessibility.
>
> This is based in part on the ATK code we had as part of the Linux GTK port
> that went away, but now rewritten on top of AXPlatformNode. This patch
> successfully exposes an accessibility tree for Views and exposes top-level
> windows and the the role and name of each View. You can test it using
> accerciser. This is just to get the infrastructure in place - we need to
> implement more of the interface for it to be useful for accessibility tools.
>
> BUG=463671
>
> Committed: https://crrev.com/f65bad877350b5f7857d29e4b1b0d4d3f5c7cb6d
> Cr-Commit-Position: refs/heads/master@{#320383}

TBR=plundblad@chromium.org,dpranke@chromium.org,sky@chromium.org,gunsch@chromium.org,dmazzoni@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=463671

Review URL: https://codereview.chromium.org/1002993002