Fix build for VaapiTFPPicture
Introduced recently by https://chromium-review.googlesource.com/756711
  "Wrap X11 headers in ui/gfx/x/x11.h"

Build error 1:
  media/gpu/vaapi/vaapi_tfp_picture.cc:
    error use of undeclared identifier 'RootWindow'; did you mean 'XRootWindow'?
      x_pixmap_ = XCreatePixmap(x_display_, RootWindow(x_display_, screen),

Build error 2:
  In file included from ../../media/gpu/vaapi_video_decode_accelerator_unittest.cc:14:
  error: expected unqualified-id
    /usr/include/X11/X.h:115:30: note: expanded from macro 'None'

Bug: 782184
Change-Id: I1b1ecf39baee160e1778e5cdd596426a63e4e054