Revert of gfx: build fix about VectorIconSource (patchset #1 id:1 of https://codereview.chromium.org/1577743002/ )
Reason for revert:
This issue is known in crbug.com/506663 and we want to fix c++ spec and clang rather than making chromium code silly.
Nico asked to revert it.

Original issue's description:
> gfx: build fix about VectorIconSource
>
> clang complains it doesn't initialize const member, so this CL calls the
> default constructor explicitly.
>
> ../../ui/gfx/paint_vector_icon.cc:287:3: error: constructor for 'gfx::(anonymous namespace)::VectorIconSource' must explicitly initialize the const member 'path_'
>   VectorIconSource(VectorIconId id,
>   ^
> ../../ui/gfx/paint_vector_icon.cc:324:34: note: 'path_' declared here
>   const std::vector<PathElement> path_;
>                                  ^
> 1 error generated.
>
> Committed: https://crrev.com/f5dc983806e7df11e05c8e5a027ccbb440c0988f
> Cr-Commit-Position: refs/heads/master@{#368650}

TBR=danakj@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.

Review URL: https://codereview.chromium.org/1588513002