Revert of Fix crash in TemplateURLService::GoogleBaseURLChanged() (patchset #1 id:1 of https://codereview.chromium.org/2612063003/ )
Reason for revert:
Breaks build.

https://uberchromegw.corp.google.com/i/official.android.continuous/builders/beta-arm/builds/5778

../../chrome/browser/search_engines/template_url_service_unittest.cc:1003:21: error: no matching function for call to 'TemplateURLServiceWithoutFallbackTest_ChangeGoogleBaseValue_Test::AddKeywordWithDate(const char [5], const char [10], const char [40], std::__ndk1::string, std::__ndk1::string, std::__ndk1::string, bool, const char [6], base::Time, base::Time, base::Time)'
       Time(), Time());

Original issue's description:
> Fix crash in TemplateURLService::GoogleBaseURLChanged()
>
> BUG=650143
>
> Review-Url: https://codereview.chromium.org/2567413002
> Cr-Commit-Position: refs/heads/master@{#440143}
> (cherry picked from commit 0df98300178db8c8daf7b69a6bbf74fa5b7b3a80)
>
> Committed: https://chromium.googlesource.com/chromium/src/+/2f418d3bf9b2b99957abbebc70abbd45b75af8c3

TBR=pkasting@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=650143

Review-Url: https://codereview.chromium.org/2611043002