Update patch set 4
Patch Set 4:

It looks like this change broke the VC++ builders on Windows. They are listed as clang builders but now that clang is the default they build with VC++ because we want to keep it working for a while.

Error is:
FAILED: obj/third_party/WebKit/Source/bindings/core/v8/bindings_core_impl/V8GeneratedCoreBindings.obj 
ninja -t msvc -e environment.x64 -- E:\b\c\goma_client/gomacc.exe "e:\b\c\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/third_party/WebKit/Source/bindings/core/v8/bindings_core_impl/V8GeneratedCoreBindings.obj.rsp /c gen/blink/bindings/core/v8/V8GeneratedCoreBindings.cpp /Foobj/third_party/WebKit/Source/bindings/core/v8/bindings_core_impl/V8GeneratedCoreBindings.obj /Fd"obj/third_party/WebKit/Source/bindings/core/v8/bindings_core_impl_cc.pdb"
../../third_party/WebKit/Source\core/dom/StyleEngine.h(72): error C2220: warning treated as error - no 'object' file generated
../../third_party/WebKit/Source\core/dom/StyleEngine.h(72): warning C4275: non dll-interface class 'blink::FontSelectorClient' used as base for dll-interface class 'blink::StyleEngine'
../../third_party/WebKit/Source\platform/fonts/FontSelectorClient.h(14): note: see declaration of 'blink::FontSelectorClient'
../../third_party/WebKit/Source\core/dom/StyleEngine.h(71): note: see declaration of 'blink::StyleEngine'
[10748/20200] CXX obj/third_party/WebKit/Source/bindings/core/v8/bindings_core_impl/RadioNodeListOrElement.obj

Build status (showing it going red on 9439) is here:
https://build.chromium.org/p/chromium.fyi/builders/CrWinClang64%28dll%29

Can you take a look?

Patch-set: 4
CC: Bruce Dawson <1128439@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>