Make scoped_refptr constexpr default constructible.
Remove support for opaque types in scoped_refptr. These weren't used
anywhere and already strongly discouraged.
"constexpr" implies "inline" and as such template instantiation being
in a separate translation unit breaks the single-definition rule,
generating errors like the following:
FAILED: obj/base/x64/base_unittests
TOOL_VERSION=1511399083 ../../build/toolchain/mac/linker_driver.py clang++  -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker obj/base/base_unittests.xcent -arch x86_64 -Werror -isysroot /b/build/slave/cache/xcode_ios_9c40b.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk -stdlib=libc++ -mios-simulator-version-min=10.0 -Wl,-ObjC -o "obj/base/x64/base_unittests" -Wl,-filelist,"obj/base/x64/base_unittests.rsp"  -framework UIKit -framework CoreFoundation -framework CoreGraphics -framework CoreText -framework Foundation
Undefined symbols for architecture x86_64:
  "scoped_refptr<base::OpaqueRefCounted>::scoped_refptr()", referenced from:
      RefCountedUnitTest_ScopedRefPtrToOpaque_Test::TestBody() in ref_counted_unittest.o
  "scoped_refptr<base::OpaqueRefCountedThreadSafe>::scoped_refptr()", referenced from:
      RefCountedUnitTest_ScopedRefPtrToOpaqueThreadSafe_Test::TestBody() in ref_counted_unittest.o
ld: symbol(s) not found for architecture x86_64

Not supporting opaque types is a fallout of scoped_refptr needing to know
the type is a subclass of RefCounted(ThreadSafe). Workarounds have already
been attempted and failed.

Prior discussion and conclusion to discourage their usage :
https://groups.google.com/a/chromium.org/d/topic/chromium-dev/0khIRhxDq6E/discussion

Bug: 800760
Change-Id: I1a413cad642e1703f4722dc597a91436f6c0c711