Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > Can you reenable corresponding stories to see if these new recordings fix it? 
> 
> Yeah but not until we fix the DCHECKs that some of them hit. Only the Gmail one is actually disabled currently. I'm going to send some additional changes shortly.
> 
> > Also I don't see your change to facebook story?
> 
> It's there in the JSON file. I can't tell whether the actual recorded data was updated in cloud storage. How can I check? And where is the file locally? I see:
> 
> -rw------- 1 wkorman eng 36 Sep  1 13:27 ./tools/perf/page_sets/data/top_25_007.wprgo
> 
> but it's only 36 bytes.

It doesn't look like it did the upload. I switched branches, did some other stuff (but did not record again), and when I switch back and try to run the techcrunch story I get the error below.

So I guess I need to re-record with the hacks again, but I still don't know how to upload the WPRgo files after (or as part of) the re-recording. If the solution is to use the script:

% depot_tools/upload_to_google_storage.py <path to .wprgo file> --bucket=<appropriate bucket>

then we have to figure out what's up with the .wprgo file since for whatever reason record_wpr is outputting just a 36 byte file.

[ RUN      ] http://techcrunch.com
(WARNING) 2017-09-01 16:01:46,654 shared_page_state.DumpStateUponFailure:140  Cannot dump browser state: No browser.
(WARNING) 2017-09-01 16:01:46,655 screenshot.TryCaptureScreenShot:45  Either tab has crashed or browser does not support taking tab screenshot. Skip taking screenshot on failure.
Traceback (most recent call last):
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py", line 98, in _RunStoryAndProcessErrorIfNeeded
    state.WillRunStory(story)
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_event_impl/decorators.py", line 52, in traced_function
    return func(*args, **kwargs)
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/page/shared_page_state.py", line 241, in WillRunStory
    archive_path, page.make_javascript_deterministic)
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_event_impl/decorators.py", line 52, in traced_function
    return func(*args, **kwargs)
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/core/network_controller.py", line 42, in StartReplay
    make_javascript_deterministic)
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/network_controller_backend.py", line 193, in StartReplay
    local_ports = self._StartReplayServer()
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/network_controller_backend.py", line 227, in _StartReplayServer
    return self._wpr_server.StartServer()
  File "/usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/util/webpagereplay_go_server.py", line 283, in StartServer
    ''.join(self._LogLines()))
ReplayNotStartedError: Web Page Replay failed to start. Log output:
2017/09/01 16:01:12 Loading cert from /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/web_page_replay_go/wpr_cert.pem
2017/09/01 16:01:12 Loading key from /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/web_page_replay_go/wpr_key.pem
2017/09/01 16:01:12 Loading script from /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/web_page_replay_go/deterministic.js
Error openining archive file: gunzip failed: gzip: invalid header

[  FAILED  ] http://techcrunch.com (34257 ms)

Traceback (most recent call last):
  RunBenchmark at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:332
    expectations=expectations, metadata=benchmark.GetMetadata())
  Run at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:203
    _RunStoryAndProcessErrorIfNeeded(story, results, state, test)
  _RunStoryAndProcessErrorIfNeeded at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/story_runner.py:98
    state.WillRunStory(story)
  traced_function at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_event_impl/decorators.py:52
    return func(*args, **kwargs)
  WillRunStory at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/page/shared_page_state.py:241
    archive_path, page.make_javascript_deterministic)
  traced_function at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/common/py_trace_event/py_trace_event/trace_event_impl/decorators.py:52
    return func(*args, **kwargs)
  StartReplay at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/core/network_controller.py:42
    make_javascript_deterministic)
  StartReplay at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/network_controller_backend.py:193
    local_ports = self._StartReplayServer()
  _StartReplayServer at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/platform/network_controller_backend.py:227
    return self._wpr_server.StartServer()
  StartServer at /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/telemetry/telemetry/internal/util/webpagereplay_go_server.py:283
    ''.join(self._LogLines()))
ReplayNotStartedError: Web Page Replay failed to start. Log output:
2017/09/01 16:01:12 Loading cert from /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/web_page_replay_go/wpr_cert.pem
2017/09/01 16:01:12 Loading key from /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/web_page_replay_go/wpr_key.pem
2017/09/01 16:01:12 Loading script from /usr/local/google/home/wkorman/workspace/chromium/src/third_party/catapult/web_page_replay_go/deterministic.js
Error openining archive file: gunzip failed: gzip: invalid header

Locals:
  is_posix : True
  log_fh   : <closed file '/tmp/tmpmJBO9H', mode 'w' at 0x7f393de520c0>

[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ]  http://techcrunch.com

1 FAILED TEST

Patch-set: 2
Reviewer: Walter Korman <1128438@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>