Update patch set 1
Patch Set 1: Commit-Queue+1

⌚

Example output:
[7450/9212] ACTION //device/sensors:java__lint(//build/toolchain/android:android_clang_arm)  
FAILED: gen/device/sensors/java__lint/result.xml gen/device/sensors/java__lint/config.xml                 
python ../../build/android/gyp/lint.py --lint-path ../../third_party/android_tools/sdk/tools-lint/bin/lint --cache-dir android_lint_cache --platform-xml-path ../../third_party/android_tools/sdk/platform-tools/api/api-versions.xml --android-sdk-version=26 --depfile gen/device/sensors/java__lint.d --config-path ../../build/android/lint/suppressions.xml -
-product-dir=. --processed-config-path gen/device/sensors/java__lint/config.xml --result-path gen/device/sensors/java__lint/result.xml --include-unexpected-failures --java-sources-file=gen/device/sensors/java.sources --jar-path gen/device/sensors/java.javac.jar --classpath=@FileArg\(gen/device/sensors/java.build_config:javac:interface_classpath\) --res
ource-sources=@FileArg\(gen/device/sensors/java.build_config:deps_info:owned_resources_dirs\) --resource-sources=@FileArg\(gen/device/sensors/java.build_config:deps_info:owned_r
esources_zips\) --srcjars=@FileArg\(gen/device/sensors/java.build_config:gradle:bundled_srcjars\) --can-fail-build                                                               
                                                                                                                                  
Traceback (most recent call last):                                                                                                                     
  File "../../build/android/gyp/lint.py", line 206, in _OnStaleMd5                                                       
    stderr_filter=stderr_filter, fail_func=fail_func)
  File "/usr/local/google/home/wnwen/clankium1/src/build/android/gyp/util/build_utils.py", line 186, in CheckOutput                                                              
    raise CalledProcessError(cwd, args, stdout + stderr)               
CalledProcessError: Command failed: ( cd /usr/local/google/home/wnwen/clankium1/src; third_party/android_tools/sdk/tools-lint/bin/lint -Werror --exitcode --showall --xml out/Deb
ug/gen/device/sensors/java__lint/result.xml --classpath out/Debug/gen/device/sensors/java.javac.jar --config out/Debug/gen/device/sensors/java__lint/config.xml --libraries out/D
ebug/lib.java/base/base_java.interface.jar:out/Debug/lib.java/third_party/android_tools/support/support-annotations-27.0.0.interface.jar:out/Debug/lib.java/build/android/buildho
oks/build_hooks_java.interface.jar:out/Debug/lib.java/build/android/buildhooks/build_hooks_android_java.interface.jar --sources /tmp/tmp05Qvgh/SRC_ROOT1 --sources /tmp/tmp05Qvgh
/SRC_ROOT2 /tmp/tmp05Qvgh/SRC_ROOT3 )             
                                                                                                                                                                                 
Scanning SRC_ROOT3: ....                                                                                                                                                         
Scanning SRC_ROOT3 (Phase 2):                                                   
Lint found No errors or warnings                                             
                                                                            
Unexpected failure during lint analysis of DeviceSensors.java (this is a bug in lint or one of the libraries it depends on)                                                      
AbortCompilation:ProblemHandler.handle(ProblemHandler.java:159)<-ProblemHandler.handle(ProblemHandler.java:226)<-ProblemReporter.handle(ProblemReporter.java:2393)<-ProblemReport
er.isClassPathCorrect(ProblemReporter.java:4761)                                                                                                                                 
                                                                                                                                                      
                                                                                             
Please refer to output above for unexpected lint failures.                                                
                                                                                                                                                                                
Traceback (most recent call last):                                                            
  File "../../build/android/gyp/lint.py", line 402, in <module>                      
    sys.exit(main())                                                               
  File "../../build/android/gyp/lint.py", line 398, in main                       
    depfile_deps=classpath)                                                                                                                                                      
  File "/usr/local/google/home/wnwen/clankium1/src/build/android/gyp/util/build_utils.py", line 602, in CallAndWriteDepfileIfStale
    pass_changes=True)                                                                                                                                 
  File "/usr/local/google/home/wnwen/clankium1/src/build/android/gyp/util/md5_check.py", line 87, in CallAndRecordIfStale         
    function(*args)                                 
  File "/usr/local/google/home/wnwen/clankium1/src/build/android/gyp/util/build_utils.py", line 585, in on_stale_md5                                                             
    function(*args)                                                                                                                       
  File "../../build/android/gyp/lint.py", line 393, in <lambda>        
    silent=args.silent),                                               
  File "../../build/android/gyp/lint.py", line 258, in _OnStaleMd5
    raise Exception('Lint failed.')
Exception: Lint failed.

Patch-set: 1
Reviewer: agrieve <1126674@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Eric Stevenson <1178079@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Peter Wen <1002869@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+1
Work-in-progress: false