Update patch set 25
Patch Set 25:

> Patch Set 25:
> 
> > Patch Set 25:
> > 
> > FYI: After this patch, I get this error:
> > # git cl presubmit
> > ```
> > Running presubmit commit checks ...
> > 
> > ** Presubmit ERRORS **
> > generate_buildbot_json_coveragetest (0.03s) failed
> > Traceback (most recent call last):
> >   File "generate_buildbot_json_coveragetest.py", line 6, in <module>
> >     import coverage
> >   File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
> >     return real_import(name, globals, locals, fromlist, level)
> > ImportError: No module named coverage
> > ```
> > 
> > `sudo pip install coverage` fixed the issue for me. I hope this is the right package thought.
> > 
> > The other members of my team didn't have any problems. So I guess it's okay.
> 
> Arthur, what change to src/testing/buildbot were you trying to make at the time? Do you think it would be too onerous to require that people install Python's coverage module in order to make changes in that directory?

You are right, I was modifying: src/testing/buildbot/mojo.fyi.network_content_browsertests.filter.
I understand now why I was the only one in my team not able to do 'git cl upload'.

I don't know how it works, but maybe we can automatically install it with `gclient runhooks`. Alternatively, we can test if the package is available before importing it and give the user instructions to solve their issue.

It took me easily 1 hours when I tried to fix it by doing git pull, gclient sync, gclient runhooks, ... After doing `pip install coverage` I was not sure if it was the right thing to do. If it is not too hard, I think it might worth doing something to not bother someone else.

Hopefully, it will affect only the changes to src/testing/buildbot/. So the inconvenience will be limited.

Patch-set: 25
CC: Arthur Sonzogni <1228344@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>