Revert of Revert of Roll src/third_party/skia 8bcc7a0:724ae28 (patchset #1 id:1 of https://codereview.chromium.org/1202733005/)
Reason for revert:
Reverting the revert. This was not the cause of the compile error.

Original issue's description:
> Revert of Roll src/third_party/skia 8bcc7a0:724ae28 (patchset #1 id:1 of https://codereview.chromium.org/1209603002/)
>
> Reason for revert:
> Appears to break ChromiumOS daisy comple:
>
> [1451/10422] CXX obj/third_party/skia/src/gpu/skia_library.GrProcOptInfo.o
> FAILED: /b/build/goma/gomacc armv7a-cros-linux-gnueabi-g++ -B/b/build/slave/ChromiumOS_daisy_Compile/build/.cros_cache/chrome-sdk/tarballs/daisy+7201.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/binutils-bin/2.24-gold -MMD -MF obj/third_party/angle/src/libANGLE/renderer/gl/glx/libANGLE.FunctionsGLX.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DCHROMIUM_BUILD -DCR_CLANG_REVISION=239765-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CRAS=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_REMOTING=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_CONFIGURATION_POLICY -DENABLE_NOTIFICATIONS -DENABLE_HIDPI=1 -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DDONT_EMBED_BUILD_METADATA -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_BACKGROUND=1 -DENABLE_GOOGLE_NOW=1 -DCLD_VERSION=2 -DENABLE_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DSAFE_BROWSING_SERVICE -DLIBANGLE_IMPLEMENTATION -DANGLE_ENABLE_OPENGL -DANGLE_USE_X11 -DANGLE_TRANSLATOR_STATIC -DUSE_LIBPCI=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DOS_CHROMEOS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../third_party/angle/src -I../../third_party/angle/include -I../../third_party/angle/src/third_party/khronos -Igen/angle -I../../third_party/angle/src -I../../third_party/angle/include -pthread -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -Wno-format -Wno-unused-result -march=armv7-a -mtune=generic-armv7-a -mfpu=neon -mfloat-abi=hard -mthumb --sysroot=/b/build/slave/ChromiumOS_daisy_Compile/build/.cros_cache/chrome-sdk/tarballs/daisy+7201.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -g -pipe -march=armv7-a -mtune=cortex-a15 -mfpu=neon -mfloat-abi=hard -D__google_stl_debug_vector=1 -gsplit-dwarf -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wno-deprecated -Wno-abi -std=gnu++11 -Wno-narrowing -Wno-literal-suffix  -c ../../third_party/angle/src/libANGLE/renderer/gl/glx/FunctionsGLX.cpp -o obj/third_party/angle/src/libANGLE/renderer/gl/glx/libANGLE.FunctionsGLX.o
> ../../third_party/angle/src/libANGLE/renderer/gl/glx/FunctionsGLX.cpp:15:20: fatal error: GL/glx.h: No such file or directory
>  #include <GL/glx.h>
>                     ^
> compilation terminated.
>
> https://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20daisy%20Compile/builds/1491
>
> Original issue's description:
> > Roll src/third_party/skia 8bcc7a0:724ae28
> >
> > Summary of changes available at:
> > https://chromium.googlesource.com/skia/+log/8bcc7a0..724ae28
> >
> > CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel
> > TBR=fmalita@google.com
> >
> > Committed: https://crrev.com/7760d3cb5f3b1a9516617afe6f7843766fa02fd5
> > Cr-Commit-Position: refs/heads/master@{#335941}
>
> TBR=fmalita@google.com,skia-deps-roller@chromium.org
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
>
> Committed: https://crrev.com/0e62c727fcb52f79cc07d176956f4444ae62cc8b
> Cr-Commit-Position: refs/heads/master@{#335950}

TBR=fmalita@google.com,skia-deps-roller@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1206743006