Revert of NaCl: Update revision in DEPS, 2363d1a -> a3e1e94 (patchset #1 id:1 of https://codereview.chromium.org/905793003/)
Reason for revert:
Looks like it broke the build:

http://build.chromium.org/p/chromium.webkit/builders/Linux%20Tests/builds/42375/steps/compile/logs/stdio

FAILED: cd ../../remoting; python ../native_client/build/build_nexe.py --root .. --product-dir ../out/Release/xyz --config-name Release -t ../out/Release/gen/sdk/ --arch pnacl --build newlib_pexe --name ../out/Release/remoting_key_tester_newlib.pexe --objdir ../out/Release/obj/remoting/remoting_key_tester_pexe.gen/pnacl_newlib/remoting_key_tester_pexe "--include-dirs=../out/Release/gen/tc_pnacl_newlib/include .. .. \"../out/Release/gen\"" "--compile_flags=-O2 -g -Wall -fdiagnostics-show-option -Werror  -gline-tables-only -Wno-unused-function -Wno-char-subscripts -Wno-c++11-extensions -Wno-unnamed-type-template-args -Wno-extra-semi -Wno-unused-private-field -Wno-char-subscripts -Wno-unused-function " --gomadir /mnt/data/b/build/goma "--defines=\"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_DEFAULT_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=x86\" \"BINARY_CORE=1\" \"BINARY_DESKTOP=2\" \"BINARY_HOST_ME2ME=3\" \"BINARY_NATIVE_MESSAGING_HOST=4\" \"BINARY_REMOTE_ASSISTANCE_HOST=5\" V8_DEPRECATION_WARNINGS \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD \"CR_CLANG_REVISION=223108\" \"TOOLKIT_VIEWS=1\" UI_COMPOSITOR_IMAGE_TRANSPORT \"USE_AURA=1\" \"USE_ASH=1\" \"USE_PANGO=1\" \"USE_CAIRO=1\" \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_X11=1\" \"USE_CLIPBOARD_AURAX11=1\" ENABLE_ONE_CLICK_SIGNIN ENABLE_PRE_SYNC_BACKUP \"ENABLE_REMOTING=1\" \"ENABLE_WEBRTC=1\" ENABLE_PEPPER_CDMS ENABLE_CONFIGURATION_POLICY ENABLE_NOTIFICATIONS USE_UDEV DONT_EMBED_BUILD_METADATA \"ENABLE_TASK_MANAGER=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_AUTOFILL_DIALOG=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_GOOGLE_NOW=1\" \"CLD_VERSION=2\" \"ENABLE_PRINTING=1\" \"ENABLE_BASIC_PRINTING=1\" \"ENABLE_PRINT_PREVIEW=1\" \"ENABLE_SPELLCHECK=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\" \"ENABLE_APP_LIST=1\" \"ENABLE_SETTINGS_APP=1\" \"ENABLE_SUPERVISED_USERS=1\" \"ENABLE_MDNS=1\" \"ENABLE_SERVICE_DISCOVERY=1\" V8_USE_EXTERNAL_STARTUP_DATA \"USE_LIBPCI=1\" \"USE_GLIB=1\" \"USE_NSS=1\" __STDC_CONSTANT_MACROS __STDC_FORMAT_MACROS" "--link_flags=-B../out/Release/gen/tc_pnacl_newlib/lib -O3 -lppapi_stub -lppapi_cpp" "--source-list=../out/gypfiles/remoting/pnacl_newlib.remoting_key_tester_pexe.source_list.gypcmd"
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/bin/le32-nacl-ld.gold:error: cannot open ../out/Release/gen/tc_pnacl_newlib/lib/libnacl.a: No such file or directory
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to '_realloc_r'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to 'read'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to 'close'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to 'lseek'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to '_calloc_r'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to 'isatty'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to 'fstat'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to '_free_r'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc.a:error: undefined reference to '_malloc_r'
../out/Release/gen/tc_pnacl_newlib/lib/libpthread.a:error: undefined reference to '__pthread_initialize_minimal'
../out/Release/gen/tc_pnacl_newlib/lib/libpthread.a:error: undefined reference to '__nacl_tls_initialize_memory'
../out/Release/gen/tc_pnacl_newlib/lib/libpthread.a:error: undefined reference to 'calloc'
../out/Release/gen/tc_pnacl_newlib/lib/libpthread.a:error: undefined reference to '__nacl_tls_combined_size'
../out/Release/gen/tc_pnacl_newlib/lib/libpthread.a:error: undefined reference to '__libnacl_mandatory_irt_query'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc++.a:error: undefined reference to 'malloc'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/le32-nacl/lib/libc++.a:error: undefined reference to 'free'
../out/Release/gen/tc_pnacl_newlib/lib/libppapi_stub.a:error: undefined reference to '_exit'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/lib/clang/3.5.0/lib/le32-nacl/unwind_stubs.bc:error: undefined reference to 'write'
/mnt/data/b/build/slave/Linux_Tests/build/src/out/Release/gen/sdk/linux_x86/pnacl_newlib/lib/clang/3.5.0/lib/le32-nacl/unwind_stubs.bc:error: undefined reference to 'abort'
FAILED with 1: ../out/Release/gen/sdk/linux_x86/pnacl_newlib/bin/pnacl-clang++ -o ../out/Release/remoting_key_tester_newlib.pexe.debug -Wl,--as-needed ../out/Release/obj/remoting/remoting_key_tester_pexe.gen/pnacl_newlib/remoting_key_tester_pexe/remoting_key_tester_61dcf3bc.o -B../out/Release/gen/tc_pnacl_newlib/lib -O3 -lppapi_stub -lppapi_cpp

Original issue's description:
> NaCl: Update revision in DEPS, 2363d1a -> a3e1e94
>
> This pulls in the following Native Client changes:
>
> 6c11549: (mseaborn@chromium.org) Add IRT interface for PNaCl's sandboxed linker to use to talk to Chromium
> 9fff96b: (teravest@chromium.org) NaCl: Remove use of NACL_BUILD_* in common.gypi.
> 76d6d4b: (mseaborn@chromium.org) PNaCl: Update Binutils revision in pnacl/COMPONENT_REVISIONS: use new IRT interface
> a3e1e94: (jfb@chromium.org) Delete Windows time code
>
> BUG=none
> TEST=browser_tests and nacl_integration
> CQ_EXTRA_TRYBOTS=tryserver.chromium.linux:linux_rel_precise32,linux_arm_compile,linux_nacl_sdk_build
>
> Committed: https://crrev.com/accbfa1e86e32df669fad209185cba4acd6847be
> Cr-Commit-Position: refs/heads/master@{#315133}

TBR=jfb@chromium.org,mseaborn@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=none

Review URL: https://codereview.chromium.org/905043002