Revert of Roll WebRTC 14876:14880 (4 commits) (patchset #1 id:1 of https://codereview.chromium.org/2473653002/ )
Reason for revert:
Breaks https://build.chromium.org/p/chromium.linux/builders/Blimp%20Linux%20%28dbg%29/builds/14848/steps/compile/logs/stdio
[881/894] SOLINK ./libcontent.so
FAILED: libcontent.so libcontent.so.TOC
../../third_party/webrtc/modules/desktop_capture/desktop_capturer.cc:45: error: undefined reference to 'webrtc::DesktopCapturer::CreateRawWindowCapturer(webrtc::DesktopCaptureOptions const&)'
../../third_party/webrtc/modules/desktop_capture/desktop_capturer.cc:56: error: undefined reference to 'webrtc::DesktopCapturer::CreateRawScreenCapturer(webrtc::DesktopCaptureOptions const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Original issue's description:
> Roll WebRTC 14876:14880 (4 commits)
>
> Changes: https://chromium.googlesource.com/external/webrtc/trunk/webrtc.git/+log/21c188f..17cd377
>
> $ git log 21c188f..17cd377 --date=short --no-merges --format=%ad %ae %s
> 2016-11-01 zijiehe@chromium.org Add CreateWindowCapturer() and CreateScreenCapturer() in DesktopCapturer
> 2016-11-01 deadbeef@webrtc.org Adding data channel ID to Java binding of DataChannel.
> 2016-11-01 kwiberg@webrtc.org Let RTC_[D]CHECK_op accept arguments of different signedness
> 2016-11-01 perkj@webrtc.org Let ViEEncoder express resolution requests as Sinkwants. This removes the VideoSendStream::LoadObserver interface and the implementation in WebrtcVideoSendStream and replace it with VideoSinkWants through the VideoSourceInterface.
>
> TBR=
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_chromium_archive_rel_ng;master.tryserver.chromium.mac:mac_chromium_archive_rel_ng
> BUG=
>
> Committed: https://crrev.com/3255d9679451e5ccbf460f87928551da19787d7f
> Cr-Commit-Position: refs/heads/master@{#429239}

TBR=perkj@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2464243003