Fix mac_views_browser compile after r513338
Failing since http://go/macviewsbuilder/builds/27922 with

avatar_button.cc:46:15: error: unused variable 'kGenericAvatarIconSize'

To fix, expose the code in AvatarButton::SetupThemeColorButton() used
for Windows to Mac also. profile_chooser_controller.mm uses
kAccountCircleIcon also and AvatarButton::IsCondensible() has TODO
"all platforms should return true". So we will want this eventually.

Bug: 565989, 425229
Change-Id: Ib5ed53e5dd0cfb247e0a29271dcde6ade5f43089