Update patch set 23
Patch Set 23:

> Patch Set 23:
> 
> > Patch Set 23:
> > 
> > > Patch Set 23:
> > > 
> > > > Patch Set 23:
> > > > 
> > > > > Patch Set 23:
> > > > > 
> > > > > Also have we able to verify that this benchmark will have non zero return code if there are leaks?
> > > > 
> > > > Currently the return code is Success even when there are leaks.
> > > > I could not find a way to modify the result values with metrics, so I was thinking of adding a script like run_leak_detector_as_googletest (just like run_telemetry_benchmark_as_googoletest) and changing the results there.
> > > > Could you tell me what you think?
> > > 
> > > I think you should discuss with Ben & Ethan about extending the metrics system to support failure value. One idea I have is that in your memory leak metric, you can add s.t like:
> > > 
> > > if leaked_objects > 0:
> > >   add failure value
> > 
> > Why does the benchmark need to return nonzero if there are leaks? Also, is there a link to the Catapult-side CL that implements the metric?
> 
> leakDetectionMetric was added in https://chromiumcodereview.appspot.com/3012153002
> 
> Metrics can make run_benchmark return nonzero exit code by throwing an error. I added `throw new Error('occam');` to memoryMetric:
> 
> ~/dev/o/src ./tools/perf/run_benchmark system_health.memory_desktop --story-filter=blank --pageset-repeat=1 --browser=stable
> [ RUN      ] load:chrome:blank@{'case': 'load', 'group': 'chrome'}
> (WARNING) 2017-11-06 10:45:07,034 timeline_based_measurement._ComputeTimelineBasedMetrics:327  Processing resulting traces took 1.963 seconds
> Traceback (most recent call last):
>   File "/usr/local/google/home/benjhayden/dev/o/src/third_party/catapult/telemetry/telemetry/value/failure.py", line 41, in _GetExcInfoFromMessage
>     raise Exception(message)
> Exception: MapFunctionError: occam
>     at new memoryMetric 
> ... redacted TBMv2 back trace...
> [  FAILED  ] load:chrome:blank@{'case': 'load', 'group': 'chrome'} (16980 ms)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ]  load:chrome:blank@{'case': 'load', 'group': 'chrome'}
> 1 FAILED TEST
> View result at file:///usr/local/google/home/benjhayden/dev/o/src/tools/perf/results.html
> ~/dev/o/src echo $?
> 1
> 
> 
> The results.html file contains only the benchmark_duration value produced by telemetry, nothing from the memoryMetric. If you want to use results.html to drill down into leaks, then I would submit for consideration making telemetry synthesize FailureValues from non-numeric samples, so that your metric can say `histogram.addSample('error message', {...diagnostics});` instead of throwing an error. That would allow telemetry to produce a useful results.html (with tables for errors and their diagnostics), and also return non-zero exit code.
> 
> But I would also like to know why the benchmark needs to return nonzero.

This benchmark will also be used as a test on CQ. Any CL that causes a leak would turn this one red & blocks CQ

Patch-set: 23
Reviewer: Ned Nguyen <1128435@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>