Update patch set 25
Patch Set 25:

> Patch Set 25:
> 
> FYI: After this patch, I get this error:
> # git cl presubmit
> ```
> Running presubmit commit checks ...
> 
> ** Presubmit ERRORS **
> generate_buildbot_json_coveragetest (0.03s) failed
> Traceback (most recent call last):
>   File "generate_buildbot_json_coveragetest.py", line 6, in <module>
>     import coverage
>   File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 152, in SetupPathsAndImport
>     return real_import(name, globals, locals, fromlist, level)
> ImportError: No module named coverage
> ```
> 
> `sudo pip install coverage` fixed the issue for me. I hope this is the right package thought.
> 
> The other members of my team didn't have any problems. So I guess it's okay.

Arthur, what change to src/testing/buildbot were you trying to make at the time? Do you think it would be too onerous to require that people install Python's coverage module in order to make changes in that directory?

Patch-set: 25