Create patch set 4
Uploaded patch set 4.

error c2071 on win no need to export class member

Patch-set: 4
Patch-set-description: error c2071 on win no need to export class member
Subject: Fix a bug in TracingHandler
Commit: d8bdb6e724c6e4148d68209612794dd8d9fb834b
Tag: autogenerated:gerrit:newPatchSet
Groups: d8bdb6e724c6e4148d68209612794dd8d9fb834b