Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > I failed to notice at the time that this change is dependent on VS 2017. I believe it is the first such change. This is okay but I wanted to put a note in explicitly mentioning that in case people hit this build break.
> > 
> > And, I should land a CL to make the VS 2017 dependency official now, by explicitly failing to build with VS 2015 with an informative error message.
> 
> I got a build break with this change using the tool chain on Windows. Here's an error:
> ninja -t msvc -e environment.x64 -- "c:\src\chromium\src\third_party\depot_tools\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64/cl.exe" /nologo /showIncludes  @obj/cc/paint/paint/paint_op_buffer.obj.rsp /c ../../cc/paint/paint_op_buffer.cc /Foobj/cc/paint/paint/paint_op_buffer.obj /Fd"obj/cc/paint/paint_cc.pdb"
> C:\src\chromium\src\base/time/time.h(727): error C3249: illegal statement or sub-expression for 'constexpr' function
> ninja: build stopped: subcommand failed.

That error means that you are using VS 2015. I can see that you are using VS 2015 because:
a) VS 2017 handles this code fine
b) I recognize f53e4598951162bad6330f7a167486c7ae5db1e5 as the VS 2015 hash

You probably have GYP_MSVS_VERSION set. Clear that or set it to 2017, then run gclient runhooks and gn gen. VS 2015 is no longer supported.

Patch-set: 4