Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> I got a presubmit error locally, I didn't understand if it's related to my CL:
> 
> 
> ** Presubmit ERRORS **
> Validating WPR archives failed:
> 
> ***************
> 
> Traceback (most recent call last):
>   <module> at /usr/local/google/code/chromium/src/tools/perf/validate_wpr_archives:102
>     sys.exit(main(sys.argv[1:]))
>   main at /usr/local/google/code/chromium/src/tools/perf/validate_wpr_archives:85
>     for s in GetAllStorySets():
>   GetAllStorySets at /usr/local/google/code/chromium/src/tools/perf/validate_wpr_archives:39
>     story_sets.append(benchmark().CreateStorySet(options))
>   CreateStorySet at /usr/local/google/code/chromium/src/tools/perf/benchmarks/system_health.py:113
>     take_memory_measurement=True)
>   __init__ at /usr/local/google/code/chromium/src/tools/perf/page_sets/system_health/system_health_stories.py:34
>     self.AddStory(story_class(self, take_memory_measurement))
>   __init__ at /usr/local/google/code/chromium/src/tools/perf/page_sets/system_health/system_health_story.py:71
>     extra_browser_args=extra_browser_args)
> TypeError: __init__() got an unexpected keyword argument 'extra_browser_args'

I bet this is because you haven't run gclient sync :-)

Patch-set: 1
Reviewer: Ned Nguyen <1128435@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>