Revert of Add webusb permission bubble mojom (patchset #3 id:40001 of https://codereview.chromium.org/1404213004/ )
Reason for revert:
Causes compile failure on Windows builder:
http://build.chromium.org/p/chromium/builders/Win/builds/36553

c:\b\build\slave\win\build\src\out\release\gen\components\webusb\public\interfaces\webusb_permission_bubble.mojom-internal.h(13) : fatalerror C1083: Cannot open include file: 'device/devices_app/usb/public/interfaces/device.mojom-internal.h': No such file or directory

Original issue's description:
> Add webusb permission bubble mojom
>
> This patch added webusb permission bubble mojom.
> It has function GetPermission to get a device after
> user has granted permission to it. And this function
> is used by class WebUSBClientImpl.
>
> BUG=492204
>
> Committed: https://crrev.com/9e3fbccf392bc87e66424051e94978d7802bba0e
> Cr-Commit-Position: refs/heads/master@{#354442}

TBR=reillyg@chromium.org,nick@chromium.org,tsepez@chromium.org,juncai@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=492204

Review URL: https://codereview.chromium.org/1409023002