Update patch set 3
Patch Set 3:

Not sure why the last bot is failing. I keep seeing some suspicious stdio:

ERROR:root:Error generating serial map
Traceback (most recent call last):
  File "/b/swarm_slave/w/ir/third_party/catapult/common/battor/battor/battor_wrapper.py", line 53, in IsBattOrConnected
    android_device_map = battor_device_mapping.GenerateSerialMap()
  File "/b/swarm_slave/w/ir/third_party/catapult/devil/devil/utils/battor_device_mapping.py", line 218, in GenerateSerialMap
    'Phone detected with no corresponding BattOr')
BattOrError: Phone detected with no corresponding BattOr

Looks like this might be a bug with our bot setup, I can't imagine it's actually caused by this change.

Patch-set: 3
Reviewer: Nate Fischer <1167294@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>