Revert "[M52] service worker: Don't BadMessageReceived when a response for a timed out request arrives"
This reverts commit 7ef056c2aa636fda9e93f2a6825ce8c7e7dcd845.

Broke build:
c:\b\build\slave\win_stable\build\src\content\browser\service_worker\embedded_worker_registry.cc(71):
error C2653: 'EmbeddedWorkerStatus': is not a class or namespace name
c:\b\build\slave\win_stable\build\src\content\browser\service_worker\embedded_worker_registry.cc(71):
error C2065: 'STOPPING': undeclared identifier

R=tyoshino@chromium.org
BUG=625040

Review URL: https://codereview.chromium.org/2168033002 .