Revert of Revert of Partially revert removal of synchronous AudioHardwareConfig requests. (patchset #1 id:1 of https://codereview.chromium.org/1047093002/)
Reason for revert:
Tree cycled to green before this revert patch was in.

http://build.chromium.org/p/chromium.webkit/builders/Mac%20Builder%20%28dbg%29/builds/78610

Let me revert the revert.

Original issue's description:
> Revert of Partially revert removal of synchronous AudioHardwareConfig requests. (patchset #1 id:1 of https://codereview.chromium.org/1042953002/)
>
> Reason for revert:
> Blink Gardening.
> Tree closer. This CL looks culprit.
>
> blink: Tree is closed (Automatic: "compile" on http://build.chromium.org/p/chromium.webkit/builders/Mac%20Builder%20%28dbg%29/builds/78608 "Mac Builder (dbg)"
>
> blink 192783 : 192783
> chromium 322927 : 322932
>
> http://build.chromium.org/p/chromium.webkit/builders/Mac%20Builder%20%28dbg%29/builds/78608/steps/compile/logs/stdio
>
> [3175/3219] CXX obj/content/shell/renderer/content_shell_lib.shell_render_view_observer.o
> [3176/3219] SOLINK libcontent.dylib, POSTBUILDS
> FAILED: if [ ! -e libcontent.dylib -o ! -e libcontent.dylib.TOC ] || otool -l libcontent.dylib | grep -q LC_REEXPORT_DYLIB ; then /Volumes/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -framework Cocoa -framework Foundation -framework IOKit -framework Security -framework SystemConfiguration -Wl,-search_paths_first -mmacosx-version-min=10.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -L. -install_name @rpath/libcontent.dylib -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o libcontent.dylib @libcontent.dylib.rsp && { otool -l libcontent.dylib | grep LC_ID_DYLIB -A 5; nm -gP libcontent.dylib | cut -f1-2 -d' ' | grep -v U$; true; } > libcontent.dylib.TOC; else /Volumes/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -framework Cocoa -framework Foundation -framework IOKit -framework Security -framework SystemConfiguration -Wl,-search_paths_first -mmacosx-version-min=10.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -L. -install_name @rpath/libcontent.dylib -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o libcontent.dylib @libcontent.dylib.rsp && { otool -l libcontent.dylib | grep LC_ID_DYLIB -A 5; nm -gP libcontent.dylib | cut -f1-2 -d' ' | grep -v U$; true; } > libcontent.dylib.tmp && if ! cmp -s libcontent.dylib.tmp libcontent.dylib.TOC; then mv libcontent.dylib.tmp libcontent.dylib.TOC ; fi; fi
> Undefined symbols for architecture x86_64:
>   "ViewMsg_SetAudioHardwareConfig::Read(IPC::Message const*, Tuple<media::AudioParameters, media::AudioParameters>*)", referenced from:
>       bool ViewMsg_SetAudioHardwareConfig::Dispatch<content::RenderThreadImpl, content::RenderThreadImpl, void, void (content::RenderThreadImpl::*)(media::AudioParameters const&, media::AudioParameters const&)>(IPC::Message const*, content::RenderThreadImpl*, content::RenderThreadImpl*, void*, void (content::RenderThreadImpl::*)(media::AudioParameters const&, media::AudioParameters const&)) in content.render_thread_impl.o
>   "media::AudioHardwareConfig::AudioHardwareConfig()", referenced from:
>       content::RenderThreadImpl::RenderThreadImpl(content::InProcessChildThreadParams const&) in content.render_thread_impl.o
>       content::RenderThreadImpl::RenderThreadImpl(content::InProcessChildThreadParams const&) in content.render_thread_impl.o
>       content::RenderThreadImpl::RenderThreadImpl(scoped_ptr<base::MessageLoop, base::DefaultDeleter<base::MessageLoop> >) in content.render_thread_impl.o
>       content::RenderThreadImpl::RenderThreadImpl(scoped_ptr<base::MessageLoop, base::DefaultDeleter<base::MessageLoop> >) in content.render_thread_impl.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ninja: build stopped: subcommand failed.
>
> Original issue's description:
> > Partially revert removal of synchronous AudioHardwareConfig requests.
> >
> > This regressed cold page load time on OSX by 5% :(, so revert all
> > changes related to the synchronous IPC removal, but keep cleanup
> > ones related to dead AudioMessageFilter device change handling.
> >
> > Revert "Use the worker task runner instead of the main audio thread."
> > commit http://crrev.com/06def69114b5ecae4f0ee0aa875181568fe7902c
> >
> > Revert "Remove synchronous AudioHardwareConfig request."
> > commit http://crrev.com/19faf60586e58f244371697b49eb61959d9c7be9
> >
> > BUG=469737
> > TEST=audio works.
> >
> > Committed: https://crrev.com/5a5e42e169522531244c67b7892c4e827179e6ac
> > Cr-Commit-Position: refs/heads/master@{#322928}
>
> TBR=nasko@chromium.org,creis@chromium.org,dalecurtis@chromium.org
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=469737
>
> Committed: https://crrev.com/dd41f62badda4ed64987669ac9b11c7ad3101734
> Cr-Commit-Position: refs/heads/master@{#322945}

TBR=nasko@chromium.org,creis@chromium.org,dalecurtis@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=469737

Review URL: https://codereview.chromium.org/1040263002