Revert "[Sync] Record sync memory usage in histogram broken by datatypes"
Fix ChromiumOS x86-generic Compile builder:
obj/components/sync/libsync.a(directory.o)(.debug_addr+0x25c0): error:
undefined reference to 'unsigned int
sync_pb::EstimateMemoryUsage<sync_pb::DataTypeProgressMarker>(sync_pb::DataTypeProgressMarker
const&)'

TBR=pavely@chromium.org,isherman@chromium.org,pnoland@chromium.org

Bug: 706214
Change-Id: I6694cc322b3f0ff302c4b47386c0e3084ac1508f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true