Revert "VideoFrame: Segregate Pixel Format and Storage Type."
This reverts commit 80f289fe303323361d07c5b58b23f8499903a154.

Appears to have broken chromium OS compile:

../../content/common/gpu/media/v4l2_device.cc: In static member function 'static media::VideoFrame::Format content::V4L2Device::V4L2PixFmtToVideoFrameFormat(uint32)':
../../content/common/gpu/media/v4l2_device.cc:46:14: error: 'NV12' is not a member of 'media::VideoFrame'
       return media::VideoFrame::NV12;
              ^
../../content/common/gpu/media/v4l2_device.cc: In static member function 'static uint32 content::V4L2Device::VideoFrameFormatToV4L2PixFmt(media::VideoFrame::Format)':
../../content/common/gpu/media/v4l2_device.cc:65:10: error: 'NV12' is not a member of 'media::VideoFrame'
     case media::VideoFrame::NV12:
          ^
[..snip..]

In file included from ../../base/memory/weak_ptr.h:69:0,
                 from ../../base/bind_helpers.h:148,
                 from ../../base/bind_internal.h:8,
                 from ../../base/bind.h:8,
                 from ../../content/common/gpu/media/v4l2_image_processor.cc:12:
../../content/common/gpu/media/v4l2_image_processor.cc: In member function 'bool content::V4L2ImageProcessor::Initialize(media::VideoFrame::Format, media::VideoFrame::Format, gfx::Size, gfx::Size, gfx::Size, const Closure&)':
../../content/common/gpu/media/v4l2_image_processor.cc:112:28: error: 'NV12' is not a member of 'media::VideoFrame'
   DCHECK_EQ(output_format, media::VideoFrame::NV12);
                            ^
../../base/logging.h:671:22: note: in definition of macro 'DCHECK_OP'
             (val1), (val2), #val1 " " #op " " #val2))                     \
                      ^
../../content/common/gpu/media/v4l2_image_processor.cc:112:3: note: in expansion of macro 'DCHECK_EQ'
   DCHECK_EQ(output_format, media::VideoFrame::NV12);
   ^
ninja: build stopped: subcommand failed.

BUG=489744
CQ_INCLUDE_TRYBOTS=tryserver.blink:linux_blink_rel
TBR=mcasas@chromium.org

Review URL: https://codereview.chromium.org/1161803003