Specify the base namespace of ::mojom in user_media_client_impl_unittest.cc.
When I introduced a forward declaration in content::mojom namespace in
content/common/service_worker/service_worker_types.h, I saw the following errors:
https://crrev.com/2410333006/#ps300001

--------------
./../content/renderer/media/user_media_client_impl_unittest.cc:79:3:
  error: no type named 'MediaDevicesDispatcherHostPtr' in namespace 'content::mojom';
  did you mean '::mojom::MediaDevicesDispatcherHostPtr'?
  mojom::MediaDevicesDispatcherHostPtr CreateInterfacePtrAndBind() {
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ::mojom::MediaDevicesDispatcherHostPtr
gen/content/common/media/media_devices.mojom.h:134:7:
   note: '::mojom::MediaDevicesDispatcherHostPtr' declared here
using MediaDevicesDispatcherHostPtr = mojo::InterfacePtr<MediaDevicesDispatcherHost>;
      ^
../../content/renderer/media/user_media_client_impl_unittest.cc:84:17:
  error: no template named 'MediaDevicesDispatcherHost' in namespace 'content::mojom';
  did you mean '::mojom::MediaDevicesDispatcherHostStub'?
  mojo::Binding<mojom::MediaDevicesDispatcherHost> binding_;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                ::mojom::MediaDevicesDispatcherHostStub
gen/content/common/media/media_devices.mojom.h:205:7:
  note: '::mojom::MediaDevicesDispatcherHostStub' declared here
class MediaDevicesDispatcherHostStub
      ^
--------------

TBR=mcasas@chromium.org

BUG=

Review-Url: https://chromiumcodereview.appspot.com/2427363004