Revert "Merge MultiActivityTestRule implementation to itself"
This reverts commit 0f7f955367c6f37424facf1b0b68a9c8b7b6b723.

Reason for revert: Breaks build https://uberchromegw.corp.google.com/i/internal.client.clank_tot/builders/clang-clankium-tot-builder/builds/55559

Error:
python ../../build/android/gyp/javac.py --depfile=gen/clank/javatests/clank_test_java__compile_java.d --jar-path=gen/clank/javatests/clank_test_java.javac.jar --java-srcjars=\[\] --java-srcjars=@FileArg\(gen/clank/javatests/clank_test_java.build_config:javac:srcjars\) --java-version=1.8 --classpath=@FileArg\(gen/clank/javatests/clank_test_java.build_config:deps_info:javac_full_classpath\) --interface-classpath=@FileArg\(gen/clank/javatests/clank_test_java.build_config:deps_info:javac_full_interface_classpath\) --processorpath=@FileArg\(gen/clank/javatests/clank_test_java.build_config:javac:processor_classpath\) --processors=@FileArg\(gen/clank/javatests/clank_test_java.build_config:javac:processor_classes\) --bootclasspath=lib.java/android.interface.jar --chromium-code=1 --use-errorprone-path bin/errorprone --processorpath=\[\"lib.java/tools/android/errorprone_plugin/errorprone_plugin_java.jar\"\] @gen/clank/javatests/clank_test_java.sources
Traceback (most recent call last):
  File "../../build/android/gyp/javac.py", line 571, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/android/gyp/javac.py", line 567, in main
    pass_changes=True)
  File "/b/build/slave/clang-clankium-tot-builder/build/src/build/android/gyp/util/build_utils.py", line 606, in CallAndWriteDepfileIfStale
    pass_changes=True)
  File "/b/build/slave/clang-clankium-tot-builder/build/src/build/android/gyp/util/md5_check.py", line 87, in CallAndRecordIfStale
    function(*args)
  File "/b/build/slave/clang-clankium-tot-builder/build/src/build/android/gyp/util/build_utils.py", line 589, in on_stale_md5
    function(*args)
  File "../../build/android/gyp/javac.py", line 560, in <lambda>
    classpath_inputs, classpath),
  File "../../build/android/gyp/javac.py", line 337, in _OnStaleMd5
    attempt_build()
  File "../../build/android/gyp/javac.py", line 335, in <lambda>
    stderr_filter=ColorJavacOutput)
  File "/b/build/slave/clang-clankium-tot-builder/build/src/build/android/gyp/util/build_utils.py", line 190, in CheckOutput
    raise CalledProcessError(cwd, args, stdout + stderr)
util.build_utils.CalledProcessError: Command failed: ( cd /b/build/slave/clang-clankium-tot-builder/build/src/out/Debug; bin/errorprone -g -encoding UTF-8 -sourcepath : -Xep:FloatingPointLiteralPrecision:OFF -Xep:SynchronizeOnNonFinalField:OFF -Xep:JavaLangClash:OFF -Xep:ArgumentSelectionDefectChecker:OFF -Xep:NarrowingCompoundAssignment:OFF -Xep:TypeParameterUnusedInFormals:OFF -Xep:ReferenceEquality:OFF -Xep:UseCorrectAssertInTests:OFF -Xep:CatchFail:OFF -Xep:JUnitAmbiguousTestClass:OFF -Xep:AssertionFailureIgnored:OFF -Xep:MissingOverride:OFF -Xep:MissingFail:OFF -Xep:StaticGuardedByInstance:OFF -Xep:DefaultCharset:OFF -Xep:JdkObsolete:OFF -Xep:FunctionalInterfaceClash:OFF -Xep:FutureReturnValueIgnored:OFF -Xep:OperatorPrecedence:OFF -Xep:ThreadJoinLoop:OFF -Xep:NamedParameters:OFF -Xep:StringSplitter:OFF -Xep:ClassNewInstance:OFF -Xep:ClassCanBeStatic:OFF -Xep:FloatCast:OFF -Xep:ThreadLocalUsage:OFF -Xep:Finally:OFF -Xep:FragmentNotInstantiable:OFF -Xep:HidingField:OFF -Xep:IntLongMath:OFF -Xep:BadComparable:OFF -Xep:EqualsHashCode:OFF -Xep:TypeParameterShadowing:OFF -Xep:ImmutableEnumChecker:OFF -Xep:InputStreamSlowMultibyteRead:OFF -Xep:BoxedPrimitiveConstructor:OFF -Xep:OverrideThrowableToString:OFF -Xep:CollectionToArraySafeParameter:OFF -source 1.8 -target 1.8 -Xlint:unchecked -Xlint:deprecation -bootclasspath lib.java/android.interface.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar -processorpath lib.java/tools/android/errorprone_plugin/errorprone_plugin_java.jar -d /tmp/tmp66g6kA/classes -classpath @/tmp/tmp66g6kA/classpath.txt @/tmp/tmp66g6kA/files_list.txt )
../../clank/javatests/src/com/google/android/apps/chrome/externalauth/ExternalAuthTest.java:14: warning: [deprecation] MockPackageManager in android.test.mock has been deprecated
import android.test.mock.MockPackageManager;
                        ^
../../clank/javatests/src/org/chromium/chrome/browser/instantapps/InstantAppsHandlerInternalTest.java:18: warning: [deprecation] InstantAppsApi in com.google.android.gms.instantapps has been deprecated
import com.google.android.gms.instantapps.InstantAppsApi.LaunchDataResult;
                                         ^
../../clank/javatests/src/org/chromium/chrome/browser/instantapps/InstantAppsHandlerInternalTest.java:18: warning: [deprecation] InstantAppsApi in com.google.android.gms.instantapps has been deprecated
import com.google.android.gms.instantapps.InstantAppsApi.LaunchDataResult;
                                         ^
../../clank/javatests/src/com/google/android/apps/chrome/externalauth/ExternalAuthTest.java:42: warning: [deprecation] MockPackageManager in android.test.mock has been deprecated
    private class AuthTestPackageManager extends MockPackageManager {
                                                 ^
../../clank/javatests/src/com/google/android/apps/chrome/help/FeedbackCategoryChooserActivityTest.java:146: warning: [deprecation] locale in Configuration has been deprecated
        config.locale = locale;
              ^
../../clank/javatests/src/com/google/android/apps/chrome/help/FeedbackCategoryChooserActivityTest.java:147: warning: [deprecation] updateConfiguration(Configuration,DisplayMetrics) in Resources has been deprecated
        resources.updateConfiguration(config, resources.getDisplayMetrics());
                 ^
../../clank/javatests/src/com/google/android/apps/chrome/locale/LocaleManagerInternalTest.java:323: error: cannot find symbol
        final Instrumentation instrumentation = mTestRule.getInstrumentation();
                                                         ^
  symbol:   method getInstrumentation()
  location: variable mTestRule of type MultiActivityTestRule
1 error
6 warnings

Original change's description:
> Merge MultiActivityTestRule implementation to itself
> 
> Merge MultiActivityTestCommon into MultiActivityTestRule since there is
> no long need for sharing the implementation with other classes
> 
> Bug: 711517
> Change-Id: I30612a8815763a56fc9764008913e6c36c846df7
> Reviewed-on: https://chromium-review.googlesource.com/881833
> Reviewed-by: Jinsuk Kim <jinsukkim@chromium.org>
> Reviewed-by: John Budorick <jbudorick@chromium.org>
> Commit-Queue: Yoland Yan <yolandyan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#531981}

TBR=yolandyan@chromium.org,jinsukkim@chromium.org,jbudorick@chromium.org

Change-Id: I7d88e9cb187b1cf8535322b6a37d6d3016b7acb2
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 711517