Update patch set 5
Patch Set 5:

chromeos_amd64-generic_chromium_compile_only_ng fails to compile due to old minigbm. Would you happen to know how can I roll up?

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.linux%2Fchromeos_amd64-generic_chromium_compile_only_ng%2F376209%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout
FAILED: obj/ui/ozone/platform/drm/gbm/drm_thread.o 
/b/c/goma_client/gomacc x86_64-cros-linux-gnu-clang++ -B/b/c/b/chromeos_amd64_generic_chromium_compile_only_ng/.cros_cache/chrome-sdk/tarballs/amd64-generic+9649.0.0+target_toolchain/usr/x86_64-pc-linux-gnu/x86_64-cros-linux-gnu/binutils-bin/2.25.51-gold -Wno-unknown-warning-option -MMD -MF obj/ui/ozone/platform/drm/gbm/drm_thread.o.d -DOZONE_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"305735-3\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DOS_CHROMEOS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DUSE_EGL -DENABLE_IPC_FUZZER -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 -DUSE_EVDEV -DUSE_EVDEV_GESTURES -DMESA_EGL_NO_X11_HEADERS -I../.. -Igen -I../../third_party/khronos -I../../gpu -I../../third_party/libwebp/src -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/third_party/vulkan -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I/b/c/b/chromeos_amd64_generic_chromium_compile_only_ng/.cros_cache/chrome-sdk/tarballs/amd64-generic+9649.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/libdrm -I../../third_party/mesa/src/include -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -m64 -march=x86-64 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../../.cros_cache/chrome-sdk/tarballs/amd64-generic+9649.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=gnu++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -pipe -pipe -pipe -march=x86-64 -msse3 -fno-split-dwarf-inlining -D__google_stl_debug_vector=1 -Wno-unknown-warning-option -Wno-inline-asm -c ../../ui/ozone/platform/drm/gpu/drm_thread.cc -o obj/ui/ozone/platform/drm/gbm/drm_thread.o
../../ui/ozone/platform/drm/gpu/drm_thread.cc:120:15: error: use of undeclared identifier 'GBM_BO_USE_TEXTURING'; did you mean 'GBM_BO_USE_RENDERING'?
      flags = GBM_BO_USE_TEXTURING;
              ^~~~~~~~~~~~~~~~~~~~
              GBM_BO_USE_RENDERING

Patch-set: 5
Reviewer: Dongseong Hwang <1112153@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>