Remove trailing '\' to avoid build failure on gcc 4.x toolchain.
The trailing '\' on a comment line produces following error on gcc 4.8

chrome/browser/extensions/chrome_url_request_util.h:29:1:
    error: multi-line comment [-Werror=comment]

TBR=fsamuel@chromium.org, lfg@chromium.org, rockot@chromium.org
NOTRY=true

Review URL: https://codereview.chromium.org/552103003

Cr-Commit-Position: refs/heads/master@{#295278}
(cherry picked from commit 33f197bf06e457f0a2a3616f15e0f44683cc2a2c)