Revert of Change mojo_public_bindings_unittests to use chromium environment. (patchset #5 id:70001 of https://codereview.chromium.org/1406073004/ )
Reason for revert:
Broke compile on ChromeOS GN bot:

http://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20GN%20%28dbg%29/builds/11875/

[4097/4100] STAMP obj/chrome/test/browser_tests_js_webui.stamp
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -pie -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -B../../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -Wl,--icf=all -pthread -m64 -Wl,-rpath=\$ORIGIN/ -Wl,-rpath-link= -Wl,--disable-new-dtags -Wl,--export-dynamic -o ./chrome -Wl,--start-group @./chrome.rsp ./libbase.so ./libbase_i18n.so ./libicui18n.so ./libicuuc.so ./libprefs.so ./libui_base.so ./libskia.so ./libplatform.so ./libevents_base.so ./libgfx.so ./libgeometry.so ./liburl.so ./libnet.so ./libprotobuf_lite.so ./libcrcrypto.so ./libboringssl.so ./libnative_theme.so ./libkeyed_service_core.so ./libsql.so ./libwebdata_common.so ./libsessions.so ./libprotocol.so ./libcontent.so ./libmojo_system_impl.so ./libgpu.so ./libsync.so ./libcloud_policy_proto_generated_compile.so ./libpolicy_component.so ./libproto.so ./libmojo_environment_impl.so ./libipc.so ./libcommon.so ./libgin.so ./libv8.so ./libppapi_shared.so ./libaccessibility.so ./libgfx_ipc.so ./libgl_wrapper.so ./libmessage_center.so ./libblink_common.so ./libblink_web.so ./libblink_platform.so ./libgles2_c_lib.so ./libmedia.so ./libdevice_event_log.so ./libdevice_core.so ./libchromeos.so ./libdbus.so ./liburl_matcher.so ./libbluetooth.so ./libkeyboard_with_content.so ./libprinting.so ./libkeyed_service_content.so ./libonc.so ./libshared_memory_support.so ./libgcm.so ./libstorage_common.so ./libui_base_ime.so ./libstorage_browser.so ./libchrome_apps.so ./libcc.so ./libppapi_host.so ./libaura.so ./libcompositor.so ./libevents.so ./libviews.so ./libash.so ./libkeyboard.so ./libx11_events_platform.so ./libdevices.so ./libgfx_x11.so ./libwebview.so ./libgesture_detection.so ./libsnapshot.so ./libbrowser_ui_views.so ./libnet_with_v8.so ./libsurface.so ./libweb_dialogs.so ./libppapi_proxy.so ./libwallpaper.so ./libash_with_content.so ./liblogin.so ./libcore.so ./libuser_manager.so ./libownership.so ./libproxy_config.so ./libapp_list.so ./libui_chromeos.so ./libdisplay.so ./libfile_manager.so ./libwm.so ./libcaptive_portal.so ./libdomain_reliability.so ./libchromium_sqlite3.so ./libstartup_tracing.so ./libuser_prefs.so ./libshell_dialogs.so ./libmidi.so ./libmojo_common_lib.so ./libmessage_pump.so ./libgles2_implementation.so ./libgles2_utils.so ./libtranslator.so -Wl,--end-group  -ldl -lpangocairo-1.0 -lpango-1.0 -lcairo -lgobject-2.0 -lglib-2.0 -lX11 -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -ldbus-1 -lpthread -lrt -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lexpat -lXrandr -lm -lfontconfig -lfreetype
../../third_party/mojo/src/mojo/edk/embedder/embedder.cc:132:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:33:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:39:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:48:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:63:error: undefined reference to 'mojo::edk::internal::g_platform_support'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:66:error: undefined reference to 'mojo::edk::internal::g_platform_support'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:67:error: undefined reference to 'mojo::edk::internal::g_platform_support'
clang:error: linker command failed with exit code 1 (use -v to see invocation)
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -B../../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -Wl,--icf=all -pthread -m64 -Wl,-rpath=\$ORIGIN/ -Wl,-rpath-link= -Wl,--disable-new-dtags -Wl,--export-dynamic -o ./interactive_ui_tests -Wl,--start-group @./interactive_ui_tests.rsp ./libnet.so ./libskia.so ./libsync.so ./libviews.so ./libui_touch_selection.so ./libchromeos.so ./libcontent.so ./libmojo_system_impl.so ./libgpu.so ./libblink_common.so ./libblink_web.so ./libblink_platform.so ./libgles2_c_lib.so ./liburl.so ./libv8.so ./libcc_blink.so ./libbase.so ./libbase_i18n.so ./libicui18n.so ./libicuuc.so ./libcrcrypto.so ./libprotobuf_lite.so ./libboringssl.so ./libnet_with_v8.so ./libstorage_common.so ./libui_base.so ./libplatform.so ./libevents_base.so ./libgfx.so ./libgeometry.so ./libui_base_ime.so ./libevents.so ./libgesture_detection.so ./libdevices.so ./libgfx_x11.so ./libgl_wrapper.so ./libx11_window.so ./libmojo_environment_impl.so ./libscheduler.so ./libcc.so ./libcc_surfaces.so ./libgles2_implementation.so ./libgl_in_process_context.so ./libgles2_utils.so ./libmedia.so ./libmojo.so ./libmojo_common_lib.so ./libmessage_pump.so ./libppapi_host.so ./libppapi_proxy.so ./libipc.so ./libppapi_shared.so ./libstorage_browser.so ./libcompositor.so ./libsurface.so ./libaura.so ./libwm.so ./libgin.so ./libprefs.so ./libnative_theme.so ./libkeyed_service_core.so ./libsql.so ./libwebdata_common.so ./libsessions.so ./libprotocol.so ./libcloud_policy_proto_generated_compile.so ./libpolicy_component.so ./libproto.so ./libcommon.so ./libaccessibility.so ./libgfx_ipc.so ./libmessage_center.so ./libdevice_event_log.so ./libdevice_core.so ./libdbus.so ./liburl_matcher.so ./libbluetooth.so ./libkeyboard_with_content.so ./libprinting.so ./libkeyed_service_content.so ./libonc.so ./libshared_memory_support.so ./libgcm.so ./libchrome_apps.so ./libash.so ./libkeyboard.so ./libx11_events_platform.so ./libwebview.so ./libsnapshot.so ./libbrowser_ui_views.so ./libweb_dialogs.so ./libwallpaper.so ./libash_with_content.so ./liblogin.so ./libcore.so ./libuser_manager.so ./libownership.so ./libproxy_config.so ./libapp_list.so ./libui_chromeos.so ./libdisplay.so ./libfile_manager.so ./libcaptive_portal.so ./libdomain_reliability.so ./libchromium_sqlite3.so ./libstartup_tracing.so ./libuser_prefs.so ./libshell_dialogs.so ./libmidi.so ./libtranslator.so -Wl,--end-group  -ldl -lXtst -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lfontconfig -lX11 -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lexpat -lm -ldbus-1 -lpthread -lXrandr -lfreetype
../../third_party/mojo/src/mojo/edk/embedder/embedder.cc:132:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:33:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:39:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:48:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:63:error: undefined reference to 'mojo::edk::internal::g_platform_support'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:66:error: undefined reference to 'mojo::edk::internal::g_platform_support'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:67:error: undefined reference to 'mojo::edk::internal::g_platform_support'
clang:error: linker command failed with exit code 1 (use -v to see invocation)
FAILED: ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -B../../third_party/binutils/Linux_x64/Release/bin -fuse-ld=gold -Wl,--icf=all -pthread -m64 -Wl,-rpath=\$ORIGIN/ -Wl,-rpath-link= -Wl,--disable-new-dtags -Wl,--export-dynamic -o ./unit_tests -Wl,--start-group @./unit_tests.rsp ./libnet.so ./libskia.so ./libgl_wrapper.so ./libv8.so ./libwm.so ./libdevices.so ./libdbus.so ./libviews.so ./libbase.so ./libbase_i18n.so ./libicui18n.so ./libicuuc.so ./libprefs.so ./libui_base.so ./libplatform.so ./libevents_base.so ./libgfx.so ./libgeometry.so ./liburl.so ./libprotobuf_lite.so ./libcrcrypto.so ./libboringssl.so ./libnative_theme.so ./libkeyed_service_core.so ./libsql.so ./libwebdata_common.so ./libsessions.so ./libprotocol.so ./libcontent.so ./libmojo_system_impl.so ./libgpu.so ./libsync.so ./libcloud_policy_proto_generated_compile.so ./libpolicy_component.so ./libproto.so ./libmojo_environment_impl.so ./libipc.so ./libcommon.so ./libgin.so ./libppapi_shared.so ./libaccessibility.so ./libgfx_ipc.so ./libmessage_center.so ./libblink_common.so ./libblink_web.so ./libblink_platform.so ./libgles2_c_lib.so ./libmedia.so ./libdevice_event_log.so ./libdevice_core.so ./libchromeos.so ./liburl_matcher.so ./libbluetooth.so ./libkeyboard_with_content.so ./libprinting.so ./libkeyed_service_content.so ./libonc.so ./libshared_memory_support.so ./libgcm.so ./libstorage_common.so ./libui_base_ime.so ./libstorage_browser.so ./libchrome_apps.so ./libcc.so ./libppapi_host.so ./libaura.so ./libcompositor.so ./libevents.so ./libash.so ./libkeyboard.so ./libx11_events_platform.so ./libgfx_x11.so ./libwebview.so ./libgesture_detection.so ./libsnapshot.so ./libbrowser_ui_views.so ./libnet_with_v8.so ./libsurface.so ./libweb_dialogs.so ./libppapi_proxy.so ./libwallpaper.so ./libash_with_content.so ./liblogin.so ./libcore.so ./libuser_manager.so ./libownership.so ./libproxy_config.so ./libapp_list.so ./libui_chromeos.so ./libdisplay.so ./libfile_manager.so ./libcaptive_portal.so ./libdomain_reliability.so ./libchromium_sqlite3.so ./libstartup_tracing.so ./libuser_prefs.so ./libshell_dialogs.so ./libmidi.so ./libmojo_common_lib.so ./libmessage_pump.so ./libgles2_implementation.so ./libgles2_utils.so ./libtranslator.so ./libcc_blink.so ./libx11_window.so ./libscheduler.so ./libcc_surfaces.so ./libgl_in_process_context.so ./libmojo.so -Wl,--end-group  -ldl -ldbus-1 -lpthread -lrt -lX11 -lXcomposite -lXcursor -lXdamage -lXext -lXfixes -lXi -lXrender -lXtst -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lexpat -lXrandr -lm -lfontconfig -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lfreetype
../../third_party/mojo/src/mojo/edk/embedder/embedder.cc:132:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:33:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:39:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/entrypoints.cc:48:error: undefined reference to 'mojo::edk::internal::g_core'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:63:error: undefined reference to 'mojo::edk::internal::g_platform_support'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:66:error: undefined reference to 'mojo::edk::internal::g_platform_support'
../../third_party/mojo/src/mojo/edk/embedder/test_embedder.cc:67:error: undefined reference to 'mojo::edk::internal::g_platform_support'
clang:error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Original issue's description:
> Change mojo_public_bindings_unittests to use chromium environment.
>
> This is needed by the associated interface implementation, which uses
> base::MessageLoop and related classes. It won't work with the standalone
> environment, and we want to stop using the standalone environment anyway.
>
> BUG=546067
>
> Committed: https://crrev.com/70bfaf3f892dcfe48e980c01e22422226816f717
> Cr-Commit-Position: refs/heads/master@{#358146}

TBR=sky@chromium.org,yzshen@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=546067

Review URL: https://codereview.chromium.org/1430913005