Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> hmm... this is fine, but I'm curious why it was a problem before.  Do you know why the compile failed?

The actual error was:
../..\ipc/ipc_message.h(18): fatal error C1083: Cannot open include file: 'ipc/ipc_features.h': No such file or directory

My guess is because "common_constants" target (that includes constants.cc)
is a source_set, it cannot depend on generated header (ipc_features.h is
generated), does that sound right?

Patch-set: 3
Reviewer: Istiaque Ahmed <1001727@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>