Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> > Patch Set 6:
> > 
> > I'm getting a build error related to this patch on Windows (using Clang):
> > 
> > FAILED: obj/third_party/WebKit/Source/platform/platform/platform_jumbo_3.obj
> > C:\src\goma/gomacc.exe ../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /nologo /showIncludes /FC  @obj/third_party/WebKit/Source/platform/platform/platform_jumbo_3.obj.rsp /c gen/third_party/WebKit/Source/platform/platform_jumbo_3.cc /Foobj/third_party/WebKit/Source/platform/platform/platform_jumbo_3.obj /Fd"obj/third_party/WebKit/Source/platform/platform_cc.pdb"
> > In file included from gen/third_party/WebKit/Source/platform/platform_jumbo_3.cc:69:
> > C:\src\chromium\src\third_party\WebKit\Source\platform\fonts\FontVariantNumeric.cpp(11,20):  error: redefinition of 'kUnknownString'
> > static const char* kUnknownString = "Unknown";
> >                    ^
> > C:\src\chromium\src\third_party\WebKit\Source\platform\fonts\FontVariantEastAsian.cpp(11,20):  note: previous definition is here
> > static const char* kUnknownString = "Unknown";
> >                    ^
> > 1 error generated.
> 
> I think this is a jumbo-build-specific issue, there is a fix in discussion here:
> 
> https://chromium-review.googlesource.com/c/chromium/src/+/693863
> 
> Jumbo is only an optional build currently, right? I want to make sure landing fix tomorrow is soon enough.

I figured that it was because one of my experimental GN flags :). It seems like a serious issue with the jumbo builds :(, I'd have hoped that moving this to an anonymous namespace will fix the issue but it's apparently not the case :(

Patch-set: 6