Update patch set 4
Patch Set 4:

msw@, I need some help with this, please.

The change is causing a failure on the win_chromium_rel_ng bot in gfx_unittests (Windows-7-SP1) on RenderTextTest.ElidedText/HarfBuzz.  One particular line fails:
../../ui/gfx/render_text_unittest.cc(1043): error:       Expected: WideToUTF16(cases[i].display_text)
      Which is: L"012\xF0\x2026"
To be equal to: render_text->GetDisplayText()
      Which is: L"012\xF0\x9D\x2026"
Google Test trace:
../../ui/gfx/render_text_unittest.cc(1028): Testing cases[22] '012??'

This test passes on linux (bots and my workstation).

I don't know how Windows and Linux differ in their rendertext implements to understand why it can fail on one platform instead of the other, not can I read / understand unicode enough to figure out what that test case is meant to test.  (Too bad it wasn't commented like many of other unicode-like tests in the file.)

You reviewed the original change by skanuj@ that landed this test.
https://codereview.chromium.org/119813002

This means I have at least three reasons you might have knowledge I don't that could help figure this out.

Please. :-)

thanks,
mark

Patch-set: 4
Reviewer: Mark Pearson <1001310@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0