Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > hmm... this is fine, but I'm curious why it was a problem before.  Do you know why the compile failed?
> > 
> > The actual error was:
> > ../..\ipc/ipc_message.h(18): fatal error C1083: Cannot open include file: 'ipc/ipc_features.h': No such file or directory
> > 
> > My guess is because "common_constants" target (that includes constants.cc)
> > is a source_set, it cannot depend on generated header (ipc_features.h is
> > generated), does that sound right?
> 
> Hmm... source_sets should be able to specify deps.  If we just made common_constants in extensions/common/BUILD.gn depend on //ipc (or potentially //ipc:message_support) would that work?

I think so.
I'm planning to try that on a subsequent CL as it would be useful to share kIgnoreRoutingId constant with api_event_listeners.cc. Since this is orthogonal to this CL and reproducing failure requires me to send CLs to win_x64_archive bot every time, I'm leaving this out from here.

Patch-set: 3
Reviewer: Istiaque Ahmed <1001727@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>