Update patch set 8
Patch Set 8:

> Patch Set 8:
> 
> Could not start com.apple.debugserver!
> Done.
> Uninstalling 'com.google.gtest.sql-unittests'
> Uninstall: RemovingApplication (50%)
> 
> Uninstall: GeneratingApplicationMap (90%)
> 
> Uninstall: Complete
> idevice-app-runner returned 255
> 
> Traceback (most recent call last):
>   File "src/ios/build/bots/scripts/run.py", line 171, in <module>
>     sys.exit(main(args, test_args))
>   File "src/ios/build/bots/scripts/run.py", line 61, in main
>     return 0 if tr.launch() else 1
>   File "/b/swarm_slave/w/ir/src/ios/build/bots/scripts/test_runner.py", line 330, in launch
>     self.restart()
> TypeError: 'bool' object is not callable

Thank you Justin for attaching the log!

The issue didn't happen when the method name was 'restart_device_and_check' instead of 'restart'. This failed because the method name is same as a class bool value 'restart' in the same scope. I will fix this in another CL.

Patch-set: 8