Fix build failure when using GYP
The failure was:
In file included from ../../components/arc/bitmap/bitmap_type_converters.cc:5:
../../components/arc/bitmap/bitmap_type_converters.h:8:10: fatal error: 'components/arc/common/bitmap.mojom.h' file not found

Missing dependency.

BUG=
TEST=Build succeeds

Review-Url: https://codereview.chromium.org/2109063007