Fix Beta Builder base::SplitString compile errors.
The new base::SplitString API is from M45 and thus doesn't compile on M44.

FAILED: ninja -t msvc -e environment.x86 -- "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\chrome\installer\setup\setup_unittests.update_active_setup_version_work_item.obj.rsp /c ..\..\chrome\installer\setup\update_active_setup_version_work_item.cc /Foobj\chrome\installer\setup\setup_unittests.update_active_setup_version_work_item.obj /Fdobj\chrome\setup_unittests.cc.pdb
c:\b\build\slave\win_beta\build\src\chrome\installer\setup\update_active_setup_version_work_item.cc(52) : error C2039: 'TRIM_WHITESPACE' : is not a member of 'base'
c:\b\build\slave\win_beta\build\src\chrome\installer\setup\update_active_setup_version_work_item.cc(52) : error C2065: 'TRIM_WHITESPACE' : undeclared identifier
c:\b\build\slave\win_beta\build\src\chrome\installer\setup\update_active_setup_version_work_item.cc(52) : error C2039: 'SPLIT_WANT_NONEMPTY' : is not a member of 'base'
c:\b\build\slave\win_beta\build\src\chrome\installer\setup\update_active_setup_version_work_item.cc(52) : error C2065: 'SPLIT_WANT_NONEMPTY' : undeclared identifier

Same error is about to happen in setup_util.cc with the merge of http://crrev.com/34b55e602ac6216bced81297addab784355d2690

BUG=488247, 502363
TEST=setup_unittests.exe --gtest_filter=*ActiveSetup* (compiled and executed on branch-heads/2403 with this fix)
TBR=grt@chromium.org

Review URL: https://codereview.chromium.org/1235003002 .