Update patch set 1
Patch Set 1:

So the original patch did not have a provisional PR made for it because it contained binary files (and provisional PRs receive their patches from the Gerrit API, which doesn't include the binary contents). Here is the output:

patch does not apply
error: cannot apply binary patch to 'mediacapture-fromelement/webm/test-av-384k-44100Hz-1ch-320x240-30fps-10kfr.webm' without full index line
error: mediacapture-fromelement/webm/test-av-384k-44100Hz-1ch-320x240-30fps-10kfr.webm: patch does not apply
error: cannot apply binary patch to 'mediacapture-fromelement/webm/test-v-128k-320x240-24fps-8kfr.webm' without full index line
error: mediacapture-fromelement/webm/test-v-128k-320x240-24fps-8kfr.webm: patch does not apply

The easiest way to go forward this is to make an upstream WPT PR first with the changes (you can duplicate the original: https://github.com/w3c/web-platform-tests/pull/6546) then wait for those changes to be imported automatically into Chromium. I'll make that upstream PR now for you. Let me know if you want to tackle this a different way.

Patch-set: 1
Reviewer: Jeff Carpenter <1168241@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>