Update patch set 12
Patch Set 12:

Hi Emik, this CL is causing a compiler error for me. Do I need to update a build flag or something?

/../third_party/WebKit/Source/platform/fonts/shaping/ShapeResult.cpp:469:3: error: unknown type name 'hb_glyph_flags_t'; did you mean 'hb_glyph_info_t'?
  hb_glyph_flags_t flags = hb_glyph_info_get_glyph_flags(glyph_infos + i);
  ^~~~~~~~~~~~~~~~
  hb_glyph_info_t
/usr/local/google/chromium/.cros_cache/chrome-sdk/tarballs/eve+9916.0.0+sysroot_chromeos-base_chromeos-chrome.tar.xz/usr/include/harfbuzz/hb-buffer.h:72:3: note: 'hb_glyph_info_t' declared here
} hb_glyph_info_t;
  ^
../../third_party/WebKit/Source/platform/fonts/shaping/ShapeResult.cpp:469:28: error: use of undeclared identifier 'hb_glyph_info_get_glyph_flags'
  hb_glyph_flags_t flags = hb_glyph_info_get_glyph_flags(glyph_infos + i);
                           ^
../../third_party/WebKit/Source/platform/fonts/shaping/ShapeResult.cpp:470:19: error: use of undeclared identifier 'HB_GLYPH_FLAG_UNSAFE_TO_BREAK'
  return (flags & HB_GLYPH_FLAG_UNSAFE_TO_BREAK) == 0;
                  ^
3 errors generated.

Patch-set: 12
CC: Kyle Horimoto <1001529@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>