Update patch set 6
Patch Set 6:

This seems to be causing flaky build errors on chromeos-amd64-generic-rel:
https://ci.chromium.org/buildbot/tryserver.chromium.chromiumos/chromeos-amd64-generic-rel/

In file included from ../../third_party/WebKit/Source/platform/heap/ThreadState.cpp:60:
In file included from ../../third_party/WebKit/public/platform/Platform.h:56:
In file included from ../../third_party/WebKit/public/platform/WebURLLoader.h:36:
../../third_party/WebKit/public/platform/WebURLRequest.h:41:10: fatal error: 'services/network/public/interfaces/request_context_frame_type.mojom-shared.h' file not found
#include "services/network/public/interfaces/request_context_frame_type.mojom-shared.h"

Probably need to add some DEPS to BUILD.gn. I will revert for now.

Patch-set: 6
Reviewer: Matt Falkenhagen <1000128@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>