Revert of [PresentationAPI] Update PresentationDispatcher to use availability URL. (patchset #1 id:1 of https://codereview.chromium.org/1287043006/ )
Reason for revert:
Speculative revert due to failure of linux_arm Compile on the waterfall.

http://build.chromium.org/p/chromium.linux/builders/Linux%20ARM/builds/2277/steps/compile/logs/stdio

[715/4680] RULE yasm genperf for source/patched-yasm/modules/arch/x86/x86regtmod.gperf
FAILED: cd ../../third_party/yasm; ../../out/Release/genversion ../../out/Release/gen/third_party/yasm/version.mac
../../out/Release/genversion: 1: ../../out/Release/genversion: Syntax error: word unexpected (expecting ")")
FAILED: cd ../../third_party/yasm; ../../out/Release/genperf "source/patched-yasm/modules/arch/x86/x86cpu.gperf" "../../out/Release/gen/third_party/yasm/x86cpu.c"
../../out/Release/genperf: 1: ../../out/Release/genperf: Syntax error: word unexpected (expecting ")")
FAILED: cd ../../third_party/yasm; ../../out/Release/genperf "source/patched-yasm/modules/arch/x86/x86regtmod.gperf" "../../out/Release/gen/third_party/yasm/x86regtmod.c"
../../out/Release/genperf: 1: ../../out/Release/genperf: Syntax error: word unexpected (expecting ")")
FAILED: cd ../../ppapi/native_client; python ../../native_client/build/build_nexe.py --root ../.. --product-dir ../../out/Release/xyz --config-name Release -t ../../native_client/toolchain/ --strip-all --arch arm --build newlib_nexe --name ../../out/Release/nacl_irt_arm.nexe --objdir ../../out/Release/obj/ppapi/native_client/nacl_irt.gen/irt-arm/nacl_irt "--include-dirs=../../out/Release/gen/tc_newlib/include ../.. .. \"../../out/Release/gen\" ../../third_party/khronos ../../gpu ../.." "--compile_flags=-Wno-unused-local-typedefs -Wno-psabi -ffunction-sections -fdata-sections -fomit-frame-pointer -fasynchronous-unwind-tables  -O2 -g -Wall -fdiagnostics-show-option -Werror " --gomadir /b/build/goma "--defines=\"__STDC_LIMIT_MACROS=1\" \"__STDC_FORMAT_MACROS=1\" \"_GNU_SOURCE=1\" \"_DEFAULT_SOURCE=1\" \"_BSD_SOURCE=1\" \"_POSIX_C_SOURCE=199506\" \"_XOPEN_SOURCE=600\" \"DYNAMIC_ANNOTATIONS_ENABLED=1\" \"DYNAMIC_ANNOTATIONS_PREFIX=NACL_\" \"NACL_BUILD_ARCH=arm\" V8_DEPRECATION_WARNINGS \"CLD_VERSION=2\" \"_FILE_OFFSET_BITS=64\" CHROMIUM_BUILD \"CR_CLANG_REVISION=242792-1\" UI_COMPOSITOR_IMAGE_TRANSPORT \"USE_AURA=1\" \"USE_ASH=1\" \"USE_PANGO=1\" \"USE_CAIRO=1\" \"USE_DEFAULT_RENDER_THEME=1\" \"USE_LIBJPEG_TURBO=1\" \"USE_X11=1\" \"USE_CLIPBOARD_AURAX11=1\" ENABLE_ONE_CLICK_SIGNIN ENABLE_PRE_SYNC_BACKUP \"ENABLE_WEBRTC=1\" \"ENABLE_MEDIA_ROUTER=1\" ENABLE_PEPPER_CDMS ENABLE_CONFIGURATION_POLICY ENABLE_NOTIFICATIONS \"ENABLE_HIDPI=1\" \"ENABLE_TOPCHROME_MD=1\" USE_UDEV DONT_EMBED_BUILD_METADATA FIELDTRIAL_TESTING_ENABLED \"ENABLE_TASK_MANAGER=1\" \"ENABLE_EXTENSIONS=1\" \"ENABLE_PLUGINS=1\" \"ENABLE_SESSION_SERVICE=1\" \"ENABLE_THEMES=1\" \"ENABLE_AUTOFILL_DIALOG=1\" \"ENABLE_BACKGROUND=1\" \"ENABLE_GOOGLE_NOW=1\" \"ENABLE_PRINTING=1\" \"ENABLE_BASIC_PRINTING=1\" \"ENABLE_PRINT_PREVIEW=1\" \"ENABLE_SPELLCHECK=1\" \"ENABLE_CAPTIVE_PORTAL_DETECTION=1\" \"ENABLE_APP_LIST=1\" \"ENABLE_SETTINGS_APP=1\" \"ENABLE_SUPERVISED_USERS=1\" \"ENABLE_MDNS=1\" \"ENABLE_SERVICE_DISCOVERY=1\" V8_USE_EXTERNAL_STARTUP_DATA FULL_SAFE_BROWSING SAFE_BROWSING_CSD SAFE_BROWSING_DB_LOCAL SAFE_BROWSING_SERVICE __ARMEL__ __arm__ NVALGRIND \"USE_LIBPCI=1\" \"USE_OPENSSL=1\" \"USE_GLIB=1\" \"USE_NSS_CERTS=1\"" "--link_flags=-B../../out/Release/gen/tc_irt/libarm -Wl,--gc-sections -Wl,--start-group -lirt_browser -lpnacl_irt_shim_for_irt -lppapi_proxy_nacl -lppapi_ipc_nacl -lppapi_shared_nacl -lgles2_implementation_nacl -lgles2_cmd_helper_nacl -lgles2_utils_nacl -lcommand_buffer_client_nacl -lcommand_buffer_common_nacl -ltracing_nacl -lgpu_ipc_nacl -lipc_nacl -lbase_nacl -lshared_memory_support_nacl -lsrpc -limc_syscalls -lplatform -lgio -Wl,--end-group -lm " "--source-list=../../out/gypfiles/ppapi/native_client/irt-arm.nacl_irt.source_list.gypcmd" "--tls-edit=../../out/Release/tls_edit" "--irt-linker=../../native_client/build/link_irt.py"
Traceback (most recent call last):
  File "../../native_client/build/link_irt.py", line 236, in <module>
    sys.exit(Main())
  File "../../native_client/build/link_irt.py", line 229, in Main
    linker.Link(remaining_args)
  File "../../native_client/build/link_irt.py", line 163, in Link
    tls_edit_err = self.Run(tls_edit_cmd, possibly_script=False)
  File "/b/build/slave/Linux_ARM/build/src/native_client/build/build_nexe_tools.py", line 137, in Run
    raise Error('%s\nFAILED: %s' % (' '.join(cmd_line), str(err)))
build_nexe_tools.Error: /b/build/slave/Linux_ARM/build/src/out/Release/tls_edit ../../out/Release/nacl_irt_arm.nexe.debug.raw ../../out/Release/nacl_irt_arm.nexe.debug
FAILED: [Errno 8] Exec format error

Original issue's description:
> [PresentationAPI] Update PresentationDispatcher to use availability URL.
>
> This patch updates PresentationDispatcher to use the availability URL passed
> with the observer from Blink to start/stop presentation display availability
> listening.
>
> It also removes the no-longer-needed API that passes the URL separately.
>
> This is part 4 of a four-part patch and will land after #3 rolls.
>
> 1. [blink] https://codereview.chromium.org/1280713003
> 2. [content] https://codereview.chromium.org/1266923003
> 3. [blink] https://codereview.chromium.org/1274333004
> 4. [content] This patch.
>
> BUG=510814
>
> Committed: https://crrev.com/0033065242a9e2bdd5047196423a25000abf266b
> Cr-Commit-Position: refs/heads/master@{#343206}

TBR=imcheng@chromium.org,mlamouri@chromium.org,mfoltz@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=510814

Review URL: https://codereview.chromium.org/1290813005