content: common: fix missing mojo dependency in GN build
content/common/mojo/service_registry_impl.cc requires the mojo type
converters from mojo/common:common_base.

../../third_party/mojo/src/mojo/public/cpp/bindings/string.h:40: error: undefined reference to 'mojo::TypeConverter<mojo::String, base::BasicStringPiece<std::string> >::Convert(base::BasicStringPiece<std::string> const&)'

BUG=none

Review URL: https://codereview.chromium.org/1298443003