Update patch set 1
Patch Set 1:

I am not sure we should do this CL, but if yes, there are some issues need your help.

Since WebServiceWorkerRegistration.h is in the third_party/WebKit/public/, I think it should include navigation_preload_state.mojom-shared.h instead of xxx-blink.h? But it has a compile issue:
----------------------------
error: no type named 'NavigationPreloadState' in namespace 'blink::mojom::blink'; did you mean 'mojom::internal::NavigationPreloadState_Data'? 
----------------------------

I see some files in third_party/WebKit/public/ folder use xxx-blink.h, it indeed can pass the above issue, but there is other error:
-----------------
error: 'STATIC_ASSERT_ENUM' macro redefined 
-----------------

So, do you have any solution about that or we should keep the blink::WebNavigationPreloadState? Thanks a lot.

Patch-set: 1
Reviewer: Matt Falkenhagen <1000128@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Makoto Shimazu <1125915@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Kinuko Yasuda <1001472@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
CC: Han Leon <1161621@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Xiaofeng Zhang <1223459@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false