Revert of Speculative fix for perf test performance regressions. (patchset #1 id:1 of https://codereview.chromium.org/2190083002/ )
Reason for revert:
Speculative revert to see if that fixes the WebRTC Win7 Tester bot.

See https://build.chromium.org/p/chromium.webrtc/builders/Win7%20Tester/builds/28171

Sample error logs:
[ RUN      ] PPAPINaClPNaClTest.MediaStreamVideoTrack
[4788:5076:0729/174935:WARNING:chrome_browser_main_win.cc(419)] Command line too long for RegisterApplicationRestart
[5744:3076:0729/174935:ERROR:dxva_video_decode_accelerator_win.cc(273)] EGL_EXT_device_query missing
[5744:3076:0729/174935:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 273
[6048:3772:0729/174935:ERROR:singleton_hwnd.cc(34)] Cannot create windows on non-UI thread!
[4788:4472:0729/174936:WARNING:embedded_test_server.cc(202)] Request not handled. Returning 404: /favicon.ico
[4788:4168:0729/174936:ERROR:nacl_process_host.cc(337)] NaCl process exited with status -1073741674 (0xc0000096)
[4788:5076:0729/174936:INFO:CONSOLE(0)] "NativeClient: NaCl module crashed", source: http://127.0.0.1:50824/test_case.html?mode=nacl_pnacl&testcase=MediaStreamVideoTrack (0)
e:\b\c\b\win_builder\src\chrome\test\ppapi\ppapi_test.cc(249): error: Value of: handler.message().c_str()
  Actual: "Plugin crashed. 'NaCl module crashed'"
Expected: "PASS"
[5744:3300:0729/174936:ERROR:node_controller.cc(1099)] Could not be introduced to peer 71198AAF592CFFC1.CFEE94F16E49B4BD
[4788:5076:0729/174937:WARNING:url_request_context_getter.cc(43)] URLRequestContextGetter leaking due to no owning thread.
[  FAILED  ] PPAPINaClPNaClTest.MediaStreamVideoTrack, where TypeParam =  and GetParam() =  (2255 ms)
[98/98] PPAPINaClPNaClTest.MediaStreamVideoTrack (2556 ms)
Retrying 1 test (retry #3)
[ RUN      ] PPAPINaClPNaClTest.MediaStreamVideoTrack
[5628:4292:0729/174937:WARNING:chrome_browser_main_win.cc(419)] Command line too long for RegisterApplicationRestart
[1440:4176:0729/174937:ERROR:dxva_video_decode_accelerator_win.cc(273)] EGL_EXT_device_query missing
[1440:4176:0729/174937:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_accelerator_win.cc on line 273
[4792:5844:0729/174937:ERROR:singleton_hwnd.cc(34)] Cannot create windows on non-UI thread!
[5628:6016:0729/174938:WARNING:embedded_test_server.cc(202)] Request not handled. Returning 404: /favicon.ico
[5628:6104:0729/174939:ERROR:nacl_process_host.cc(337)] NaCl process exited with status -1073741674 (0xc0000096)
[5628:4292:0729/174939:INFO:CONSOLE(0)] "NativeClient: NaCl module crashed", source: http://127.0.0.1:50830/test_case.html?mode=nacl_pnacl&testcase=MediaStreamVideoTrack (0)
e:\b\c\b\win_builder\src\chrome\test\ppapi\ppapi_test.cc(249): error: Value of: handler.message().c_str()
  Actual: "Plugin crashed. 'NaCl module crashed'"
Expected: "PASS"
[1440:1012:0729/174939:ERROR:node_controller.cc(1099)] Could not be introduced to peer 326301B2EC2EF45.56A4474DAFD5DD29
[5628:4292:0729/174939:WARNING:url_request_context_getter.cc(43)] URLRequestContextGetter leaking due to no owning thread.
[  FAILED  ] PPAPINaClPNaClTest.MediaStreamVideoTrack, where TypeParam =  and GetParam() =  (2243 ms)
[99/99] PPAPINaClPNaClTest.MediaStreamVideoTrack (2537 ms)
1 test failed:
    PPAPINaClPNaClTest.MediaStreamVideoTrack (e:\b\c\b\win_builder\src\chrome\test\ppapi\ppapi_browsertest.cc:1164)

Will reland if the revert doesn't fix the issue.

Original issue's description:
> Speculative fix for perf test performance regressions.
>
> BUG=623804
>
> Committed: https://crrev.com/1eadbdccdb0dee6fe9e169ac374bfa6c1ad9d03d
> Cr-Commit-Position: refs/heads/master@{#408789}

TBR=wfh@chromium.org,waffles@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=623804

Review-Url: https://codereview.chromium.org/2196103003