Use DLOG_IF() for REPORT_OVERFLOW().
Stop using WTFReportError(). The old and new output follow:

Old:
ERROR: !(m_value >= 0)
../../third_party/WebKit/Source/platform/LayoutUnit.h(111) : unsigned int
blink::LayoutUnit::toUnsigned() const

New:
[93371:1295:0323/130149:16342045796099:ERROR:LayoutUnit.h(114)] LayoutUnit
overflow !(m_value >= 0) in unsigned int blink::LayoutUnit::toUnsigned() const

Also,
 - Reverse the condition to enable REPORT_OVERFLOW.
  In the original code, REPORT_OVERFLOW produces code if ERROR_DISABLED, that is
  to say, release build. This is a regression by [1].
 - Remove unused stuff in Assertions.{h,cpp}.

[1] https://chromium.googlesource.com/chromium/src/+/98b71017864f766227d319f81468db00e9a00b73%5E%21/third_party/WebKit/Source/platform/LayoutUnit.h

BUG=596760

Review URL: https://codereview.chromium.org/1827733002