Update patch set 2
Patch Set 2:

Argh, hit enter soon.

The test file causes this warning:
compilation error: file http://www.example.com/ line 8 element stylesheet
xsl:version is missing: document may not be a stylesheet

I have no idea--should I add version or not just to make the warning go away? Is there some conceivable world where not specifying version would have a different result from specifying the version? I'm tempted to add it just to make the test output less noisy. WDYT?

Patch-set: 2
Reviewer: Daniel Cheng <1001168@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>