Revert of bluetooth: android: Initial Low Energy Discovery Sessions. (patchset #9 id:320001 of https://codereview.chromium.org/1150833002/)
Reason for revert:
Downstream Chrome build encountered runtime errors:

java.lang.NoClassDefFoundError: org/chromium/device/bluetooth/ChromeBluetoothAdapter 6a6b6: 07-08 23:04:48.277 3034 3054 W System.err: at org.chromium.base.library_loader.Linker.nativeLoadLibrary(Native Method) 6a6b6: 07-08 23:04:48.277 3034 3054 W System.err: at org.chromium.base.library_loader.Linker.loadLibrary(Linker.java:747) 6a6b6: 07-08 23:04:48.277 3034 3054 W System.err: at org.chromium.base.library_loader.LibraryLoader.loadLibrary(LibraryLoader.java:304) 6a6b6: 07-08 23:04:48.277 3034 3054 W System.err: at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:241) 6a6b6: 07-08 23:04:48.277 3034 3054 W System.err: at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:123) 6a6b6: 07-08 23:04:48.277 3034 3054 W System.err: at org.chromium.chrome.browser.init.NativeInitializationController$1.run(NativeInitializationController.java:83) 6a6b6: 07-08 23:04:48.287 3034 3054 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.device.bluetooth.ChromeBluetoothAdapter" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.google.android.apps.chrome.tests-1.apk", zip file "/data/app/com.google.android.apps.chrome-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.google.android.apps.chrome.tests-1, /data/app-lib/com.google.android.apps.chrome-1, /vendor/lib, /system/lib]] 6a6b6: 07-08 23:04:48.287 3034 3054 W System.err: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56) 6a6b6: 07-08 23:04:48.287 3034 3054 W System.err: at java.lang.ClassLoader.loadClass(ClassLoader.java:497) 6a6b6: 07-08 23:04:48.287 3034 3054 W System.err: at java.lang.ClassLoader.loadClass(ClassLoader.java:457)

Original issue's description:
> bluetooth: android: Initial Low Energy Discovery Sessions.
>
> Add ability to start a low energy scan, though do nothing with the
> results for now besides log that they are found.
>
> Rename hasBluetoothPermission -> hasBluetoothCapability because the
> permissions, SDK version, and hardware feature must all be present.
>
> BUG=488575
>
> Committed: https://crrev.com/649ce43ef16cd8c4a3315f2ebfa5823dcc06585e
> Cr-Commit-Position: refs/heads/master@{#337924}

TBR=ortuno@chromium.org,tedchoc@chromium.org,armansito@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=488575

Review URL: https://codereview.chromium.org/1226103005