Update patch set 2
Patch Set 2:

Oops forgot to write the reason.

> Reason for revert: <INSERT REASONING HERE>
Broke win build:
FAILED: obj/third_party/WebKit/Source/platform/platform/FontCacheSkiaWin.obj 
ninja -t msvc -e environment.x86 -- C:\b\c\goma_client/gomacc.exe "c:\b\c\win_toolchain\vs_files\f53e4598951162bad6330f7a167486c7ae5db1e5\vc\bin\amd64_x86/cl.exe" /nologo /showIncludes  @obj/third_party/WebKit/Source/platform/platform/FontCacheSkiaWin.obj.rsp /c ../../third_party/WebKit/Source/platform/fonts/win/FontCacheSkiaWin.cpp /Foobj/third_party/WebKit/Source/platform/platform/FontCacheSkiaWin.obj /Fd"obj/third_party/WebKit/Source/platform/platform_cc.pdb"
../../third_party/WebKit/Source/platform/fonts/win/FontCacheSkiaWin.cpp(38): fatal error C1083: Cannot open include file: 'platform/RuntimeEnabledFeatures.h': No such file or directory

Patch-set: 2