Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > Andrei, PTAL, thank you!
> 
> Seems unfortunate that we only depend on the exact contents of the response on Cronet tests.
> 
> Is there a reason the failures on the bots output no useful data, just timeouts?

The failures contain useful data:
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.android%2FAndroid_Cronet_ARMv6_Builder%2F5936%2F%2B%2Frecipes%2Fsteps%2Fcronet_test_instrumentation_apk%2F0%2Fstdout
C  211.065s Main  Caused by: org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
C  211.065s Main    java.lang.AssertionError(expected:<74> but was:<73>)
C  211.065s Main    java.lang.IllegalStateException(Cannot shutdown with active requests.)
C  211.065s Main  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:39)
C  211.065s Main  	at org.chromium.net.CronetTestRule.runBase(CronetTestRule.java:140)
C  211.065s Main  	... 28 more

C  211.063s Main  Caused by: java.lang.AssertionError: expected:<121> but was:<120>
C  211.063s Main  	at org.junit.Assert.fail(Assert.java:88)
C  211.063s Main  	at org.junit.Assert.failNotEquals(Assert.java:834)
C  211.063s Main  	at org.junit.Assert.assertEquals(Assert.java:645)
C  211.063s Main  	at org.junit.Assert.assertEquals(Assert.java:631)
C  211.063s Main  	at org.chromium.net.CronetTestCommon.assertResponseEquals(CronetTestCommon.java:192)
C  211.063s Main  	at org.chromium.net.CronetTestRule.assertResponseEquals(CronetTestRule.java:176)
C  211.063s Main  	at org.chromium.net.CronetUrlRequestTest.testMockNotFound(CronetUrlRequestTest.java:657)
C  211.063s Main  	at java.lang.reflect.Method.invokeNative(Method.java)
C  211.063s Main  	at java.lang.reflect.Method.invoke(Method.java:515)
C  211.063s Main  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
C  211.063s Main  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
C  211.063s Main  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
C  211.063s Main  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
C  211.063s Main  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
C  211.063s Main  	at org.chromium.base.test.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:37)
C  211.063s Main  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
C  211.063s Main  	at org.chromium.net.CronetTestRule.runBase(CronetTestRule.java:140)
C  211.064s Main  	... 28 more

C  211.062s Main  Caused by: java.lang.AssertionError: expected:<77> but was:<76>
C  211.062s Main  	at org.junit.Assert.fail(Assert.java:88)
C  211.062s Main  	at org.junit.Assert.failNotEquals(Assert.java:834)
C  211.062s Main  	at org.junit.Assert.assertEquals(Assert.java:645)
C  211.062s Main  	at org.junit.Assert.assertEquals(Assert.java:631)
C  211.062s Main  	at org.chromium.net.CronetTestCommon.assertResponseEquals(CronetTestCommon.java:192)
C  211.062s Main  	at org.chromium.net.CronetTestRule.assertResponseEquals(CronetTestRule.java:176)
C  211.062s Main  	at org.chromium.net.CronetUrlRequestTest.testMockMultiRedirect(CronetUrlRequestTest.java:633)
C  211.062s Main  	at java.lang.reflect.Method.invokeNative(Method.java)
C  211.062s Main  	at java.lang.reflect.Method.invoke(Method.java:515)
C  211.062s Main  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
C  211.062s Main  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
C  211.062s Main  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
C  211.062s Main  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
C  211.062s Main  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
C  211.062s Main  	at org.chromium.base.test.ScreenshotOnFailureStatement.evaluate(ScreenshotOnFailureStatement.java:37)
C  211.062s Main  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
C  211.062s Main  	at org.chromium.net.CronetTestRule.runBase(CronetTestRule.java:140)
C  211.062s Main  	... 28 more

Patch-set: 3
Reviewer: Paul Jensen <1002888@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>