Update patch set 2
Patch Set 2:

(1 comment)

> Patch Set 2:
> 
> In a conditional, are you sure you need to use Get() for ScopedComPtr  or could you simply dereference like so:
> if (*ptr)
> return;
> or
> EXPECT_TRUE(*ptr);
> However, I think that in tests statements such as
> EXPECT_NE(nullptr, ptr.Get());
> would be more readable.

Before the rebase, I could just do:

EXPECT_TRUE(ptr) but now i need to explictly ask for .Get().  Or I get the following error:

../../third_party/googletest/src/googletest/include\gtest/gtest-printers.h(140): error C2440: 'reinterpret_cast': cannot convert from 'const Microsoft::WRL::Details::ComPtrRef<const Microsoft::WRL::ComPtr<IAccessibleTable>>' to 'const unsigned char *'

I think it's perfectly find to call .Get() which is the public MS API to get at the raw pointer -- and IMO, it's cleaner than dereferencing.


> For test file:
> 1. Could you go through the test file and ensure that when you are calling a method e.g. get_table the COM interface you are declaring the out argument to have is the interface that the method actually returns?

Yes.  I verified that every call to get_table() does get queried to IAccessibleTable and that resulting value is tested against nullptr.


> 2. Could you also ensure that you are calling the COM method on the correct interface, i.e. IAccessible doesn't implement get_table.

I think I understand what you're asking, and the test code does that.  I could be misunderstanding you.

The result of the query to IAccessibleTable is used to access the table com methods.

> 3. Ensure that QueryService is used to retrieve the IAccessible2 interface in all cases.

Confirmed. We use the helper method ToIAccessible2 for this.

> 
> In main code:
> long is not LONG.
> LONG (all caps) means int.
> 
> Please use LONG (all caps) throughout Windows code when value will be returned to caller or when it's a COM method argument. Otherwise for internal use, please stick to int.
> Please use static_cast<LONG> to convert int to LONG, even though we know it's an int, it makes it clearer.

This is a good catch -- I will send you a followup cl since there are other that are long and should be LONG (fe all of the Relation code).

> 
> 
>  #include <oleacc.h>
>  #include <stdint.h>
> +#include <algorithm>
>  
>  C++ headers should go in their own section - Style Guide.
>  Do we need limits.h?

Removed -- we didn't need any of them! :)

>  
>  
> +  for (int i = 0; i < rows; ++i) {
> +    for (int j = 0; j < columns; ++j) {
> +      auto* cell = GetTableCell(i, j);
> 
> I like auto but Style Guide says only use it when type is complex to type or already mentioned, like on the right hand side because of a static_cast.

The text says:
"Use auto to avoid type names that are noisy, obvious, or unimportant"

I don't think the type here is very important since we're implementing a table method and GetTableCell is the workhorse of how table access happens in this code.

I would prefer auto here, but if you are strong about this point, i don't care that much. ;)


> 
> 
> 
>    *column_count = 0;
> 
>    Thanks for following the rules of COM correctly.
>    Check out arguments to ensure they are not NULL, initialize out arguments to default values, check in arguments and state for correctness and then do work.
>    Could you make sure it's followed in all the methods you modified though? I know that we haven't been following the rules consistently.

I can tell you that this isn't followed consistently at all and we should do a follow up.  I think that's a big enough work item on it's own.  I'll file a crbug.


> +    bool selected = true;
> +    for (int j = 0; j < rows && selected == true; ++j) {
> 
> No need to say "== true".
> I think you don't need to check selected. You could use break in the loop.

Yes, this does make it explicit and clear.

> 
> +      auto* cell = GetTableCell(j, i);
> +      if (!cell || !(cell->GetData().state & (1 << ui::AX_STATE_SELECTED)))
> 
> Isn't there a HasState method? If so, use throughout.

Done.

> +HRESULT AXPlatformNodeWin::AllocateSelectedResults(std::vector<long>& results,
> +                                                   long max,
> +                                                   long** selected,
> +                                                   long* n_selected) {
> +  auto count = std::min((long)results.size(), max);
> +  *n_selected = count;
> +  *selected = static_cast<long*>(CoTaskMemAlloc(sizeof(long) * count));
> 
> 
> Could we give a more generic name to this method?

Happy to take suggestions, but I am bad with naming.  It's not public and I moved it to the bottom of the file to make sure that that people don't try to use it.

> What if count becomes minus or zero either because the vector is empty or max is negative or zero?

This is prechecked before the call (max > 0).

> Should we add a DCHECK for *selected to make sure it's really allocated before writing to it?

I didn't this this allocator could fail without the world being doomed?

> I thought there were some methods that required the actual objects to be returned instead of their indices.

get_cellAt() and get_selectedCells() do return IUknowns, but those are not implemented in this CL.

> +  if (!children || !n_children || max_children >= LONG_MAX || max_children <= 0)
> 
> Is max_children == 0 really an invalid value according to IA2 Spec? Most likely, but could you check?

As you know, the spec for these APIs is less than desirable. http://accessibility.linuxfoundation.org/a11yspecs/ia2/docs/html/interface_i_accessible_table.html#a41743ec3a786776ebb1c227d3bac7859

Does not define what max_children does.  E_INVALIDARG for now?


> How could max_children be greater than LONG_MAX if by definition it's a long?
> Anyway, as I said LONG in Win is an int.

Follow up; Yup.

Patch-set: 2
Reviewer: Doug Turner <1214309@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>