Update patch set 1
Patch Set 1: Code-Review+1

Steven,
The given command
   roll-dep src/third_party/chromite chromiumos/chromite.git
is no longer working.  It's giving me the error
   error: Directory not found: chromiumos/chromite.git (/ssd/chrome/chromiumos/chromite.git)
On Achuith's advice, I removed the second arg (chromiumos/chromite.git), and it seems to have worked fine.  Are you familiar with this change?  Do you know if it's permanent?  If so, we should update the instructions in
  https://yaqs.googleplex.com/eng/q/5529020734636032 and
  crbug.com/762650

Patch-set: 1
Reviewer: Steven Bennetts <1000191@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Greg Levin <1113104@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Code-Review=+1
Work-in-progress: false