[ios] Use square brackets syntax for nulling out toJSON property.
Closure reports an error for the old code:

../../ios/web/web_state/js/resources/common.js:40: ERROR - assignment to
property toJSON of __gCrWeb.common.JSONSafeObject.prototype
found   : null
required: function (this:Object, string=): *
  __gCrWeb.common.JSONSafeObject.prototype.toJSON = null;
  ^

BUG=None

Review-Url: https://codereview.chromium.org/2475643003