Update patch set 9
Patch Set 9:

This is causing compile failure for MSVC:

c:\b\c\b\win\src\third_party\webkit\source\platform\heap\heappage.cpp(799) : error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win\src\third_party\webkit\source\platform\heap\heappage.cpp(799) : warning C4702: unreachable code

Might be good thing to fix anyway. Going to revert

Patch-set: 9
CC: Samuel Huang <1001928@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>