Revert "Media Engagement: Add DAFSA generator and reader"
This reverts commit 8812513406603d77fa69083eccc96326d9744ed8.

Reason for revert: Breaks the Windows build

This breaks the Windows build (in some situation), https://chromium-review.googlesource.com/c/chromium/src/+/810787 fix some issue but it's not sufficient, e.g. https://ci.chromium.org/buildbot/tryserver.chromium.win/win7_chromium_rel_ng/60438 failed with the following stack trace:
FAILED: gen/chrome/test/data/media/engagement/preload/test.pb 
C:/b/depot_tools/win_tools-2_7_6_bin/python/bin/python.exe ../../tools/media_engagement_preload/make_dafsa.py ../../chrome/test/data/media/engagement/preload/test.json gen/chrome/test/data/media/engagement/preload/test.pb
Traceback (most recent call last):
  File "../../tools/media_engagement_preload/make_dafsa.py", line 17, in <module>
    import media_engagement_preload_pb2
  File "C:\b\c\b\win\src\tools\media_engagement_preload\media_engagement_preload_pb2.py", line 8, in <module>
    from google.protobuf import descriptor as _descriptor
  File "C:\b\c\b\win\src\third_party\protobuf\python\google\protobuf\descriptor.py", line 37, in <module>
    import six
ImportError: No module named six

Original change's description:
> Media Engagement: Add DAFSA generator and reader
> 
> Add a tool to generate preload data in DAFSA format and
> add a MediaEngagementPreloadedList class to read it.
> 
> BUG=787464
> 
> TBR=dpranke@chromium.org
> 
> Change-Id: If0d99a2e1091d0b23699f2173d8146582173ee54
> Reviewed-on: https://chromium-review.googlesource.com/803994
> Commit-Queue: Becca Hughes <beccahughes@chromium.org>
> Reviewed-by: Dale Curtis <dalecurtis@chromium.org>
> Reviewed-by: Mounir Lamouri <mlamouri@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#522068}

TBR=dalecurtis@chromium.org,mlamouri@chromium.org,beccahughes@chromium.org

Change-Id: I1b5bbaf0dc435a28905bfdaf15142115e8636d2e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 787464