Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Please use the following command for this (which will include the list of changes):
> > 
> >  roll-dep src/third_party/chromite chromiumos/chromite.git
> > 
> > +This week's gardener
> Hi,
> 
> On top of tree running 'roll-dep', it shows me:
> Warning: src/third_party/chromite is not checked out at the expected revision in DEPS
> error: Expected to find commit 84f9b9637ce29b0351c847a793c41d27cddb1ae4 for chromiumos/chromite.git in DEPS
> 
> After I update DEPS according to the error message(commit locally or not), it shows me:
> error: Ensure /usr/local/google/home/xiaochu/chromium/src is clean first (no non-merged commits).
> 
> Is there a procedure somewhere I can follow?

You need to be on ToT and have run gclient sync. It might be confused because ToT DEPS references the old commit, but you may have the new commit checked out in src/third_party/chromite/src.

In third_party/chromite/src, you should be at edcefea34e6071e9fdd673a9e0932932453df515 (as shown in DEPS on ToT). If necessary, do a `git reset --hard edcefea3` in src/third_party/chromite/src.

Patch-set: 1
Reviewer: Michael Giuffrida <1003321@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>