closure: fix compiler error via downcasting.
(ERROR) Error in: help.js
## /mnt/data/b/build/slave/Closure_Compilation_Linux/build/src/chrome/browser/resources/chromeos/user_images_grid.js:128: ERROR - as
## found   : function (new:cr.ui.ListItem, (Object|null)): ?
## required: function (new:cr.ui.ListItem, *): ?
##       this.itemConstructor =
##       ^

TBR=arv@chromium.org
BUG=393873

Review URL: https://codereview.chromium.org/653283002