Update patch set 1
Patch Set 1:

PTAL

The linker error is:
FAILED: video_capture.service exe.unstripped/video_capture.service 
../../third_party/android_ndk/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mipsel-linux-android/4.9.x/../../../../mipsel-linux-android/bin/ld: warning: libjnigraphics.so, needed by ./libgfx.cr.so, not found (try using -rpath or -rpath-link)
../../third_party/android_ndk/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mipsel-linux-android/4.9.x/../../../../mipsel-linux-android/bin/ld: warning: libandroid.so, needed by ./libgpu.cr.so, not found (try using -rpath or -rpath-link)
./libgfx.cr.so: undefined reference to `AndroidBitmap_lockPixels'
./libgl_wrapper.cr.so: undefined reference to `ANativeWindow_release'
./libgfx.cr.so: undefined reference to `AndroidBitmap_unlockPixels'
./libgfx.cr.so: undefined reference to `AndroidBitmap_getInfo'
./libgl_wrapper.cr.so: undefined reference to `ANativeWindow_fromSurface'
./libgpu.cr.so: undefined reference to `ANativeWindow_acquire'

as per our public buildbot [1] and Chromium's MIPS Android debug builder [2]

Similar is done in [3] but that doesn't add any path to rpath-link since
build/linux/sysroot_ld_path.sh returns empty list due to Android sysroot
not having etc/ld.so.conf nor etc/ld.so.conf.d/*.conf.

[1] http://www.rt-rk.com/mips-buildbot/builders/Debug_build/builds/1456/steps/Build/logs/stdio
[2] https://ci.chromium.org/buildbot/tryserver.chromium.android/android_compile_mips_dbg/107
[3] https://chromium-review.googlesource.com/c/chromium/src/+/834609/4/build/config/posix/BUILD.gn#99

Patch-set: 1
Reviewer: Brian Sheedy <1163549@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Scott Graham <1144260@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
CC: Petar Jovanovic <1002356@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gordana Cmiljanovic <1117686@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false