Update patch set 4
Patch Set 4:

It appears that proguard is upset because it doesn't know about the O symbols yet. Should I go back to using reflection? Or are we planning to fix this?

//android_webview:system_webview_apk__proguard(//build/toolchain/android:android_clang_arm64)

Warning: org.chromium.ui.base.WindowAndroid:
    can't find referenced method 'boolean isScreenWideColorGamut()'
    in library class android.content.res.Configuration
Warning: org.chromium.ui.display.PhysicalDisplayAndroid:
    can't find referenced method 'boolean isWideColorGamut()'
    in library class android.view.Display
Warning: there were 2 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Error: Please correct the above warnings first.

Patch-set: 4
Reviewer: ccameron chromium <1002358@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0