Update patch set 6
Patch Set 6:

tapted@ can you take a look?

This fails to compile in:

../../chrome/browser/ui/cocoa/tab_dialogs_views_mac.mm:82:48: error: no matching constructor for initialization of 'ManagePasswordsBubbleView'

Do you think we could replace this code with call(s) to ManagePasswordsBubbleView::ShowBubble instead of having almost-duplicate code, or is the NSWindow usage really necessary?

It also fails in test(s) which I'll take care of.

Patch-set: 6
Reviewer: Trent Apted <1002092@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Peter Boström <1126912@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0