Revert of [Android] Remove adb_commands from telemetry. (patchset #13 id:240001 of https://codereview.chromium.org/1141833003/)
Reason for revert:
On 2015/06/03 at 03:23:53, commit-bot wrote:
> Patchset 13 (id:??) landed as https://crrev.com/c951c9e158d55d2be18f8226200679aee55f336d
> Cr-Commit-Position: refs/heads/master@{#332538}

This change breaks --browser=list when non-rooted Android devices are attached.

$ tools/perf/run_benchmark --browser=list
ERROR:root:Fail to create platform instance for Android device 04f120591b9223e1.

Traceback (most recent call last):
  <module> at tools/perf/run_benchmark:20
    sys.exit(benchmark_runner.main(config))
  main at tools/telemetry/telemetry/benchmark_runner.py:433
    options, args = parser.parse_args()
  ParseArgs at tools/telemetry/telemetry/core/browser_options.py:179
    device)
  Cacher at tools/telemetry/telemetry/decorators.py:30
    cacher.__cache[key] = obj(*args, **kwargs)
  GetAllAvailableBrowsers at tools/telemetry/telemetry/core/browser_finder.py:147
    browser_finder.FindAllAvailableBrowsers(options, device))
  FindAllAvailableBrowsers at tools/telemetry/telemetry/core/backends/chrome/android_browser_finder.py:217
    android_platform = platform.GetPlatformForDevice(device, finder_options)
  GetPlatformForDevice at tools/telemetry/telemetry/core/platform/__init__.py:58
    finder_options))
  CreatePlatformForDevice at tools/telemetry/telemetry/core/platform/android_platform_backend.py:186
    platform_backend = AndroidPlatformBackend(device, finder_options)
  __init__ at tools/telemetry/telemetry/core/platform/android_platform_backend.py:148
    self._device.EnableRoot()
  TimeoutRetryWrapper at build/android/pylib/device/decorators.py:57
    return timeout_retry.Run(impl, timeout, retries)
  Run at build/android/pylib/utils/timeout_retry.py:161
    thread_group.JoinAll(child_thread.GetWatcher())
  JoinAll at build/android/pylib/utils/reraiser_thread.py:143
    self._JoinAll(watcher)
  _JoinAll at build/android/pylib/utils/reraiser_thread.py:130
    thread.ReraiseIfException()
  run at build/android/pylib/utils/reraiser_thread.py:76
    self._ret = self._func(*self._args, **self._kwargs)
  RunOnTimeoutThread at build/android/pylib/utils/timeout_retry.py:150
    ret[0] = func(*args, **kwargs)
  impl at build/android/pylib/device/decorators.py:51
    return f(*args, **kwargs)
  EnableRoot at build/android/pylib/device/device_utils.py:289
    'Cannot enable root in user builds.', str(self))
CommandFailedError: (device: 04f120591b9223e1) Cannot enable root in user builds.

Locals:
  retries : 3
  timeout : 30

Original issue's description:
> [Android] Remove adb_commands from telemetry.
>
> ...because it's an abomination.
>
> BUG=476709
>
> Committed: https://crrev.com/c951c9e158d55d2be18f8226200679aee55f336d
> Cr-Commit-Position: refs/heads/master@{#332538}

TBR=dtu@chromium.org,nednguyen@google.com,primiano@chromium.org,skyostil@chromium.org,sullivan@chromium.org,picksi@chromium.org,zhenw@chromium.org,jbudorick@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=476709

Review URL: https://codereview.chromium.org/1145153005