Revert of Revert "Revert of Implement GetDisplayed on android M+ (patchset #3 id:60001 of https://codereview.… (patchset #1 id:1 of https://codereview.chromium.org/2585823002/ )
Reason for revert:
org.chromium.chrome.browser.push_messaging.PushMessagingTest#testDefaultNotification
is still failing consistently on the Marshmallow bots:

https://test-results.appspot.com/dashboards/flakiness_dashboard.html#testType=chrome_public_test_apk&tests=org.chromium.chrome.browser.push_messaging.PushMessagingTest

Example log:
https://build.chromium.org/p/chromium.android/builders/Marshmallow%2064%20bit%20Tester/builds/7408

org.chromium.chrome.browser.push_messaging.PushMessagingTest#testDefaultNotification (run #1):
junit.framework.AssertionFailedError: expected:<1> but was:<2>
	at org.chromium.chrome.browser.notifications.NotificationTestBase.waitForNotification(NotificationTestBase.java:107)
	at org.chromium.chrome.browser.push_messaging.PushMessagingTest.testDefaultNotification(PushMessagingTest.java:246)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
	at org.chromium.chrome.test.ChromeActivityTestCaseBase.runTest(ChromeActivityTestCaseBase.java:752)
	at org.chromium.base.test.BaseTestResult.runParameterized(BaseTestResult.java:161)
	at org.chromium.base.test.BaseTestResult.run(BaseTestResult.java:124)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)

Original issue's description:
> Revert "Revert of Implement GetDisplayed on android M+ (patchset #3 id:60001 of https://codereview.chromium.org/2536313003/ )"
>
> This reverts commit 06b647e40c84fb6d13e09b13eabfa201b0aa6a32.
>
> It also includes an extra null check in case no active notifications are
> returned.
>
> TBR=peter,avi
>
> BUG=
>
> Committed: https://crrev.com/ef0ab6b078544507d8ae76371bc962095858554d
> Cr-Commit-Position: refs/heads/master@{#439278}

TBR=avi@chromium.org,peter@rybin.spb.ru,miguelg@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=

Review-Url: https://codereview.chromium.org/2589333002