Update patch set 2
Patch Set 2:

Looks like you need to rebase.

First, rewinding head to replay your work on top of it...
Applying: Revert "Revert "Enable GPU sandboxing for AMD platform""
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
M	content/common/BUILD.gn
M	content/common/sandbox_linux/sandbox_seccomp_bpf_linux.cc
Falling back to patching base and 3-way merge...
Auto-merging content/common/sandbox_linux/sandbox_seccomp_bpf_linux.cc
CONFLICT (content): Merge conflict in content/common/sandbox_linux/sandbox_seccomp_bpf_linux.cc
Auto-merging content/common/BUILD.gn
Patch failed at 0001 Revert "Revert "Enable GPU sandboxing for AMD platform""

Patch-set: 2
Reviewer: Justin TerAvest <1115020@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0