Revert "Catch PlatformSensor::StartSensor failure in Windows tests"
This reverts commit 2379e90cc1c6eea76dd871511d3affe7536803fd.

Reason for revert: PlatformSensor tests are failing on Windows after this change.

First failing build: https://build.chromium.org/p/chromium.win/builders/Win10%20Tests%20x64%20%28GCE%29/builds/47

Sample failure output:
[ RUN      ] PlatformSensorAndProviderTestWin.SensorStateChangedToReady
../../services/device/generic_sensor/platform_sensor_and_provider_unittest_win.cc(530): error: Value of: StartListening(sensor, client.get(), configuration)
  Actual: false
Expected: true
[  FAILED  ] PlatformSensorAndProviderTestWin.SensorStateChangedToReady (5 ms)

Original change's description:
> Catch PlatformSensor::StartSensor failure in Windows tests
> 
> This patch fixes a timeout in the PlatformSensorAndProviderTestWin tests
> where if PlatformSensor::StartSensors fails the tests will still wait
> until SetEventSink is called on the mock ISensor. This does not fix
> issue 756986 but turns a timeout into a proper test failure.
> 
> Bug: 756986
> Change-Id: I003023a87de24da3b85c56474f6ae1d96e3db2a9
> Reviewed-on: https://chromium-review.googlesource.com/658070
> Reviewed-by: Jun Cai <juncai@chromium.org>
> Commit-Queue: Reilly Grant <reillyg@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#500733}

TBR=reillyg@chromium.org,juncai@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 756986
Change-Id: I13134cac7757d598c9f3e50fd198f5915ec7a3d0