Add OS type checking to process_json.py
File adding a workaround to a GPU driver bug the os type "win" was
misspelled as "windows". This caused a one-week delay in testing the
workaround. This adds an OS type check to avoid this error in the
future. It was confirmed that this check would have detected and
prevented the recent error, with this error message:

    Exception: Unknown OS type "windows" for entry 248

Bug: 775898,785648
Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
Change-Id: Idd1a4266087acbae24cfc6e60ac873f17c7ac7ef