Fix ChromeVox api re-injection on re-load
When toggling ChromeVox, api injection gets blocked due to stricter same
origin policies since this code was written:

Error: Blocked script execution in
'https://docs.google.com/document/d/1WKvVF1Qu7LrJjAsop0HrmhgTvq3ZNI2IiBvPrThIpRU/edit'
because the document's frame is sandboxed and the 'allow-scripts'
permission is not set.  From
https://docs.google.com/document/d/1WKvVF1Qu7LrJjAsop0HrmhgTvq3ZNI2IiBvPrThIpRU/edit

This makes a fix by removing the previous script node.

Test: toggle ChromeVox off/on repeatedly. Verify Docs with braille mode
off keeps on working.
Bug:
Cq-Include-Trybots: master.tryserver.chromium.linux:closure_compilation
Change-Id: Ibcc5e66d070d658a41ce7b5f7176bf3b67d7cfec