Update patch set 6
Patch Set 6:

seems missing somethiong (builded with bundled clang)

FAILED: obj/components/machine_intelligence/machine_intelligence/generic_logistic_regression_inference.o 
/tmp/makepkg/chromium-dev/src/chromium-64.0.3251.0/third_party/llvm-build/Release+Asserts/bin/clang++  -MMD -MF obj/components/machine_intelligence/machine_intelligence/generic_logistic_regression_inference.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -DCR_CLANG_REVISION=\"315613-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -I../.. -Igen -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -Igen/shim_headers/zlib_shim -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/protobuf/src -I../../third_party/boringssl/src/include -I/usr/include/nss -I/usr/include/nspr -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pipe -pthread -fcolor-diagnostics -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -m64 -march=x86-64 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -Wno-enum-compare-switch -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-tautological-unsigned-enum-zero-compare -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-header-guard -std=gnu++14 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fstack-protector-strong  -Wno-unknown-warning-option -c ../../components/machine_intelligence/generic_logistic_regression_inference.cc -o obj/components/machine_intelligence/machine_intelligence/generic_logistic_regression_inference.o
../../components/machine_intelligence/generic_logistic_regression_inference.cc:15:25: error: use of undeclared identifier 'exp'
  return 1.0f / (1.0f + exp(-x));
                        ^
1 error generated.

Patch-set: 6
CC: Gustavo Alvarez <1128049@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>