Revert of ScreenCapture for Android phase1, part I (patchset #12 id:340001 of https://codereview.chromium.org/1917023003/ )
Reason for revert:
Break compile step on Android

Builder logs:
https://build.chromium.org/p/chromium/builders/Android/builds/58512/steps/compile/logs/stdio

Failure:
In file included from ../../media/capture/content/thread_safe_capture_oracle.h:15:0,
                 from ../../media/capture/content/screen_capture_device_core.h:15,
                 from ../../media/capture/content/android/screen_capture_machine_android.h:12,
                 from ../../media/capture/content/android/screen_capture_jni_registrar.cc:10:
../../media/capture/video/video_capture_device.h:33:55: fatal error: media/mojo/interfaces/image_capture.mojom.h: No such file or directory
 #include "media/mojo/interfaces/image_capture.mojom.h"

Original issue's description:
> ScreenCapture for Android phase1, part I
>
> The document about ScreenCapture for Android is here, https://goo.gl/QNH29g.
> This cl is mainly based on the https://codereview.chromium.org/1140113002/.
> Only the codes under media/ are included here, which implements the JAVA
> capture with Android MediaProjection API and JNI connectors, with some issues
> fixed so it can always work.
> The control part in content/ and chrome/ will be in the next cl, as part II.
>
> BUG=487935
>
> Committed: https://crrev.com/2f731e17983201082d9fc725cf7717868fc1e75d
> Cr-Commit-Position: refs/heads/master@{#403555}

TBR=dalecurtis@chromium.org,mcasas@chromium.org,michaelbai@chromium.org,miu@chromium.org,qinmin@chromium.org,sergeyu@chromium.org,tedchoc@chromium.org,braveyao@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=487935

Review-Url: https://codereview.chromium.org/2116883002