sandbox: Add missing 'base' namespace qualifier to MD5DigestToBase16 call.
I found this while doing https://codereview.chromium.org/1099453002/.

Log file:
http://build.chromium.org/p/tryserver.chromium.linux/builders/linux_chromium_rel_ng/builds/55588/steps/compile%20%28with%20patch%29/logs/stdio

Error:
../../sandbox/linux/bpf_dsl/codegen_unittest.cc:65:12: error: use of
undeclared identifier 'MD5DigestToBase16'; did you mean
'base::MD5DigestToBase16'?
    return MD5DigestToBase16(digest_);
               ^~~~~~~~~~~~~~~~~
base::MD5DigestToBase16 ../../base/md5.h:64:25: note: 'base::MD5DigestToBase16' declared here
BASE_EXPORT std::string MD5DigestToBase16(const MD5Digest& digest);
                        ^
1 error generated.

BUG=None
TEST=trybots
R=mdempsky@chromium.org

Review URL: https://codereview.chromium.org/1055933010