Update patch set 1
Patch Set 1:

compiler doesn't like it

Exception: [OriginTrialEnabled] and [RuntimeEnabled] must not be specified on the same definition: MediaCapabilities

Maybe you need to update the runtime_enabled_features.json5, and that defines the flag?
https://chromium.googlesource.com/chromium/src/+/master/docs/origin_trials_integration.md

Patch-set: 1
Reviewer: Chrome Cunningham <1129179@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>