Update patch set 16
Patch Set 16:

This was reverted for causing the following compile failures on the linux builders.

../../content/common/sandbox_linux/bpf_cros_amd_gpu_policy_linux.cc:122:10: error: use of undeclared identifier '__NR_socket'
    case __NR_socket:
         ^
../../content/common/sandbox_linux/bpf_cros_amd_gpu_policy_linux.cc:123:10: error: use of undeclared identifier '__NR_socketpair'; did you mean 'socketpair'?
    case __NR_socketpair: {
         ^~~~~~~~~~~~~~~
         socketpair
../../build/linux/debian_jessie_i386-sysroot/usr/include/i386-linux-gnu/sys/socket.h:119:12: note: 'socketpair' declared here
extern int socketpair (int __domain, int __type, int __protocol,
           ^
../../content/common/sandbox_linux/bpf_cros_amd_gpu_policy_linux.cc:123:10: error: value of type 'int (int, int, int, int *) throw()' is not implicitly convertible to 'int'
    case __NR_socketpair: {
         ^~~~~~~~~~~~~~~
3 errors generated.

Patch-set: 16
CC: Roger McFarlane <1002376@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>