Revert of Added bluetooth LE support on Mac platform (patchset #13 id:340001 of https://codereview.chromium.org/791763005/)
Reason for revert:
Breaks compile:
http://build.chromium.org/p/chromium.mac/builders/Mac%20Builder/builds/17750

../../device/bluetooth/bluetooth_low_energy_discovery_manager_mac.mm:119:30: error: class method '+UUIDWithString:' not found (return type defaults to 'id') [-Werror,-Wobjc-method-access]
      CBUUID* uuid = [CBUUID UUIDWithString:uuidString];
                             ^~~~~~~~~~~~~~

../../device/bluetooth/bluetooth_low_energy_device_mac.mm:82:39: error: use of undeclared identifier 'CBAdvertisementDataIsConnectable'
      [advertisementData objectForKey:CBAdvertisementDataIsConnectable];
                                      ^
../../device/bluetooth/bluetooth_low_energy_device_mac.mm:85:39: error: use of undeclared identifier 'CBAdvertisementDataServiceDataKey'
      [advertisementData objectForKey:CBAdvertisementDataServiceDataKey];
                                      ^
2 errors generated.

Original issue's description:
> Added bluetooth LE support on Mac platform
>
> BUG=449682
>
> Committed: https://crrev.com/42f79f8b08a99190627f3a67e86a378987104a4a
> Cr-Commit-Position: refs/heads/master@{#315190}

TBR=armansito@chromium.org,avi@chromium.org,groby@chromium.org,dvh@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=449682

Review URL: https://codereview.chromium.org/871843009