Revert "Don't cache suggestion or download thumbnails on low-memory devices."
This reverts commit 78ff44b8ab5faa97295d76468f99bd1457d3dcca.

Reason for revert: Suspect change braking tablet testers:
https://uberchromegw.corp.google.com/i/chromium.android/builders/KitKat%20Tablet%20Tester

TileGridLayoutTest#testNumColumnsCalculatedEqualToMeasurement:
java.lang.AssertionError: The calculated number of columns should be equal to the minimum number of columns across screen orientations. expected:<6> but was:<5>

Will reland if bots are not fixed.

Original change's description:
> Don't cache suggestion or download thumbnails on low-memory devices.
> 
> Bug: 718925
> Change-Id: Ie11a88d9864bf6e4a4e85f7dc15c4e4e01bb00fe
> Reviewed-on: https://chromium-review.googlesource.com/574856
> Reviewed-by: Maria Khomenko <mariakhomenko@chromium.org>
> Reviewed-by: Theresa <twellington@chromium.org>
> Commit-Queue: Bernhard Bauer <bauerb@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#488639}

TBR=bauerb@chromium.org,mariakhomenko@chromium.org,twellington@chromium.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 718925
Change-Id: I281ef5ea1430dac383eaaf11a63ce34db8ab45ab