Revert "Unship frames() animation timing function"
This reverts commit f4fc014f1342eba26b8febacb518247f0207a712.

Reason for revert: Causing build failure:

../../third_party/WebKit/Source/platform/animation/TimingFunction.h:219:12: error: 'FramesTimingFunctionEnabled' is not a member of 'blink::RuntimeEnabledFeatures'
     DCHECK(RuntimeEnabledFeatures::FramesTimingFunctionEnabled());
            ^

https://uberchromegw.corp.google.com/i/official.android.continuous/builders/beta-arm/builds/8762/steps/Build%20libchrome.so/logs/stdio

BUG=646265

Original change's description:
> Unship frames() animation timing function
> 
> This patch unships the frames() animation timing function due to
> unresolved issues over the naming.
> 
> No intent is required as the timing function has not reached the
> stable channel of Chrome yet.
> 
> Ongoing spec discussion:
> https://github.com/w3c/csswg-drafts/issues/1301
> 
> TBR=alancutter@chromium.org
> 
> (cherry picked from commit ffcd346677e9dd28037da9619c510274d9318bfe)
> 
> Bug: 646265
> Change-Id: Ice19051813a96eaa55229e46ef6630a75333b5b8
> Reviewed-on: https://chromium-review.googlesource.com/552218
> Commit-Queue: Alan Cutter <alancutter@chromium.org>
> Reviewed-by: Suzy Howlett <suzyh@chromium.org>
> Reviewed-by: Noel Gordon <noel@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#483584}
> Reviewed-on: https://chromium-review.googlesource.com/574988
> Reviewed-by: Alan Cutter <alancutter@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3112@{#628}
> Cr-Branched-From: b6460e24cf59f429d69de255538d0fc7a425ccf9-refs/heads/master@{#474897}

TBR=noel@chromium.org,alancutter@chromium.org,suzyh@chromium.org

Change-Id: I85ff5ade3dbc64c82fda8f0271d617ab4f744f22
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 646265