Raise an exception when the wpr_archive_info isn't created.
This is to provide a more user friendly error. This:

  AssertionError: Pageset archive_data_file path must be specified.

instead of this:

  AttributeError: 'NoneType' object has no attribute 'AddNewTemporaryRecording'

BUG=

Review URL: https://codereview.chromium.org/660143002