Revert "Add timestamp to requests for experimental contextual suggestions."
This reverts commit e76e0e99dc3b8b2b7ad502603331ea7104745a1a.

Reason for revert: 

This breaks MSVC build in webrtc.
https://logs.chromium.org/v/?s=chromium%2Fbb%2Ftryserver.chromium.win%2Fwin-msvc-dbg%2F6610%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout
e:\b\c\b\win\src\chrome\browser\autocomplete\chrome_autocomplete_provider_client.cc(249) : error C2220: warning treated as error - no 'object' file generated
e:\b\c\b\win\src\chrome\browser\autocomplete\chrome_autocomplete_provider_client.cc(249) : warning C4702: unreachable code

Original change's description:
> Add timestamp to requests for experimental contextual suggestions.
> 
> The experimental contextual suggestions service provides 0-suggest
> autocomplete suggestions based on the URL that is visited in the active
> tab, at the time the address bar is focused. This CL adds to the request
> a timestamp corresponding to the time the user started navigating the
> URL for which the suggestions are requested.
> 
> This change is a requirement for the process of enabling server-side
> logging of the contextual suggestions that are sent to Chrome clients.
> If logged, contextual suggestions are to be removed as soon as a
> synced user removes from their history the page that was visited at the
> time the suggestions were displayed. The timestamp is necessary for
> matching suggestions with the corresponding navigation.
> 
> TBR=rohitrao
> for mechanical changes to ios/c/b/a/*
> 
> Bug: 692471
> Change-Id: I6939d108cfab91b69640acdbb3b8307687999320
> Reviewed-on: https://chromium-review.googlesource.com/879167
> Commit-Queue: Gheorghe Comanici <gcomanici@chromium.org>
> Reviewed-by: Mark Pearson <mpearson@chromium.org>
> Reviewed-by: Rohit Rao <rohitrao@chromium.org>
> Reviewed-by: Justin Donnelly <jdonnelly@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#531999}

TBR=rohitrao@chromium.org,mpearson@chromium.org,jdonnelly@chromium.org,gcomanici@chromium.org

Change-Id: I49b16be6ba23baf3fe4cfb26bb8980d6164f646a
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 692471