Update patch set 5
Patch Set 5:

> The only risk of loss due to narrowing to the bit field width would be when we initialize these structs. Fortunately, clang has a warning (-Wbitfield-constant-conversion) for this case when a constant is used to initialize, as it is by our generated code. Build failure looks like this:
> 
> gen/blink/bindings/core/v8/V8Window.cpp:9152:80: error: implicit truncation from 'blink::V8PrivateProperty::CachedAccessorSymbol' to bit-field changes value from 2 to 0 [-Werror,-Wbitfield-constant-conversion]
>     { "document", V8Window::documentAttributeGetterCallback, nullptr, nullptr, V8PrivateProperty::kWindowDocumentCachedAccessor, static_cast<v8::PropertyAttribute>(v8::DontDelete | v8::ReadOnly), V8DOMConfiguration::kOnInstance, V8DOMConfiguration::kCheckHolder, V8DOMConfiguration::kAllWorlds },
> 
> For this reason I am comfortable making the bitfield just as large as we need now, and adding bits as we need them in the future.

I simply didn't know this warning, and I'm super happy with this.  Now I understand that we don't need to worry about this.  Thanks for the detailed explanation.

Patch-set: 5