Revert "Surface synchronization: Allocate new id when ScreenInfo changes"
This reverts commit 33c9f078c32cf1e07bb56204ae0274952a5b9492.

Reason for revert: Broke RenderWidgetHostViewAuraTest.AutoResizeWithScale on webrtc Win7 tester:
https://build.chromium.org/deprecated/chromium.webrtc/builders/Win7%20Tester/builds/39819

 RUN      ] RenderWidgetHostViewAuraTest.AutoResizeWithScale
../../content/browser/renderer_host/render_widget_host_view_aura_unittest.cc(2325): error: Expected equality of these values:
  1u
    Which is: 1
  sink_->message_count()
    Which is: 2
[  FAILED  ] RenderWidgetHostViewAuraTest.AutoResizeWithScale (4 ms)
[5671/5671] RenderWidgetHostViewAuraTest.AutoResizeWithScale (4 ms)
1 test failed:
    RenderWidgetHostViewAuraTest.AutoResizeWithScale (../../content/browser/renderer_host/render_widget_host_view_aura_unittest.cc:2290)
Tests took 58 seconds.

Original change's description:
> Surface synchronization: Allocate new id when ScreenInfo changes
> 
> RenderWidgetHostViewAura::UpdateScreenInfo only calls
> window_->AllocateLocalSurfaceId() in auto-resize mode. We want
> ScreenInfo to be synchronized across clients independent of whether
> auto-resize is on or not. This CL fixes crbug.com/791154, in
> which the renderer crashes because it doesn't receive a new
> LocalSurfaceId when device scale factor changes.
> 
> Bug: 672962,791154
> Change-Id: If9c3836aee980a31e8d50159f6491b52bf812a6d
> Reviewed-on: https://chromium-review.googlesource.com/836820
> Reviewed-by: Antoine Labour <piman@chromium.org>
> Commit-Queue: Saman Sami <samans@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#525557}

TBR=piman@chromium.org,samans@chromium.org

Change-Id: Ibbc55040ed21f6100af69699e665eed435561dc1
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 672962, 791154