Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > I'm a bit confused by this CL. Isn't the eventual plan to remove the prefixed versions anyway? Why would we point them at the thing that will be removed in the deprecation message?
> > 
> > Currently, on Canary and on Stable, you can run
> > videoelement.webkitEnterFullscreen()
> > 
> > and it works, but it also gives you a deprecation message saying to use requestFullscreen() instead. Then when you try to use requestFullscreen it gives you an error "Uncaught TypeError: video.requestFullscreen is not a function".
> > 
> > So the point is just that if we're going to have a flag that determines what functions are available, then we should also have that flag determine what function we recommend the developer using in the deprecation message. In this way, we don't tell the developer to use a function that doesn't exist.
> 
> The bug also explains in detail :)

I'll defer to foolip for this one. But it looks like the work to unprefix fullscreen is in progress: https://bugs.chromium.org/p/chromium/issues/detail?id=383813, though I don't know what the timeline for exposing the unprefixed version to the web is.

My point is it would feel kind of silly to point developers at Element.wekbitEnterFullscreen--only to say in two months that that's been deprecated in favor of Element.enterFullscreen.

Also it seems like this bug affects basically all the fullscreen properties, so it's not just enterFullscreen / exitFullscreen: see the IDL files in https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/fullscreen/

Patch-set: 3
Reviewer: Daniel Cheng <1001168@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>