Fix errors caused by illegal #define of snprintf.
Because VS has, for a long time, not had snprintf some developers have
fixed this with #define snprintf _snprintf. This is scary because the
two functions behave differently, and it also breaks with VS 2015 which
does implement snprintf. So, the #defines all need a version check.

The errors are:

stdio.h(1926): warning C4005: 'snprintf': macro redefinition
libxml\win32\config.h(98): note: see previous definition of 'snprintf'
libxml\src\include\win32config.h(98): note: see previous def of 'snprintf'
stdio.h(1929): fatal error C1189: #error:  Macro definition of snprintf
conflicts with Standard Library function declaration

R=cpu@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1072653003