Revert of Make CSSComputedStyledeclaration::getPropertyCSSValue return const (patchset #3 id:40001 of https://codereview.chromium.org/2034013002/ )
Reason for revert:
"""
../../third_party/WebKit/Source/core/css/cssom/ComputedStylePropertyMap.cpp:14:15: error: cannot initialize a variable of type 'blink::CSSValue *' with an rvalue of type 'const blink::CSSValue *'
    CSSValue* cssValue = m_computedStyleDeclaration->getPropertyCSSValueInternal(propertyID);
"""

https://build.chromium.org/p/chromium.memory.fyi/builders/Chromium%20Linux%20TSan%20Builder/builds/23734/steps/compile/logs/stdio

Original issue's description:
> Make CSSComputedStyledeclaration::getPropertyCSSValue return const
>
> Make CSSComputedStyledeclaration::getPropertyCSSValue() return a const
> CSSValue* instead of a regular CSSValue*. This required changing
> CSSStyleDeclaration::getPropertyCSSValueInternal() return a const
> CSSValue* as well, and marking CSSValueList::copy() as a const method
> (which it already was, it was just missing the const modifier). This is
> pre-work for making CSSValueList store const CSSValues.
>
> This patch is mostly mechanical changes, but does contain one logic
> change: the static method mergeTextDecorationValues in EditingStyle
> needs to be changed since it modifies a CSSValueList that points inside
> the mutable style. Instead, the function is changed to take two
> CSSValueLists and return a new one, and the callsite is changed to
> replace the old CSSValueList with the new one in the style rather than
> modifying the old CSSValueList in-place.
>
> BUG=526586
>
> Committed: https://crrev.com/5896ec297d9240b691e7f70a239498b795531dc1
> Cr-Commit-Position: refs/heads/master@{#398151}

TBR=haraken@chromium.org,timloh@chromium.org,yukishiino@chromium.org,sashab@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=526586

Review-Url: https://codereview.chromium.org/2042113002