Revert of Quic: add unittests for reduced PING Timeout (patchset #2 id:20001 of https://codereview.chromium.org/2307933003/ )
Reason for revert:
Broke cronet compile:
https://build.chromium.org/p/chromium.android/builders/Android%20Cronet%20Lollipop%20Builder/builds/1164

../../net/quic/core/quic_connection_test.cc:2980:8: error: redefinition of 'class net::test::{anonymous}::QuicConnectionTest_ReducedPingTimeout_Test'
 TEST_P(QuicConnectionTest, ReducedPingTimeout) {
        ^
../../testing/gtest/include/gtest/internal/gtest-internal.h:1211:3: note: in definition of macro 'GTEST_TEST_CLASS_NAME_'
   test_case_name##_##test_name##_Test
   ^
../../net/quic/core/quic_connection_test.cc:2980:1: note: in expansion of macro 'TEST_P'
 TEST_P(QuicConnectionTest, ReducedPingTimeout) {
 ^
../../net/quic/core/quic_connection_test.cc:2935:8: error: previous definition of 'class net::test::{anonymous}::QuicConnectionTest_ReducedPingTimeout_Test'
 TEST_P(QuicConnectionTest, ReducedPingTimeout) {
        ^
../../testing/gtest/include/gtest/internal/gtest-internal.h:1211:3: note: in definition of macro 'GTEST_TEST_CLASS_NAME_'
   test_case_name##_##test_name##_Test
   ^
../../net/quic/core/quic_connection_test.cc:2935:1: note: in expansion of macro 'TEST_P'
 TEST_P(QuicConnectionTest, ReducedPingTimeout) {
 ^

Original issue's description:
> Quic: add unittests for reduced PING Timeout
>
> BUG=
>
> Committed: https://crrev.com/df9cb098cf816fb589e0ad6627012b524c78e9eb
> Cr-Commit-Position: refs/heads/master@{#416401}

TBR=rch@chromium.org,zhongyi@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review-Url: https://codereview.chromium.org/2296393005