Revert "Remove color correct rendering flag"
This reverts commit 1f214ec236bb904b61bac8ccddea7ac77ae013f2.

Reason for revert:
pixel_test.cc:183:17: error: no member named 'enable_color_correct_rasterization' in 'cc::LayerTreeSettings';

Original change's description:
> Remove color correct rendering flag
> 
> This is always on now
> 
> R=​dcheng (ipc)
> TBR=hubbe
> 
> Bug: 759215
> Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel
> Change-Id: I5fa39ba61eae96658fed55a3b38d102a163ebd08
> Reviewed-on: https://chromium-review.googlesource.com/695907
> Commit-Queue: ccameron chromium <ccameron@chromium.org>
> Reviewed-by: Daniel Cheng <dcheng@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#506061}

TBR=dcheng@chromium.org,ccameron@chromium.org

Change-Id: Ie745959545b3fbbaf686a941f49ce945b2eafe9f
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 759215
Cq-Include-Trybots: master.tryserver.blink:linux_trusty_blink_rel