fix closure compile
This fixes a closure compile error I'm seeing when adding additional
targets:

 /media/ssd2/c_new/tot2/src/ui/file_manager/file_manager/background/js/test_util_base.js:158: ERROR - inconsistent return type
 found   : Element
 required: (HTMLElement|null)
   return target;
          ^

TBR=fukino
CC=yawano

Review URL: https://codereview.chromium.org/1315603006