Revert of Add commands for go to beginning and end. (patchset #11 id:290001 of https://codereview.chromium.org/617493004/)
Reason for revert:
Broke compile in ChromeOS [1].

230/7506 | 0.279] STAMP obj/third_party/angle/src/copy_scripts.actions_rules_copies.stamp
[231/7506 | 0.281] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/latin-upper-normal.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/latin-upper-normal.json
[232/7506 | 0.282] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/latin-upper-double-accent.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/latin-upper-double-accent.json
[233/7506 | 0.284] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_angles.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_angles.json
[234/7506 | 0.285] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/latin-upper-single-accent.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/latin-upper-single-accent.json
[235/7506 | 0.287] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_arrows.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_arrows.json
[236/7506 | 0.288] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_characters.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_characters.json
[237/7506 | 0.290] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_delimiters.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_delimiters.json
[238/7506 | 0.292] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_digits.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_digits.json
[239/7506 | 0.293] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_geometry.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_geometry.json
[240/7506 | 0.294] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_harpoons.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_harpoons.json
[241/7506 | 0.296] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_non_characters.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_non_characters.json
[242/7506 | 0.297] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_symbols.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_symbols.json
[243/7506 | 0.299] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_whitespace.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/math_whitespace.json
[244/7506 | 0.300] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/other_stars.json resources/chromeos/chromevox/chromevox/background/mathmaps/symbols/other_stars.json
[245/7506 | 0.302] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/check_off.ogg resources/chromeos/chromevox/chromevox/background/earcons/check_off.ogg
[246/7506 | 0.303] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/check_on.ogg resources/chromeos/chromevox/chromevox/background/earcons/check_on.ogg
[247/7506 | 0.305] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/collapsed.ogg resources/chromeos/chromevox/chromevox/background/earcons/collapsed.ogg
[248/7506 | 0.306] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/editable_text.ogg resources/chromeos/chromevox/chromevox/background/earcons/editable_text.ogg
[249/7506 | 0.308] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/ellipsis.ogg resources/chromeos/chromevox/chromevox/background/earcons/ellipsis.ogg
[250/7506 | 0.309] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/button.ogg resources/chromeos/chromevox/chromevox/background/earcons/button.ogg
[251/7506 | 0.311] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/busy_progress_loop.ogg resources/chromeos/chromevox/chromevox/background/earcons/busy_progress_loop.ogg
[252/7506 | 0.312] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/busy_working_loop.ogg resources/chromeos/chromevox/chromevox/background/earcons/busy_working_loop.ogg
[253/7506 | 0.313] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/expanded.ogg resources/chromeos/chromevox/chromevox/background/earcons/expanded.ogg
[254/7506 | 0.315] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/font_change.ogg resources/chromeos/chromevox/chromevox/background/earcons/font_change.ogg
[255/7506 | 0.316] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/link.ogg resources/chromeos/chromevox/chromevox/background/earcons/link.ogg
[256/7506 | 0.318] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/invalid_keypress.ogg resources/chromeos/chromevox/chromevox/background/earcons/invalid_keypress.ogg
[257/7506 | 0.319] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/listbox.ogg resources/chromeos/chromevox/chromevox/background/earcons/listbox.ogg
[258/7506 | 0.321] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/long_desc.ogg resources/chromeos/chromevox/chromevox/background/earcons/long_desc.ogg
[259/7506 | 0.322] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/new_mail.ogg resources/chromeos/chromevox/chromevox/background/earcons/new_mail.ogg
[260/7506 | 0.323] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/object_close.ogg resources/chromeos/chromevox/chromevox/background/earcons/object_close.ogg
[261/7506 | 0.325] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/object_enter.ogg resources/chromeos/chromevox/chromevox/background/earcons/object_enter.ogg
[262/7506 | 0.326] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/object_delete.ogg resources/chromeos/chromevox/chromevox/background/earcons/object_delete.ogg
[263/7506 | 0.328] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/object_deselect.ogg resources/chromeos/chromevox/chromevox/background/earcons/object_deselect.ogg
[264/7506 | 0.329] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/object_exit.ogg resources/chromeos/chromevox/chromevox/background/earcons/object_exit.ogg
[265/7506 | 0.331] COPY ../../chrome/browser/resources/chromeos/chromevox/chromevox/background/earcons/object_open.ogg resources/chromeos/chromevox/chromevox/background/earcons/object_open.ogg
FAILED: cd ../../chrome/browser/resources/chromeos/chromevox; python tools/jsbundler.py -m copy -d ../../../../../out/Debug/resources/chromeos/chromevox -w ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog:closure ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/base.js cvox2/background/automation_util.js host/interface/abstract_earcons.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/object/object.js common/spannable.js common/chromevox.js common/node_state.js common/xpath_util.js host/interface/tts_interface.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/dom/nodetype.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/debug/error.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/string/string.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/asserts/asserts.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/i18n/pluralrules.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/i18n/ordinalrules.js ../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/i18n/messageformat.js host/interface/abstract_tts.js common/dom_predicates.js common/aria_util.js common/memoize.js common/dom_util.js common/selection_util.js common/cursor.js common/traverse_util.js common/cursor_selection.js common/nav_braille.js host/chrome/braille_key_types.js host/interface/braille_interface.js chromevox/background/tabs_api_handler.js cvox2/background/background.js cvox2/background/loader.js
Traceback (most recent call last):
  File "tools/jsbundler.py", line 345, in <module>
    main()
  File "tools/jsbundler.py", line 331, in main
    LinkOrCopyFiles(bundle.GetSources(), options.dest_dir)
  File "tools/jsbundler.py", line 251, in LinkOrCopyFiles
    os.path.join(dest_dir, source.GetOutPath()))
  File "tools/jsbundler.py", line 247, in LinkOrCopyOneFile
    shutil.copy(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 117, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
shutil.Error: `../../../../../chrome/third_party/chromevox/third_party/closure-library/closure/goog/base.js` and `../../../../../out/Debug/resources/chromeos/chromevox/closure/base.js` are the same file
ninja: build stopped: subcommand failed.

[1] http://build.chromium.org/p/chromium.webkit/builders/Linux%20ChromiumOS%20Builder%20%28dbg%29/builds/3703

Original issue's description:
> Add commands for go to beginning and end.
>
> This cl uses some new keybindings for these commands. Since we can bind control and search, this seems like a natural choice.
>
> Also, some fixes were made to background.js (uncovered by the unit test).
>
> TEST=BackgroundTest.*
>
> Committed: https://crrev.com/ee4b857ca20186868aad7a5b22fc454a11b6fe86
> Cr-Commit-Position: refs/heads/master@{#298270}

TBR=dmazzoni@chromium.org,plundblad@chromium.org,dtseng@chromium.org
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/636613002