Update patch set 3
Patch Set 3:

> Please verify if tracing still works in other applications which use any subclass of ContentApplication, e.g. CastApplication.

Thanks. The cast application "should" work since it is using BrowserStartupController to init the browser process:

//chromecast/browser/android/apk/src/org/chromium/chromecast/shell/CastBrowserHelper.java

However, I don't know how to test it. I can build "cast_shell_apk" and I can install it; but, "cast_shell_apk launch" fails with:

devil.android.device_errors.AdbShellCommandFailedError: (device: HT6530200122) shell command run via adb failed on the device:
  command: monkey -p org.chromium.chromecast.shell -c android.intent.category.LAUNCHER 1
exit status: 252

Do you know how I should test the cast app?

Patch-set: 3
Reviewer: Ehsan Chiniforooshan <1112474@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>