Update patch set 3
Patch Set 3:

Hmmm, that didn't work. There is a patch failure I don't totally get.

> First, rewinding head to replay your work on top of it...
Applying: Moved project configs to infra/config branch
.git/rebase-apply/patch:150: new blank line at EOF.
+
warning: 1 line adds whitespace errors.
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Patch failed at 0001 Moved project configs to infra/config branch
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

I based this on the instructions in https://chromium.googlesource.com/chromium/src.git/+/infra/config/README.md and https://crrev.com/c/568370 by sadrul@ that added the builder when we still needed it. It looks like 568370 is on branch refs/meta/config and my patch is on infra/config. Is that the problem or any idea what I did wrong?

Patch-set: 3
Reviewer: kylechar <1146978@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0