vs2015: fix const warning in cloud_print_service.cc
FAILED: ninja -t msvc -e environment.x86 -- "d:\src\depot_tools\win_toolchain\vs_files\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\cloud_print\service\win\cloud_print_service.cloud_print_service.obj.rsp /c ..\..\cloud_print\service\win\cloud_print_service.cc /Foobj\cloud_print\service\win\cloud_print_service.cloud_print_service.obj /Fdobj\cloud_print\service\cloud_print_service.cc.pdb
d:\src\cr3\src\cloud_print\service\win\cloud_print_service.cc(151): error C2440: 'return': cannot convert from 'const TCHAR *' to 'wchar_t *'
d:\src\cr3\src\cloud_print\service\win\cloud_print_service.cc(151): note: Conversion loses qualifiers

R=vitalybuka@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1165303003