Revert "m62 merge: cros: make VK_MEDIA_PLAY_PAUSE handle media contents on chrome browser"
This reverts commit 4ff8ca4ae7a9345c2dd99fb518299435da582648.

Reason for revert: breaks compile:
../../chrome/browser/ui/ash/media_client.cc:159:14: error: no type named 'MediaSession' in namespace 'content'
    content::MediaSession* media_session = content::MediaSession::Get(


Original change's description:
> m62 merge: cros: make VK_MEDIA_PLAY_PAUSE handle media contents on chrome browser
> 
> changes:
> (1) Provide the support to make VK_MEDIA_PLAY_PAUSE handle toggling play
> and pause on active browser's active tab. If there is an active browser,
> then instead of dispatching this event, handle active tab's media session
> play pause.
> (2) add FindBrowserWithActiveWindow() in browser_finder.h.
> (3) add Activate/IsActive in TestBrowserWindowAura, which is hooked to
> the aura window's activation.
> (4) refactor test in MultiUserWindowManagerChromeOSTest for new change.
> 
> TBR: sky@chromium.org, mlamouri@chromium.org
> 
> state on active browser's active tab.
> 
> (cherry picked from commit cb6871bbc25c3992e5d6656081308a493ce94cb2)
> 
> Bug: 763483
> Test: tested on device, the play/pause button could toggle the playback
> Change-Id: Ied566bf1f6c84edeaa762bb3a6e133720c1291c5
> Reviewed-on: https://chromium-review.googlesource.com/666199
> Reviewed-by: Scott Violet <sky@chromium.org>
> Reviewed-by: Mounir Lamouri <mlamouri@chromium.org>
> Commit-Queue: Qiang(Joe) Xu <warx@chromium.org>
> Cr-Original-Commit-Position: refs/heads/master@{#503510}
> Reviewed-on: https://chromium-review.googlesource.com/691185
> Reviewed-by: Qiang(Joe) Xu <warx@chromium.org>
> Cr-Commit-Position: refs/branch-heads/3202@{#499}
> Cr-Branched-From: fa6a5d87adff761bc16afc5498c3f5944c1daa68-refs/heads/master@{#499098}

TBR=sky@chromium.org,mlamouri@chromium.org,warx@chromium.org

Change-Id: I6c06262f3c65d57f73d9d32659cd5dc47dfcd28e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 763483