Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > I've uploaded patchset 2, which still doesn't compile.
> > 
> > - I removed render_frame_id
> > - I removed request_id
> > - I added QuotaStorageCode
> > - I fixed most of the mojo syntax errors
> > - I moved the .mojom file to storage/
> > - I added a reference in storage/common/BUILD.gn
> > 
> > I have several followup questions, but first, I am currently blocked on this compile error:
> > 
> > In file included from gen/storage/public/interfaces/quota.mojom-blink.cc:15:
> > In file included from gen/storage/public/interfaces/quota.mojom-blink.h:26:
> > In file included from ../../mojo/public/cpp/bindings/lib/serialization.h:17:
> > In file included from ../../mojo/public/cpp/bindings/lib/native_struct_serialization.h:22:
> > In file included from ../../mojo/public/cpp/bindings/native_struct.h:13:
> > ../../mojo/public/cpp/bindings/struct_ptr.h:95:18: error: no member named 'Hash' in 'url::mojom::blink::Origin'
> >     return ptr_->Hash(seed);
> >            ~~~~  ^
> > ../../mojo/public/cpp/bindings/lib/wtf_hash_util.h:38:66: note: in instantiation of member function 'mojo::StructPtr<url::mojom::blink::Origin>::Hash' requested here
> >   static size_t Hash(size_t seed, const T& value) { return value.Hash(seed); }
> >                                                                  ^
> > ../../mojo/public/cpp/bindings/lib/wtf_hash_util.h:57:28: note: in instantiation of member function 'mojo::internal::WTFHashTraits<mojo::StructPtr<url::mojom::blink::Origin>, true>::Hash' requested here
> >   return WTFHashTraits<T>::Hash(seed, value);
> >                            ^
> > gen/storage/public/interfaces/quota.mojom-blink.cc:51:26: note: in instantiation of function template specialization 'mojo::internal::WTFHash<mojo::StructPtr<url::mojom::blink::Origin> >' requested here
> >   seed = mojo::internal::WTFHash(seed, this->origin_url);
> >                          ^
> > 1 error generated.
> 
> Hmm, somehow the blink typemaps for Origin aren't being applied... no idea why that would happen though, since the ones for Url are working correctly (as they are used by blobs.mojom). Let me try to figure out what's going on...

Ah, nothing mysterious. Just a missing dependency from the //storage/public/interfaces target to //url/mojo:url_mojom_origin

Patch-set: 2
Reviewer: Marijn Kruisselbrink <1110029@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>