Revert of [remoting android] Fix lint and presubmit warnings (patchset #2 id:20001 of https://codereview.chromium.org/1878853002/ )
Reason for revert:
Breaks compilation on

https://uberchromegw.corp.google.com/i/internal.client.clank/builders/arm64-unpublished-builder/builds/1173

and

https://uberchromegw.corp.google.com/i/internal.client.clank/builders/arm64-unpublished-builder-rel/builds/980

../../remoting/android/java/src/org/chromium/chromoting/Chromoting.java:212: error: cannot find symbol
        mDrawerLayout.addDrawerListener(mDrawerToggle);
             ^
  symbol:   method addDrawerListener(ActionBarDrawerToggle)

Original issue's description:
> [remoting android] Fix lint and presubmit warnings
>
> Use AlertDialog class from support library.
> Use DrawerLayout.addDrawerListener() (the newer version of the support
> library added this and marked setDrawerListener() as deprecated).
> Add super.onCreate() in Application-derived class.
>
> Committed: https://crrev.com/81b87493d4df793b1a0acb0e8025aab9da5c1e82
> Cr-Commit-Position: refs/heads/master@{#386562}

TBR=joedow@chromium.org,lambroslambrou@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review URL: https://codereview.chromium.org/1879023003