Revert of Adding decoding capabilities to the TestVideoRenderer class (patchset #7 id:120001 of https://codereview.chromium.org/1190383007/)
Reason for revert:
The new tests are failing on the DrMemory bots: see http://build.chromium.org/p/chromium.memory.fyi/builders/Windows%20Unit%20%28DrMemory%20full%29%20%283%29/builds/7009 for more details.

An example of the failure:
d:\src\chromium\src\remoting\test\test_video_renderer_unittest.cc(119): error: Expected: (error) < (error_limit), actual: 0.406962 vs 0.02

The problem is due to hard coded times in the test, at line 110. Tests shouldn't rely on waiting 'long enough' for something to happen, as 'long enough' is too variable / flaky. The test should ideally be rewritten to wait for a quit task to be posted instead.

Original issue's description:
> Updated Test Driver with video decoding capabilities so that when a video sample is received from remote host, it can be decoded and rendered to buffer in memory.
>
> BUG=
>
> Committed: https://crrev.com/497e9a05decbcd344d774e52c1b89cdece525d99
> Cr-Commit-Position: refs/heads/master@{#336445}

TBR=joedow@chromium.org,liaoyuke@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/1219633002