Update patch set 9
Patch Set 9:

> Patch Set 9:
> 
> (1 comment)

With dependencies arranged as you say, moving WebDevToolsAgentImpl (alone) to controller gives these link errors. 

../../third_party/WebKit/Source/web/LocalFrameClientImpl.cpp:440: error: undefined reference to 'blink::WebDevToolsAgentImpl::DidStartProvisionalLoad(blink::LocalFrame*)'
../../third_party/WebKit/Source/web/WebFrameWidgetImpl.cpp:1084: error: undefined reference to 'blink::WebDevToolsAgentImpl::LayerTreeViewChanged(blink::WebLayerTreeView*)'
../../third_party/WebKit/Source/web/LocalFrameClientImpl.cpp:468: error: undefined reference to 'blink::WebDevToolsAgentImpl::DidCommitLoadForLocalFrame(blink::LocalFrame*)'
../../third_party/WebKit/Source/web/WebFrameWidgetImpl.cpp:262: error: undefined reference to 'blink::WebDevToolsAgentImpl::PaintOverlay()'
../../third_party/WebKit/Source/web/LocalFrameClientImpl.cpp:595: error: undefined reference to 'blink::WebDevToolsAgentImpl::CacheDisabled()'
../../third_party/WebKit/Source/web/WebFrameWidgetImpl.cpp:370: error: undefined reference to 'blink::WebDevToolsAgentImpl::HandleInputEvent(blink::WebInputEvent const&)'
../../third_party/WebKit/Source/web/WebLocalFrameImpl.cpp:1896: error: undefined reference to 'blink::WebDevToolsAgentImpl::Create(blink::WebLocalFrameBase*, blink::WebDevToolsAgentClient*)'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:3963: error: undefined reference to 'blink::WebDevToolsAgentImpl::LayerTreeViewChanged(blink::WebLayerTreeView*)'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:796: error: undefined reference to 'blink::WebDevToolsAgentImpl::ScreencastEnabled()'
../../third_party/WebKit/Source/web/WebLocalFrameImpl.cpp:2304: error: undefined reference to 'blink::WebDevToolsAgentImpl::WillBeDestroyed()'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:2169: error: undefined reference to 'blink::WebDevToolsAgentImpl::HandleInputEvent(blink::WebInputEvent const&)'
../../third_party/WebKit/Source/platform/heap/TraceTraits.h:225: error: undefined reference to 'blink::WebDevToolsAgentImpl::Trace(blink::Visitor*)'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:2031: error: undefined reference to 'blink::WebDevToolsAgentImpl::PaintOverlay()'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:3903: error: undefined reference to 'blink::WebDevToolsAgentImpl::RootLayerCleared()'
../../third_party/WebKit/Source/platform/heap/GarbageCollected.h:216: error: undefined reference to 'blink::WebDevToolsAgentImpl::~WebDevToolsAgentImpl()'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:4127: error: undefined reference to 'blink::WebDevToolsAgentImpl::LayoutOverlay()'
../../third_party/WebKit/Source/web/WebViewImpl.cpp:3882: error: undefined reference to 'blink::WebDevToolsAgentImpl::RootLayerCleared()'

They can be solved by extending the interface in platform/web/WebDevToolsAgent.h. That was the purpose of my WebDevToolsAgentCore.h which was mistakenly in this CL for a brief time.

Patch-set: 9
Reviewer: Nicholas Verne <1210615@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>