Update patch set 6
Patch Set 6:

> Created a revert of this change as Ie7345f57f90bc8a3bdf43936a6ef6e655c613ae2

This caused compile failures on Linux and Android. Sample output:

FAILED: obj/gpu/gpu_unittests/gles2_cmd_decoder_unittest_base.o 
...

../../gpu/command_buffer/service/gles2_cmd_decoder_unittest_base.cc:2155:7: error: use of undeclared identifier 'engine_'
      engine_->GetSharedMemoryBuffer(kSharedMemoryId);
      ^
../../gpu/command_buffer/service/gles2_cmd_decoder_unittest_base.cc:2155:38: error: use of undeclared identifier 'kSharedMemoryId'
      engine_->GetSharedMemoryBuffer(kSharedMemoryId);
                                     ^
../../gpu/command_buffer/service/gles2_cmd_decoder_unittest_base.cc:2156:45: error: use of undeclared identifier 'kSharedMemoryId'
  ClientDiscardableHandle handle(buffer, 0, kSharedMemoryId);
                                            ^
../../gpu/command_buffer/service/gles2_cmd_decoder_unittest_base.cc:2159:24: error: use of undeclared identifier 'kSharedMemoryId'
  cmd.Init(texture_id, kSharedMemoryId, 0);
                       ^
4 errors generated.

Patch-set: 6
CC: Tim Sergeant <1130680@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>