Revert "Refactor Cronet prefs managers into CronetPrefsManager class"
This reverts commit 482dc2449c50bb20d5067a9ae856fd953c870262.

Reason for revert: broke bots, "error: use of undeclared identifier
'thread_checker_'"

Original change's description:
> Refactor Cronet prefs managers into CronetPrefsManager class
> 
> This will allow reusing the Cronet prefs related code on iOS.
> 
> BUG=740172
> 
> Cq-Include-Trybots: master.tryserver.chromium.android:android_cronet_tester
> Change-Id: Icda8bb30d37db8e57ed4653f0d848d1a1fd4b275
> Reviewed-on: https://chromium-review.googlesource.com/629099
> Reviewed-by: Miriam Gershenson <mgersh@chromium.org>
> Reviewed-by: Helen Li <xunjieli@chromium.org>
> Commit-Queue: Andrei Kapishnikov <kapishnikov@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#497259}

TBR=mgersh@chromium.org,xunjieli@chromium.org,kapishnikov@chromium.org

Change-Id: Iba94e917f2d5374a4a6ba5043cc931dd39816234
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 740172
Cq-Include-Trybots: master.tryserver.chromium.android:android_cronet_tester