fuchsia: use temp file name on sdk extraction
On some machines, seeking within the tempfile and then using tarfile
with a fileobj was resulting in strange errors from tarfile:

  tarfile.ReadError: empty file

Since the tempfile is already named, just use the name to extract, which
appears to work.

Bug: 707030
Change-Id: I3e4a24a08c24493ad9a6bbd7c00a2d7cca43eacb