Revert of Add download_file_types.proto with ascii->binary conversion, as a resource. (patchset #7 id:120001 of https://codereview.chromium.org/1857983002/ )
Reason for revert:
This cl is breaking  Android Debug (Nexus 5):
https://build.chromium.org/p/chromium.gpu/builders/Android%20Debug%20%28Nexus%205%29/builds/7159

Error log:
FAILED: python ../../chrome/browser/resources/safe_browsing/gen_file_type_proto.py -i ../../chrome/browser/resources/safe_browsing/download_file_types.asciipb -o gen/chrome/browser/resources/safe_browsing/download_file_types.pb -p pyproto/chrome/common/safe_browsing
Traceback (most recent call last):
  File "../../chrome/browser/resources/safe_browsing/gen_file_type_proto.py", line 13, in <module>
    import google.protobuf.text_format as text_format
ImportError: No module named google.protobuf.text_format
ninja: build stopped: subcommand failed.

Original issue's description:
> Add download_file_types.proto with ascii->binary conversion, as a resource.
>
> We'll maintain an ASCII version of the data in the repo, and build
> the binary version as a Resource at build time.  The data will later be
> updated at runtime.
>
> BUG=596555
>
> Committed: https://crrev.com/d57ee6f2e12ac55ac832ca36429545e370467290
> Cr-Commit-Position: refs/heads/master@{#386818}

TBR=asanka@chromium.org,jialiul@chromium.org,jialiul@google.com,thestig@chromium.org,nparker@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=596555

Review URL: https://codereview.chromium.org/1881273002