Revert of Track frame context URL using first script heuristic (patchset #7 id:120001 of https://codereview.chromium.org/2296923004/ )
Reason for revert:
broke compile:
https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Win%20x64%20Builder%20%28dbg%29/builds/93915
c:\b\c\b\win_layout\src\third_party\webkit\source\core\inspector\inspectorwebperfagenttest.cpp(48) : error C2220: warning treated as error - no 'object' file generated
c:\b\c\b\win_layout\src\third_party\webkit\source\core\inspector\inspectorwebperfagenttest.cpp(48) : warning C4702: unreachable code

Original issue's description:
> Track frame context URL using first script heuristic
>
> BUG=635596
>
> Committed: https://crrev.com/7012b38dafd3fcaaeaee7b7413718b4b6d7493ca
> Cr-Commit-Position: refs/heads/master@{#418931}

TBR=caseq@chromium.org,alph@chromium.org,pfeldman@chromium.org,dgozman@chromium.org,panicker@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=635596

Review-Url: https://codereview.chromium.org/2345023002