Fix illegal use of const in container contents to unbreak VS 2015.
For details see the STL Breaking Changes (VS14 CTP1) section of:
http://blogs.msdn.com/b/vcblog/archive/2014/06/06/
c-14-stl-features-fixes-and-breaking-changes-in-
visual-studio-14-ctp1.aspx

In particular:
"The Standard has always forbidden containers of const elements...
...elements must be Assignable, which const T isn't."

Error message is:
error C2338: The C++ Standard forbids containers of const
elements because allocator<const T> is ill-formed.

R=cpu@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1066213002