Revert of [DevTools] Rename entities in js_protocol, remove deprecated ones. (patchset #1 id:1 of https://codereview.chromium.org/2249743002/ )
Reason for revert:
Compile failed on Linux ChromiumOS GN https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20GN/builds/44080

../../headless/lib/headless_devtools_client_browsertest.cc:177:56: error: no member named 'Run' in 'headless::runtime::ExperimentalDomain'
    devtools_client_->GetRuntime()->GetExperimental()->Run(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../../headless/lib/headless_devtools_client_browsertest.cc:178:18: error: no member named 'RunParams' in namespace 'headless::runtime'
        runtime::RunParams::Builder().Build());
        ~~~~~~~~~^

Original issue's description:
> [DevTools] Rename entities in js_protocol, remove deprecated ones.
>
> BUG=635947
>
> Committed: https://crrev.com/816474328ff9b737dffbe733c0d7b2c286151ffb
> Cr-Commit-Position: refs/heads/master@{#412043}

TBR=pfeldman@chromium.org,dgozman@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=635947

Review-Url: https://codereview.chromium.org/2249663003