Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > Hello, +Helen re: 'git cl upload' failure I mentioned in doc.
> 
> Walter: the pasted log seems to be truncated. I don't see any presubmit warnings
> 
> -------Quote from comment-----------------
> Log excerpt:
> 
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> Changes to be committed:
> (use "git reset HEAD <file>..." to unstage)
> 
> modified: tools/perf/page_sets/data/top_25.json
> deleted: tools/perf/page_sets/data/top_25_000.wpr.sha1
> new file: tools/perf/page_sets/data/top_25_000.wprgo.sha1
> deleted: tools/perf/page_sets/data/top_25_001.wpr.sha1
> new file: tools/perf/page_sets/data/top_25_001.wprgo.sha1
> deleted: tools/perf/page_sets/data/top_25_002.wpr.sha1
> new file: tools/perf/page_sets/data/top_25_002.wprgo.sha1
> deleted: tools/perf/page_sets/data/top_25_003.wpr.sha1
> new file: tools/perf/page_sets/data/top_25_003.wprgo.sha1
> deleted: tools/perf/page_sets/data/top_25_004.wpr.sha1
> new file: tools/perf/page_sets/data/top_25_004.wprgo.sha1
> 
> wkorman@lemur:~/chrome$ git new-branch 756002_migrate_wpr_top_25
> Switched to branch 756002_migrate_wpr_top_25.
> wkorman@lemur:~/chrome$ git commit
> [756002_migrate_wpr_top_25 6948a1980c9a] Migrate top_25 PageSet to WprGo.
> 11 files changed, 33 insertions(+), 33 deletions(-)
> delete mode 100644 tools/perf/page_sets/data/top_25_000.wpr.sha1
> create mode 100644 tools/perf/page_sets/data/top_25_000.wprgo.sha1
> delete mode 100644 tools/perf/page_sets/data/top_25_001.wpr.sha1
> create mode 100644 tools/perf/page_sets/data/top_25_001.wprgo.sha1
> delete mode 100644 tools/perf/page_sets/data/top_25_002.wpr.sha1
> create mode 100644 tools/perf/page_sets/data/top_25_002.wprgo.sha1
> delete mode 100644 tools/perf/page_sets/data/top_25_003.wpr.sha1
> create mode 100644 tools/perf/page_sets/data/top_25_003.wprgo.sha1
> delete mode 100644 tools/perf/page_sets/data/top_25_004.wpr.sha1
> create mode 100644 tools/perf/page_sets/data/top_
> --------- End of Quote -------------------

I just had it happen again on another change, that log:

** Presubmit ERRORS **
Validating WPR archives failed:

***************

Traceback (most recent call last):
  <module> at /usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/validate_wpr_archives:102
    sys.exit(main(sys.argv[1:]))
  main at /usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/validate_wpr_archives:97
    '\n'.join(missing_sha_files))
AssertionError: These SHA files are missing. Did you forget to check them in?
/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_001.wpr.sha1
/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_000.wpr.sha1
/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_003.wpr.sha1
/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_002.wpr.sha1
/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_004.wpr.sha1

Locals:
  archive_infos     : [<telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ce3d90>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6cfe050>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6cfe090>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6cfe0d0>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6cfe110>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6cfe150>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6cfe190>, <telemetry.wpr.arc ...  at 0x7f5bb6ba4590>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba45d0>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba4610>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba4650>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba4690>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba46d0>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba4750>, <telemetry.wpr.archive_info.WprArchiveInfo object at 0x7f5bb6ba4790>] (truncated)
  args              : ['/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_000.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_001.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_002.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_003.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_004.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_006.wprgo.sha1']
  missing_archives  : set([])
  missing_sha_files : set([u'/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_001.wpr.sha1', u'/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_000.wpr.sha1', u'/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_003.wpr.sha1', u'/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_002.wpr.sha1', u'/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_004.wpr.sha1'])
  options           : Namespace(wpr_sha_files=['/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_000.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_001.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_002.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_003.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_004.wprgo.sha1', '/usr/local/google/home/wkorman/workspace/chromium/src/tools/perf/page_sets/data/top_25_006.wprgo.sha1'])
  parser            : ArgumentParser(prog='Validate whether WPR archives are properly stored in CloudStorage.', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
  s                 : <telemetry.story.story_set.StorySet object at 0x7f5bb6ce3a10>


Running all tests in /usr/local/google/home/wkorman/workspace/chromium/src/third_party/WebKit/PerformanceTests
***************

Patch-set: 1
Reviewer: Walter Korman <1128438@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>