Ensure _LLVMFuzzerInitialize is always exported and marked used on Mac.
The linker's -dead_strip was removing the fuzzer initializer because it
was unreachable and not exported. Explicitly tell the linker to
-export_symbol it so that it can be resolved through dlsym and invoked
by the fuzzer driver.

For fuzz targets that do not define their own LLVMFuzzerInitialize(),
this will add a new Undefined reference to the symbol table for it, due
to the forced export. This should not cause issues, though, since the
symbol will not be able to be resolved.

Bug: 687076
Change-Id: I8fe5c523ade491a48cd7abbf85c69edb872c97db