Update patch set 21
Patch Set 21:

> Patch Set 21:
> 
> When I ran a CQ Dry Run on patch 19, I ran into some problems in mac: 
> 
> Undefined symbols for architecture x86_64:
>   "BrowserView::GetBrowserViewForBrowser(Browser const*)", referenced from:
>       NewTabPromoDialogTest::ShowDialog(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in new_tab_promo_dialog_browsertest.o
>   "NewTabButton::ShowPromo()", referenced from:
>       NewTabPromoDialogTest::ShowDialog(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in new_tab_promo_dialog_browsertest.o
> ld: symbol(s) not found for architecture x86_64
> 
> 
> Does anyone know how I might approach solving this? I'm not completely sure what the issue even is.

I think the issue is that your implementation is views-specific, but your browsertest is added to the section of the .gn that includes it for all toolkits.  YOu probably want to move it to the toolkit_views-specific set of source files for browser_tests.

Patch-set: 21
Reviewer: Peter Kasting <1000805@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>