Revert "Do not push the reseted needs_show_scrollbars to active tree"
This reverts commit 85997065863790a2aa8aa1773d6ca7ea6a6a81fd.

Breaks official Android build

https://uberchromegw.corp.google.com/i/official.android.continuous/builders/beta-arm/builds/8779

../../cc/layers/scrollbar_layer_unittest.cc: In member function 'virtual void cc::{anonymous}::AuraScrollbarLayerTest_ScrollbarLayerCreateAfterSetScrollable_Test::TestBody()':
../../cc/layers/scrollbar_layer_unittest.cc:829:17: error: 'class cc::Layer' has no member named 'SetScrollable'
   scroll_layer->SetScrollable(layer_tree_root->bounds());

BUG=740795

Change-Id: Id2d4b862593e4e69bc1e27e349a0670b677178f7