Revert "Always suppress system WKWebView Context Menu and show custom context menu."
This reverts commit 2d85a12f776d580fd9d2f12da4a8a94ee81d3245.

Reason for revert: Fails compile on ios-device-xcode-clang and others since
https://build.chromium.org/p/chromium.mac/builders/ios-device-xcode-clang/builds/34563

error like

crw_context_menu_controller.mm:233:18: error: using integer absolute value function 'abs' when argument is of floating point type [-Werror,-Wabsolute-value]
  float deltaX = abs(_locationForLastTouch.x - currentTouchLocation.x);

Original change's description:
> Always suppress system WKWebView Context Menu and show custom context menu.
> 
> Triggering the context menu is done independently of fetching details of the DOM
> element the user long pressed. Previously, if the details of the DOM element
> were not available when the long press recognizer completed, the system context
> menu would be displayed instead of Chrome's custom context menu.
> 
> The system context menu can cause the user lots of confusion. For example, the
> "Add to Reading List" item which is shown on the system context menu conflicts
> with the Chrome Reading List feature. If the user taps the system Reading List
> item, the item will not be added to their Chrome Reading list, but they will
> likely believe that it has been successfully added.
> 
> To resolve these problems, this change always suppresses the system context
> menu and waits for the DOM element to be returned before showing the custom
> Chrome Context Menu. In addition, iFrames will no longer show the WKWebView
> context menu.
> 
> Now, the custom context menu will always be displayed once the DOM element
> details have been fetched as long as the user is still long pressing on the
> element.
> 
> Bug: 542933
> Change-Id: Ia47e659868449bb514fc6b679e0f233c2bcd8182
> Reviewed-on: https://chromium-review.googlesource.com/579585
> Reviewed-by: Eugene But <eugenebut@chromium.org>
> Commit-Queue: Mike Dougherty <michaeldo@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#496606}

TBR=eugenebut@chromium.org,michaeldo@chromium.org

Change-Id: Ica45fa69581983c8e81d6852c74f4646fa08d731
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 542933