Update patch set 9
Patch Set 9:

> Patch Set 9:
> 
> > Patch Set 9:
> > 
> > I doubt the Chromium tooling would accept a review from me. If you submit a PR against GitHub w3c/web-platform-tests I can merge it, but no guarantees it'll happen within an hour.
> 
> If so, let me fix it in Chromium. But it seems to me that chromium-wpt-export-bot will make a PR automatically if there is an update in w3c/web-platform-tests in blink's test. So I wonder if I should make a PR in the GitHub w3c/web-platform-tests manually. Is this urgent?

I restore it in my local, then I try to upload it. But, there is a presubmit error as below,
 
** Presubmit ERRORS **
* The following files are passing testharness results without console error messages, they should be removed:
 /home/gyuyoung/chromium/src/third_party/WebKit/LayoutTests/external/wpt/html/webappapis/system-state-and-capabilities/the-navigator-object/historical.window-expected.txt
ERROR: found passing testharness results without console error messages.

Because isProtocolHandlerRegistered was removed, all tests are passed. 

This is a testharness.js-based test.
PASS registerContentHandler() is removed
PASS isProtocolHandlerRegistered() is removed
PASS isContentHandlerRegistered() is removed
PASS unregisterContentHandler() is removed
Harness: the test ran to completion.

In such case, I know that we can remove the test. That's why I removed it before landing. Does anyone know how to handle in this case?

Patch-set: 9