Update patch set 18
Patch Set 18:

This seems to have upset the jumbo builders because of kMinPixelsPerTitleCharacter and kMessageCharacterLimit appearing twice in the same translation unit once the message_center jumbo unit (with all the code) has been created. I can look at either renaming or sharing them depending on what you think would be the best solution.

In file included from gen/ui/message_center/message_center_jumbo_1.cc:25:
./../../ui/message_center/views/notification_view_md.cc:122:11: error: redefinition of 'kMinPixelsPerTitleCharacter'
const int kMinPixelsPerTitleCharacter = 4;
          ^
./../../ui/message_center/views/notification_view.cc:58:11: note: previous definition is here
const int kMinPixelsPerTitleCharacter = 4;
          ^
In file included from gen/ui/message_center/message_center_jumbo_1.cc:25:
./../../ui/message_center/views/notification_view_md.cc:125:18: error: redefinition of 'kMessageCharacterLimit'
constexpr size_t kMessageCharacterLimit =
                 ^
./../../ui/message_center/views/notification_view.cc:60:18: note: previous definition is here
constexpr size_t kMessageCharacterLimit =
                 ^
2 errors generated.

Patch-set: 18