Fix compile failure when use_sysroot=false
Compiling without the sysroot on a system at least as new as Debian
Jessie would result in compile failures like this:

In file included from
../../components/os_crypt/key_storage_keyring.cc:16:
../../components/os_crypt/keyring_util_linux.h:16:9: error:
'GNOME_KEYRING_DEPRECATED' macro redefined [-Werror,-Wmacro-redefined]

This was because gnome-keyring.h was included before
keyring_util_linux.h which redefined macros GNOME_KEYRING_DEPRECATED
and GNOME_KEYRING_DEPRECATED_FOR.  This CL removes the first include
to gnome-keyring.h

Review-Url: https://codereview.chromium.org/2352763003