Revert of Add button to add new FSP services to Files app. (patchset #8 id:140001 of https://codereview.chromium.org/1056433003/)
Reason for revert:
Broke the build:
http://build.chromium.org/p/chromium.fyi/builders/Closure%20Compilation%20Linux/builds/18940

## /mnt/data/b/build/slave/Closure_Compilation_Linux/build/src/ui/file_manager/file_manager/foreground/js/navigation_list_model.js:33: ERROR - NavigationModelShortcutItem cannot extend this type; structs can only extend structs
## function NavigationModelShortcutItem(label, entry) {

Original issue's description:
> Add button to add new FSP services to Files app.
>
> This CL adds a FSP suggest dialog which can be shown by clicking the button at
> the end of the left nav.
>
> TEST=Tested manually by clicking on the new button in the left nav.
> BUG=471722

TBR=hirono@chromium.org,mtomasz@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=471722

Review URL: https://codereview.chromium.org/1058873004