Revert of ChannelMojo: Ensure that it always has ScopedIPCSupport (patchset #1 id:1 of https://codereview.chromium.org/1054253005/)
Reason for revert:
It breaks the lkgr bots for various win ASAN, such as: http://build.chromium.org/p/chromium.lkgr/waterfall?builder=Win%20ASan%20Release

[17485/19602] CXX obj\content\test\test_support_content.fake_plugin_service.obj
FAILED: ninja -t msvc -e environment.x86 -- "..\..\third_party/llvm-build/Release+Asserts/bin/clang-cl" -m32 /nologo /showIncludes /FC @obj\tools\ipc_fuzzer\message_replay\ipc_fuzzer_replay.replay_process.obj.rsp /c ..\..\tools\ipc_fuzzer\message_replay\replay_process.cc /Foobj\tools\ipc_fuzzer\message_replay\ipc_fuzzer_replay.replay_process.obj /Fdobj\tools\ipc_fuzzer\message_replay\ipc_fuzzer_replay.cc.pdb
..\..\tools\ipc_fuzzer\message_replay\replay_process.cc(96,68) :  error(clang): too few arguments to function call, expected 3, have 2
        IPC::ChannelMojo::CreateClientFactory(nullptr, channel_name), this,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      ^
..\..\ipc/mojo/ipc_channel_mojo.h(80,3) :  note(clang): 'CreateClientFactory' declared here
  static scoped_ptr<ChannelFactory> CreateClientFactory(
  ^
1 error generated.
clang-cl.exe: warning: falling back to C:\b\depot_tools\win_toolchain\vs2013_files\win8sdk\bin\..\..\VC\bin\amd64_x86\cl.exe
clang-cl.exe: error: clang frontend command failed with exit code 2 (use -v to see invocation)
..\..\tools\ipc_fuzzer\message_replay\replay_process.cc(96) : error C2660: 'IPC::ChannelMojo::CreateClientFactory' : function does not take 2 arguments

Original issue's description:
> ChannelMojo: Ensure that it always has ScopedIPCSupport
>
> ChannelMojo has ScopedIPCSupport, but it is instantiated only in
> in-process mode. This CL lets it always instantiate to make it
> clear that ChannelInfo is protected by the ScopedIPCSupport.
> It simplifies the relationship between the support object and
> the channel, and makes the lifecycle invariant reasonable.
>
> With this change, we no longer need to protect ChannelMojo with
> ScopedIPCSupport on its client side. Now it's built-in.
>
> Note that this is a speculative fix of fuzzer generated crash,
> where Mojo channel related globals are gone before when channel
> mojo is being destroyed.
>
> BUG=473438
> R=viettrungluu@chromium.org, rockot@chromium.org
>
> Committed: https://crrev.com/808706e71c213c916815e967e3156cae64d12c00
> Cr-Commit-Position: refs/heads/master@{#324308}

TBR=rockot@chromium.org,viettrungluu@chromium.org,creis@chromium.org,morrita@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=473438

Review URL: https://codereview.chromium.org/1069943003