Don't list display_unittests twice for ClangToTLinuxUBSanVptr tester
Unbreaks that bot after https://codereview.chromium.org/1825723002/ added the
same test a second time, causing:

AssertionError: Triggered same task twice: display_unittests/Ubuntu-12.04/546a7a6818/ClangToTLinuxUBSanVptr tester/363

BUG=597105
TBR=robliao

Review URL: https://codereview.chromium.org/1840233003 .