CrOs sysroot: update to Debian stretch and add libva
This CL updates the Debian sysroot we use for CrOs bots
to Debian stretch, and adds libva. With that, we start
compiling the va-specific files in //media/gpu, which
need to be fixed:


vaapi_video_encode_accelerator.h:264:53: error: [chromium-style] WeakPtrFactory members which refer to their outer class must be the last member in the outer class definition.
base::WeakPtrFactory<VaapiVideoEncodeAccelerator> weak_this_ptr_factory_;


vaapi_picture.h:58:37: error: [chromium-style] virtual methods with non-empty bodies shouldn't be declared inline.
virtual bool AllowOverlay() const { return false; }

Bug:
Cq-Include-Trybots: master.tryserver.chromium.android:android_optional_gpu_tests_rel;master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
Change-Id: I86e2ab11764a623c48113a161036bd494dbcf44c