Update patch set 2
Patch Set 2:

Note: Reason for manual import:

The automatic import (https://chromium-review.googlesource.com/c/558493/) passed CQ but never submitted due to a mistake in the invocation of git cl:

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.infra.cron%2Fwpt-importer%2F264%2F%2B%2Frecipes%2Fsteps%2FImport_changes_from_WPT_to_Chromium%2F0%2Fstdout
webkitpy.common.system.executive.ScriptError: Failed to run "['git', 'cl', 'cl', 'upload', '--send-mail']" exit_code: 2
output: Usage: git cl <command> [options]
git cl: error: no such option: --send-mail


Looks like this was fixed in https://chromium-review.googlesource.com/c/558982/, thanks Philip!

Patch-set: 2