Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> This CL is causing a compiler error:
> 
> ../../cc/test/pixel_test.cc:183:17: error: no member named 'enable_color_correct_rasterization' in 'cc::LayerTreeSettings'; did you mean 'enable_oop_rasterization'?
>       settings_.enable_color_correct_rasterization,
>                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                 enable_oop_rasterization
> ../../cc/trees/layer_tree_settings.h:145:8: note: 'enable_oop_rasterization' declared here
>   bool enable_oop_rasterization = false;
>        ^
> In file included from ../../cc/test/pixel_test.cc:5:
> In file included from ../../cc/test/pixel_test.h:5:
> In file included from ../../base/files/file_util.h:15:
> In file included from ../../buildtools/third_party/libc++/trunk/include/set:389:
> In file included from ../../buildtools/third_party/libc++/trunk/include/__tree:16:
> ../../buildtools/third_party/libc++/trunk/include/memory:3065:32: error: no matching constructor for initialization of 'cc::LayerTreeResourceProvider'
>     return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
>                                ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ../../cc/test/pixel_test.cc:180:35: note: in instantiation of function template specialization 'std::__1::make_unique<cc::LayerTreeResourceProvider, cc::TestInProcessContextProvider *, cc::TestSharedBitmapManager *, viz::TestGpuMemoryBufferManager *, bool, bool &, viz::ResourceSettings &>' requested here
>   child_resource_provider_ = std::make_unique<LayerTreeResourceProvider>(
>                                   ^
> ../../cc/resources/layer_tree_resource_provider.h:20:3: note: candidate constructor not viable: requires 5 arguments, but 6 were provided
>   LayerTreeResourceProvider(
>   ^
> ../../cc/resources/layer_tree_resource_provider.h:78:28: note: candidate constructor not viable: requires 1 argument, but 6 were provided
>   DISALLOW_COPY_AND_ASSIGN(LayerTreeResourceProvider);
>                            ^
> 2 errors generated.
> [877/17898] CXX obj/ui/gl/gl_unittest_utils/gl_mock.o
> ninja: build stopped: subcommand failed.

Maybe you missing something when rebase ?  enable_color_correct_rasterization is here: https://chromium.googlesource.com/chromium/src/+/master/cc/trees/layer_tree_settings.h#95

Patch-set: 3