Revert "Fix Website Settings crash with Plugins ASK setting."
This reverts commit 5abc69b1a406999169052b7d457de86fd67c6f8c.

Reason for revert:

The Linux GN bot failed compile:
http://build.chromium.org/p/chromium.linux/buildstatus?builder=Linux%20GN&number=19568

Due to error running grit:
KeyError: 'Duplicate keys: [18500]'

We have seen this error before, and it should have already been fixed
in grit's resource_ids....

I expect the problem is with GN since this failure isn't happening on
any other bot, however reverting in the meantime to make the tree green
until this is sorted out.

TBR=tommycli@chromium.org
NOTRY=true

Review URL: https://codereview.chromium.org/825753002