Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> (1 comment)
> 
> Please make sure code owners are included as the reviewers.
> 
> It seems like bulk-moving 
> - web/InspectorOverlayAgent.*,
> - web/web/WebDevToolsAgentImpl.* and
> - web/PageOverlay.*
> 
> would be a much smaller and a more straightforward mechanical change. The only dependency that you would need to inject would be ToWebFrameWidgetImpl in WebDevToolsAgentImpl, but it should be mechanical change to move it into the call site that is anyways in web.

It's a great suggestion, but unfortunately this approach won't work. Here's a patch to show the problem that happens:
https://chromium-review.googlesource.com/536374

ninja: Entering directory `out/Default'
[12/59] SOLINK ./libblink_core.so
FAILED: libblink_core.so libblink_core.so.TOC 
python "../../build/toolchain/gcc_solink_wrapper.py" --readelf="readelf" --nm="nm" --sofile="./libblink_core.so" --tocfile="./libblink_core.so.TOC" --output="./libblink_core.so"  -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--no-as-needed -lpthread -Wl,--as-needed -fuse-ld=gold -B../../third_party/binutils/Linux_x64/Release/bin -Wl,--threads -Wl,--thread-count=4 -Wl,--icf=all -m64 -Werror -Wl,-O1 -Wl,--gc-sections --sysroot=../../build/linux/debian_jessie_amd64-sysroot -L../../build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_jessie_amd64-sysroot/lib/x86_64-linux-gnu -L../../build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=../../build/linux/debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu -Wl,--export-dynamic -o "./libblink_core.so" -Wl,-soname="libblink_core.so" @"./libblink_core.so.rsp"
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::WebDevToolsAgentImpl::InitializeSession(int, WTF::String const&, WTF::String*): error: undefined reference to 'blink::InspectorIndexedDBAgent::InspectorIndexedDBAgent(blink::InspectedFrames*, v8_inspector::V8InspectorSession*)'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::WebDevToolsAgentImpl::InitializeSession(int, WTF::String const&, WTF::String*): error: undefined reference to 'blink::DeviceOrientationInspectorAgent::DeviceOrientationInspectorAgent(blink::InspectedFrames*)'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::WebDevToolsAgentImpl::InitializeSession(int, WTF::String const&, WTF::String*): error: undefined reference to 'blink::InspectorDatabaseAgent::InspectorDatabaseAgent(blink::Page*)'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::WebDevToolsAgentImpl::InitializeSession(int, WTF::String const&, WTF::String*): error: undefined reference to 'blink::InspectorAccessibilityAgent::InspectorAccessibilityAgent(blink::Page*, blink::InspectorDOMAgent*)'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::WebDevToolsAgentImpl::InitializeSession(int, WTF::String const&, WTF::String*): error: undefined reference to 'blink::InspectorDOMStorageAgent::InspectorDOMStorageAgent(blink::Page*)'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::WebDevToolsAgentImpl::InitializeSession(int, WTF::String const&, WTF::String*): error: undefined reference to 'blink::InspectorCacheStorageAgent::InspectorCacheStorageAgent()'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::ClientMessageLoopAdapter::RunLoop(blink::WebLocalFrameBase*): error: undefined reference to 'blink::WebViewBase::AllInstances()'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::ClientMessageLoopAdapter::RunLoop(blink::WebLocalFrameBase*): error: undefined reference to 'blink::WebView::WillEnterModalLoop()'
obj/third_party/WebKit/Source/core/exported/exported/WebDevToolsAgentImpl.o:../../third_party/WebKit/Source/core/exported/WebDevToolsAgentImpl.cpp:function blink::ClientMessageLoopAdapter::RunLoop(blink::WebLocalFrameBase*): error: undefined reference to 'blink::WebView::DidExitModalLoop()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Although core/ can include headers from public/web, it can't access implementations that are still in web/. So we need to introduce these temporary parent classes in core/ with virtual methods, forcing the compiler to use a vtable to find the method definitions (and bypassing the linker problem).

Also, WebDevToolsAgentImpl has dependencies on modules/, so it can't be moved to core/ right now anyway (and we can't move it to modules/ or everything else would need to move to modules/, too). So the only way to do this is slowly and  in piecemeal :(

If you have any other suggestions though, I'm all ears.

Sasha

Patch-set: 2
Reviewer: Sasha Morrissey <1116022@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>