Update patch set 1
Patch Set 1:

@Sadrul, Eric: here's a small jumbo fixup after https://chromium-review.googlesource.com/c/chromium/src/+/840922

The chromium.fyi Jumbo Linux x64 bot is currently failing with this error:

FAILED: obj/ui/views/examples/views_examples_lib/views_examples_lib_jumbo_1.o 
/b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ui/views/examples/views_examples_lib/views_examples_lib_jumbo_1.o.d -DGFX_VECTOR_ICONS_UNSAFE -DVIEWS_EXAMPLES_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DCR_CLANG_REVISION=\"321204-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -DWEBP_EXTERN=extern -DTOOLKIT_VIEWS=1 -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -I. -I../.. -Igen -I../../build/linux/debian_stretch_amd64-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_stretch_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/libwebp/src -I../../third_party/khronos -I../../gpu -I../../third_party/libyuv/include -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/gpu -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/vulkan/include -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fdebug-prefix-map=/b/c/builder/Jumbo_Linux_x64/src=. -no-canonical-prefixes -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -Wno-enum-compare-switch -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-tautological-constant-compare -Wtautological-constant-out-of-range-compare -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=gnu++14 -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include --sysroot=../../build/linux/debian_stretch_amd64-sysroot -fvisibility-inlines-hidden -c gen/ui/views/examples/views_examples_lib_jumbo_1.cc -o obj/ui/views/examples/views_examples_lib/views_examples_lib_jumbo_1.o
In file included from gen/ui/views/examples/views_examples_lib_jumbo_1.cc:19:
./../../ui/views/examples/multiline_example.cc:35:7: error: redefinition of 'PreferredSizeLabel'
class PreferredSizeLabel : public Label {
      ^
./../../ui/views/examples/label_example.cc:36:7: note: previous definition is here
class PreferredSizeLabel : public Label {
      ^
In file included from gen/ui/views/examples/views_examples_lib_jumbo_1.cc:26:
./../../ui/views/examples/text_example.cc:50:13: error: redefinition of 'kElideBehaviors'
const char* kElideBehaviors[] = { "Elide", "No Elide", "Fade", };
            ^
./../../ui/views/examples/label_example.cc:31:13: note: previous definition is here
const char* kElideBehaviors[] = { "No Elide", "Truncate", "Elide Head",
            ^
In file included from gen/ui/views/examples/views_examples_lib_jumbo_1.cc:32:
./../../ui/views/examples/widget_example.cc:126:46: error: reference to 'DialogExample' is ambiguous
      DialogDelegate::CreateDialogWidget(new DialogExample(), NULL,
                                             ^
../../ui/views/examples/dialog_example.h:28:29: note: candidate found by name lookup is 'views::examples::DialogExample'
class VIEWS_EXAMPLES_EXPORT DialogExample : public ExampleBase,
                            ^
./../../ui/views/examples/widget_example.cc:26:7: note: candidate found by name lookup is 'views::examples::(anonymous namespace)::DialogExample'
class DialogExample : public DialogDelegateView {
      ^
./../../ui/views/examples/widget_example.cc:126:42: error: cannot initialize a parameter of type 'views::WidgetDelegate *' with an rvalue of type 'views::examples::DialogExample *'
      DialogDelegate::CreateDialogWidget(new DialogExample(), NULL,
                                         ^~~~~~~~~~~~~~~~~~~
../../ui/views/window/dialog_delegate.h:41:53: note: passing argument to parameter 'delegate' here
  static Widget* CreateDialogWidget(WidgetDelegate* delegate,
                                                    ^
4 errors generated.

Patch-set: 1
Reviewer: Sadrul Chowdhury <1000111@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Eric Willigers <1003011@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
CC: Daniel Bratell <1114374@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Mostyn Bramley-Moore <1244341@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false