Revert of add ConvertYUVAToARGBRow_MMX to media_perftests (patchset #5 id:80001 of https://codereview.chromium.org/1425263002/ )
Reason for revert:
Broke Android x86 Builder (dbg): yuv_convert_perftest.cc:function media::YUVConvertPerfTest_I422AlphaToARGBRow_SSSE3_Test::TestBody(): error: undefined reference to 'I422AlphaToARGBRow_SSSE3'

Original issue's description:
> add ConvertYUVAToARGBRow_MMX to media_perftests
>
> Add YUVConvertPerfTest.ConvertYUVAToARGBRow_MMX and YUVConvertPerfTest.I422ToARGBRow_SSSE3 to media_perftests.
> Fix math error when printing results by clearing the MMX state before doing float math.
> BUG=libyuv:473
>
> Committed: https://crrev.com/c44db295a5529b608de334b0413e5b49b2387898
> Cr-Commit-Position: refs/heads/master@{#357525}

TBR=xhwang@chromium.org,fbarchard@chromium.org,fbarchard@google.com
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=libyuv:473

Review URL: https://codereview.chromium.org/1419733007