Update patch set 2
Patch Set 2:

https://uberchromegw.corp.google.com/i/chromium.fyi/builders/EarlGreyiOS/builds/29220


ContentSuggestionsAlertFactoryTestCase/testSuggestionsAlert:
../../ios/chrome/browser/content_suggestions/content_suggestions_alert_egtest.mm:56: error: -[ContentSuggestionsAlertFactoryTestCase testSuggestionsAlert] : Exception: NoMatchingElementException
Exception Name: NoMatchingElementException
Exception Reason: Cannot find UI Element.
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher:interactable",
  "Element Matcher" : "(((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel('Cancel')) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityTraits: UIAccessibilityTraitButton))",
  "Recovery Suggestion" : "Check if the element exists in the UI hierarchy printed below. If it exists, adjust the matcher so that it accurately matches element."
}
Exception Details: Error Trace: [
  {
    "Description" : "Interaction cannot continue because the desired element was not found.",
    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code" : "0",
    "File Name" : "GREYElementInteraction.m",
    "Function Name" : "-[GREYElementInteraction matchedElementsWithTimeout:error:]",
    "Line" : "121",
    "TestCase Class" : "ContentSuggestionsAlertFactoryTestCase",
    "TestCase Method" : "testSuggestionsAlert"
  }
]
Bundle ID: org.chromium.gtest.generic-unit-test
Stack Trace: (
	0   EarlGrey                            0x0000000114e96176 -[GREYDefaultFailureHandler handleException:details:] + 1270
	1   EarlGrey                            0x0000000114e89a0f -[GREYElementInteraction grey_handleFailureOfAssertion:assertionError:userProvidedOutError:] + 4207
	2   EarlGrey                            0x0000000114e864b2 __39-[GREYElementInteraction assert:error:]_block_invoke + 1986
	3   EarlGrey                            0x0000000114eaf1b4 __59-[GREYUIThreadExecutor executeSyncWithTimeout:block:error:]_block_invoke + 68
	4   EarlGrey                            0x0000000114eac617 __54-[GREYRunLoopSpinner grey_checkConditionInActiveMode:]_block_invoke + 263
	5   CoreFoundation                      0x000000011329425c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	6   CoreFoundation                      0x0000000113279304 __CFRunLoopDoBlocks + 356
	7   CoreFoundation                      0x0000000113278a75 __CFRunLoopRun + 901
	8   CoreFoundation                      0x0000000113278494 CFRunLoopRunSpecific + 420
	9   EarlGrey                            0x0000000114eac41e -[GREYRunLoopSpinner grey_checkConditionInActiveMode:] + 350
	10  EarlGrey                            0x0000000114eab4bb -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 443
	11  EarlGrey                            0x0000000114eaec3d -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 973
	12  EarlGrey                            0x0000000114e85476 -[GREYElementInteraction assert:error:] + 1606
	13  EarlGrey                            0x0000000114e867bb -[GREYElementInteraction assertWithMatcher:error:] + 123
	14  EarlGrey                            0x0000000114e8670f -[GREYElementInteraction assertWithMatcher:] + 79
	15  ios_chrome_ui_egtests               0x0000000107ee7f86 -[ContentSuggestionsAlertFactoryTestCase testSuggestionsAlert] + 2406
	16  CoreFoundation                      0x000000011327605c __invoking___ + 140
	17  CoreFoundation                      0x0000000113275ee1 -[NSInvocation invoke] + 289
	18  EarlGrey                            0x0000000114e7b988 -[GREYTestCaseInvocation invoke] + 104
	19  XCTest                              0x0000000114557210 __24-[XCTestCase invokeTest]_block_invoke_2 + 481
	20  XCTest                              0x000000011458f9d4 -[XCTestContext performInScope:] + 190
	21  XCTest                              0x000000011455701c -[XCTestCase invokeTest] + 255
	22  EarlGrey                            0x0000000114e6c8b4 -[XCTestCase(GREYAdditions) grey_invokeTest] + 932
	23  XCTest                              0x0000000114557835 -[XCTestCase performTest:] + 457
	24  XCTest                              0x00000001145548fd -[XCTestSuite performTest:] + 491
	25  XCTest                              0x00000001145548fd -[XCTestSuite performTest:] + 491
	26  XCTest                              0x00000001145548fd -[XCTestSuite performTest:] + 491
	27  XCTest                              0x0000000114540b0c __25-[XCTestDriver _runSuite]_block_invoke + 51
	28  XCTest                              0x0000000114561fc3 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 602
	29  XCTest                              0x00000001145409a9 -[XCTestDriver _runSuite] + 436
	30  XCTest                              0x00000001145417a2 -[XCTestDriver _checkForTestManager] + 287
	31  XCTest                              0x0000000114590f5c _XCTestMain + 628
	32  CoreFoundation                      0x000000011329425c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	33  CoreFoundation                      0x0000000113279304 __CFRunLoopDoBlocks + 356
	34  CoreFoundation                      0x0000000113278a75 __CFRunLoopRun + 901
	35  CoreFoundation                      0x0000000113278494 CFRunLoopRunSpecific + 420
	36  GraphicsServices                    0x0000000117d43a6f GSEventRunModal + 161
	37  UIKit                               0x00000001119aff34 UIApplicationMain + 159
	38  ios_chrome_ui_egtests               0x0000000106e3fc63 _ZN12_GLOBAL__N_120RunUIApplicationMainEiPPc + 371
	39  ios_chrome_ui_egtests               0x0000000106e3f75e main + 414
	40  libdyld.dylib                       0x000000011a8fd68d start + 1
	41  ???                                 0x0000000000000005 0x0 + 5
)

Patch-set: 2