Revert of [KeyEvent Mac] Move WebInputEventFactory into chromium. (patchset #7 id:120001 of https://codereview.chromium.org/1331013004/ )
Reason for revert:
This caused compile failure on MacOSX 10.9 Retina
bot.

The relevant error log:

../../content/browser/renderer_host/input/web_input_event_builders_mac.mm:889:10: error: use of undeclared identifier 'NSEventTypeSmartMagnify'; did you mean 'NSEventTypeMagnify'?
    case NSEventTypeSmartMagnify:
         ^~~~~~~~~~~~~~~~~~~~~~~
         NSEventTypeMagnify
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:48:5: note: 'NSEventTypeMagnify' declared here
    NSEventTypeMagnify          = 30,
    ^
../../content/browser/renderer_host/input/web_input_event_builders_mac.mm:889:10: error: duplicate case value 'NSEventTypeMagnify'
    case NSEventTypeSmartMagnify:
         ^
../../content/browser/renderer_host/input/web_input_event_builders_mac.mm:885:10: note: previous case defined here
    case NSEventTypeMagnify:
         ^
2 errors generated.
ninja: build stopped: subcommand failed.

Original issue's description:
> [KeyEvent Mac] Move WebInputEventFactory into chromium.
>
> There was an inconsistency on the Mac platform that the WebInputEventFactory
> (old WebKit code) was being used. Other platforms have migrated to using
> builders and it was weird for the Mac code path to have some code on one
> side of the blink divide that others didn't. This change brings the Mac
> platform inline with the others by moving the input event
> factory from blink into chromium.
>
> blink change: https://codereview.chromium.org/1335673002/
>
> BUG=493833,237267
>
> Committed: https://crrev.com/8db5ca887d4560ed15bf5e6e2dce69dc85868f25
> Cr-Commit-Position: refs/heads/master@{#348989}

TBR=wez@chromium.org,sadrul@chromium.org,asvitkine@chromium.org,mnaganov@chromium.org,piman@chromium.org,dtapuska@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=493833,237267

Review URL: https://codereview.chromium.org/1345043003