Update patch set 4
Patch Set 4:

(1 comment)

> Patch Set 4:
> 
> @Bo Liu : any idea of what's going with the bots?
> 
> java.lang.UnsatisfiedLinkError: No implementation found for void org.chromium.ui.events.devices.InputDeviceObserver.nativeInputConfigurationChanged() (tried Java_org_chromium_ui_events_devices_InputDeviceObserver_nativeInputConfigurationChanged and Java_org_chromium_ui_events_devices_InputDeviceObserver_nativeInputConfigurationChanged__)
> 	at org.chromium.ui.events.devices.InputDeviceObserver.nativeInputConfigurationChanged(Native Method)
> 
> I'm not a Java/JNI expert...

I'm guessing you forgot to call RegisterNativesImpl that's in the generated header

Patch-set: 4
Reviewer: Bo Liu <1002725@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>