Reland of Make ui/gl/... consistently use on Swiftshader includes on Windows official builds. (patchset #1 id:1 of https://codereview.chromium.org/2226153002/ )
Reason for revert:
Appears to have caused
FAILED: obj/ui/gl/init/init/gl_initializer_ozone.o
../../ui/gl/init/gl_initializer_ozone.cc:47:15: error: cannot initialize a parameter of type 'EGLNativeDisplayType' (aka '_XDisplay *') with an rvalue of type 'intptr_t' (aka 'long')
              GetSurfaceFactory()->GetNativeDisplay())) {
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ui/gl/gl_surface_egl.h:58:53: note: passing argument to parameter 'native_display' here
  static bool InitializeOneOff(EGLNativeDisplayType native_display);
                                                    ^
1 error generated.

Original issue's description:
> Revert of Make ui/gl/... consistently use on Swiftshader includes on Windows official builds. (patchset #3 id:40001 of https://codereview.chromium.org/2221063003/ )
>
> Reason for revert:
> This break the Win official builds, e.g.:
>
> C:\b\build\slave\chromium-win-pgo-builder\build\src\buildtools\win\gn.exe gen //out/Release --check
>   -> returned 1
> ERROR at //ui/gl/BUILD.gn:236:7: Replacing nonempty list.
>       include_dirs = [ "//third_party/swiftshader/include" ]
>       ^-----------
> This overwrites a previously-defined nonempty list (length 1).
> See //ui/gl/BUILD.gn:132:18: for previous definition
>   include_dirs = [ "//third_party/mesa/src/include" ]
>                  ^----------------------------------
> with another one (length 1). Did you mean "+=" to append instead? If you
> really want to do this, do
>   foo = []
> before reassigning.
> See //BUILD.gn:298:7: which caused the file to be included.
>       "//ui/gl:gl_unittests",
>       ^---------------------
>
> Original issue's description:
> > Make ui/gl/... consistently use on Swiftshader includes on Windows.
> >
> > The existing code specifies the Swiftshader include directory for
> > //ui/gl/init . The Swiftshader include directory has its own
> > EGL headers, which collide with the Khronos EGL headers (which are
> > different due to Chromium-specific modifications.)
> >
> > The net effect is that //ui/gl's typedefs may collide with
> > typdefs of //ui/gl/init/... In this case, EGLNativeDisplayType
> > is incompatible with USE_OZONE=1 (intptr_t in Khronos; XDisplay* in
> > Swiftshader.)
> >
> > Moving the Swiftshader include dir to all of //ui/gl will keep things
> > consistent; making it Winows-only ensures that we aren't picking
> > up the dependency on unsupported platforms.
> >
> > R=kylechar@chromium.org,piman@chromium.org,sievers@chromium.org
> > CC=wez@chromium.org,lethalantidote@chromium.org
> > BUG=
> >
> > Committed: https://crrev.com/adbb93f546038fd7d4c809a70f8dd10d6ad2add0
> > Cr-Commit-Position: refs/heads/master@{#410493}
>
> TBR=kylechar@chromium.org,piman@chromium.org,sievers@chromium.org,kmarshall@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=
>
> Committed: https://crrev.com/b6be4d4a04a029ad14668a587be020d9629c1b69
> Cr-Commit-Position: refs/heads/master@{#410507}

TBR=kylechar@chromium.org,piman@chromium.org,sievers@chromium.org,kmarshall@chromium.org,sebmarchand@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=635702

Review-Url: https://codereview.chromium.org/2224263002