Revert of Use /LTCG:Incremental to speed up the non-clobber official builds. (patchset #2 id:20001 of https://codereview.chromium.org/2045683002/ )
Reason for revert:
I'm seeing some compiler issue on the Win perf builders (https://uberchromegw.corp.google.com/i/chromium.perf/builders/Win%20x64%20Builder/builds/9316/steps/compile/logs/stdio) :

fatal error C1001: An internal error has occurred in the compiler

BUG=616946

Original issue's description:
> Use /LTCG:Incremental to speed up the non-clobber official builds.
>
> /LTCG:Incremental is different from /INCREMENTAL, it speeds-up the link time of the WPO build without affecting the code quality and the performance, see https://blogs.msdn.microsoft.com/vcblog/2014/11/12/speeding-up-the-incremental-developer-build-scenario/ for more details on this.
>
> Committed: https://crrev.com/98fccebb0a5f6f1307ed1e598418fa472a8e1800
> Cr-Commit-Position: refs/heads/master@{#398153}

TBR=brucedawson@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2035313007
Cr-Commit-Position: refs/heads/master@{#398279}
(cherry picked from commit 2e304ec9ca19c8113db6b49405d6b2dd6d8cf2cd)

Review URL: https://codereview.chromium.org/2044943002 .