adb_profile_chrome check init status for binary manager
We will get the following error for perf_controller_unittest
if we do not have the check.

InitializationError: Trying to re-initialize the binary manager with config None

I think the reason is that there are two perf tests, and
binary manager should be initialized only once.
https://code.google.com/p/chromium/codesearch#chromium/src/tools/profile_chrome/perf_controller_unittest.py

BUG=586651

Review URL: https://codereview.chromium.org/1699523002