Revert of Improve linearized pdf load/show time. (patchset #1 id:1 of https://codereview.chromium.org/2449973004/ )
Reason for revert:
Still breaks the tree. The initial revert failed due to funny merging by the CQ in reaction to r427683.

Original issue's description:
> Reland of Improve linearized pdf load/show time. (patchset #1 id:1 of https://codereview.chromium.org/2458493002/ )
>
> Reason for revert:
> As suggested FindIt, this reverting CL is also causing the tree closure.
>
> Original issue's description:
> > Revert of Improve linearized pdf load/show time. (patchset #18 id:340001 of https://codereview.chromium.org/2349753003/ )
> >
> > Reason for revert:
> > https://build.chromium.org/p/chromium/builders/Win%20x64/builds/5423/steps/compile/logs/stdio
> >
> > FAILED: obj/pdf/pdf_unittests/document_loader_unittest.obj
> > pdf\document_loader_unittest.cc(631): error C2131: expression did not evaluate to a constant
> > pdf\document_loader_unittest.cc(631): note: failure was caused by call of undefined function or one not declared 'constexpr'
> > pdf\document_loader_unittest.cc(631): note: see usage of 'chrome_pdf::DocumentLoader::default_request_size'
> >
> >
> > Original issue's description:
> > > Improve linearized pdf load/show time.
> > > Reduce Pdf Plugin's count of reconnects.
> > > Add tests for PDFPlugin DocumentLoader.
> > >
> > > DocumentLoader was splitted into separate components, and missing tests was added for them.
> > >
> > > The main ideas in this CL are:
> > >
> > > 1) Do not reset browser initiated connection at start (includes case when we can use range requests), if we request data near current downloading position.
> > > 2) Request as much data as we can on each request, and continue loading data using current range request. (like tape rewind)
> > > 3) Isolate RangeRequest logic into DocumentLoader.  Method OnPendingRequestComplete is called, when we receive requested data (main connection, or Range connection). (like tape playing without rewing).
> > > 4) Fill this logic by tests.
> > >
> > > Example URL:
> > > http://www.major-landrover.ru/upload/attachments/f/9/f96aab07dab04ae89c8a509ec1ef2b31.pdf
> > > Comparison of changes:
> > > https://drive.google.com/file/d/0BzWfMBOuik2QNGg0SG93Y3lpUlE/view?usp=sharing
> > >
> > > Committed: https://crrev.com/7fd7423cdee0dba84faf480d10dd66dcb57110d9
> > > Cr-Commit-Position: refs/heads/master@{#427752}
> >
> > TBR=jochen@chromium.org,raymes@chromium.org,spelchat@chromium.org,rsesek@chromium.org,art-snake@yandex-team.ru
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
>
> TBR=jochen@chromium.org,raymes@chromium.org,spelchat@chromium.org,rsesek@chromium.org,art-snake@yandex-team.ru,thestig@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
>
> Committed: https://crrev.com/47b9a19cb7219538a26e0f1388fd01adac709b98
> Cr-Commit-Position: refs/heads/master@{#427782}

TBR=jochen@chromium.org,raymes@chromium.org,spelchat@chromium.org,rsesek@chromium.org,art-snake@yandex-team.ru,hongchan@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true

Review-Url: https://codereview.chromium.org/2456653002