Add system.gyp:glib as dependency to os_crypt.gypi
When building chrome with GYP_DEFINES=use_ozone=1 ozone_platform_wayland=1
use_wayland_egl=1 use_gtk=0 use_egl=1, the following build error
occurred.

In file included from ../../components/os_crypt/libsecret_util_posix.cc:5:
In file included from ../../components/os_crypt/libsecret_util_posix.h:8:
../../third_party/libsecret/libsecret/secret.h:18:10: fatal error: 'glib.h' file not found
         ^
1 error generated.

system.gyp:glib has to be added to os_crypt.gypi to fix the error.
We also need to update BUILD.gn accordingly.

TEST=build chrome with GYP_DEFINES=use_ozone=1 ozone_platform_wayland=1
use_wayland_egl=1 use_gtk=0 use_egl=1

BUG=none

Review-Url: https://codereview.chromium.org/1934193002