Update patch set 15
Patch Set 15:

> Patch Set 15:
> 
> I'm getting presubmit errors locally with my CL, which does not touch any CLs. Snippet of the exception:
> Traceback (most recent call last):
>   <module> at /usr/local/google/home/martiniss/chromium/src/tools/perf/validate_wpr_archives:102
>     sys.exit(main(sys.argv[1:]))
>   main at /usr/local/google/home/martiniss/chromium/src/tools/perf/validate_wpr_archives:85
>     for s in GetAllStorySets():
>   GetAllStorySets at /usr/local/google/home/martiniss/chromium/src/tools/perf/validate_wpr_archives:32
>     for benchmark in benchmark_finders.GetAllBenchmarks():
>   GetAllBenchmarks at /usr/local/google/home/martiniss/chromium/src/tools/perf/core/benchmark_finders.py:63
>     all_contrib_benchmarks = GetAllContribBenchmarks()
>   GetAllContribBenchmarks at /usr/local/google/home/martiniss/chromium/src/tools/perf/core/benchmark_finders.py:59
>     index_by_class_name=True).values()
>   DiscoverClasses at /usr/local/google/home/martiniss/chromium/src/third_party/catapult/common/py_utils/py_utils/discover.py:98
>     modules = DiscoverModules(start_dir, top_level_dir, pattern)
>   DiscoverModules at /usr/local/google/home/martiniss/chromium/src/third_party/catapult/common/py_utils/py_utils/discover.py:57
>     module = __import__(module_name, fromlist=[True])
> TypeError: Item in ``from list'' not a string

How do you know that is the CL that cause PRESUBMIT error?

Patch-set: 15