Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2: Code-Review+1
> > > 
> > > Confirmed that a valid SDK exists for amd64-generic, daisy, and samus.
> > 
> > Here is what I get from --board=elm
> > (sdk elm R64-10090.0.0) warx@warx0 ~/chromium/src $ cros_vm --start                                                   
> > 11:36:22: ERROR: qemu not found.                           
> > cros_vm: Unhandled exception:                              
> > Traceback (most recent call last):                         
> >   File "/usr/local/google/home/warx/chromium/src/third_party/chromite/bin/cros_vm", line 169, in <module>             
> >     DoMain()                 
> >   File "/usr/local/google/home/warx/chromium/src/third_party/chromite/bin/cros_vm", line 165, in DoMain               
> >     commandline.ScriptWrapperMain(FindTarget)              
> >   File "/usr/local/google/home/warx/chromium/src/third_party/chromite/lib/commandline.py", line 911, in ScriptWrapperMain
> >     ret = target(argv[1:])   
> >   File "/usr/local/google/home/warx/chromium/src/third_party/chromite/scripts/cros_vm.py", line 311, in main          
> >     vm.PerformAction(start=args.start, stop=args.stop, cmd=args.cmd)                                                  
> >   File "/usr/local/google/home/warx/chromium/src/third_party/chromite/scripts/cros_vm.py", line 111, in PerformAction 
> >     self.Start()             
> >   File "/usr/local/google/home/warx/chromium/src/third_party/chromite/scripts/cros_vm.py", line 126, in Start         
> >     raise VMError('qemu not found.')                       
> > chromite.scripts.cros_vm.VMError
> > 
> > I have seen this WARNING: No VM available:
> > 11:37:49: WARNING: Copy Error: src gs://chromeos-image-archive/elm-release/R64-10090.0.0/chromiumos_qemu_image.tar.xz dest /usr/local/google/home/warx/chromium/.cros_cache/chrome-sdk/tarballs/staging/tmpyYOZ2U: return code: 1; command: /usr/local/google/home/warx/chromium/.cros_cache/common/gsutil_4.27.tar.gz/gsutil/gsutil -o 'Boto:num_retries=10' cp -v -- gs://chromeos-image-archive/elm-release/R64-10090.0.0/chromiumos_qemu_image.tar.xz /usr/local/google/home/warx/chromium/.cros_cache/chrome-sdk/tarballs/staging/tmpyYOZ2U
> > CommandException: No URLs matched: gs://chromeos-image-archive/elm-release/R64-10090.0.0/chromiumos_qemu_image.tar.xz 
> > 
> > cmd=['/usr/local/google/home/warx/chromium/.cros_cache/common/gsutil_4.27.tar.gz/gsutil/gsutil', '-o', 'Boto:num_retries=10', 'cp', '-v', '--', u'gs://chromeos-image-archive/elm-release/R64-10090.0.0/chromiumos_qemu_image.tar.xz', '/usr/local/google/home/warx/chromium/.cros_cache/chrome-sdk/tarballs/staging/tmpyYOZ2U'], extra env={'BOTO_CONFIG': '/usr/local/google/home/warx/.boto'} (Temp log for crbug.com/642986)
> > 11:37:49: WARNING: No VM available.
> 
> 
> Try: sudo apt-get install qemu-kvm

thanks, but I have another ERROR (looks like i don't have a good setup?):
(sdk elm R64-10090.0.0) warx@warx0 ~/chromium/src $ cros_vm --start
18:30:53: ERROR: VM image path  does not exist.
cros_vm: Unhandled exception:
Traceback (most recent call last):
  File "/usr/local/google/home/warx/chromium/src/third_party/chromite/bin/cros_vm", line 169, in <module>
    DoMain()
  File "/usr/local/google/home/warx/chromium/src/third_party/chromite/bin/cros_vm", line 165, in DoMain
    commandline.ScriptWrapperMain(FindTarget)
  File "/usr/local/google/home/warx/chromium/src/third_party/chromite/lib/commandline.py", line 911, in ScriptWrapperMain
    ret = target(argv[1:])
  File "/usr/local/google/home/warx/chromium/src/third_party/chromite/scripts/cros_vm.py", line 311, in main
    vm.PerformAction(start=args.start, stop=args.stop, cmd=args.cmd)
  File "/usr/local/google/home/warx/chromium/src/third_party/chromite/scripts/cros_vm.py", line 111, in PerformAction
    self.Start()
  File "/usr/local/google/home/warx/chromium/src/third_party/chromite/scripts/cros_vm.py", line 133, in Start
    raise VMError('VM image path %s does not exist.' % self.image_path)
chromite.scripts.cros_vm.VMError

Patch-set: 2