Revert "applist-focus: Handle arrow key focus traversal"
This reverts commit b123ea271ea0c2d820b813125455522ccb24a0d6.

Reason for revert:
This CL causes a compile error.
The error log was:
https://build.chromium.org/p/chromium.chromiumos/builders/Linux%20ChromiumOS%20Builder%20%28dbg%29/builds/92442
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.chromiumos%2FLinux_ChromiumOS_Builder__dbg_%2F92442%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

 LINK ./app_list_unittests
(snip)
../../ui/app_list/views/app_list_view_unittest.cc:609: error: undefined reference to 'app_list::AppsContainerView::IsInFolderView() const'
../../ui/app_list/views/app_list_view_unittest.cc:718: error: undefined reference to 'app_list::AppsContainerView::IsInFolderView() const'
../../ui/app_list/views/app_list_view_unittest.cc:777: error: undefined reference to 'app_list::AppsContainerView::IsInFolderView() const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Original change's description:
> applist-focus: Handle arrow key focus traversal
> 
> Changes:
> 1. Enable arrow key focus handling in FocusManager.
> 2. Handle arrow up/down in SearchBoxView to move focus to the first/last
>    focusable element in ContentsView.
> 3. Handle arrow up/down in AppsGridView. AppsGridView has three states:
>    Peeking, Fullscreen all apps (outside folder) and Fullscreen all apps
>    (inside folder). Do separate handling for them, since they have
>    different layout.
> 
> Design Doc: go/applist-focus
> 
> BUG=766810
> TEST=AppListViewFocusTest.*
> 
> Change-Id: I2ace4b3b21a69f10011eba2ed0079e1f7aee48d0
> Reviewed-on: https://chromium-review.googlesource.com/687818
> Commit-Queue: Weidong Guo <weidongg@chromium.org>
> Reviewed-by: Xiyuan Xia <xiyuan@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#504818}

TBR=xiyuan@chromium.org,weidongg@chromium.org

Change-Id: Ic30e4ea6aea5c5c57c145be2aad0dc1d83edc777
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 766810