Update patch set 4
Patch Set 4:

> Patch Set 4: Code-Review-1
> 
> (1 comment)
> 
> Rightnow the skia renderer copy request tests crashes w/ :
> [3744:3745:1019/125939.572024:2177586545447:INFO:GrTextureOp.cpp(163)] ../../third_party/skia/src/gpu/ops/GrTextureOp.cpp:163: fatal error: "assert(numRealProxies > 0 && numRealProxies <= kMaxTextures && numRealProxies <= caps.maxFragmentSamplers())"
> 
> Received signal 6
> #0 0x7f26076fbdbd base::debug::StackTrace::StackTrace()
> #1 0x7f26076fa1ec base::debug::StackTrace::StackTrace()
> #2 0x7f26076fb775 base::debug::(anonymous namespace)::StackDumpSignalHandler()
> #3 0x7f2609ed5330 <unknown>
> #4 0x7f26053dfc37 gsignal
> #5 0x7f26053e3028 abort
> #6 0x7f26069bc679 sk_abort_no_print()
> #7 0x7f2606f8e6cf _ZZN12_GLOBAL__N_124TextureGeometryProcessor16NumSamplersToUseEiRK12GrShaderCapsENKUlvE_clEv
> #8 0x7f2606f8e16b (anonymous namespace)::TextureGeometryProcessor::NumSamplersToUse()
> #9 0x7f2606f8de17 (anonymous namespace)::TextureGeometryProcessor::Make()
> #10 0x7f2606f8b571 (anonymous namespace)::TextureOp::onPrepareDraws()
> #11 0x7f2606f554b8 GrMeshDrawOp::onPrepare()
> #12 0x7f2606edd24f GrOp::prepare()
> #13 0x7f2606ed9bfc GrRenderTargetOpList::onPrepare()
> #14 0x7f2606e9e45e GrOpList::prepare()
> #15 0x7f2606e7f560 GrDrawingManager::internalFlush()
> #16 0x7f2606e7264f GrDrawingManager::flush()
> #17 0x7f2606e7fd4d GrDrawingManager::prepareSurfaceForExternalIO()
> #18 0x7f2606ed1789 GrRenderTargetContext::prepareForExternalIO()
> #19 0x7f26070d1d4f SkGpuDevice::flushAndSignalSemaphores()
> #20 0x7f26070d1cdb SkGpuDevice::flush()
> #21 0x7f2606a37a24 SkCanvas::onFlush()
> #22 0x7f2606a379e6 SkCanvas::flush()
> #23 0x7f26093d831c viz::SkiaRenderer::FinishDrawingQuadList()

Hi Wei, I'm not sure what would cause that crash. How would I reproduce it? Also adding robertphillips@ in case that assertion means something to him.

Patch-set: 4
CC: Robert Phillips <1116012@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Brian Salomon <1000770@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>