Revert "Return empty startup tabs for incognito profile."
This reverts commit 3d657e127e0350bcabb74c12031be4c6e1fc15d8.

Reason for revert: New unittest fails:

[ RUN      ] StartupTabProviderTest.IncognitoProfile
../../chrome/browser/ui/startup/startup_tab_provider_unittest.cc(453): error: Value of: StartupTabProviderImpl().GetOnboardingTabs(incognito).empty()
  Actual: false
Expected: true
[  FAILED  ] StartupTabProviderTest.IncognitoProfile (16 ms)

https://build.chromium.org/p/chromium.win/builders/Win10%20Tests%20x64/builds/16448

Original change's description:
> Return empty startup tabs for incognito profile.
> 
> StartupTabProvider may be called when Chrome starts in an incognito profile,
> which leads to a crash at start-up. This CL addresses this and adds a unit
> test to make sure it does not regress in the future.
> 
> Bug: 769241
> Change-Id: Idea489bc05e31d7ac693cb935b1481979099bd09
> Reviewed-on: https://chromium-review.googlesource.com/689535
> Reviewed-by: Scott Violet <sky@chromium.org>
> Commit-Queue: Mihai Sardarescu <msarda@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#505395}

TBR=sky@chromium.org,msarda@chromium.org

Change-Id: I70ea9825d6dab8084292b40fa2d36d65488ff2e7
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 769241