Update patch set 4
Patch Set 4:

ughhh I messed up; I'll create a followup cl that fixes this. I'm guessing I put version = '3' instead of version = 3

Traceback (most recent call last):
  File "E:\b\rr\tmpulrxic\rw\checkout\scripts/slave\recipe_modules\swarming\resources\standard_isolated_script_merge.py", line 45, in <module>
    sys.exit(main())
  File "E:\b\rr\tmpulrxic\rw\checkout\scripts/slave\recipe_modules\swarming\resources\standard_isolated_script_merge.py", line 41, in main
    return StandardIsolatedScriptMerge(args.output_json, args.jsons_to_merge)
  File "E:\b\rr\tmpulrxic\rw\checkout\scripts/slave\recipe_modules\swarming\resources\standard_isolated_script_merge.py", line 25, in StandardIsolatedScriptMerge
    merged_results = results_merger.merge_test_results(shard_results_list)
  File "E:\b\rr\tmpulrxic\rw\checkout\scripts\slave\recipe_modules\swarming\resources\results_merger.py", line 65, in merge_test_results
    return _merge_json_test_result_format(shard_results_list)
  File "E:\b\rr\tmpulrxic\rw\checkout\scripts\slave\recipe_modules\swarming\resources\results_merger.py", line 122, in _merge_json_test_result_format
    'Unsupported version %s. Only version 3 is supported' % version)
results_merger.MergeException: Unsupported version 3. Only version 3 is supported

Patch-set: 4