Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> This caused errors for Rouslan, but not for me when running locally - I'm not sure why. When run on the bots they override the output directory.

He was getting the following error:
java.io.IOException: Could not create /chrome/test/data/android/render_tests/failures

Which was because mOutputDirectory hadn't been run through getIsolatedTestFilePath. Still not sure how it worked locally for you and me.

Patch-set: 1
Reviewer: Peter Conn <1149979@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0