Mark PreferencesTest#testSearchEnginePreferenceHttp flaky
It failed on builds [5680, 5691, 5695, 5703, 5723, 5739, 5743, 5753,
5756, 5761, 5762, 5767, 5769, 5772, 5773, 5799, 5812, 5828, 5830, 5839,
5845] of Marshmallow Tablet Tester with errors like:

[FAIL] org.chromium.chrome.browser.preferences.PreferencesTest#testSearchEnginePreferenceHttp:
java.lang.RuntimeException: Exception occured while waiting for runnable
  at org.chromium.base.ThreadUtils.runOnUiThreadBlocking(ThreadUtils.java:74)
  at org.chromium.chrome.browser.preferences.PreferencesTest.testSearchEnginePreferenceHttp(PreferencesTest.java:158)
  at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
  at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
  at org.chromium.base.test.BaseTestResult.run(BaseTestResult.java:129)
  at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
  at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
  at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
Caused by: java.util.concurrent.ExecutionException: junit.framework.AssertionFailedError
  at java.util.concurrent.FutureTask.report(FutureTask.java:94)
  at java.util.concurrent.FutureTask.get(FutureTask.java:164)
  at org.chromium.base.ThreadUtils.runOnUiThreadBlocking(ThreadUtils.java:72)
  ... 14 more
Caused by: junit.framework.AssertionFailedError
  at org.chromium.chrome.browser.preferences.PreferencesTest.indexOfFirstHttpSearchEngine(PreferencesTest.java:188)
  at org.chromium.chrome.browser.preferences.PreferencesTest.access$100(PreferencesTest.java:39)
  at org.chromium.chrome.browser.preferences.PreferencesTest$4.run(PreferencesTest.java:168)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

TBR=finnur@chromium.org
BUG=540706

Review-Url: https://codereview.chromium.org/2417903002