app_shell licenses step (fails)
Failure: See 773906

python ../../tools/licenses.py license_file gen/extensions/shell/LICENSE --gn-target //extensions/shell:app_shell --gn-out-dir .
Traceback (most recent call last):
  File "../../tools/licenses.py", line 733, in <module>
    sys.exit(main())
  File "../../tools/licenses.py", line 725, in main
    args.output_file, args.gn_out_dir, args.gn_target):
  File "../../tools/licenses.py", line 678, in GenerateLicenseFile
    directory, _REPOSITORY_ROOT, require_license_file=True)
  File "../../tools/licenses.py", line 357, in ParseDir
    "SPECIAL_CASES entry in %s" % path)
__main__.LicenseError: missing README.chromium or licenses.py SPECIAL_CASES entry in /usr/local/google/home/michaelpg/dev/c/w4/src/third_party/WebKit

Bug: 772975
Change-Id: If81511548746c074f3e1c2dbef331fadfabf82e7