Update patch set 6
Patch Set 6:

> Patch Set 6:
> 
> > Patch Set 6:
> > 
> > > Patch Set 6:
> > > 
> > > How do you suggest dealing with errors like this?
> > >   base/test/android/javatests/src/org/chromium/base/test/BaseActivityInstrumentationTestCase.java:9: warning: [deprecation] ActivityInstrumentationTestCase2 in android.test has been deprecated
> > > 
> > > https://build.chromium.org/p/tryserver.webrtc/builders/android_rel/builds/30746
> > 
> > Assuming you mean the actual failing error, which is:
> > ../../sdk/android/api/org/webrtc/MediaCodecVideoDecoder.java:107: warning: [JdkObsolete] It is very rare for LinkedList to out-perform ArrayList or ArrayDeque. Avoid it unless you're willing to invest a lot of time into benchmarking.
> >   private final Queue<TimeStamps> decodeStartTimeMs = new LinkedList<TimeStamps>();
> >                                                       ^
> >     (see http://errorprone.info/bugpattern/JdkObsolete)
> > ../../sdk/android/api/org/webrtc/MediaCodecVideoDecoder.java:115: warning: [JdkObsolete] It is very rare for LinkedList to out-perform ArrayList or ArrayDeque. Avoid it unless you're willing to invest a lot of time into benchmarking.
> >       new LinkedList<DecodedOutputBuffer>();
> >       ^
> >     (see http://errorprone.info/bugpattern/JdkObsolete)
> > error: warnings found and -Werror specified
> > 1 error
> > 
> > I'd suggest not using -Werror?
> 
> No, I mean the error that I referenced, not sure why you think otherwise.
> No, not using -Werror is not a good option.

Sorry, does this mean that warnings coming from base/ are OK but those from WebRTC's code are not? I assumed they had the same priority because they were bunched together.

Patch-set: 6