Revert "[CrOS Tether] Update connection retry attempt logic."
This reverts commit d5bd9807e5ba2490bc4165b7ae78492d9be4820a.

Reason for revert: compile failure
https://ci.chromium.org/buildbot/chromium.chromiumos/linux-chromeos-dbg/4001
message_transfer_operation_unittest.cc:2677: error: undefined reference to 'chromeos::tether::MessageTransferOperation::kMaxEmptyScansPerDevice'

Original change's description:
> [CrOS Tether] Update connection retry attempt logic.
> 
> Before this CL, we allowed 3 retries for the entire connection flow,
> which includes advertising, scanning, creating a GATT connection, and
> exchanging messages. However, it makes more sense to think of this as a
> two-part process:
>   (1) Advertising and scanning. This portion always occurs when
>       attempting a BLE connection, even if the device we're trying to
>       contact is not nearby and cannot respond.
>   (2) Creating a GATT connection and exchanging message. This portion
>       only occurs when an Android host is nearby to respond to the
>       Chromebook.
> 
> Connection attempts which fail in part (2) above indicate that the
> device actually is nearby and can potentially connect; additionally
> connection failures during this part of the connection often will
> succeed on a retry. Thus, this CL adds extra connection retry attempts
> if a previous attempt failed in part (2).
> 
> Bug: 805218, 672263
> Change-Id: Ifbedc004b96905d3f77662c45bcf2a9210b06c57
> Reviewed-on: https://chromium-review.googlesource.com/889991
> Reviewed-by: Jeremy Klein <jlklein@chromium.org>
> Commit-Queue: Kyle Horimoto <khorimoto@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#533073}

TBR=khorimoto@chromium.org,jlklein@chromium.org

Change-Id: I04d04f6655179d448ba1f949fda36bdfbb57ad0d
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 805218, 672263