Fix closure compile.
## /mnt/data/b/build/slave/Closure_Compilation_Linux/build/src/chrome/browser/resources/history/history.js:510: ERROR - actual parameter 1 of HistoryView.prototype.isInFocusGrid does not match formal parameter
## found   : (EventTarget|null)
## required: (Element|null)
##     if (this.model_.getView().isInFocusGrid(event.target))
##                                             ^

TBR=tbreisacher@chromium.org
BUG=none
TEST=green closure bots

Review URL: https://codereview.chromium.org/708613002