Update patch set 1
Patch Set 1:

There has been build breaks when using jumbo build since issue 749221. PTAL.

./../../third_party/WebKit/Source/platform/audio/VectorMathTest.cpp:188:31: error: unknown class name 'Test'; did you mean '::testing::Test'?
class VectorMathTest : public testing::Test {
                              ^~~~~~~~~~~~~
                              ::testing::Test
../../third_party/googletest/src/googletest/include/gtest/gtest.h:371:18: note: '::testing::Test' declared here
class GTEST_API_ Test {
                 ^
In file included from gen/third_party/WebKit/Source/platform/blink_platform_unittests_sources_jumbo_1.cc:33:
./../../third_party/WebKit/Source/platform/audio/VectorMathTest.cpp:282:39: error: no member named 'PrintToString' in namespace 'blink::testing'; did you mean '::testing::PrintToString'?
      EXPECT_EQ(expected_max, max) << testing::PrintToString(source);
                                      ^~~~~~~~~~~~~~~~~~~~~~
                                      ::testing::PrintToString
../../third_party/googletest/src/googletest/include/gtest/gtest-printers.h:996:15: note: '::testing::PrintToString' declared here
::std::string PrintToString(const T& value) {
              ^
2 errors generated.
ninja: build stopped: subcommand failed.

Patch-set: 1
Reviewer: Kenneth Russell <1105344@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Raymond Toy <1116024@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Eero Häkkinen <1140189@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Reviewer: Gyuyoung Kim <1233284@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false